runtime/src/main/java/org/corfudb/protocols/wireprotocol/ReadResponse.java, runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractContextStreamView.java, runtime/src/main/java/org/corfudb/runtime/view/stream/IStreamView.java, runtime/src/main/java/org/corfudb/runtime/view/stream/ThreadSafeStreamView.java
This patch add a new field in the ReadResponse such that the runtime could get the newest compaction mark from LogUnit servers when reading data.
Description:
Compaction mark is the hint to the runtime about when the versioning is lost in the LogUnit Servers. With that information, the runtime could decide to abort a TX/access if the snapshot time is smaller than the compaction mark. 
=> Compaction mark in read response

runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java, test/src/test/java/org/corfudb/CorfuTestParameters.java
Avoid flooding of checkpointer logs
=> [Port 0.2.3] Remove the log line "Runtime cache disabled.." to stop flooding

annotationProcessor/src/main/java/org/corfudb/annotations/ObjectAnnotationProcessor.java, annotations/src/main/java/org/corfudb/annotations/Mutator.java, annotations/src/main/java/org/corfudb/annotations/MutatorAccessor.java, annotations/src/main/java/org/corfudb/runtime/object/ICorfuSMR.java, annotations/src/main/java/org/corfudb/runtime/object/IGarbageIdentificationFunction.java, runtime/src/main/java/org/corfudb/protocols/logprotocol/SMRRecord.java, runtime/src/main/java/org/corfudb/protocols/logprotocol/SMRRecordLocator.java, runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java, runtime/src/main/java/org/corfudb/recovery/RecoveryUtils.java, runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java, runtime/src/main/java/org/corfudb/runtime/collections/ISMRMap.java, runtime/src/main/java/org/corfudb/runtime/collections/SMRMap.java, runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java, runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileWrapperBuilder.java, runtime/src/main/java/org/corfudb/runtime/object/ISMRStream.java, runtime/src/main/java/org/corfudb/runtime/object/StreamViewSMRAdapter.java, runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java, runtime/src/main/java/org/corfudb/runtime/object/transactions/Transaction.java, runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java, runtime/src/test/java/org/corfudb/protocols/logprotocol/SMRRecordLocatorTest.java, test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
By modifying annotation processor, this patch add APIs for the Object Layer to identify garbage. 
This PR is stack atop https://github.com/CorfuDB/CorfuDB/pull/1911,  https://github.com/CorfuDB/CorfuDB/pull/2014, https://github.com/CorfuDB/CorfuDB/pull/2003, https://github.com/CorfuDB/CorfuDB/pull/2011.
=> Add API for Object Layer to identify garbage

infrastructure/src/main/java/org/corfudb/infrastructure/DataStore.java, infrastructure/src/main/java/org/corfudb/infrastructure/IDataStore.java, infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/AbstractCompactionPolicy.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/AbstractLogSegment.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/GarbageSizeFirstPolicy.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/SegmentManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/SnapshotLengthFirstPolicy.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLog.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogCompactor.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogDataStore.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogParams.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogSegment.java, runtime/src/main/java/org/corfudb/protocols/wireprotocol/IMetadata.java, runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java, runtime/src/main/java/org/corfudb/protocols/wireprotocol/ReadResponse.java
Using per steam compaction mark has a downside of storing compacted
stream ids in each LogData's metadata, because each read on an address
needs to return the per stream compaction marks on that address, in
this way, we cannot completely remove a LogData which causes a leak.
Using global compaction mark, we only needs to store a bitmap for the
compacted addresses in a segment, which is a smaller overhead, but
sacrifices some versioning ability. This is fine since we have a policy
to ensure compaction mark does not move for a certain amount of time.
This also includes changes in #2134
=> Use global compaction mark instead of per stream to prevent leak.

runtime/src/main/java/org/corfudb/runtime/exceptions/TrimmedException.java, runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java
Typically for delta sync the remaining API is called in a very short interval (every 50ms) so printing the trim info log message warning that a checkpoint might not be loaded (which is expected as the stream is forcibly seek to a point and remaining is called from this point onwards) becomes chatty.
=> Remove Trim Info Log Message - Chatty

runtime/src/main/java/org/corfudb/protocols/logprotocol/SMRGarbageEntry.java, runtime/src/main/java/org/corfudb/protocols/logprotocol/SMRGarbageRecord.java, runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java, runtime/src/main/java/org/corfudb/runtime/GarbageInformer.java, runtime/src/main/java/org/corfudb/runtime/collections/MapLocatorStore.java, runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java, runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileWrapperBuilder.java, runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java, runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java, test/src/test/java/org/corfudb/runtime/collections/CorfuMapTest.java, test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
GarbageInformer send garbage information to LogUnits. 
This PR is stack atop https://github.com/CorfuDB/CorfuDB/pull/1911, https://github.com/CorfuDB/CorfuDB/pull/2003, https://github.com/CorfuDB/CorfuDB/pull/2014,  https://github.com/CorfuDB/CorfuDB/pull/2011 and https://github.com/CorfuDB/CorfuDB/pull/1999.
=> GarbageInformer send garbage information to LogUnits

common/src/main/java/org/corfudb/common/metrics/servers/PrometheusMetricsServer.java, it/src/main/java/org/corfudb/universe/group/cluster/AbstractCorfuCluster.java, it/src/main/java/org/corfudb/universe/node/client/LocalCorfuClient.java, runtime/pom.xml, runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java, runtime/src/main/java/org/corfudb/util/MetricsUtils.java
Allow the client to set a CorfuRuntime parameter that will allow
metrics to be consumed via an external agent.
Description:
=> Expose client metrics for external consumption

runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
CheckpointWriter uses deepSizeOf() to calculate the accurate size
of the checkpointed map as one of the metrics. However this method
would cause a heap memory bloat if the map is large, so removing it.
=> [Corfu-0.2.3] Remove deepSizeOf in CheckpointWriter which causes memory bloat.

runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
CheckpointWriter uses deepSizeOf() to calculate the accurate size
of the checkpointed map as one of the metrics. However this method
would cause a heap memory bloat if the map is large, so removing it.
Why should this be merged: prevent memory bloat
=> Remove deepSizeOf in CheckpointWriter which causes memory bloat.

runtime/src/main/java/org/corfudb/runtime/collections/CorfuQueue.java, runtime/src/main/java/org/corfudb/runtime/view/CorfuGuidGenerator.java, test/src/test/java/org/corfudb/runtime/view/CorfuGuidGeneratorTest.java
If CorfuQueue is used in a highly concurrent environment, it
causes the correction to quickly overflow and bump up the instance id.
Bumping up the instance id is really a corfu transaction.
If this transaction is nested, it aborts the parent transaction.
To avoid this, keep the use of transactions to an absolute minimum.
Make CorfuGuids tolerant of NTP time drifts upto 16 per minute
Related issue(s) (if applicable): #2152
=> CorfuGuidGenerator: Prevent transactional aborts

infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriter.java, infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java, it/src/test/resources/logback-test.xml, runtime/src/main/java/org/corfudb/protocols/wireprotocol/TailsResponse.java, runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java, runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java, runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java, runtime/src/main/java/org/corfudb/util/Utils.java, test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java, test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTrimTest.java, test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Description:
Backport of #1775 to corfu-0.2.2. This change allows prefix trim on different epochs. This change is required to avoid partition full issues found in earliest versions of Corfu due to trim failures.
- [x ] There are no TODOs left in the code
- [x ] [Coding conventions](https://github.com/CorfuDB/CorfuDB/wiki/Corfu-Style-Guidelines) (e.g. for logging, unit tests) have been followed
- [x ] Change is covered by automated tests
- [x ] Public API has Javadoc
=> Avoid batch writer epoch validation on prefixTrim.

runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java, runtime/src/main/java/org/corfudb/util/serializer/DynamicProtobufSerializer.java, runtime/src/main/java/org/corfudb/util/serializer/ProtobufSerializer.java, test/src/test/java/org/corfudb/integration/CorfuStoreIT.java
Description:
The type code of the protobuf serializer should not be exposed.
This for the following reasons:
- It should be used via the CorfuStore as it handles the initialization.
- DynamicProtobufSerializer depends on this code to override it to be able the deserialize the data.
To have the code in a single place and avoid developer errors in future.
=> Hide Protobuf Serializer TypeCode.

runtime/proto/corfu_options.proto
Description:
Otherwise consumers who have their Protobufs in proto2 syntax cannot include these headers
=> Downgrade corfu_options to proto2 for interoperability

runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiObjectSMREntry.java, runtime/src/main/java/org/corfudb/protocols/logprotocol/SMREntry.java, runtime/src/main/java/org/corfudb/protocols/wireprotocol/ILogData.java, test/src/test/java/org/corfudb/integration/TransactionStreamIT.java, test/src/test/java/org/corfudb/protocols/logprotocol/MultiObjectSMREntryTest.java
When a LogEntry is deserialized, stream updates are only deserilized
on access. In essence, allowing a stream to only deserilize its updates.
This is useful when a CorfuRuntime doesn't have the serializers for all
other stream updates within the same LogEntry.
Description:
Why should this be merged: Addresses the problem where a client needs to read stream entries that exist as a part of a bigger transaction, but doesn't have a serilizer for all other streams within the same transaction.
=> Lazy Deserialization

runtime/src/main/java/org/corfudb/protocols/logprotocol/LogEntry.java, runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiObjectSMREntry.java, runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiSMREntry.java, runtime/src/main/java/org/corfudb/protocols/logprotocol/SMREntry.java, runtime/src/main/java/org/corfudb/util/serializer/CorfuSerializer.java, test/src/test/java/org/corfudb/protocols/logprotocol/LogEntryTest.java
PR #2192 changed the serialization format of MultiObjectSMREntry.
In order to avoid data migration, this patch reverts those format
changes. Those changes are convienent, but not necessary to
implement lazy deserialization. This patch does that: lazy
deserialization without format changes.
=> Lazy Deserialization Part 2

runtime/src/main/java/org/corfudb/runtime/collections/CorfuDynamicMessage.java, runtime/src/main/java/org/corfudb/util/serializer/ProtobufSerializer.java
Description:
Fix CorfuDynamicMessage equals.
Validate schema on multiple openTables.
Fixes an equals bug which causes missing data in CorfuStore.
=> Fix CorfuDynamicMessage equals.

infrastructure/src/main/java/org/corfudb/infrastructure/log/CompactionMetadata.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/GarbageLogSegment.java, runtime/src/main/java/org/corfudb/protocols/logprotocol/SMRGarbageEntry.java
Fix garbage segment append: first dedup, then persist and finally merge.
=> Fix garbage segment append: first dedup, then persist and finally merge.

runtime/pom.xml, runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java, runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileWrapperBuilder.java, runtime/src/main/java/org/corfudb/util/ReflectionUtils.java, test/src/test/java/org/corfudb/runtime/object/ObjectBuilderTest.java
Previously, we were initializing a wrapper object with any constructor
that would match the given arguments. This approach is not sufficient
when constructor type parameters are polymorphic, since the wrong
constructor might get called.
Please take a look at Java Specification 15.12.2.5. for more
information.
Description:
=> Change how we initialize wrapper objects

runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java, runtime/src/main/java/org/corfudb/runtime/collections/ILocatorStore.java, runtime/src/main/java/org/corfudb/runtime/collections/MapLocatorStore.java, runtime/src/main/java/org/corfudb/runtime/collections/SMRMap.java
Current implementation could not mark clear() operator as garbage. This patch fixes this problem by adding a dedicated variable to track the locator of latest clear() operator. One clear() operator is marked as garbage when a new clear() is encountered.
=> fix the leaking problem of clear operation

runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java, runtime/src/main/java/org/corfudb/runtime/collections/CorfuQueue.java, runtime/src/main/java/org/corfudb/runtime/view/CorfuGuidGenerator.java, runtime/src/main/java/org/corfudb/runtime/view/ObjectBuilder.java, runtime/src/main/java/org/corfudb/util/serializer/Serializers.java, test/src/test/java/org/corfudb/CustomSerializer.java, test/src/test/java/org/corfudb/runtime/collections/CorfuMapTest.java, test/src/test/java/org/corfudb/runtime/collections/CorfuQueueTest.java, test/src/test/java/org/corfudb/runtime/collections/SMRMapTest.java, test/src/test/java/org/corfudb/runtime/object/CorfuSMRObjectProxyTest.java, test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTransactionContextTest.java
Consumers of the CorfuQueue need a way to set a custom serializer based on the integration framework.
=> CorfuQueue: Support for custom serializer & Secondary Indexes

annotationProcessor/src/main/java/org/corfudb/annotations/ObjectAnnotationProcessor.java, annotations/src/main/java/org/corfudb/runtime/object/ICorfuSMRProxy.java, runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java, runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
Currently, @PassThrough and @DontInstrument have the same behavior,
but @PassThrough methods should execute against the underlying
object and not the wrapper. This patch fixes the annotation
processor to generate correct pass-through methods.
Why should this be merged: Fixes a bug in the annotation processor, enables some clean ups in #2201 and helps fix #2225
Related issue(s) (if applicable): Enables some clean ups in #2201 and helps fix #2225
=> @PassThrough bug fix

runtime/src/main/java/org/corfudb/runtime/collections/Table.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreTest.java, test/src/test/resources/proto/sample_schema.proto
Some fields in managedResources are set only at the time the object is created and not really available on updates. This means clients would need to do an explicit get() to retrieve the old value.
This change makes the merging of previous value the default behavior for metadata fields.
=> CorfuStore: Metadata retains previous values if not set

it/src/main/java/org/corfudb/universe/scenario/fixture/Fixtures.java, it/src/main/java/org/corfudb/universe/universe/vm/ApplianceManager.java
Leveraging a new template and also disable unnecessary
VM customizations.
Description:
=> Fix VM cloning in the Universe Framework

runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java, runtime/src/main/java/org/corfudb/runtime/collections/ISMRMap.java
The unmapSecondaryIndexes is not an SMRAcessor, so the annotation
processor shouldn't generator an accessor method for it.
Why should this be merged: prevents the annotation processor of generating an accessor in CorfuTable$CORFUSMR
=> Dont Instrument unmapSecondaryIndexes

runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java, runtime/src/main/java/org/corfudb/runtime/view/stream/IStreamView.java, runtime/src/main/java/org/corfudb/runtime/view/stream/ThreadSafeStreamView.java, test/src/test/java/org/corfudb/runtime/view/QuorumReplicationStreamViewTest.java, test/src/test/java/org/corfudb/runtime/view/StreamViewTest.java
Removed unnecessary APIs.
Why should this be merged: less code, reduced complexity. 
=> Reduce stream interface

runtime/src/main/java/org/corfudb/runtime/GarbageInformer.java, runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java, test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTransactionContextTest.java, test/src/test/java/org/corfudb/runtime/object/transactions/SnapshotTransactionContextTest.java, test/src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
fix bugs and change default parameters in GarbageInformer.
=> fix bugs and change default parameters in GarbageInformer.

infrastructure/src/main/java/org/corfudb/infrastructure/BatchProcessor.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLog.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java, runtime/src/main/java/org/corfudb/runtime/exceptions/QuotaExceededException.java, runtime/src/main/java/org/corfudb/util/serializer/DynamicProtobufSerializer.java, test/src/test/java/org/corfudb/integration/CorfuStoreIT.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreTest.java, test/src/test/resources/proto/sample_schema.proto
If a table was opened with a different type but carries entries of different types, then we should be able to catch and log this error.
=> DynamicProtobufSerializer: Debug message for serializer error

runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java, runtime/src/main/java/org/corfudb/runtime/MultiCheckpointWriter.java, runtime/src/main/java/org/corfudb/runtime/collections/ContextAwareMap.java, runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java, runtime/src/main/java/org/corfudb/runtime/collections/ICorfuTable.java, runtime/src/main/java/org/corfudb/runtime/collections/ISMRMap.java, runtime/src/main/java/org/corfudb/runtime/collections/PersistedStreamingMap.java, runtime/src/main/java/org/corfudb/runtime/collections/SMRMap.java, runtime/src/main/java/org/corfudb/runtime/collections/StreamingMap.java, runtime/src/main/java/org/corfudb/runtime/collections/StreamingMapDecorator.java, test/src/test/java/org/corfudb/integration/AbstractIT.java, test/src/test/java/org/corfudb/integration/LogSizeQuotaIT.java, test/src/test/java/org/corfudb/integration/StreamAddressDiscoveryIT.java, test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java, test/src/test/java/org/corfudb/recovery/Helpers.java, test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java, test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTest.java, test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTrimTest.java, test/src/test/java/org/corfudb/runtime/view/StreamViewTest.java
In order for checkpointing to work with large (disk-backed) tables,
(Multi)CheckpointWriter needs to consume the streaming interface.
Description:
=> Make (Multi)CheckpointWriter consume StreamingMap

.travis.yml
Corfu deployment: maven silent mode, Quiet output - only show errors
Description:
=> Corfu deployment: maven silent mode, Quiet output - only show errors

runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java, runtime/src/main/java/org/corfudb/runtime/collections/PersistedStreamingMap.java, runtime/src/main/java/org/corfudb/runtime/collections/StreamingMapDecorator.java, runtime/src/main/java/org/corfudb/util/ImmutableListSetWrapper.java, test/src/test/java/org/corfudb/runtime/collections/CorfuTableTest.java
When multiple threads are operating on the same table, and one of them
is utilizing the streaming API, ConcurrentModificationException will
occur since the Stream was operating on a shared reference.
Description:
=> Streaming API needs to operate on a snapshot

test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
Depending on the available resources, the total number of retries in
ClusterReconfigIT is sometimes not sufficient.
Description:
=> Fix a flaky integration test

.travis.yml, coverage/pom.xml, pom.xml
Description:
Use Jacoco for code coverage report generation instead of Cobertura.
Update Jacoco version.
Why should this be merged: we need to keep track of code coverage in the project.
=> Use JaCoco for Codecov

runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java, runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
When the cache is disabled, entries still end up being cached due to a
bug in AddressSpaceView. This patch fixes that issue and simplifies the
logic.
Description:
=> AddressSpaceView cache fix

generator/src/main/java/org/corfudb/generator/StringIndexer.java, runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java, runtime/src/main/java/org/corfudb/runtime/collections/CorfuQueue.java, runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java, runtime/src/main/java/org/corfudb/runtime/collections/Index.java, runtime/src/main/java/org/corfudb/runtime/collections/ProtobufIndexer.java, runtime/src/main/java/org/corfudb/runtime/collections/TableOptions.java, test/src/test/java/org/corfudb/integration/ServerRestartIT.java, test/src/test/java/org/corfudb/runtime/collections/CorfuQueueTest.java, test/src/test/java/org/corfudb/runtime/collections/StringIndexer.java, test/src/test/java/org/corfudb/runtime/collections/StringMultiIndexer.java
In order to accommodate for disk-backed CorfuTable refactoring and to
improve readability, move all index interfaces and definitions out of
CorfuTable and into a separate class.
Description:
=> Move Index defintions into a separate class

runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
When calling setUndoRecord(...) during object reset do not try to
resolve the execution context.
Description:
=> Do not resolve execution context on object reset

runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java, runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java, test/src/test/java/org/corfudb/runtime/view/StreamsViewTest.java
Since streams can be opened during a runtime gc cycle, the collection
holding the opened StreamView references should be thread-safe, otherwise
adding to the collection during iteration would cause exceptions.
=> Streams view bug

runtime/src/main/java/org/corfudb/runtime/collections/TransactionPoller.java, runtime/src/main/java/org/corfudb/runtime/collections/TxnStreamingManager.java, runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java, test/src/test/java/org/corfudb/integration/StreamingIT.java
Description:
CorfuStore just has 1 Transaction poller. But to ensure that new
subscribers are taken care of, periodically this transaction poller
is refreshed and a new one is created. But this causes a leak in the
underlying runtime's TRANSACTION StreamsView's openedStreams
resulting in the JVM going out of Memory after a while.
Simple fix is to remove the prior StreamView when recreating.
+Test case to both catch the memory leak bug and validate the fix.
Results in OOM otherwise
=> Txn stream leak fix

runtime/src/main/java/org/corfudb/runtime/collections/Table.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreTest.java
Newly created CorfuStore objects need to have a version field of 0
to be compatible with some older usecases.
(Right now they start with 1)
+TestCase to validate this.
Description:
=> CorfuStore: Version should start with 0

infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java, test/src/test/java/org/corfudb/runtime/view/StateTransferTest.java
In the case of data written with a different codec than that used by the State Transfer runtime, we would overwrite the codec of compressed data. Making it imposible for a runtime reader to decompress correctly. 
A test has been added to confirm this.
=> State Transfer Codec overwrite fix

runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java, test/src/test/java/org/corfudb/integration/ServerRestartIT.java, test/src/test/java/org/corfudb/integration/StreamAddressDiscoveryIT.java, test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
Description:
Remove the tail arg from checkpoint function as it can be referenced from the snapshot's sequence. 
Make code clean and easy to read.
=> Some code cleanup. Remove the not required arg for checkpoint function.

infrastructure/src/main/java/org/corfudb/infrastructure/AbstractServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/BaseServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/HandlerMethods.java, infrastructure/src/main/java/org/corfudb/infrastructure/LayoutServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/NettyServerRouter.java, infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java, infrastructure/src/test/java/org/corfudb/infrastructure/CorfuAbstractServerTest.java, runtime/src/main/java/org/corfudb/runtime/clients/ClientMsgHandler.java, test/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java, test/src/test/java/org/corfudb/infrastructure/TestServerRouter.java, test/src/test/java/org/corfudb/runtime/clients/SequencerHandlerTest.java
Improved Thread Management
The netty router is too low level to manage threading for
different requests. This patch improves threading management
by delegating the request processing to the handlers. That way
each handler can make its own decision on how to schedule
requests and the netty router, just becomes a message router.
=> Improved Thread Management

infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java, runtime/src/main/java/org/corfudb/protocols/wireprotocol/IMetadata.java, runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
After digging into the code, looks like the compressed flag could be removed to reduce complexity.
When server serializes LogData for a client read request, it should already be in compressed state, even for the unit test framework.
=> End-to-end compression: remove compressed flag and related checks.

runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
Encountering a TrimmedException in CorfuCompileProxy is part of a normal
workflow. The current message causes a lot of confusion during
root-cause analysis, since developers incorrectly assume that Corfu
ended up in an exceptional state.
Description:
=> Mask TrimmedException in CorfuCompileProxy

infrastructure/src/main/java/org/corfudb/infrastructure/AbstractServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/BaseServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/LayoutServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java, infrastructure/src/test/java/org/corfudb/infrastructure/CorfuAbstractServerTest.java, test/src/test/java/org/corfudb/infrastructure/ManagementServerTest.java
Dispatching the heart beat request to a secondary executor
doesn't improve responsiveness in the event of starvation.
Instead it should execute directly on the IO thread for minimal
latency.
This reverts commit c5b79137d65b41ad881dce839406c97735392f1d.
Why should this be merged: Removing unnecessary threads and this is needed for #2264
=> Remove Heart Beat Executor

it/src/main/java/org/corfudb/universe/node/server/CorfuServerParams.java, it/src/main/java/org/corfudb/universe/node/server/vm/VmCorfuServerParams.java, it/src/main/java/org/corfudb/universe/universe/vm/VmManager.java
Description:
Currently Universe framework didn't allow us to use double in logSizeQuotaPercentage. 
This change fixes that
=> Change logSizeQuotaPercentage from int to double

test/src/test/java/org/corfudb/runtime/collections/DiskBackedCorfuClientTest.java
Add the previously omitted test for disk-backed CorfuTable.
Description:
=> Add DiskBackedCorfuClientTest

runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java, runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java, test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTrimTest.java
This patch fixes a bug that gets triggers when IStreamView is being
consumed directly. When initializing a stream, the condition which
dictates when a checkpoint should be loaded needs to take into account
that a stream has been previously seek-ed to some valid address.
Description:
=> Change checkpoint initialization logic

it/src/main/java/org/corfudb/universe/universe/vm/VmManager.java
Description:
Make VmManager more reliable in terms of catching runtime exceptions from ViJava lib
=> Make VmManager more reliable in terms of catching runtime exceptions 

runtime/src/main/java/org/corfudb/runtime/collections/PersistedStreamingMap.java, runtime/src/main/java/org/corfudb/runtime/collections/RocksDbEntryIterator.java, runtime/src/main/java/org/corfudb/runtime/collections/WrappedRocksIterator.java, runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java, test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java, test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTest.java, test/src/test/java/org/corfudb/runtime/collections/RocksDbEntryIteratorTest.java
This patch fixes a bug where the iterator is accessed after it
has been closed, which ends up causing a segfault.
Description:
=> PersistedStreamingMap SIGSEGV Fix

runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java
Description: When there are no secondary indexes, this log message is unnecessary.
=> Do not log empty secondary indexes when creating CorfuTable.

runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java, runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java
Although RocksDB iterators get closed automatically by finalize,
they should be closed right after they are no longer needed and
not relay on the Java's GC to release those resources.
Why should this be merged: Avoids GC-Finalize lag to release
native memory.  
=> Explicit close

runtime/src/main/java/org/corfudb/runtime/collections/CorfuStreamEntry.java, runtime/src/main/java/org/corfudb/runtime/collections/StreamListener.java, runtime/src/main/java/org/corfudb/runtime/collections/StreamingSubscriptionContext.java, test/src/test/java/org/corfudb/integration/StreamingIT.java
Consumers of the streaming api need the epoch to
reconstruct the token that represents a Corfu snapshot. 
So modify streaming api to support epoch info too.
Table.clear() is a supported UFO operation.
This must be sent to streaming api too so that it can be handled appropriately.
=> CorfuStore: Add epoch, CLEAR to streaming API

test/src/test/java/org/corfudb/runtime/view/StreamViewTest.java
Fix a faulty test case in StreamViewTest.
=> GC: Fix a faulty test case in StreamViewTest.

corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowser.java, runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java, runtime/src/main/java/org/corfudb/util/serializer/DynamicProtobufSerializer.java, test/src/test/java/org/corfudb/integration/AbstractIT.java, test/src/test/java/org/corfudb/integration/CorfuStoreBrowserIT.java
RegistryTable is a system table that does not need the
DynamicProtobufSerializer, so the printTable must handle
this differently otherwiser it will hit this exception
java.lang.ClassCastException:
org.corfudb.runtime.CorfuStoreMetadata$TableName cannot be cast to
org.corfudb.runtime.collections.CorfuDynamicKey
Related issue(s) (if applicable): #2378
=> CorfuStoreBrowser: fix RegistryTable printTable bug

runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
Remove redundant lock validation as the exclusive write lock is already held.
=> Redundant stamped lock validation.

infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java, it/src/main/java/org/corfudb/universe/universe/docker/FakeDns.java, runtime/src/main/java/org/corfudb/runtime/ViewsGarbageCollector.java, runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java, runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java, runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java, runtime/src/main/java/org/corfudb/runtime/view/QuorumFuturesFactory.java, runtime/src/main/java/org/corfudb/runtime/view/SealServersHelper.java, runtime/src/main/java/org/corfudb/util/CFUtils.java, runtime/src/main/java/org/corfudb/util/Utils.java, test/src/test/java/org/corfudb/AbstractCorfuTest.java, test/src/test/java/org/corfudb/runtime/utils/ExceptionContextTest.java
=> Retain caller's context when unwrapping exceptions

it/src/main/java/org/corfudb/universe/UniverseManager.java, it/src/main/java/org/corfudb/universe/logging/LoggingParams.java, it/src/main/java/org/corfudb/universe/node/server/AbstractCorfuServer.java, it/src/main/java/org/corfudb/universe/node/server/CorfuServer.java, it/src/main/java/org/corfudb/universe/node/server/CorfuServerParams.java, it/src/main/java/org/corfudb/universe/node/server/docker/DockerCorfuServer.java, it/src/main/java/org/corfudb/universe/node/server/process/CorfuProcessManager.java, it/src/main/java/org/corfudb/universe/node/server/process/CorfuServerPath.java, it/src/main/java/org/corfudb/universe/node/server/process/ProcessCorfuServer.java, it/src/main/java/org/corfudb/universe/node/server/vm/VmCorfuServer.java, it/src/main/java/org/corfudb/universe/scenario/fixture/Fixtures.java, it/src/main/java/org/corfudb/universe/universe/AbstractUniverse.java, it/src/main/java/org/corfudb/universe/universe/docker/DockerUniverse.java, it/src/main/java/org/corfudb/universe/universe/process/ProcessUniverse.java, it/src/main/java/org/corfudb/universe/universe/vm/VmUniverse.java
This change allows collecting Corfu cluster logs into a `target` directory, which improves the convenience of debugging the universe tests.  
Description:
=> Universe framework: collect server logs

runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java
Fixes fork join pool size bug.
Why should this be merged: fixes bug.
=> CorfuTable Thread Pool Sizing Bug

runtime/src/main/java/org/corfudb/runtime/collections/CorfuQueue.java, test/src/test/java/org/corfudb/runtime/collections/CorfuQueueTest.java, test/src/test/java/org/corfudb/runtime/concurrent/CorfuQueueTxTest.java
This is to preserve order if checkpointer runs first.
Checkpointer uses a normal HashMap and not a LinkedHashMap
causing a loss of ordering if it runs first.
Fix is to sort the entries first.
This also enables the api to allow entries to be returned
only after a user specified previous entry.
Description:
Related issue(s) (if applicable): #2454
=> CorfuQueue: Sort entries before returning in entryList()

runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java, runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java, runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
Description:
Unblock systemDownHandler if WrongClusterException 
If a node has been added to a cluster the existing
clients should exit early so they can be restarted.
Currently they just spin in systemDownHandler.
Related issue(s) (if applicable): #2409
=> Runtime: exit systemDownHandler on WrongClusterException

runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java, runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java, test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTrimTest.java
When StreamView is being consumed directly, its trim mark will change
due to externally triggered calls to gc(...). Even when the read range
is above the trim mark, TrimmedException will be thrown because
getCheckpoint().startAddress < trimMark.
Description:
=> Change how StreamView interacts with its trim mark

corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowser.java, runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java, runtime/src/main/java/org/corfudb/runtime/collections/Table.java, runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java, runtime/src/main/java/org/corfudb/util/serializer/ProtobufSerializer.java, test/src/test/java/org/corfudb/integration/CorfuStoreIT.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreTest.java
Description:
This is to help QE with their build to build upgrades.
Updating the schema on openTable allows them to migrate to
a new protobuf version without having to redeploy their setups.
Disk based tables are too huge to be iterated by conventional methods like `entrySet()`
This is the only way a large table that won't fit in memory can be reasonably iterated.
Switched browser to use this existing api speeds it up several fold.
=> CorfuStore: Build-to-Build upgrade support

runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java, test/src/test/java/org/corfudb/integration/LargeWriteIT.java
- When set during serialization and deserialization, the LogData
lastKnownSize is set to different values. It is also inaccurate
as it is set to ByteBuf's internal array length during serialization,
which is usually larger the actually (it is dynamically resized and
usually 2x of previous size). It needs to be set to the payload's
serialized size. This incorrect behavior affects transaction size
limit calculation, which results in unnecessary WriteSizeException.
- Also fixed a test where compression should be ruled out.
Related issue(s) (if applicable): #2235
=> Fix LogData lastKnownSize which is inaccurate and inconsistent.

runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java, test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
Description:
When a stream is being consumed directly (remaining/remainingUpTo
in the StreamViews), the readCpQueue is not being cleared.
If on the first access there is a valid CP to load from, the addresses
belonging to it will always remain in memory in the readCPQueue.
If other entries are found, these will be read along the ones in the readCPQueue (always,
as they're not cleared), when they're trimmed we will throw a TrimmedException on an old CP.
Why should this be merged:  TrimmedExceptions being thrown on direct stream access, provokes application restarts in a cycle.
=> Fix Trim Exception on Raw Stream Access

runtime/src/main/java/org/corfudb/runtime/collections/CorfuQueue.java, runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java, runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java, runtime/src/main/java/org/corfudb/runtime/object/transactions/SnapshotTransactionalContext.java, runtime/src/main/java/org/corfudb/runtime/object/transactions/TransactionalContext.java, runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java, test/src/test/java/org/corfudb/runtime/collections/CorfuQueueTest.java, test/src/test/java/org/corfudb/runtime/concurrent/CorfuQueueTxTest.java
The Queue needs to capture the exact address its entries were
written to, so it can then order its entries, of its orderless
hashmap (corfuTable), in the same order that its transactions
materialized.
To do this register a preCommitCallback that intercepts the
Sequencer's blessed tokenResponse and fills it up into
the payload of the fields of the Queue.
+ Randomize sleep in test case to catch out of order reliably.
Add test case for both inorder and out of order between enqueue op and txEnd.
Co-authored-by: Xiaoqin Ma <maxiaoqin2005@gmail.com>
=> CorfuQueue: Capture commit token & fix up Queue for ordering

runtime/src/main/java/org/corfudb/runtime/collections/CorfuQueue.java, runtime/src/main/java/org/corfudb/runtime/exceptions/TrimmedException.java, runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java, runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java, runtime/src/main/java/org/corfudb/runtime/object/transactions/SnapshotTransactionalContext.java, runtime/src/main/java/org/corfudb/runtime/object/transactions/TransactionalContext.java, runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java, test/src/test/java/org/corfudb/runtime/collections/CorfuQueueTest.java, test/src/test/java/org/corfudb/runtime/concurrent/CorfuQueueTxTest.java
Description:
The Queue needs to capture the exact address its entries were
written to, so it can then order its entries, of its orderless
hashmap (corfuTable), in the same order that its transactions
materialized.
To do this register a preCommitCallback that intercepts the
Sequencer's blessed tokenResponse and fills it up into
the payload of the fields of the Queue.
+ Randomize sleep in test case to catch out of order reliably.
Add test case for both inorder and out of order between enqueue op and txEnd.
Co-authored-by: Xiaoqin Ma <maxiaoqin2005@gmail.com>
Fix Trimmed Addresses Message (#2483)
=> CorfuQueue: preCommitCallbacks to capture txn address [BPORT 3.0.0]

runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
Description:
LogData class generates a huge amount of messages in the log.  
The warnings are useless, should be disabled.
FYI:
in a test that writes 3m records, the warning appeared 100k times.
=> Don't write a warning to the log when LogData size is unknown

infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
Description:
Don't print LogUnitServer messages for getter methods which don't change the state
=> Don't print LogUnitServer messages for getter methods

runtime/src/main/java/org/corfudb/runtime/object/StreamViewSMRAdapter.java, runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java, runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractContextStreamView.java, runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java, runtime/src/main/java/org/corfudb/util/serializer/Serializers.java, test/src/test/java/org/corfudb/protocols/logprotocol/LogEntryTest.java, test/src/test/java/org/corfudb/runtime/collections/CorfuTableTest.java, test/src/test/java/org/corfudb/runtime/concurrent/StreamSeekAtomicityTest.java, test/src/test/java/org/corfudb/runtime/view/StreamViewTest.java
Description:
When a stream's tail is a hole, VLO will try to sync up to tail but never add hole to its resolved queue, which means each sync will query sequencer again.
@lixinchengdu and I bring a workaround that adds hole to resolved queue to avoid re-sync.
=> A workaround to hole in tail issue.

docs/corfu-queue/corfu-queue-design.md, format/proto/types.proto, runtime/src/main/java/org/corfudb/runtime/collections/CorfuQueue.java, test/src/test/java/org/corfudb/runtime/collections/CorfuQueueTest.java, test/src/test/java/org/corfudb/runtime/concurrent/CorfuQueueTxTest.java
Ordering is whatever corfu transaction layer considers as ordering.
Since epoch doesn't feature there, remove epoch from Queue.
Also remove UUID and expose a toByteArray() for serialization of CorfuQueueId instead for cleaner abstraction.
Description:
=> CorfuQueue: Don't use epoch for ordering

docs/corfu-queue/corfu-queue-design.md, format/proto/types.proto, runtime/src/main/java/org/corfudb/runtime/collections/CorfuQueue.java, test/src/test/java/org/corfudb/runtime/collections/CorfuQueueTest.java, test/src/test/java/org/corfudb/runtime/concurrent/CorfuQueueTxTest.java
Description:
backport PR 
https://github.com/CorfuDB/CorfuDB/pull/2501
=> Remove epoch from Queue [Backport to corfu-0.3.0]

runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java, test/src/test/java/org/corfudb/runtime/collections/CorfuTableTest.java
CorfuTable values() API is inherited from Java Map interface, which
is not supposed to perform deduplication on return. If CorfuTable
contains duplicates in values, the current values() API would return
less values than expected. This patch fixes the API to return an
immutable list instead of a set.
Related issue(s) (if applicable): #2489
=> Fix CorfuTable values() API that incorrectly deduplicates on return.

runtime/src/main/java/org/corfudb/runtime/collections/CorfuQueue.java, test/src/test/java/org/corfudb/runtime/concurrent/CorfuQueueTxTest.java
Putting a generic type inside another class
doesn't work well with the shallow Gson Json serializer although it works with some.
Since we can't control which serializer the vertical will use 
avoid the random deserialization mishap by embedding
the ordering into the key which is an internal
type.
Description:
=> CorfuQueue: Don't embed generic types

runtime/src/main/java/org/corfudb/runtime/collections/CorfuQueue.java, test/src/test/java/org/corfudb/runtime/concurrent/CorfuQueueTxTest.java
Putting a generic type inside another class
doesn't work well with the shallow Gson Json serializer.
Avoid the deserialization mishap by embedding
the ordering into the key which is an internal
type.
Description:
=> CorfuQueue: Don't embed generic types [backport to 3.0.1]

log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuInterClusterReplicationServer.java, log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationSiteManagerAdapter.java, log-replication/src/main/java/org/corfudb/logreplication/send/LogEntrySender.java, log-replication/src/main/java/org/corfudb/logreplication/send/LogReplicationPendingEntry.java, log-replication/src/main/java/org/corfudb/logreplication/send/LogReplicationSenderBuffer.java, log-replication/src/main/java/org/corfudb/logreplication/send/LogReplicationSenderQueue.java, test/src/test/java/org/corfudb/LogReplicationTest.java, test/src/test/java/org/corfudb/integration/CorfuReplicationSiteConfigIT.java, test/src/test/java/org/corfudb/integration/SourceForwardingDataSender.java
* Simplfy the LogEntrySender logic.
* Start siteManager while DiscoveryService is up.
Description:
=> Add the LogReplicationSenderBuffer mechanism.

infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServerNode.java, test/src/test/java/org/corfudb/infrastructure/CorfuServerNodeTest.java
Description:
Global variable **bindFuture** might not be initialized if bindServer throws a UnrecoverableCorfuInterruptedError. Since shutdown hooker will call close method, it will throw NullPointerException and get caught by Tanuki.
Added check for null and a simple unit test.
=> Check Null in close of CorfuServerNode

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/NegotiatingState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/VerifyingRemoteLeaderState.java
Description:
If negotiation fails due to version or topologyConfigId mismatch
the behavior will be to retry negotiation.
=> Correct Behavior of Failed Negotiation

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/sample/GRPCLogReplicationServerHandler.java
Because of summarized ACKS, for replication we need to keep around all stream observers and flush on ACK all observers equal or lower than the outgoing response.
=> GRPC keep stream observers for all messages

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/TopologyDescriptor.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultClusterManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/LogReplicationPluginConfig.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SnapshotSender.java, runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java, test/src/test/java/org/corfudb/integration/CorfuReplicationSiteConfigIT.java
Description:
- Because topology is provided by an external adapter we should support multiple
active/standby clusters or non-active/standby as being provided externally.
Why should this be merged: this is an issue for current Site Manager as no active cluster and multiple standby's are part of valid configurations.
=> Support any combination of standby/active clusters from Manager

infrastructure/src/main/java/org/corfudb/infrastructure/LogReplicationServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SnapshotSender.java, runtime/src/main/java/org/corfudb/protocols/wireprotocol/logreplication/LogReplicationEntryMetadata.java
Description:
On receiver startup the topologyConfigId needs to be initialized
or received messages will be filtered out due to different topology
config id when compared to the one in the message.
Why should this be merged: Bug Fix, when starting on a topologyConfigId != 0 all messages are dropped by the receiver.
=> Startup TopologyConfigId Fix Receiver

infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java, infrastructure/src/main/resources/logback.prod.xml
If not flushed, some crucial logs can be lost.
Why should this be merged: Improves debuggability 
Related issue(s) (if applicable): #2611
=> Flush Async Logger on Exit

runtime/src/main/java/org/corfudb/runtime/exceptions/TrimmedException.java, runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java, runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java
When read option is set to ignoreTrim and non cacheable, removeFromQueue
will throw NPE when encountering TrimmedException and trying to get the
trimmed addresses list from TrimmedException.
Why should this be merged:  Fix NPE
=> Fix NullPointerException in StreamView.

runtime/src/main/java/org/corfudb/runtime/exceptions/TrimmedException.java, runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java, runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java
Description:
Backporting for 0.3.0.2
When read option is set to ignoreTrim and non cacheable, removeFromQueue
will throw NPE when encountering TrimmedException and trying to get the
trimmed addresses list from TrimmedException.
=> [Corfu-0.3.0.2] Fix NullPointerException in StreamView.

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/TopologyDescriptor.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultClusterManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/StreamsSnapshotWriter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/CorfuLogReplicationRuntime.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/utils/CorfuMessageConverter.java, test/src/test/java/org/corfudb/integration/CorfuReplicationClusterConfigIT.java, test/src/test/resources/logback-test.xml
Description:
Add Log Replication Cluster Role ITs
* Modified Default Cluster Manager to support process-based ITs
* Removed current CorfuReplicationSiteConfigIT, since it won't work on Travis.
Related issue(s) (if applicable): #2627
=> Add Log Replication Cluster Role ITs

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InSnapshotSyncState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/LogReplicationFSM.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/TestDataSender.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/TestSnapshotReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SenderBufferManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SnapshotSender.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/StreamsSnapshotReader.java, runtime/src/main/java/org/corfudb/protocols/wireprotocol/logreplication/LogReplicationEntryMetadata.java, test/src/test/java/org/corfudb/infrastructure/logreplication/LogReplicationFSMTest.java, test/src/test/java/org/corfudb/integration/LogReplicationAbstractIT.java
Description:
- Fix Intermittent Failure on FSM Unit Test
- Fix onSnapshotEnd condition to check for an ack SNAPSHOT_END instead of SNAPSHOT_REPLICATED (intermediate acks)
Why should this be merged: stabilize log replication master branch
=> Fix FSM Unit Test and Snapshot Plugin Condition

corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowser.java, corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserMain.java, test/src/test/java/org/corfudb/integration/CorfuStoreBrowserIT.java
Using corfu browser we can now load data into a dummy table.
This is useful for testing checkpoint issues as well as live testing log-replication feature
Description:
=> Add option to load data into corfu table

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/TestLogEntryReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/IllegalTransactionStreamsException.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/LogEntrySender.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/LogReplicationError.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SnapshotSender.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/LogEntryReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/SnapshotReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/StreamsLogEntryReader.java, runtime/src/main/java/org/corfudb/protocols/logprotocol/OpaqueEntry.java, test/src/test/java/org/corfudb/integration/LogReplicationIT.java, utils/src/main/java/org/corfudb/utils/lock/LockClient.java, utils/src/main/java/org/corfudb/utils/lock/states/HasLeaseState.java
Description:
Allow replication when a transaction is executed across
replicated and non-replicated streams. Filter out the streams
of interest and disregard all other streams.
=> Log Entry Sync allow mixed Transactions

infrastructure/proto/log_replication_metadata.proto, infrastructure/src/main/java/org/corfudb/infrastructure/LogReplicationServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryServiceAdapter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/CorfuReplicationClusterManagerAdapter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/CorfuReplicationClusterManagerBaseAdapter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationAckReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationSourceManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/LogReplicationFSM.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/TestDataSender.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/TestSnapshotReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogEntryWriter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/SnapshotSinkBufferManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/LogEntrySender.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/LogEntrySenderBufferManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SenderBufferManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SnapshotSender.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SnapshotSenderBufferManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/SnapshotReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/CorfuLogReplicationRuntime.java, runtime/src/main/java/org/corfudb/protocols/wireprotocol/logreplication/LogReplicationEntryMetadata.java, test/src/test/java/org/corfudb/infrastructure/logreplication/LogReplicationFSMTest.java, test/src/test/java/org/corfudb/integration/AckDataSender.java, test/src/test/java/org/corfudb/integration/LogReplicationIT.java
Add support on non-leader active node to respond to queries for Replication Status.
Description:
The leader on the active site keeps an up-to-date in-memory copy of the last ACK received.  A thread periodically reads this ACK value and updates the replication completion status in the metadata table, which is shared among cluster members.  On receiving a query for the replication status, any node(leader or not) can read the metadata table and get the completion  status.
#2624 
=> Support queryReplicationStatus() on non-leader Active Node.

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationSourceManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogEntrySinkBufferManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogEntryWriter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/StreamsSnapshotWriter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/LogReplicationHandler.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/StoppedState.java, runtime/src/main/java/org/corfudb/runtime/view/stream/OpaqueStream.java, test/src/test/java/org/corfudb/integration/ReplicationReaderWriterIT.java, utils/src/main/java/org/corfudb/utils/lock/LockClient.java, utils/src/main/java/org/corfudb/utils/lock/states/HasLeaseState.java, utils/src/main/java/org/corfudb/utils/lock/states/LockState.java
Description:
Add a dedicated executor for lock acquired monitoring. The reason is that sharing the executor with the lease renewal task can lead to a blocking scenario, where if lease renewal task is stuck, lock client would not expire on the current lock (already lost). 
Why should this be merged: fixes a potential bug when lease renewal is stuck.
=> Dedicated Executor for acquired lock monitoring

test/src/test/java/org/corfudb/infrastructure/logreplication/LogReplicationFSMTest.java, test/src/test/java/org/corfudb/infrastructure/logreplication/LogReplicationTest.java, test/src/test/java/org/corfudb/integration/CorfuReplicationReconfigurationIT.java, test/src/test/java/org/corfudb/integration/CorfuReplicationTrimIT.java, test/src/test/java/org/corfudb/integration/DefaultDataControl.java, test/src/test/java/org/corfudb/integration/LockIT.java, test/src/test/java/org/corfudb/integration/LogReplicationAbstractIT.java, test/src/test/java/org/corfudb/integration/LogReplicationIT.java, test/src/test/java/org/corfudb/integration/ReplicationReaderWriterIT.java, test/src/test/java/org/corfudb/integration/SourceForwardingDataSender.java, test/src/test/java/org/corfudb/integration/StreamAddressDiscoveryIT.java, test/src/test/java/org/corfudb/runtime/view/stream/OpaqueStreamTest.java, test/src/test/java/org/corfudb/utils/TestLockListener.java
Move log statements to a logger (instead of printing to stdout).
Why should this be merged: Reduces log pollution during testing.
=> Use Logger Instead Of Printing to stdout

test/src/test/java/org/corfudb/integration/LockIT.java, test/src/test/java/org/corfudb/utils/TestLockListener.java
Description: this change modifies the assertion of a test to avoid intermittent failures.
Why should this be merged: fix an intermittently failing test
Related issue(s) (if applicable): #2689
=> Fix testSingleLockClient intermittent failure

infrastructure/src/main/java/org/corfudb/infrastructure/LogReplicationServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuInterClusterReplicationServerNode.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/TopologyDescriptor.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/LogReplicationHandler.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/LogReplicationServerRouter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/VerifyingRemoteLeaderState.java, utils/src/main/java/org/corfudb/utils/lock/LockClient.java, utils/src/main/java/org/corfudb/utils/lock/states/HasLeaseState.java
Description:
- Fix a NPE that we hit on stopLogReplication when an invalid topology is provided onProcessNotificationUpdate. 
- Shutdown Corfu Log Replication Service whenever Discovery Service is terminated. 
- Fix some logs to improve current readability/debugging
Why should this be merged: fix some ongoing bugs in LR
=> Fix NPE & Shutdown Server for UnrecoverableErrors

runtime/src/main/java/org/corfudb/runtime/collections/CorfuQueue.java, test/src/test/java/org/corfudb/runtime/collections/CorfuQueueTest.java
Since CorfuQueue::enqueue depends on a transactional context to
work correctly, a validation step is required to fail enqueue
calls that are not within a transaction.
Why should this be merged: Porting #2712
=> Fail Non-Transactional Enqueue

runtime/src/main/java/org/corfudb/protocols/logprotocol/SMREntry.java, runtime/src/main/java/org/corfudb/runtime/collections/CorfuQueue.java, runtime/src/main/java/org/corfudb/util/serializer/CorfuQueueSerializer.java, runtime/src/main/java/org/corfudb/util/serializer/Serializers.java, test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTest.java, test/src/test/java/org/corfudb/runtime/collections/CorfuQueueTest.java, test/src/test/java/org/corfudb/runtime/concurrent/CorfuQueueTxTest.java
Since this queue is designed to be used with protobufs, this patch
removes Java generics from the API and uses ProtoBuf's ByteString
instead. Fixing the queue type will allow us to serialize the queues
SMREntries much more efficiently.
The benchmarks below show how different serializers perform
with different payload sizes.
4MB Payload
Benchmark                           Mode  Cnt    Score    Error  Units
JsonBenchmark.GoogleGson           thrpt    5    0.818 ±  0.157  ops/s
JsonBenchmark.ObjectOutputStream   thrpt    5  336.744 ± 54.049  ops/s
JsonBenchmark.QueueSerializer      thrpt    5  358.410 ±  9.058  ops/s
8MB Payload
Benchmark                           Mode  Cnt    Score    Error  Units
JsonBenchmark.kryoSerializer       thrpt    5  116.545 ± 72.152  ops/s …
=> Remove Java Generics From CorfuQueue's API

runtime/src/main/java/org/corfudb/protocols/logprotocol/SMREntry.java, runtime/src/main/java/org/corfudb/runtime/collections/CorfuQueue.java, runtime/src/main/java/org/corfudb/util/serializer/CorfuQueueSerializer.java, runtime/src/main/java/org/corfudb/util/serializer/Serializers.java, test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTest.java, test/src/test/java/org/corfudb/runtime/collections/CorfuQueueTest.java, test/src/test/java/org/corfudb/runtime/concurrent/CorfuQueueTxTest.java
Since this queue is designed to be used with protobufs, this patch
removes Java generics from the API and uses ProtoBuf's ByteString
instead. Fixing the queue type will allow us to serialize the queues
SMREntries much more efficiently.
This patch adds a new queue serializer that is backwards compatible
with Serializers.JSON, it should just work without migration.
The benchmarks below show how different serializers perform
with different payload sizes.
4MB Payload
Benchmark                           Mode  Cnt    Score    Error  Units
JsonBenchmark.GoogleGson           thrpt    5    0.818 ±  0.157  ops/s
JsonBenchmark.ObjectOutputStream   thrpt    5  336.744 ± 54.049  ops/s
JsonBenchmark.QueueSerializer      thrpt    5  358.410 ±  9.058  ops/s
8MB Payload
Benchmark …
=> Remove Java Generics From CorfuQueue's API + New Queue Serializer

infrastructure/src/main/java/org/corfudb/infrastructure/BatchProcessor.java, runtime/src/main/java/org/corfudb/protocols/wireprotocol/StreamsAddressResponse.java, runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java, runtime/src/main/java/org/corfudb/runtime/view/Layout.java, runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java, runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java, runtime/src/main/java/org/corfudb/runtime/view/stream/StreamAddressSpace.java, runtime/src/main/java/org/corfudb/util/Utils.java, test/src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java, test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java, test/src/test/java/org/corfudb/integration/ServerRestartIT.java, test/src/test/java/org/corfudb/integration/StreamAddressDiscoveryIT.java, test/src/test/java/org/corfudb/runtime/utils/UtilsTest.java, test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java, test/src/test/java/org/corfudb/runtime/view/stream/StreamAddressSpaceTest.java
Prior to this patch, the global tail, stream tails and stream bit
sets were retrieved and computed from the first node in the last
segment. This assumption is incorrect because it can be a node
that is being rebuilt (via state transfer), or in some edge cases
it is not possible to compute the sequencer state from a single node.
This leads to the possibility of computing a view of the log that
is incomplete during reconfiguration of the sequencer. In
consequence, leading to inconsistent reads, data loss and
cluster instability.
This patch introduces multiple fixes to compute the sequencer's
state from all the segments (possibly aggregating views from different
nodes) and forcing the view computation and the reconfiguration to
happen on the same epoch.
Port #2715
=> Sequencer Reconfiguration Corruption Fixes

runtime/src/main/java/org/corfudb/protocols/wireprotocol/DataType.java, runtime/src/main/java/org/corfudb/protocols/wireprotocol/ILogData.java, runtime/src/main/java/org/corfudb/protocols/wireprotocol/IMetadata.java, runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java, runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java.rej, runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java, runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java, runtime/src/main/java/org/corfudb/runtime/view/replication/ChainReplicationProtocol.java, runtime/src/main/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocol.java, runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java, test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java
Description:
Backport for Corfu-0.3.0.2
Stream write path performance optimization.
- Reuse serialization handle, which reduces number of serializations.
- Acquire token after payload serialized, which reduces reader wait time.
=> [Corfu- 0.3.0.2] Write path optimization

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/LogReplicationFSM.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/CorfuDataSender.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/LogEntrySender.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SenderBufferManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SnapshotSender.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/CorfuLogReplicationRuntime.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/NegotiatingState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/ReplicatingState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/VerifyingRemoteLeaderState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/WaitingForConnectionsState.java, test/src/test/java/org/corfudb/integration/LogReplicationIT.java
Description:
Catch TimeoutExceptions correctly as these are wrapped by the CompletableFuture in an ExecutionException.
Why should this be merged: functional bug
=> LR Fix Timeout Exceptions

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationSourceManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/utils/LogReplicationStreamNameTableManager.java, utils/src/main/java/org/corfudb/utils/lock/states/NoLeaseState.java
Description:
Due to the clustering workflow constraints in the production environment, we have to restart the LR once the WCE is hit. This patch registers systemDownHandler on the CorfuRuntime and calls it every time WCE is hit. This should shut down LR JVM that will subsequently get restarted.
=> Register System.exit for systemDownHandler for LR CorfuRuntime 

infrastructure/src/main/java/org/corfudb/infrastructure/LogReplicationServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryServiceAdapter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/CorfuReplicationClusterManagerAdapter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/CorfuReplicationClusterManagerBaseAdapter.java
Description:
We hit a NPE when SiteMgr plugin calls prepareToBecomeStandby and no localDescriptor is defined.
Removing this API as we no longer have any specific actions on this call (it evolved from the initial design).
Why should this be merged: bug found in actual setups
=> NPE in prepareToBecomeStandby

infrastructure/src/main/java/org/corfudb/infrastructure/LogReplicationServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java, runtime/src/main/java/org/corfudb/util/Utils.java
Description:
SinkBufferManager has a field `lastProcessedSeq` to apply entry and send ACK. It is initialized when the discovery service starts.
When a non-leader node acquires the lock, `lastProcessedSeq` is very likely outdated, and won't process new entries.
Fix bug.
=> Reset SinkBufferManager on negotiation

codecov.yml
Description:
Disable codecov/patch status which measures lines adjusted in the pull request and leave only codecov/project status which measures overall project coverage and compares it against the base of the pull request or parent commit.
=> Disable Codecov Patch

runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java, runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java, test/src/test/java/org/corfudb/integration/CorfuLongRunningClientIT.java
Description:
Handle sync of non-transactional access under lock even in the event
of TrimmedExceptions, otherwise, thread interleaving may lead to inconsistent state.
Why should this be merged: existing bug which manifests in intermittent data loss.
=> Non-Transactional Access Trim Exception Handling

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/TopologyDescriptor.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationAckReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationSourceManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InLogEntrySyncState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InSnapshotSyncState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/LogReplicationFSM.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/TestLogEntryReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/LogEntrySender.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/LogReplicationError.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SenderBufferManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SenderPendingMessageQueue.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SnapshotSender.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/LogEntryReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/StreamsLogEntryReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/StreamsSnapshotReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/ReplicatingState.java, test/src/test/java/org/corfudb/integration/CorfuReplicationClusterConfigIT.java
Description:
- Calculate replicated remaining entries based on the txStream
to avoid the issue of holes enforced on regular streams by the checkpointer.
- Minor bug fix, restarted Snapshot Sync same baseSnapshot (not reject)
- Add some valuable logging for debugging
Why should this be merged: bug found in setups running checkpointing
=> Calculate Remaining Replicated Entries based on TxStream

test/src/test/java/org/corfudb/integration/StreamingIT.java
We do not have a test where a single listener subscribes to multiple tables
and verifies that updates made to those tables in a single transaction are
received in the same CorfuStreamEntry.
Why should this be merged:  Test a different usecase of the streaming layer
=> Add Test for Single Listener to Multiple Tables in StreamingIT.

runtime/src/main/java/org/corfudb/runtime/view/ConservativeFailureHandlerPolicy.java, runtime/src/main/java/org/corfudb/runtime/view/Layout.java, runtime/src/main/java/org/corfudb/runtime/view/LayoutBuilder.java, runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java, test/src/test/java/org/corfudb/infrastructure/LayoutBuilderTest.java
Description:
Log tail nodes need to serve queries, so when sequencer fails over, we
try to elect a non-tail node as the primary sequencer if possible to
have better load distribution.
Related issue(s) (if applicable): #2575
=> When sequncer fails over, elect non-tail node as primary if possible.

infrastructure/proto/sample.proto, infrastructure/src/main/java/org/corfudb/infrastructure/LogReplicationServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultLogReplicationConfigAdapter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/StreamsSnapshotWriter.java, test/src/test/java/org/corfudb/integration/CorfuReplicationE2EIT.java, test/src/test/java/org/corfudb/integration/CorfuReplicationReconfigurationIT.java, test/src/test/java/org/corfudb/integration/CorfuReplicationTrimIT.java, test/src/test/java/org/corfudb/integration/LogReplicationAbstractIT.java
Description:
Resume Snapshot Sync Apply on node restart or leadership change. 
If the lead standby node is restarted after a snapshot transfer is completed but while apply is still not completed, there is no current way to resume snapshot apply on leadership change or restart. 
Why should this be merged: potential bug
=> Resume Snapshot Sync Apply on Restart

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/LogReplicationEventListener.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultClusterManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/utils/LogReplicationStreamNameTableManager.java, runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java, runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java, runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java, runtime/src/main/java/org/corfudb/util/serializer/DynamicProtobufSerializer.java, runtime/src/main/java/org/corfudb/util/serializer/ProtobufSerializer.java, test/src/test/java/org/corfudb/integration/CorfuReplicationClusterConfigIT.java, test/src/test/java/org/corfudb/integration/CorfuReplicationReconfigurationIT.java, test/src/test/java/org/corfudb/integration/CorfuStoreBrowserIT.java, test/src/test/java/org/corfudb/integration/CorfuStoreIT.java, utils/src/main/java/org/corfudb/utils/lock/persistence/LockStore.java
LR does require TX Logging to be disabled on the standby site to avoid
generation of DCNs on replicated data and CorfuStore enforces it to be enabled.
=> CorfuStore option Tx Logging Disabled

test/src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java
Description:
Fix LogUnitServerTest flakiness
=> CICD workflow: flaky tests. Fix LogUnitServerTest flakiness

corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowser.java, corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserMain.java, runtime/proto/example_schemas.proto, runtime/src/main/java/org/corfudb/runtime/collections/CorfuQueue.java, runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java, runtime/src/main/java/org/corfudb/runtime/collections/CorfuStoreShim.java, runtime/src/main/java/org/corfudb/runtime/collections/CorfuStreamEntry.java, runtime/src/main/java/org/corfudb/runtime/collections/MetadataOptions.java, runtime/src/main/java/org/corfudb/runtime/collections/Query.java, runtime/src/main/java/org/corfudb/runtime/collections/StreamManager.java, runtime/src/main/java/org/corfudb/runtime/collections/Table.java, runtime/src/main/java/org/corfudb/runtime/collections/TableMetrics.java, runtime/src/main/java/org/corfudb/runtime/collections/TxnContext.java, runtime/src/main/java/org/corfudb/runtime/collections/TxnContextShim.java, runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java, samples/src/main/java/org/corfudb/samples/CorfuStoreSample.java, test/src/test/java/org/corfudb/infrastructure/logreplication/LogUpdateAPITest.java, test/src/test/java/org/corfudb/integration/CorfuStoreBrowserIT.java, test/src/test/java/org/corfudb/integration/CorfuStoreIT.java, test/src/test/java/org/corfudb/integration/CorfuStorePerfIT.java, test/src/test/java/org/corfudb/integration/StreamingIT.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreShimTest.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreTest.java, test/src/test/java/org/corfudb/runtime/collections/DiskBackedCorfuClientTest.java, utils/src/main/java/org/corfudb/utils/lock/persistence/LockStore.java
Description:
1. Adds Queue Api (not implementation)
2. Fix stream tails to be supported without opening the table
3. Fixes null pointer in Corfu browser when the metadata is null
=> CorfuStore: Queue API, Stream Tails, CorfuBrowser null pointer fix

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultLogReplicationConfigAdapter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/ILogReplicationConfigAdapter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/utils/LogReplicationStreamNameTableManager.java
Description:
Log Replication should stop if the plugin fails to fetch important info
such as streams to replicate and version.
Why should this be merged: Better Error Handling
=> Stop Log Replication if Plugin fails to read the configuration.

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultLogReplicationConfigAdapter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/ILogReplicationConfigAdapter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/utils/LogReplicationStreamNameTableManager.java
Log Replication should stop if the plugin fails to fetch important info
such as streams to replicate and version.
Co-authored-by: Anny Martinez <annymartinez.m@gmail.com>
Cherry-picks: #2814 
Related issue(s) (if applicable): #2814
=> Stop Log Replication if Plugin fails to read the configuration. (#2814)

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultClusterManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/utils/LogReplicationStreamNameTableManager.java, test/src/test/java/org/corfudb/integration/CorfuReplicationReconfigurationIT.java, utils/src/main/java/org/corfudb/utils/lock/persistence/LockStore.java
Description: Enable Tx Logging for LR. 
Why should this be merged: UI relies on Tx logging updates to refresh UI content. Currently, UI does not reflect replicated data.
=> Enable Tx Logging Back on Standby

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
Description:
Fix LR NPE when queryReplicationStatus is called and cluster configuration has still not been set by external configuration provider (Cluster Manager).
Why should this be merged: avoid NPE
=> [Port 0.3.1.1] Fix NullPointerException in queryReplicationStatus 

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/LogReplicationEvent.java, runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java, runtime/src/main/java/org/corfudb/util/Utils.java
In CorfuDB UUIDs are mostly used for logging purposes, thus true
randomness is not required. Using UUID.randomUUID for transaction
IDs can be really slow because it uses secureRandom. This patch
uses a PRNG to generate those ids much faster.
Why should this be merged: Reduces the `Transaction::begin` time by up to 50+ milliseconds
=> Use A PRNG for ID Generation

infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServerCache.java
Changed evict logs to trace.
Why should this be merged: Polluting server logs when debug is enabled
=> Change Sequencer Cache Logging Level

infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServerNode.java, infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/sample/NettyLogReplicationServerChannelAdapter.java, test/src/test/java/org/corfudb/infrastructure/ServerContextBuilder.java, test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java, test/src/test/java/org/corfudb/runtime/clients/NettyCommTest.java, test/src/test/java/org/corfudb/test/concurrent/TestThreadGroups.java
This patch makes both boss and worker threads use the same
EventLoopGroup. Since CorfuDB clients tend to have long lived
connections and the rate at which new connections are made is
relatively low reusing the same thread pool for both tasks
shouldn't impact performance.
Why should this be merged: Removes unnecessary code.
=> Remove The Boss EventLoopGroup

common/src/main/java/org/corfudb/common/metrics/micrometer/JVMMetrics.java, common/src/main/java/org/corfudb/common/metrics/micrometer/MeterRegistryProvider.java, runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
Excessive JVM pauses can adversely affect the fault detection system
rendering the cluster instable because of unnecessary reconfigurations.
Safepoint metrics are crucial for debugging such problems, so this patch
adds safe point stats to the standard collection process.
Why should this be merged: Improves debugging cluster instability and performance issues.
=> Collect Metrics for JVM Safe Point Stats

infrastructure/src/main/java/org/corfudb/infrastructure/IServerRouter.java, infrastructure/src/main/java/org/corfudb/infrastructure/NettyServerRouter.java, runtime/src/main/java/org/corfudb/protocols/wireprotocol/ClientHandshakeHandler.java, runtime/src/main/java/org/corfudb/protocols/wireprotocol/NettyCorfuMessageEncoder.java, runtime/src/main/java/org/corfudb/runtime/clients/BaseHandler.java, runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java, test/src/test/java/org/corfudb/infrastructure/TestServerRouter.java, test/src/test/java/org/corfudb/runtime/clients/TestChannelContext.java, test/src/test/java/org/corfudb/runtime/clients/TestClientRouter.java
It produces lots of new lines when logging the Protobuf
Messages. This modification helps to make things logged in a
cleaner way without new lines.
Description:
=> Shorten the logging of Protobuf Messages

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationAckReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InitializedState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/StoppedState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java
Description:
Handle TAE for LR sync status update
=> [backport]Handle TAE for LR sync status update

runtime/src/main/java/org/corfudb/runtime/collections/StreamManager.java
For CorfuStore streaming, If the LogData polled does not contain any table of interest, avoid decompressing and deserializing the LogData.
Why should this be merged: Address OOM issue and make it more efficient.
=> Streaming: Avoid LogData decompression if not containing any table of interest.

corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowser.java, test/src/test/java/org/corfudb/integration/CorfuStoreBrowserIT.java
If the metadata schema is null, trying to read the corresponding entry throws a NPE.  This PR fixes the issue.
=> Fix NPE thrown by browser tool when value and/or metadata are null.

infrastructure/src/main/resources/logback.prod.xml
Description:
We need to reduce the size of metrics logs in production.
=> Reduce server metrics log size

runtime/proto/corfu_options.proto, runtime/proto/example_schemas.proto, runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java, runtime/src/main/java/org/corfudb/runtime/collections/Index.java, runtime/src/main/java/org/corfudb/runtime/collections/ProtobufIndexer.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreShimTest.java
Description: 
Support access to secondary indexes through a given alias instead
of secondary index full path.
A custom alias can be specified upon protoBuf definition, otherwise the alias
defaults to the name of the last attribute in the multi-level secondary key path.
Why should this be merged: client request
=> Nested Secondary Index Alias Support

runtime/proto/queue.proto, runtime/src/main/java/org/corfudb/util/serializer/DynamicProtobufSerializer.java
Description:
1. queue.proto does not set package correctly.
2. The message name should be generated correctly without a package name.
In `DynamicProtobufSerializer`, the key in `messagesFdProtoNameMap` is `.CorfuGuidMsg` but `getFullMessageName` returns `CorfuGuidMsg` (without prefix dot)
=> Fix package name in queue.proto

infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/LogMetadata.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationAckReader.java, infrastructure/src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java, infrastructure/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java, runtime/proto/rpc_common.proto, runtime/src/main/java/org/corfudb/protocols/CorfuProtocolCommon.java, runtime/src/main/java/org/corfudb/protocols/wireprotocol/ICorfuPayload.java, runtime/src/main/java/org/corfudb/runtime/view/Address.java, runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java, runtime/src/main/java/org/corfudb/runtime/view/stream/StreamAddressSpace.java, test/src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java, test/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java, test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java, test/src/test/java/org/corfudb/integration/ServerRestartIT.java, test/src/test/java/org/corfudb/integration/StreamAddressDiscoveryIT.java, test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java, test/src/test/java/org/corfudb/runtime/utils/UtilsTest.java, test/src/test/java/org/corfudb/runtime/view/SequencerViewTest.java, test/src/test/java/org/corfudb/runtime/view/stream/StreamAddressSpaceTest.java
This refactor hides the stream's bitmap implementation from the
consumers. It also improves code robustness and fixes some bugs
related to directly consuming the bitmap. Furthermore, this change will
allow for easily changing the implementation to optimize encoding
and certain APIs.
Why should this be merged: Improves code quality and allows for future optimizations.
=> Hide Stream Bitmap Implementation

runtime/src/main/java/org/corfudb/protocols/CorfuProtocolLogData.java
Since the backing array of a ByteBuf can be larger than the number of bytes written, this PR reduces unnecessary copying of data when serializing LogData into Protobuf by using appropriate bounds.
Description:
=> Reduce Protobuf LogData Payload Size

runtime/proto/corfu_options.proto, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreTest.java, test/src/test/resources/proto/sample_schema.proto
Description:
Added ownership validation table schema option
=> Add ownership validation table schema option

runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
This log error dumps the binary which is noisy and can lead to OOM in the case of applications with small heap size.
=> Remove Verbose Log Error

common/src/main/java/org/corfudb/common/metrics/micrometer/JVMMetrics.java, common/src/main/java/org/corfudb/common/metrics/micrometer/registries/LoggingMeterRegistryWithHistogramSupport.java, infrastructure/src/main/java/org/corfudb/infrastructure/BatchProcessor.java, runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- Change metrics from milliseconds to microseconds (prevents reporting
0's for sub-millisecond metrics)
- Unify cache metrics types
Why should this be merged: Improves metrics reporting
=> Improve Metrics Collection and Reporting

infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java, test/src/test/java/org/corfudb/integration/StreamingIT.java
Description:
With current code, subscribing to an empty table will cause a NPE and furthermore the subscriber
will be automatically unsubscribed, therefore, future updates are lost. Fix to this bug + test.
Why should this be merged: bug currently encountered by clients
=> Streaming API Bug Fix

runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java, test/src/test/java/org/corfudb/integration/WorkflowIT.java, test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
Removing batch size operation when adding SMR entries of a table into a checkpoint log entry during compaction.
Description:
The issue was seen when compactor tried adding 3 entries amounting to more than the standard write size of 25 MB of any type of log entry. Each log entry were less than 25MB but during checkpointing, the checkpointer was considering a batch operation on a fixed batch size of <50 SMR entries, leading to a write entry with >25MB of serialized data.
This fix would add each SMR entry until the limit is reached. And then, create a checkpoint log entry and proceed to add the next SMR entry, leading to a dynamic sized batches of SMR entries with a hard check on the size of each checkpointed log entry.
A scenario where in a customer of the DB …
=> Removing batch size on smr entries and adding a limit on smr entry serialized size

runtime/src/main/java/org/corfudb/runtime/collections/CorfuStreamEntries.java, runtime/src/main/java/org/corfudb/runtime/collections/StreamManager.java, runtime/src/main/java/org/corfudb/runtime/collections/StreamSubscription.java, test/src/test/java/org/corfudb/integration/StreamingIT.java
Description: subscribers need a means to know the last synced timestamp. If an error occurs (for instance, a poison pill) they can attempt to re-subscribe from this point (instead of having to sync the complete space or use a timestamp which could incur in data loss).  
Why should this be merged: requirement from clients.
=> StreamListener expose Timestamp for Re-Subscription

corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowser.java, corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserMain.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java, test/src/test/java/org/corfudb/integration/CorfuStoreBrowserIT.java
Description: add operation that provides visibility into the system's stream tags, to avoid abuse use and ease debugging. 
We are adding 4 new operations: listTags, listTagsMap, listTagsForTable & listTablesForTag.
Why should this be merged: required in initial stages to facilitate UFO migration.
=> CorfuBrowser tool tag support

.github/workflows/pull_request.yml, it/pom.xml
Description: The Universe Tests were getting skipped earlier unintentionally even after mentioning the maven build profile. Adding execution id and execution goals ensured that they are not skipped.
Why should this be merged: This resumes the universal tests in the GitHub Actions.
=> Fix skipping of Universe Tests in GitHub Actions

infrastructure/src/main/resources/logback.prod.xml
In  prod, when `org.apache.logging.log4j` is on the classpath, the default logger is being  created with this line:
`Logger logger = LoggerFactory.getLogger("org.corfudb.client.metricsdata");`
This logger is debug-enabled by default and inherits appenders additively from the logger hierarchy. This results in these metrics logs being logged into corfu.9000.log, which causes a lot of pollution. 
This  patch disables the logging level on this logger by default
=> Disable runtime logs on the server explicitly

common/src/main/java/org/corfudb/common/metrics/micrometer/MeterRegistryProvider.java
Description:
When the Corfu server is being reset the registry for JVM is still present, so its inaccurate to throw the exception.
=> Dont throw exception on server resets

runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java, runtime/src/main/java/org/corfudb/runtime/collections/CorfuStreamQueueEntry.java, runtime/src/main/java/org/corfudb/runtime/collections/StreamNotificationTask.java, runtime/src/main/java/org/corfudb/runtime/collections/StreamPollingTask.java, runtime/src/main/java/org/corfudb/runtime/collections/StreamSubscription.java, runtime/src/main/java/org/corfudb/runtime/collections/StreamSubscriptionMetrics.java, runtime/src/main/java/org/corfudb/runtime/collections/StreamingManager.java, test/src/test/java/org/corfudb/integration/StreamingIT.java
Description:
- Add metric to hold time spent by entries in streaming queue
- Add trace logging to ease performance/functional debugging
- Move streaming to runtime parameters to ease experimentation (tuning)
Why should this be merged:  help with performance issues in the client.
=> Instrument Streaming API

test/src/test/java/org/corfudb/infrastructure/TestServerRouter.java
Description:
Floods logs hampering debugging. Reducing to debug
=> Set TestServerRouter sendMessage to debug to reduce log flood

runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java, test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
=> [Backport] Exclude CP Entries from AddressSpaceView Cache

runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java, test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
Description:
New checkpoint entry batch policy introduced large checkpoint entry, which can be more than 25MB
Exclude all checkpoint entry from the addressSpaceView cache (read cache) to avoid OOM
=> Exclude CP Entries from AddressSpaceView Cache

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, runtime/src/main/java/org/corfudb/runtime/view/replication/ReadWaitHoleFillPolicy.java, test/src/test/java/org/corfudb/integration/CorfuReplicationClusterConfigIT.java, utils/src/main/java/org/corfudb/utils/lock/LockClient.java, utils/src/main/java/org/corfudb/utils/lock/persistence/LockStore.java, utils/src/main/java/org/corfudb/utils/lock/states/HasLeaseState.java
Description:
Fixed a bug that log replication can not stop when the distributed lock is released.
Added an IT to test lock release scenario.
Added more logging around lock state transition.
=> Log Replication: Bug fix + More Lock logging

runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java, runtime/src/main/java/org/corfudb/runtime/collections/Table.java, runtime/src/main/java/org/corfudb/runtime/collections/TableMetrics.java, runtime/src/main/java/org/corfudb/runtime/collections/TimingHistogram.java, runtime/src/main/java/org/corfudb/runtime/collections/TxnContext.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreShimTest.java, test/src/test/resources/logback-test.xml
Encapsulate the Metrics and Histograms into
TableMetrics & TimingHistogram for readable logging and abstraction.
Description:
Metrics are critical to triaging and debugging issues.
=> CorfuStore: Add Metrics with Micrometer

infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
Description: With UFO on 'open' all streams are verified against the registry table,
so there is no need to warn on unexisting streams (they exist but are empty).
Why should this be merged: Log spew
=> Reduce Sequencer Logs

runtime/src/main/java/org/corfudb/runtime/collections/TimingHistogram.java
InfluxDB convention does not allow 'time' as a key, hence we see exceptions in client logs.
=> Fix time key issue

runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractStreamContext.java, runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java, test/src/test/java/org/corfudb/integration/StreamingIT.java
Description: correct corner case for streaming API when th number of updates is zero for a listener and the runtimeGC kicks in modifying boundary conditions (gcTrimMark). 
Why should this be merged: customer bug
=> Streaming API TrimmedExceptions fix due to runtimeGC

runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java
Description:
Why should this be merged: Sometimes consumers call openTable() with differing schema definitions unintentionally which can cause tricky bugs later. To help them triage the callers, dump the full stack trace and make some noise when the schema change is detected.
=> CorfuStore: Print full stack trace if schema has changed

runtime/src/main/java/org/corfudb/protocols/logprotocol/OpaqueEntry.java, runtime/src/main/java/org/corfudb/runtime/Backup.java, runtime/src/main/java/org/corfudb/runtime/Restore.java, test/src/test/java/org/corfudb/runtime/BackupRestoreIT.java
Description:
Updated APIs to allow backup and restore all UFO tables.
Added extra logging such as elapsed time for backing up / restoring each table, and table names.
Rolling upgrade requires Corfu to back up all tables before upgrade so that they are able to roll back Corfu to a previous state if something failed after the upgrade.
=> Full backup restore and more logging

runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java, runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java, runtime/src/main/java/org/corfudb/runtime/collections/CorfuStoreMetrics.java, runtime/src/main/java/org/corfudb/runtime/exceptions/TransactionAlreadyStartedException.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreShimTest.java
Description: current getHighestSequenceNumber returns highest sequence number regardless of it being a DATA or HOLE entry. This patch allows this API to distinguish and retrieve highest sequence number of a valid DATA entry. 
Why should this be merged: client request
=> GetHighestSequenceNumber API filter HOLE entries

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationAckReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/StreamsLogEntryReader.java, runtime/src/main/java/org/corfudb/runtime/collections/StreamManager.java, runtime/src/main/java/org/corfudb/runtime/collections/StreamingManager.java, runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java, runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java, runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java, test/src/test/java/org/corfudb/integration/CorfuReplicationReconfigurationIT.java, test/src/test/java/org/corfudb/integration/LogReplicationAbstractIT.java, test/src/test/java/org/corfudb/integration/LogReplicationIT.java, test/src/test/java/org/corfudb/integration/ReplicationReaderWriterIT.java, test/src/test/java/org/corfudb/integration/StreamingIT.java, test/src/test/java/org/corfudb/runtime/view/StreamViewTest.java
Description:
Fix an incorrect TrimmedException which derives from the case of 'tagged' streams which do not receive updates over a long period of time. This leads to a state in which the last synced point (globalPointer) will fall below the log trim mark. In this case, we should not throw a TrimmedException as it is up to date and the pointer has not moved because there are no actual updates. 
- Also move LR in the direction of its own dedicated transaction stream, as this will disappear soon. 
Why should this be merged: bug fix
=> Streaming API Trim Exceptions Bug Fix - 2

runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java, runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java, test/src/test/java/org/corfudb/integration/StreamingIT.java
Description: Add new streaming subscribe API which takes a stream tag and namespace
(table names are not required).
Why should this be merged: usability / client request
=> Add Streaming API

test/src/test/java/org/corfudb/infrastructure/ReconfigurationEventHandlerTest.java, test/src/test/java/org/corfudb/runtime/CorfuRuntimeTest.java
Description: In unit test suite sealMinServerSet() is not guarded by fault detector. In some cases we expect every server in the cluster to be sealed but the test case only waits for min server set. We can use TestRules to avoid this for some cases, but ideally those relies on TestRouter needs to be refactored with mocking as it makes the unit tests not "unit".
Why should this be merged: Fixed the flaky issue in these unit tests:     
* CorfuRuntimeTest -  doesNotUpdateToLayoutWithSmallerEpoch    
* ReconfigurationEventHandlerTest - updateLayoutOnFailure
Related issue(s) (if applicable): #2853  #2915
=> Flaky unit test fix

runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
Description: Minor fix in the imports to use Java's Supplier class over guava's Supplier class.
The current implementation uses guava based Supplier, it throws IncompatibleClassChangeError when a java based supplier is passed in its place as observed in corfudb-cloud repo test cases. Though both the Suppliers are interchangeable the auto-conversion is not happening in some cases. The time() method expects the Supplier to be a Java-based one and all of its callers already use the Java-based Supplier. This PR changes it to use Java one over guava one.
=> Change LogData to use Java Supplier over guava

runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java
Returning trim mark is problematic for idle tables
since trim makr moves on every checkpoint & trim cycle
impling additional data which is not true.
Description:
=> CorfuStore: Return -1 as default for getHighestSequence()

common/pom.xml, common/src/main/java/org/corfudb/common/util/CompatibilityVectorUtils.java, infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/LogReplicationClientRouter.java, infrastructure/src/test/java/org/corfudb/infrastructure/ServerHandshakeHandlerTest.java, runtime/proto/service/corfu_message.proto, runtime/src/main/java/org/corfudb/protocols/service/CorfuProtocolMessage.java, runtime/src/test/java/org/corfudb/runtime/ClientHandshakeHandlerTest.java
Description: We introduce the compatibility vectors for communicating the information about features that are supported by the sender and receiver. We represent each feature as an enum value in a Java file and set its corresponding enum number's index to 1 in the BitSet and store it in Protobuf's ByteString format. The BitSet values will be the same across both the client and the server of a particular version.
Why should this be merged: Enables features compatibility checks for rolling upgrades.
=> Introduce Compatibility Vector for RPCs

.github/workflows/publish-corfu.yml, .github/workflows/pull_request.yml, .mvn/settings.xml, annotationProcessor/pom.xml, pom.xml, runtime/pom.xml
Description: Our traffic is exceeding the data transfer limit of JFrog free tier limit. We are migrating to Github Packages in this PR.
=> Migrate artifacts hosting from JFrog to Github Packages

common/pom.xml, infrastructure/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java, runtime/pom.xml, runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java, runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java, runtime/src/main/java/org/corfudb/runtime/view/stream/StreamAddressSpace.java, test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java, test/src/test/java/org/corfudb/runtime/view/stream/StreamAddressSpaceTest.java
Optimize StreamAddressSpace Range Operations 
This patch introduces space/runtime optimizations and makes the
following changes:
2. On trim create a suffix copy to avoid needing to call runOptimize
and trim on the bitmap
3. Replace linear scan range queries with bitwise operations
Why should this be merged: Fixes a performance bug caused by linear time range queries and improves sanity checking
prevent silent in memory corruption.
=> Optimize StreamAddressSpace Range Operations

runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java, runtime/src/main/java/org/corfudb/runtime/exceptions/WrongClusterException.java
The cluster ID is specified as a UUID in the layout, but it is being
logged as a base64 number which makes it harder to correlate the log
messages with the layout information.
Why should this be merged: Improves logging consistency and improves debugging
=> Fix Cluster Id Logs

runtime/proto/example_schemas.proto, runtime/src/main/java/org/corfudb/runtime/collections/ProtobufIndexer.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreSecondaryIndexTest.java
Description:
Fix a bug where unset 'oneOf' sub-fields throw a NullPointerException, also
verified unset fields work in the context of;
- Repeatead/Repeated indexes
- Repeated/Non-primitive 'oneOf'
- Non-repetated/Non-primitive 'oneOf'
Why should this be merged: bug reported by clients with secondary indexes
Related issue(s) (if applicable): Internal Report
=> Bug Fix nested secondary indexes for unset values

corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowser.java, corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserMain.java, runtime/pom.xml, runtime/proto/corfu_store_metadata.proto, runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java, runtime/src/main/java/org/corfudb/util/serializer/DynamicProtobufSerializer.java, test/src/test/java/org/corfudb/integration/CorfuStoreBrowserIT.java
Add Support for Editing Records in CorfuStore Tables.
Description:
Allow editing the record corresponding to a given key in a CorfuStore table.
CorfuStore tables contain records in protobuf format.  To construct a protobuf from the JSON string inputs, use type information stored in TableRegistry.
Why should this be merged: Editing an existing record is a key requirement for debugging and troubleshooting.
=> Add Support for Editing Records in CorfuStore Tables.

.github/workflows/code-coverage.yml, README.md, pom.xml
Description: This commit creates an action that generates code coverage report, and sends it to the [Codacy dashboard ](https://app.codacy.com/gh/CorfuDB/CorfuDB/dashboard?branch=codacy-codecoverage)automatically for every pull request. 
=> Create Codacy coverage reporter action

corfudb-tools/README, corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserMain.java
Fix the validation of user-provided namespace and tablename in CorfuStoreBrowserMain.
Also update the README with sample usage of the editor command.
=> Fix namespace and tableName validation in CorfuStoreBrowserMain.  Update README.

runtime/src/main/java/org/corfudb/runtime/view/stream/StreamAddressSpace.java
Description:
- Due to underlying bug in server reset: data wipe + data transfer
(data seems to be available for scan and address spaces are populated
before data transfer starts).
Why should this be merged: unblock Corfu merge (still to be brought back and fix underlying bug)
=> Remove Trim Mark Comparison in StreamAddressSpace.addAddress

.github/workflows/pull_request.yml
Description:  This patch will make compatibility test logs available in GitHub Action
=> Upload compatibility test logs to GitHub Action

runtime/src/main/java/org/corfudb/runtime/collections/StreamListener.java, runtime/src/main/java/org/corfudb/runtime/collections/StreamSubscription.java, test/src/test/java/org/corfudb/integration/StreamingIT.java
Description: to be compliant with the former behavior of the streaming (DCN) api, updates within the same transaction boundary should be de-duplicated for correct streaming processing. 
Why should this be merged: bug in clients (change of behavior)
=> Deduplicate Stream Updates for same keys within a transaction

runtime/proto/example_schemas.proto, runtime/src/main/java/org/corfudb/runtime/collections/ManagedTxnContext.java, runtime/src/main/java/org/corfudb/runtime/collections/StreamListenerResumeOrDefault.java, runtime/src/main/java/org/corfudb/runtime/collections/StreamListenerResumeOrFullSync.java, runtime/src/main/java/org/corfudb/runtime/collections/StreamListenerResumePolicy.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreSecondaryIndexTest.java
Description: secondary indexes on an Enum type should be queried based on the ValueDescriptor of the value of interest, this is due to the internal way that protoBuf deals with enum fields. This PR adds a test that shows the correct usage of secondary indexes on first and nested levels over an enum type (for future reference, as it is currently used by clients).
Why should this be merged: example of usage pattern and increase code coverage.
=> Add Tests for Secondary Indexes on Enum Types

runtime/src/main/java/org/corfudb/runtime/collections/TxnContext.java, runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java, runtime/src/main/java/org/corfudb/runtime/object/transactions/TransactionalContext.java, runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java
Filling a stacktrace is expensive and using getStackTrace() for
logging a message before an exception is thrown is superfluous
because the exception being thrown already has the stack trace
filled.
Why should this be merged: Remove unnecessary logging statements that contribute to latency
=> Remove Unnecessary Debug Statements

runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java, runtime/src/main/java/org/corfudb/runtime/collections/StreamPollingTask.java
This patch removes random sleeps between polling and replaces it
with a fixed sleep duration, which makes stream polling follow a
fixed delay schedule. This also reduces the load being generated
by the pollers and makes performance more predictable.
Pre-this patch when the user specifies a poll period of 50ms, the
scheduler will use a random sleep value between [0, 50), this means
that the poller will run every 24.5ms (i.e., expected value of
Random(50)) on average, in essence doubling the frequency, which is
not expected by the user.
Why should this be merged: Performance Fix
=> Stream Polling Delay Period Fix

runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreShimTest.java
Description:
If protoBuf schema is already present, do not attempt to update definitions.
These APIs should be available on upgrade path.
Why should this be merged: current client bug, as 'options' section does not match equality (serialized compared to non-serialized) when they actually do match, leading, to TransactionAbortedException's (conflict) on startup.
=> Remove equality check on protoBuf descriptors for every openTable

corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditor.java, corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditorMain.java, test/src/test/java/org/corfudb/integration/CorfuStoreBrowserEditorIT.java
Stream Tag was not available as an input parameter to the browser/editor tool from the CLI.  Add this option.
Why should this be merged:  To support query operations based on stream tag.
=> Expose Stream Tag option as input to the Browser/Editor tool.

pom.xml, runtime/src/main/java/org/corfudb/runtime/collections/Table.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreShimTest.java, test/src/test/java/org/corfudb/runtime/concurrent/CorfuQueueTxTest.java, test/src/test/java/org/corfudb/runtime/object/CompileProxyTest.java, test/src/test/java/org/corfudb/runtime/view/replication/ChainReplicationProtocolTest.java
Description:
If we do not fail deletes on non-existent keys, that results in extra SMR operations which confuses stream listeners who aren't expecting duplicate delete operations.
=> Table: Fail delete if called on a non-existent key

pom.xml, runtime/src/main/java/org/corfudb/runtime/collections/Table.java, test/src/test/java/org/corfudb/integration/StreamingIT.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreShimTest.java, test/src/test/java/org/corfudb/runtime/concurrent/CorfuQueueTxTest.java
Description:
Need not throw an exception instead simply skip the delete operation to ensure stream listeners only receive one notification as suggested by @vjeko 
Remove unused dependency from pom.xml as suggested by @xnull 
Fixup unit test with a finally block as suggested by @xnull 
=> Table: Make delete idempotent

corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditor.java, runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiObjectSMREntry.java, runtime/src/main/java/org/corfudb/protocols/logprotocol/SMREntry.java, runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java, runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java, runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java, runtime/src/main/java/org/corfudb/util/serializer/DynamicProtobufSerializer.java, runtime/src/main/java/org/corfudb/util/serializer/Serializers.java, test/src/test/java/org/corfudb/integration/CorfuStoreBrowserEditorIT.java, test/src/test/java/org/corfudb/integration/CorfuStoreIT.java, test/src/test/java/org/corfudb/integration/LogReplicationAbstractIT.java, test/src/test/java/org/corfudb/integration/ReplicationReaderWriterIT.java, test/src/test/java/org/corfudb/integration/TransactionStreamIT.java, test/src/test/java/org/corfudb/protocols/logprotocol/LogEntryTest.java, test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java, test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTest.java, test/src/test/java/org/corfudb/runtime/object/CorfuSMRObjectProxyTest.java, test/src/test/java/org/corfudb/runtime/view/stream/OpaqueStreamTest.java, test/src/test/java/org/corfudb/util/serializer/SerializersTest.java
Different corfu runtime instances can have different custom serializers based on
the opened tables. The existing serializers is a static member shared by all
corfu runtimes in a JVM which is problematic when multiple runtimes register
their own custom serialzier.
Description:
=> Avoid sharing custom serializers among runtime instances

runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java, runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java, test/src/test/java/org/corfudb/integration/WorkflowIT.java, test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
When checkpointer batches SMR entries, comparing only serialized and compressed
entry size could cause OOM since it might read too many entries into memory before
serialization and compression. Add new threshold numOfEntries as a quick fix.
Description:
=> Add numOfEntries as a threshold in checkpointer's batching strategy

infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java, test/src/test/java/org/corfudb/runtime/view/SequencerViewTest.java
Use the same default value for a stream's trim mark whether it
exists or not.
Why should this be merged: Simplifies code that needs to use the StreamAddressSpace::getTrimMark
=> Unify Stream Trim Mark Values

runtime/src/main/java/org/corfudb/runtime/collections/TxnContext.java
Some logic might result in commit() being called on
a transaction with no reads or writes.
Treat this as a normal case and avoid logging a warning
to reduce noise in the logs.
Description:
=> TxnContext: Don't log a warning on empty transactions

runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
Description:
Current StreamManager design suffers from noisy neighbour problem. If more than 4 subscribers are slow to process notifications then all the other subscribers lag. Increase parallelism as a stop-gap measure.
=> StreamingManager: Double stream threads for perf issues

runtime/src/main/java/org/corfudb/runtime/collections/OpaqueCorfuDynamicRecord.java, runtime/src/main/java/org/corfudb/util/serializer/DynamicProtobufSerializer.java, runtime/src/main/java/org/corfudb/util/serializer/KeyDynamicProtobufSerializer.java, test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
Deserializing CorfuDynamicRecord can be expensive. Protobuf DynamicMessage
comes with a high memory overhead. Also there are some functionalities that
doesn't require deserializing CorfuDynamicRecord, such as Compactor. The
new serializer and opaque record will allow to keep the payload and metadata
in ByteString format and only deserialize the Key message.
Description:
Reduce compactor's memory usage due to DynamicMessage's overhead
=> Introduce KeyDynamicProtobufSerializer and OpaqueCorfuDynamicRecord

runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
It is better to change the client side values instead of defaults here.
This reverts commit 36a76f470dd39d663d63acd664624f90fab4c4fc.
Description:
=> Revert "StreamingManager: Double stream threads for perf issues (#3050)"

common/src/main/java/org/corfudb/common/metrics/micrometer/README.md, runtime/pom.xml, runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java, runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
Description:
Adding readCache metrics: avg-entry-size and number of entries in readCache. Since the ask of these 2 metrics is for tuning the readCache, they can be enabled via corfuRuntimeParameters. 
By default, the 2 metrics are disabled.
This change uses [ehcache's sizeOf()](https://github.com/ehcache/sizeof) to get the deep size of an object. 
I did some performance test, on proton and PHC, to check the time overhead of using sizeOf, and:
1. p99 for a single sizeOf operation is around 1 ms. The tail latencies that I saw ranged between 1 ms - 13 ms 
2. when we read the entire readCache to calculate the avg-entry-size always, it takes a couple of minutes (3 mins is the longest seen). This is outside of read/write flow and this is the approach taken in this PR. …
=> Adding 2 readCache metrics: avg-entry-size and number of entries in readCache

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/LogReplicationConfig.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultLogReplicationConfigAdapter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/ILogReplicationConfigAdapter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogEntryWriter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/StreamsSnapshotWriter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/utils/LogReplicationStreamNameTableManager.java, infrastructure/src/test/java/org/corfudb/infrastructure/LogReplicationServerTest.java, runtime/src/main/java/org/corfudb/runtime/collections/TxnContext.java, runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java, runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java, runtime/src/main/java/org/corfudb/runtime/object/transactions/SnapshotTransactionalContext.java, runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteSetInfo.java, test/src/test/java/org/corfudb/integration/CorfuReplicationReconfigurationIT.java, test/src/test/java/org/corfudb/integration/LogReplicationAbstractIT.java, test/src/test/java/org/corfudb/integration/LogReplicationIT.java, test/src/test/java/org/corfudb/integration/LogReplicationReaderWriterIT.java, test/src/test/resources/proto/sample_schema.proto
Description:
In order to support selective streaming on the standby site,
consumers must provide a map of tables of interest and stream tags through
the ILogReplicationConfigAdapter. Only tables given by the adapter
will stream data on the standby (for both snapshot and delta sync).
Why should this be merged:  client feature request
=> Support Selective Streaming on Standby

runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java, runtime/src/main/java/org/corfudb/runtime/collections/Table.java, runtime/src/main/java/org/corfudb/util/ImmutableListSetWrapper.java
Table.java, which is a wrapper on top of CorfuTable only allows for
immutable objects types - protobuf types - and doesn't need a
write lock to execute the scan queries. This patch reduces locking
by allowing multiple threads to execute the scan simultaneously on
different versions of the Table.
Why should this be merged: Reduces locking for concurrent scanning queries.
=> Optimize scanAndFilter for Immutable Objects

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/LogReplicationConfig.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/StreamsSnapshotWriter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/utils/LogReplicationStreamNameTableManager.java, runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java, runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java, test/src/test/java/org/corfudb/integration/CorfuReplicationReconfigurationIT.java
Description:
One stream can have log data on a standby cluster, where nobody opens this stream.
Compactor will not see this stream in the tableRegistry and will trim this stream's data.
Later, the site becomes active, but this stream was trimmed and LR hit trimmed exception.
So we need to replicate tableRegistry across clusters, and it is merge only - we do not wipe out data for this table.
=> LR: replicate registryTable

test/src/test/java/org/corfudb/infrastructure/ReconfigurationEventHandlerTest.java
Description: 
* updateLayoutOnFailure: Previously we were using configured rules to avoid unexpected server endpoints to get sealed by sealMinServerSet(), but it would slow down the test and in some cases the node healing would happen and increase the server epoch, which made the test intermittently fails. Removed the rule configuration in this test to make the test more stable.
=> Flaky test fix: updateLayoutOnFailure

runtime/src/main/java/org/corfudb/runtime/collections/streaming/StreamingTask.java
Description: reduce log level for streaming task notifications as it is spewing client logs. 
Why should this be merged: reduce logging output
=> Noisy Log Statement for StreamingTask

corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditor.java, corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditorMain.java, test/src/test/java/org/corfudb/integration/CorfuStoreBrowserEditorIT.java
Description: provide an additional functionality on CorfuBrowser so it prints LogData metadata map. 
Print looks like this:
========== Metadata Map ==========
BACKPOINTER_MAP  :: {e05e7a5c-333e-38da-a19f-a682f52e9821=6, a60dd28c-7cc4-335f-bfc6-90c91ed57e39=6, 6d260a60-08ea-3faf-a0b3-43f4fa45ae2a=6, e751df29-358c-34ac-9501-6c8dfb6ace12=6}
GLOBAL_ADDRESS  :: 7
CLIENT_ID  :: f98577f5-b522-41f1-817f-fbdf1a1d11b2
THREAD_ID  :: 13
EPOCH  :: 0
PAYLOAD_CODEC  :: ZSTD
==================================
Why should this be merged: This will allow debugging in cases where logic depends on metadata information (for instance timestamp retrieval used in streaming). 
Related issue(s) (if applicable): client bug
=> Enable function to print log metadata map on Browser

infrastructure/proto/log_format.proto, infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java, test/src/test/java/org/corfudb/integration/CorfuStoreIT.java
Description:  'Epoch' is one of several fields captured by the ILogData metadata map.
We have a bug where the epoch (metadata) is never persisted as part of LogEntry.
Therefore, entries read from disk (no longer available in the server's cache) do not have the epoch and are
returned to client's as epoch -1 (for instance in the case of StreamListeners).
Why should this be merged: bug fix, incorrect epoch returned on client's callbacks. Several clients rely on the timestamp to determine if it's higher or not.
=> Persist EPOCH in LogEntry

corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditor.java, corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditorMain.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultClusterManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java, runtime/proto/corfu_options.proto, runtime/proto/example_schemas.proto, runtime/src/main/java/org/corfudb/runtime/collections/CorfuStoreShim.java, runtime/src/main/java/org/corfudb/runtime/collections/ProtobufIndexer.java, runtime/src/main/java/org/corfudb/runtime/collections/Table.java, runtime/src/main/java/org/corfudb/runtime/collections/TableOptions.java, runtime/src/main/java/org/corfudb/runtime/collections/TableParameters.java, runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java, samples/proto/person_profile.proto, test/src/test/java/org/corfudb/infrastructure/logreplication/LogUpdateAPITest.java, test/src/test/java/org/corfudb/integration/CorfuReplicationClusterConfigIT.java, test/src/test/java/org/corfudb/integration/CorfuReplicationReconfigurationIT.java, test/src/test/java/org/corfudb/integration/CorfuStoreBrowserEditorIT.java, test/src/test/java/org/corfudb/integration/CorfuStoreIT.java, test/src/test/java/org/corfudb/integration/LogReplicationAbstractIT.java, test/src/test/java/org/corfudb/integration/StreamingIT.java, test/src/test/java/org/corfudb/integration/StreamingPatternsIT.java, test/src/test/java/org/corfudb/runtime/BackupRestoreIT.java, test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreSecondaryIndexTest.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreShimTest.java, test/src/test/resources/proto/sample_schema.proto, test/src/test/resources/proto/test_schema.proto
Description:
There are many tables which share the same protobuf definition but require different behavior for the corfu features like
stream tags, replication etc.
Before this change, these table options were extracted from the message level options which means there was
no way to differentiate between different tables that share the same schema definition.
Moving the corfu schema options to TableOptions allows clients to define different behavior while still sharing the same underlying protobuf message
=> Move Schema options to TableOptions

runtime/src/main/java/org/corfudb/runtime/Backup.java, runtime/src/main/java/org/corfudb/runtime/Restore.java, runtime/src/main/java/org/corfudb/runtime/exceptions/BackupRestoreException.java, test/src/test/java/org/corfudb/runtime/BackupRestoreIT.java
Description:
Add extra clean up before Backup/Restore is run
Add BackupRestoreException to wrap any exceptions during B/R
1. Backup uses temp dir to hold tables before packing them into a single file.
Restore has the same logic to help extract the backup file.
B/R used to delete temporary directories in the end.
But if B/R failed the clean up is not guaranteed to happen.
Add extra clean up before backup and restore.
2. Add BackupRestoreException to wrap any exceptions during B/R
=> Clean up temp dirs before backup and restore

runtime/src/main/java/org/corfudb/runtime/collections/TxnContext.java
Description:
Change to use debug when closing a tx without commit()
It's reported that there are many warn logs when closing a tx.
It should be downgraded to debug.
=> Change to use debug when closing a tx without commit()

runtime/src/main/java/org/corfudb/runtime/collections/streaming/DeltaStream.java, runtime/src/main/java/org/corfudb/runtime/collections/streaming/StreamPollingScheduler.java, runtime/src/main/java/org/corfudb/runtime/collections/streaming/StreamingTask.java, test/src/test/java/org/corfudb/runtime/collections/streaming/DeltaStreamTest.java
Description:
- Remove trimMark precondition validation on streaming scheduler based on current prefixTrim protocol
(refer to DeltaStream refresh method for more details).
- Streaming Scheduler should be able to catch exceptions and propagate to tasks to allow the system to
recover and not silently die.
Why should this be merged: streaming stops in the event of a sequencer change, when the sequencer node has been bootstrapped with bitmaps of an untrimmed Log Unit, hence, there is an apparent regression in the trim mark.
=> Streaming Poller Trim Mark Fix

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java, test/src/test/java/org/corfudb/integration/CorfuReplicationReconfigurationIT.java, test/src/test/java/org/corfudb/integration/LogReplicationAbstractIT.java
Description:
Cluster role change notifications are async between nodes, if any node receives onClusterRoleChange
after replication has completed on leader node, the status of this flag will be incorrectly overwritten.
Changing status replication reset to be executed only by leader node.
Why should this be merged: customer bug
=> Log Replicator DataConsistent flag 'reset' bug fix

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationAckReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InLogEntrySyncState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java, test/src/test/java/org/corfudb/integration/CorfuReplicationReconfigurationIT.java, test/src/test/java/org/corfudb/integration/CorfuStoreIT.java
Description:
- In the event of log entry sync wherein tx stream is advancing but no update
to replicated streams has ever occurred (currentTxStreamProcessed = -1) the remaining entries
is incorrectly computed, this fixes that edge case.
- On log entry sync re-negotiation base snapshot timestamp can be persisted as part of the replication status.
Why should this be merged: current bug
=> Fix calculation remaining entries when no deltas are present

infrastructure/src/main/java/org/corfudb/infrastructure/LogReplicationServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InSnapshotSyncState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/WaitSnapshotApplyState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SnapshotSender.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/CorfuLogReplicationRuntime.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/LogReplicationClientRouter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/NegotiatingState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/ReplicatingState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/client/IClientChannelAdapter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/sample/GRPCLogReplicationClientChannelAdapter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/sample/NettyLogReplicationClientChannelAdapter.java, infrastructure/src/test/java/org/corfudb/infrastructure/LogReplicationServerTest.java
Description:
The remote leader loss event is not currently being processed when in Negotiation or Replicating states. Also, proper stop of replication process is also fixed.
Why should this be merged: bug fix for leadership loss in the middle of log replication
=> Add remote leader loss to Negotiation and Replicating State

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/LogReplicationConfig.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/StreamsSnapshotWriter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/StreamsLogEntryReader.java, test/src/test/java/org/corfudb/integration/CorfuReplicationClusterConfigIT.java, test/src/test/java/org/corfudb/integration/CorfuReplicationReconfigurationIT.java, test/src/test/java/org/corfudb/integration/LogReplicationAbstractIT.java
Description:
Clearing 'empty' streams on snapshot sync start can cause "apparent" data loss issues in
subsequent swithovers. This is because a 'clear' enforces an update to a stream that has
not been opened by upper layers. If the stream has not been opened it will not be checkpointed.
On a switchover, when attempting to read this stream (as it is intended for replication) we can
hit a TrimmedException.
Why should this be merged: current customer bug
=> Exclude 'clearing' EMPTY streams to replicate

infrastructure/src/main/java/org/corfudb/infrastructure/LogReplicationServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/StreamsSnapshotWriter.java
Description:
- Fix regression onSnapshotSyncEnd validation (read MSB and not LSB)
- Add call to onSnapshotSyncEnd on leadership loss
Why should this be merged: onSnapshotSyncEnd never called due to a regression causing checkpointer/trimmer to be freezes and overtime lead applications to OOM. Client bug.
=> Bug fix onSnapshotSyncPlugin

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultSnapshotSyncPlugin.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/LogReplicationPluginConfig.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java, runtime/proto/example_schemas.proto, test/src/test/java/org/corfudb/integration/LogReplicationAbstractIT.java, test/src/test/resources/transport/grpcConfig.properties
Description: this change adds a test to validate that onSnapshotSyncPlugin is being called before and after snapshot sync is completed. 
Why should this be merged: increase code coverage and catch potential issues in plugin call at the starts and end of snapshot sync.
=> Integration Test for onSnapshotSyncPlugin

test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
Description:
Fixing the flaky ClusterReconfigIT.forceRemoveAfterSeal test
The test sometimes seems to fail at the assertThrownBy statement - Here, a WrongEpochException is expected be thrown, while there are no exceptions thrown at this point sometimes. This is because, there might be a little delay in the node to see that the other 2 nodes have been shutdown. To account for the slight delay, retry is introduced.
=> Fixing the flaky ClusterReconfigIT.forceRemoveAfterSeal test

pom.xml, runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java, runtime/src/main/java/org/corfudb/runtime/collections/CorfuStoreShim.java, runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreShimTest.java
Description:
Why should this be merged: Some clients have a small footprint and only want to consume notifications made on a table.
The would like to open a table only for processing the initial snapshot and then have a way to remove that table from memory so that it does not take up space in the heap.
=> CorfuStore: Add support for closeTable() to remove unused tables

infrastructure/proto/sample.proto, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java, runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java, runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java, runtime/src/main/java/org/corfudb/runtime/object/transactions/Transaction.java, runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java, test/src/test/java/org/corfudb/infrastructure/logreplication/LogReplicationTest.java, test/src/test/java/org/corfudb/infrastructure/logreplication/LogUpdateAPITest.java, test/src/test/java/org/corfudb/integration/CorfuLongRunningClientIT.java, test/src/test/java/org/corfudb/integration/CorfuReplicationClusterConfigIT.java, test/src/test/java/org/corfudb/integration/CorfuStoreIT.java, test/src/test/java/org/corfudb/integration/LogReplicationAbstractIT.java, test/src/test/java/org/corfudb/integration/LogReplicationIT.java, test/src/test/java/org/corfudb/integration/LogReplicationReaderWriterIT.java, test/src/test/java/org/corfudb/integration/StreamingIT.java, test/src/test/java/org/corfudb/integration/TransactionStreamIT.java, test/src/test/java/org/corfudb/runtime/BackupRestoreIT.java, test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTransactionContextTest.java, test/src/test/java/org/corfudb/runtime/object/transactions/WriteAfterWriteTransactionContextTest.java, test/src/test/java/org/corfudb/runtime/view/ObjectsViewTest.java, test/src/test/java/org/corfudb/runtime/view/StreamViewTest.java
With stream tags, transaction stream(and hence transaction logging) are
no longer required.
Why should this be merged:  Code Cleanup
=> Remove Transaction Logging and Transaction Stream

infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/FileSystemAgent.java
Description: This PR adds a scheduler to the `PartitionAgent` to set values for `PartitionAttribute` fields - `readOnly`, `availableSpace`, `totalSpace`. These values are then to be used by the Failure Detector and other components like metrics. The values are reset every 5 seconds using a scheduler.
Why should this be merged: Sets values to the `PartitionAttribute` fields every 5 seconds.
=> Failure detector read only filesystem 4: PartitionAttribute

infrastructure/src/main/java/org/corfudb/infrastructure/log/FileSystemAgent.java
When an IO exception is encountered from updating partition attribute
statistics, we reinitialize the scheduler. Since the exception is
caught, this can lead to duplicate tasks being scheduled.
Description:
=> FileSystemAgent Scheduler Fix

pom.xml
Description:
Maven removed http support for repositories to prevent Possible Man-In-The-Middle-Attack after version 3.8.1, update pom.xml to support new versions of Maven. 
Maven release notes: 
https://maven.apache.org/docs/3.8.1/release-notes.html
=> update pom.xml to support maven over 3.8.1

pom.xml, runtime/pom.xml
Description:
Bump netty and grpc versions to avoid vulnerabilities.
=> Bump netty and grpc versions

common/src/main/java/org/corfudb/common/metrics/micrometer/README.md, runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java, runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java, runtime/src/main/java/org/corfudb/runtime/collections/PersistedStreamingMap.java, runtime/src/main/java/org/corfudb/runtime/collections/StreamingMapDecorator.java, runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
Description:Adding additional metrics required to measure compactor's performance -
1. checkpoint.timer - Tracks the time taken to checkpoint each stream
2. checkpoint.write_size, checkpoint.write_entries, vlo.sync.read_size, vlo.sync.read_entries - Helps track the i/o activity done by the compactor
3. corfu_table metrics - Can help distinguish performance of diskBacked and non-diskBacked reads and writes
=> Adding additional metrics required to measure compactor's performance -

infrastructure/src/main/java/org/corfudb/infrastructure/log/FileSystemAgent.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLog.java, test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java, test/src/test/java/org/corfudb/integration/AbstractIT.java, test/src/test/java/org/corfudb/integration/StreamAddressDiscoveryIT.java
Description:
Before #3112 InMemoryStreamLog didn't need any information about the disk, and #3112 tried to read disk info during creation, which caused errors in private infrastructure. I have changed FileSystemAgent in an exact way how it worked before #3112 changes. 
I have added:
Complete integration of "memory mode" into FileSystemAgent.
This fix takes into account that StreamLog can work in "in-memory" mode. 
=> Fix InMemoryStreamLog

.github/workflows/injection-framework-test.yml
Description: Pass corfu server version into universe-tests.
Why should this be merged: Prevents the 'universe-tests' suite from failing.
=> Pass corfu server version into universe-tests 3.2.1

pom.xml
Fix version compatibility of grpc with netty-tcnative library.
Description: This PR fixes the version mismatch between netty and grpc libraries.
More info: Refer [grpc version compatibility chart](https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty).
Why should this be merged: Fixes version mismatch from #3159.
=> Netty grpc versions upgrade fix

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InLogEntrySyncState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InSnapshotSyncState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogEntrySinkBufferManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogEntryWriter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/SinkBufferManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/LogEntrySender.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SnapshotSender.java, test/src/test/java/org/corfudb/integration/LogReplicationIT.java, test/src/test/java/org/corfudb/integration/SourceForwardingDataSender.java
1. Clear pendingMsgs queue on REPLICATION_STOP event
2. On the standby, update lastProcessedTs only when the msg is processed
Description:
=> Log Replication: Flush pending messages on replication stop

infrastructure/src/main/java/org/corfudb/infrastructure/LogReplicationServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/test/java/org/corfudb/infrastructure/LogReplicationServerTest.java
Description:
Scenario: cluster1 is ACTIVE and cluster2 is STANDBY. There is a topology change notification after which cluster2 gets demoted from STANDBY to NONE/INVALID role; Active stops replication to cluster2 and cluster2's role changes to NONE/INVALID.
Let's say there is another topology change where cluster 2 is reinstated as a STANDBY, and cluster1 receives this before cluster2. Active starts replication to cluster2, and cluster2, even though not standby from cluster2's perspective, processes the msg because currently we don't have a guard checking for the role on the recipient side. Fixing this.
The Behaviour should be that cluster2 ignores/drops the requests until cluster2 knows that it is STANDBY.
=> LogReplication: Drop request when cluster not standby

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java, test/src/test/java/org/corfudb/integration/LogReplicationIT.java, test/src/test/java/org/corfudb/integration/SourceForwardingDataSender.java
Description:
set isDataConsistent flag while processing the snapshot_start marker.
During the snapshot Sync, LR clears regular streams in 2 places so the data on standby is not polluted by local writes:
1. During transfer phase: Clear streams that have data to be replicated
2. During apply phase: Clear streams that have local writes on standby, but no writes on active.
Currently, the isDataConsistent flag is set to false during the apply phase, which can lead to inconsistent view of data as streams are cleared in transfer phase. This PR fixes this issue by marking dataConsistent flag to false as soon as standby sees the snapshot_Start marker.
=> LogReplication: set DataConsistent to false on snapshotStart marker

infrastructure/src/main/java/org/corfudb/infrastructure/log/LogMetadata.java, runtime/src/main/java/org/corfudb/runtime/view/stream/StreamAddressSpace.java
Description:
During StreamAddressSpace initialization upon corfu server restart,
the stream trim mark is set to the latest checkpoint address. Since
the log files are scanned in reversed order, all previous addresses
will be regarded as trimmed and cause log spew which impacts server
bootstrap performance.
Avoid log spew
=> Avoid log spew during StreamAddressSpace initialization

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/utils/LogReplicationStreamNameTableManager.java
During startup, the discovery service can write to the table of streams
to replicate.  If multiple LRs are starting concurrently, they can hit a
TX abort, causing the startup to fail.  Add retries around this block to
address the issue.
Also add retries during setup of the topology config id.
Why should this be merged:  Bug Fix
=> Handle TX Abort due to Concurrent Access on LR Startup

test/src/test/java/org/corfudb/integration/CorfuReplicationE2EIT.java, test/src/test/java/org/corfudb/integration/CorfuReplicationReconfigurationIT.java, test/src/test/java/org/corfudb/integration/LogReplicationAbstractIT.java
Description: 
Previously all the LR related integration tests are running against in memory tables. This change will config the CorfuReplicationE2EIT to run with disk-based tables.
Prepare for the potential usage of LR for non-config Corfu.
=> Test LR behavior against disk based tables

infrastructure/src/main/java/org/corfudb/infrastructure/LogReplicationServer.java, infrastructure/src/test/java/org/corfudb/infrastructure/LogReplicationServerTest.java, runtime/src/main/java/org/corfudb/protocols/service/CorfuProtocolLogReplication.java
Description:
Issue: We put up a guard on the STANDBY side to check if the role is standby before processing the leadership/negotiation/log_entry requests, drop the request if not standby. (https://github.com/CorfuDB/CorfuDB/commit/6df67c81226a980b48b1628d6a85166a5339fd65)
Before this guard, the remote cluster would process the requests even when the role was none/invalid. This creates an issues when the cluster's role changes to standby thereby resetting metadata when the remote is the middle of replicating entries.
But, dropping the request has an issue that the Leadership and Negotiation queries are blocking calls, so for active to proceed, the remote node has to respond back and not just drop the request.
The PR aims at this new behaviour of leadership and negotiation queries:
1. …
=> LogReplication: change query response behaviour on standby

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SnapshotSender.java, runtime/src/main/java/org/corfudb/runtime/collections/ProtobufIndexer.java, test/src/test/java/org/corfudb/integration/StreamingIT.java
Description:
The re-generation of streaming updates (data change notifications) through the use of the 'touch' API is a valid use case. Add a test that covers this scenario.
Why should this be merged: increase code coverage and provide examples of valid use cases
=> Add Streaming Use Case Test

corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditor.java
Without this fix the first null pointer exception stops printing
the table making it extremely difficult to triage critical
field issues.
Tolerating null allows the browser to do a best effort
and print out as many values as it can even in case
of an incorrectly filled up table.
Description:
=> CorfuStoreBrowser: tolerate Nulls in key, value or metadata sections

corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditor.java
…(#3193)
Without this fix the first null pointer exception stops printing
the table making it extremely difficult to triage critical
field issues.
Tolerating null allows the browser to do a best effort
and print out as many values as it can even in case
of an incorrectly filled up table.
Description:
=> CorfuStoreBrowser: tolerate Nulls in key, value or metadata sections (#3193)

corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditor.java, test/src/test/java/org/corfudb/integration/CorfuStoreBrowserEditorIT.java
Description:
Why should this be merged: Because registry table's TableDescriptors use the Any protobuf type the browser fails to print the registry table which makes it hard to figure out what the schemas are in any given setup.
This fix avoids using the JsonPrinter for the TableDescriptor since there is a known issue
=> CorfuStoreBrowser: Fix printing of all schemas in registry table

runtime/src/main/java/org/corfudb/runtime/view/CorfuGuidGenerator.java
Description:
Since the guid returns a signed long, the sign bit derived
from the timestamp should be kept 0 for unit tests which
need the guid to be ordered monotonically.
Note that this does not break CorfuQueue since the ordering in there
comes from the sequencer tail
=> CorfuGuid: Always ensure MSB is 0 for unit test ordering 

runtime/src/main/java/org/corfudb/runtime/view/CorfuGuidGenerator.java
Description:
Since the guid returns a signed long, the sign bit derived
from the timestamp should be kept 0 for unit tests which
need the guid to be ordered monotonically.
Note that this does not break CorfuQueue since the ordering in there 
comes from the sequencer tail
=> CorfuGuid: Always ensure MSB is 0 for unit test ordering

corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditor.java, test/src/test/java/org/corfudb/integration/CorfuStoreBrowserEditorIT.java
Because registry table's TableDescriptors uses Any protobuf
type the browser fails to print the registry table which
makes it hard to figure out what the schemas are in any given setup.
This fix avoids using the JsonPrinter for the
TableDescriptor since there is a known issue.
CorfuStoreBrowser: fix up loader to re-use table entry
Minor fixes and comments from reviewers
Description:
=> CorfuStoreBrowser: Fix printing of all schemas in registry table 

pom.xml, runtime/pom.xml
Update gRPC and Netty versions to overcome security vulnerability CVE-2017-5645
Description:
Update gRPC and Netty versions to overcome security vulnerability CVE-2017-5645.
References:
https://github.com/grpc/grpc-java/releases/tag/v1.45.1
https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty
Why should this be merged: Fixes Vulnerabilities.
=> Update grpc netty versions - master

runtime/src/main/java/org/corfudb/runtime/collections/ProtobufIndexer.java
This patch improves ProtobufIndexer's performance by:
1. Reducing unnecessary string allocations
2. Retrieving fields directly via field numbers instead of scaning (i.e., findFieldByName)
Why should this be merged: Improves read and secondary index reads performance
=> ProtobufIndexer Enhancements

test/src/test/java/org/corfudb/utils/LockStoreTest.java, utils/src/main/java/org/corfudb/utils/lock/persistence/LockStore.java
Make Lock Operations in LR Atomic.
Description:
Making the read-update-write path in Lock operations atomic.  The lock is currently only used in LogReplication(LR) but has been implemented in a generic way.
=> Make Lock Operations in LR Atomic.

runtime/src/main/java/org/corfudb/runtime/collections/ProtobufIndexer.java
This patch improves ProtobufIndexer's performance by:
1. Reducing unnecessary string allocations
2. Retrieving fields directly via field numbers instead of scaning (i.e., findFieldByName)
Why should this be merged: porting performance fix from master
=> ProtobufIndexer Enhancements (#3195)

infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/FileSystemAgent.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
Description:
Without this shutdown, the scheduler in PartitionAgent keeps trying to run its task even when the LogUnitServer is shutdown.
=> Graceful shutdown of the PartitionAgent scheduler

pom.xml, runtime/pom.xml
netty:         4.1.75
netty-tcnative:2.0.51
grpc:          1.45.1
Update gRPC and Netty versions to overcome security vulnerability CVE-2017-5645
Description:
=> Backport Update grpc netty versions

corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditorMain.java
Description:
Increase the SYSTEM_DOWN_RETRIES of corfu browser/editor to 60
There are new usages of corfu editor invoked by programs.
We have seen that the old SYSTEM_DOWN_RETRIES(5) is too
small and can be exausted too quickly.
=> Increase the SYSTEM_DOWN_RETRIES of corfu browser/editor to 60

coverage/pom.xml, lombok.config, pom.xml
Description: Currently proto auto-generated files are showing less coverage for the repository. 
This commit helps in reducing the percentage and getting more realistic values by excluding the proto files.
=> Exclude proto files from Jacoco coverage reporter

runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java, test/src/test/java/org/corfudb/integration/CorfuStoreIT.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreShimTest.java, test/src/test/java/org/corfudb/runtime/object/transactions/AbstractTransactionContextTest.java
If the streams accessed in a transaction are empty
commit() would return -1 as the commit() address
which makes it impossible to use as a stream
re-subscription point.
So if this corner case is detected, return the address from
transaction's snapshot already obtained from the sequencer
Description:
=> commit() returns >0 address if streams in txn are empty

.ci/generator-docker-build.sh, .ci/infrastructure-docker-build.sh, .github/workflows/compatibility-test.yml, .github/workflows/injection-framework-test.yml, .github/workflows/publish-corfu.yml, .github/workflows/universe-test.yml, cmdlets/pom.xml, docs/dockerized-corfu.md, generator/pom.xml, infrastructure/pom.xml, it/pom.xml, pom.xml
Description:
- Docker build process has been extracted from maven and now is in .ci/infrastructure-docker-build.sh which makes build process more flexible simple and straightforward
- protobuf plugin fix
- migrate to a newer version of maven-compiler-plugin  (the old version didn't print the reason of compilation error in case of lombok annotation-processing failures)
- Lombok needed to be updated because it caused compilation error in the result of fix in the protobuf plugin  
=> Better CI integration of a docker build

runtime/proto/corfu_store_metadata.proto, runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreShimTest.java
Currently if a protobuf file has changed we do not capture the
latest changes in the ProtobufDescriptor table.
This can cause issues if the key's type has changed since the
compactor depends on the key's type to make its KeyDynamicProtobuf
But since the protobuf map comparison is not deterministic
we version the protobuf file descriptor and on first open
after upgrade we just update the schema.
Description:
Related issue(s) (if applicable): #3221
=> TableRegistry: Use GitRepo version to detect Protobuf file changes

runtime/proto/corfu_store_metadata.proto, runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreShimTest.java
Description:
Currently if a protobuf file has changed we do not capture the
latest changes in the ProtobufDescriptor table.
This can cause issues if the key's type has changed since the
compactor depends on the key's type to make its KeyDynamicProtobuf
But since the protobuf map comparison is not deterministic
we version the protobuf file descriptor and on first open
after upgrade we just update the schema.
Related issue(s) (if applicable): #3225
=> [0.3.2.2] TableRegistry: Use GitRepo version to detect Protobuf file changes

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/sample/GRPCLogReplicationClientChannelAdapter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/sample/GRPCLogReplicationServerHandler.java
Description: Fix grpc transport plugin to handle async requests
Related issue(s) (if applicable): #3191
=> Fix grpc transport plugin to handle async requests

pom.xml, runtime/pom.xml
Address security vulnerability CVE-2022-24823
Description:
Upgrade netty 4.1.77 & grpc 1.46.0 (#3242)
Address security vulnerability CVE-2022-24823
=> Upgrade netty 4.1.77 & grpc 1.46.0 (#3242)

pom.xml
Description:
This addresses
CVE-2021-42550 as per https://nvd.nist.gov/vuln/detail/CVE-2021-42550
=> Update logback to 1.2.11

pom.xml
This addresses
CVE-2021-42550 as per https://nvd.nist.gov/vuln/detail/CVE-2021-42550
Description:
=> Update logback to 1.2.11 (#3246)

corfudb-tools/src/main/java/org/corfudb/compactor/CorfuStoreCompactorConfig.java, corfudb-tools/src/main/java/org/corfudb/compactor/CorfuStoreCompactorMain.java, runtime/src/main/java/org/corfudb/runtime/DistributedCompactor.java, test/src/test/java/org/corfudb/runtime/checkpoint/DistributedCompactorTest.java
A way of creating an immutable Corfu compactor config which is more resistant to input errors
Description:
=> A way of creating immutable corfu compactor config

runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java, runtime/src/main/java/org/corfudb/runtime/Restore.java, test/src/test/java/org/corfudb/runtime/BackupRestoreIT.java
Restoring tables using transactions could cause high memory
usage after restore. Today Restore is performed while all client
JVMs are shut down. This means restore could never encounter 
conflicts so it can be made non-transactional. After this change, 
the backed-up Corfu and restored Corfu have exact same stream 
views and there will be no more large transactions after restore.
Related issue(s) (if applicable): #3236
=> Make Restore non-transactional

runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java, runtime/src/main/java/org/corfudb/runtime/Restore.java, test/src/test/java/org/corfudb/runtime/BackupRestoreIT.java
Restoring tables using transactions could cause high memory
usage after restore. Today Restore is performed while all client
JVMs are shut down. This means restore could never encounter conflicts
so it can be made non-transactional. After this change, the backed-up
Corfu and restored Corfu have exact same stream views and there will
be no more large transactions after restore.
=> [Cherrypick to corfu-0.3.2.2] Make Restore non-transactional (#3249)

common/src/main/java/org/corfudb/common/metrics/micrometer/MicroMeterUtils.java, runtime/src/main/java/org/corfudb/runtime/collections/PersistedStreamingMap.java
The get and put methods in PersistedStreamingMap will be invoked many number of times while syncing. So
having multiple System.currentTimeMillis() reduces performance in some systems. Collecting timer at every
nth call to these methods optimizes the performance.
Description:
=> Optimize PersistedStreamingMap performance

runtime/src/main/java/org/corfudb/runtime/collections/PersistedStreamingMap.java, runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
This patch introduces a couple of optimizations that target metrics and Rocksdb:
- PersistedStreamingMap: Disable Synchronous Writes
- VersionLockedObject: Unnecessary Computation of Undo Records
Why should this be merged: Improves PersistedStreamingMap's performance
=> PersistedStreamingMap Optimizations

runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java, runtime/src/main/java/org/corfudb/runtime/collections/CorfuStoreShim.java, runtime/src/main/java/org/corfudb/runtime/collections/Table.java, runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreShimTest.java
Remove closeTable() since removing table metadata
from TableRegistry creates problems for stream
re-subscription since that layer needs the table metadata
So instead modify the api to do a freeTableData()
instead which only removes the Table's **_cached_** records
while retaining all the Table metadata.
Table's cache will get repopulated on the first access
Test case to validate that re-subscription works
Description:
Related issue(s) (if applicable): #3258
=> freeTableData() api to only reset CorfuTable & GC objects

runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java, runtime/src/main/java/org/corfudb/runtime/collections/CorfuStoreShim.java, runtime/src/main/java/org/corfudb/runtime/collections/Table.java, runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreShimTest.java
Remove closeTable() since removing table metadata
from TableRegistry creates problems for stream
re-subscription since that layer needs the table metadata
So instead modify the api to do a freeTableData()
instead which only removes the Table's records
while retaining all the Table metadata
Test case to validate that re-subscription works
Description:
=> freeTableData() api to only reset CorfuTable & GC objects (#3259)

cmdlets/pom.xml, it/pom.xml
Addresses CVE-2020-36518
Description:
=> Update jackson-databind to 2.13.3

common/src/main/java/org/corfudb/common/metrics/micrometer/README.md, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InSnapshotSyncState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/WaitSnapshotApplyState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/LogEntrySender.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SnapshotSender.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/LogReplicationClientRouter.java
Description:
* Removed `logreplication.rtt` which is never used nor recorded.
* Change the duration related metrics time unit to nanoseconds.
* Make the snapshot duration metrics to include initialization and shadow streams apply period.
* Added two separate metrics for the duration of TRANSFER and APPLY phase of snapshot sync.
=> Fix and cleanup for some LR related metrics

cmdlets/pom.xml, it/pom.xml
Addresses CVE-2020-36518
Description:
=> Update jackson-databind to 2.13.3 (#3261)

corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditor.java, corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditorMain.java, test/src/test/java/org/corfudb/integration/CorfuStoreBrowserEditorIT.java
When users want to delete a large number of records
doing it one by one ends up being extremely slow
Instead add support for batch transactional
deletion capability.
+Test case code coverage.
Related issue(s) (if applicable): #3274
=> CorfuStoreBrowser: Batch deletion capability

common/src/main/java/org/corfudb/common/metrics/micrometer/MicroMeterUtils.java, runtime/src/main/java/org/corfudb/runtime/collections/PersistedStreamingMap.java
To capture PersistedStreamingMap metrics in all extreme scenarios, such as RocksDB compaction
requires sampling with a PRNG.
Description:
=> Modify sampling of PersistedStreamingMap metrics using PRNG

infrastructure/src/main/java/org/corfudb/infrastructure/LogReplicationRuntimeParameters.java, infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuInterClusterReplicationServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationSourceManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/StreamsSnapshotWriter.java, test/src/test/java/org/corfudb/integration/AbstractIT.java, test/src/test/java/org/corfudb/integration/CorfuReplicationLargeTxIT.java
Currently, snapshot sync updates received for a stream are not applied atomically on the Sink.  First, a stream is cleared.  In a subsequent transaction, the updates(SMR entries) are applied one-by-one, each in a separate transaction.
This increases the window during which applications observe inconsistent data.
This window can be minimized by atomically clearing + applying all(if possible) updates.  If the size of the transaction exceeds CorfuRuntime's MAX_WRITE_SIZE, the updates can be applied in batches.
Why should this be merged:  Reduces the time for which data is inconsistent during snapshot sync.
=> Apply updates to a stream atomically during Snapshot Sync

runtime/proto/corfu_store_metadata.proto, runtime/src/main/java/org/corfudb/runtime/Restore.java, runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java, runtime/src/test/java/org/corfudb/security/tls/ReloadableTrustManagerTest.java, runtime/src/test/java/org/corfudb/security/tls/TlsUtilsTest.java, test/src/test/java/org/corfudb/runtime/BackupRestoreIT.java
Description:
The new restore mode 'PARTIAL_TAGGED' supports restoring
tables which have 'requires_backup_support' tag using a
full backup file. This PR also adds the backup tag to
RegistryTable and ProtobufDescriptorTable to avoid tables
which are opened after three compaction cycles from being
skip-checkpointed and trimmed.
New restore mode requested by users.
=> Add support for restoring tagged tables from a full backup

infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServerNode.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/sample/NettyLogReplicationServerChannelAdapter.java
The code can throw NPE in case if a parameter is not set
Description:
=> Fix possible NPE if a "disable cert expiry check file" parameter is not present in ServerContext

corfudb-tools/pom.xml, pom.xml, runtime/pom.xml
Description:
Needed for upgrade compatibility since previous revert reverted this necessary library update as well.
=> Bump up commons-io to 2.11.0 & git-commit-id to 4.9.10

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultLogReplicationConfigAdapter.java, test/src/test/java/org/corfudb/integration/CorfuReplicationMultiSinkIT.java, test/src/test/java/org/corfudb/integration/CorfuReplicationMultiSourceIT.java, test/src/test/java/org/corfudb/integration/CorfuReplicationMultiSourceSinkIT.java
Test Cleanup for Multi Source/Sink tests to make them flexible and reusable.
Description:
=> Test Cleanup to make them flexible and reusable.

runtime/src/main/java/org/corfudb/runtime/Restore.java, test/src/test/java/org/corfudb/runtime/BackupRestoreIT.java
Restore reads RegistryTable table to get requires_backup_support tag.
Table name can not be used as the key to read the RegistryTable due to
a limitation of TarArchiveOutputStream which truncates file names if
longer than 100 characters.
=> Restore reads table options indexed by UUID instead of table names

infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServerCache.java, infrastructure/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java, test/src/test/java/org/corfudb/runtime/object/transactions/SequencerServerCacheTest.java
The sequencer cache implements a sliding window to help with cache
eviction, which incorrectly assumes that conflict keys are unique.
This can lead to a memory leak when the same keys are written over
and over again. This patch also fixes a bug where the cache evicts
partial conflicts keys for a particular timestamp. This can lead to
incorrect resolutions and can cause data loss.
Description:
Why should this be merged:  Fixes eviction bugs that can cause incorrect resolutions and memory bloat.
Related issue(s) (if applicable): #3009
=> Fix sequencer cache eviction policy

runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteAfterWriteTransactionalContext.java
Since the WRITE_AFTER_WRITE transaction type only need to detect
write-write conflicts there is no need to track the the read set.
=> WriteAfterWriteTransactional: Don't track reads

runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java, runtime/src/main/java/org/corfudb/runtime/collections/Table.java, test/src/test/java/org/corfudb/integration/ServerRestartIT.java, test/src/test/java/org/corfudb/runtime/collections/CorfuTableTest.java
This patch changes the return type of getByIndex API from Collection
to Stream. Since consumers of this API immediately call stream() to
perform subsequent operations, this eliminates the creation of a
collection that is immediately thrown away, thus reducing temporal
garbage.
Description:
Why should this be merged: Reduces temporal garbage for getByIndex queries.
=> Update CorfuTable getByIndex API

runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java, runtime/src/main/java/org/corfudb/runtime/collections/Table.java, test/src/test/java/org/corfudb/integration/ServerRestartIT.java, test/src/test/java/org/corfudb/runtime/collections/CorfuTableTest.java
Reverts CorfuDB/CorfuDB#3340 - Creates a regression with respect to concurrency, where the VLO can modify the entry set backing the map, and hence the content of the stream, before they are collected.
=> Revert "Update CorfuTable getByIndex API"

runtime/src/main/java/org/corfudb/runtime/collections/CorfuQueue.java
The filter() and sort() sequence of operations performed on the entryStream() needs to be reversed.
Description:
=> @queue: Fix a bug in entryList() API

infrastructure/Dockerfile
Switch from Alpine to Debian as the default base image. The previous image was missing several native libraries, including ld-linux-x86-64.so.
Description:
=> @docker: Change the default base image

infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
Capture queue delay and the cost of executing the handler.
Why should this be merged: Improves metrics collections
=> Metrics: Measure Sequencer's Loop Latency

scripts/corfu_server.sh
Added -XX:+UseG1GC to the server launcher script.
Why should this be merged: Brings the server defaults closer to what what is being tested
=> Change The Default Garbage Collector

infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java, it/src/main/java/org/corfudb/universe/group/cluster/AbstractCluster.java, it/src/main/java/org/corfudb/universe/node/server/CorfuServerParams.java, it/src/main/java/org/corfudb/universe/universe/docker/DockerUniverse.java
Release all resources during the shutdown of the AbstractCluster and the DockerUniverse.
Description:
=> @universe: Release resources on shutdown

it/src/main/java/org/corfudb/universe/UniverseManager.java, it/src/main/java/org/corfudb/universe/group/cluster/CorfuClusterParams.java, it/src/main/java/org/corfudb/universe/node/server/CorfuServerParams.java, it/src/main/java/org/corfudb/universe/node/server/docker/DockerCorfuServer.java, it/src/main/java/org/corfudb/universe/scenario/fixture/FixtureUtil.java, it/src/main/java/org/corfudb/universe/scenario/fixture/Fixtures.java, it/src/test/java/org/corfudb/universe/group/CorfuClusterParamsTest.java, it/src/test/java/org/corfudb/universe/node/server/CorfuServerParamsTest.java
Allow the client to specify container resources when invoking the test/benchmark.
Description:
=> @Universe: Parameterize ContainerResources

runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java, runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java, runtime/src/main/java/org/corfudb/runtime/object/transactions/NoOpSMRStream.java, runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteSetSMRStream.java, test/src/test/java/org/corfudb/runtime/collections/DiskBackedCorfuClientTest.java
Since we are not computing undo records for monotonic objects, we need to prevent the optimistic stream from rolling back on a context switch as well. This patch effectively:
* Avoids applying updates on the optimistic streams. This avoids the issue of garbage accumulation. Since monotonic policy does not support read your own writes semantics, these updates are not even necessary.
* Avoids applying undo records on optimistic streams. This prevents NoRollbackException for being generated.
Description:
=> @vlo @monotonic Fix NoRollbackException

runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java, runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java, runtime/src/main/java/org/corfudb/runtime/object/transactions/SnapshotTransactionalContext.java, test/src/test/java/org/corfudb/runtime/collections/DiskBackedCorfuClientTest.java
Since monotonic objects do not permit any rollbacks, returning the maximum address read as the commit address for read-only transactions can cause streamers to miss data if they use this address as a subscription point. Instead we return the minimum address observed while reading.  However, we note that streamers using this address as a subscription point can observe duplicate data.
Description:
=> Update commit address computation for disk-backed tables

runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java, test/src/test/java/org/corfudb/runtime/collections/CorfuTableTest.java
Remove empty secondary index containers when the primary key is unmapped.
Why should this be merged: porting fix
=> Fix Secondary Index Leak

infrastructure/Dockerfile
Reverts CorfuDB/CorfuDB#3351
Reason: bootstrap fails on Kubernetes
=> Revert "@docker: Change the default base image"

pom.xml, runtime/pom.xml
This reverts commit e737aafefcbab748b6e1946f56fcf16b2f0bd482.
Description:
The netty, netty-tcnative and grpc versions need to be reverted to unblock testing.
=> Revert "Bump netty version to 4.1.80 from 4.1.77 (#3360)"

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogEntryWriter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/StreamsLogEntryReader.java, test/src/test/java/org/corfudb/infrastructure/logreplication/LogEntryWriterTest.java, test/src/test/java/org/corfudb/infrastructure/logreplication/MetadataManagerTest.java, test/src/test/java/org/corfudb/infrastructure/logreplication/TestUtils.java, test/src/test/java/org/corfudb/integration/CorfuReplicationReconfigurationIT.java, test/src/test/java/org/corfudb/integration/LogReplicationIT.java, test/src/test/java/org/corfudb/integration/SourceForwardingDataSender.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreShimTest.java
During log entry sync, multiple transactions are batched in a single message by the Sender.  Before this fix, the receiver coalesced and applied them all as a single  transaction.  This PR addresses the issue and maintains the transaction boundaries to be the same as what was received.
As multiple transactions are grouped in a single transaction on the receiver, the order of streaming updates is not consistent with the sender without this fix.
Tests Added
--------------
LogEntryWriterTest
---------------------
1. Verify that each opaque entry in a LogReplicationEntryMsg is applied
in a separate transaction.
2. Verify that redundant apply of the same LogReplicationEntryMsg is not
performed.
3. Verify that 2 LogReplicationEntryMsgs with overlapping sequence …
=> Preserve Transaction Boundary on LR Receiver.

infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java, runtime/src/main/java/org/corfudb/runtime/view/stream/StreamAddressSpace.java, runtime/src/test/java/org/corfudb/runtime/clients/SequencerHandlerTest.java, test/src/test/java/org/corfudb/runtime/utils/UtilsTest.java, test/src/test/java/org/corfudb/runtime/view/stream/StreamAddressSpaceTest.java
This patch exposes a new floor API for StreamAddressSpace. This core
operation will allow MVCC to efficiently determine the latest version that
is visible from a particular timestamp.  This patch also disables caching
within the Roaring64NavigableMap backing the address space in order
to allow for concurrent optimistic read operations on the data structure.
Description:
Why should this be merged: Adds support for core operation used in MVCC.
=> Disable Caching and Add Support For Floor Queries

test/src/test/java/org/corfudb/runtime/collections/PersistentCorfuTableTest.java
Description:
In the testUncommittedChangesIsolationBetweenParallelTxns, when write transaction is committed before the read transaction starts, the reader result assertion fails. This fix adds a writeLatch to prevent this.
=> Fix a flaky test in PersistentCorfuTableTest

runtime/src/main/java/org/corfudb/runtime/object/MVOCorfuCompileProxy.java, runtime/src/main/java/org/corfudb/runtime/object/MultiVersionObject.java, runtime/src/main/java/org/corfudb/runtime/object/StreamViewSMRAdapter.java, runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractContextStreamView.java, test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java, test/src/test/java/org/corfudb/runtime/collections/PersistentCorfuTableTest.java, test/src/test/java/org/corfudb/runtime/view/StreamViewTest.java
This patch introduces an optimization for MVCC to better handle corner cases involving tables without updates under certain multi-threaded interleaving access patterns.
Description:
=> MVCC Special Handling For Tables Without Updates

cmdlets/pom.xml, it/pom.xml, pom.xml, runtime/pom.xml
Address
https://nvd.nist.gov/vuln/detail/CVE-2022-42003
https://nvd.nist.gov/vuln/detail/CVE-2022-42004
Description:
=> Update jackson databind to 2.14.0-rc1 (#3378)

test/src/test/java/org/corfudb/integration/LogReplicationAbstractIT.java
Why should this be merged: Addresses the flakiness in a LogReplication IT
=> Fix the flakiness in CorfuReplicationE2EIT.

runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java, runtime/src/main/java/org/corfudb/runtime/collections/ICorfuTable.java, runtime/src/main/java/org/corfudb/runtime/collections/PersistentCorfuTable.java, runtime/src/main/java/org/corfudb/runtime/collections/Table.java, runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java, runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileWrapperBuilder.java, runtime/src/main/java/org/corfudb/runtime/object/ICorfuSMRProxyInternal.java, runtime/src/main/java/org/corfudb/runtime/object/MVOCache.java, runtime/src/main/java/org/corfudb/runtime/object/MVOCorfuCompileProxy.java, runtime/src/main/java/org/corfudb/runtime/object/MultiVersionObject.java, runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java, runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreShimTest.java, test/src/test/java/org/corfudb/runtime/collections/PersistentCorfuTableTest.java, test/src/test/java/org/corfudb/runtime/collections/SMRMapTest.java
Tables opened with NO_CACHE option should not be registered in MVOCache. Tables opened with CACHE option should remove all its versions in MVOCache when calling resetTableData. Without this fix, both NO_CACHE and resetTableData are broken and it causes memory leak which is a regression from VLO.
Description:
Previously a MVO object will be registered in both ObjectsView and MVOCache. 
The latter can be removed and merged into the former. This avoids an existing
memory leak since NO_CACHE has no effect in storing objects in MVOCache.
Bug fix and code cleanup.
=> Bug fix in NO_CACHE and freeTableData for MVO use case

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogEntryWriter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/utils/LogReplicationConfigManager.java, test/src/test/java/org/corfudb/integration/LogReplicationIT.java
Description:
This PR addresses 3 items:
- Avoid unnecessary sync with the Registry Table during Log Entry Sync
- Set correct logging level for a message to avoid it from becoming noisy
- Fix a test method which was changed in a prior PR and was not serving the intended purpose
=> Minor LR Fixes Identified During Code Inspection.

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/LRRollingUpgradeHandler.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultAdapterForUpgrade.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultAdapterForUpgradeActive.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultAdapterForUpgradeStandby.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultLogReplicationConfigAdapter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/ILogReplicationVersionAdapter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/utils/LogReplicationConfigManager.java, test/src/test/java/org/corfudb/integration/CorfuReplicationUpgradeIT.java
Description:
LR needs to adhere to a mode where not all cluster nodes are upgraded to the latest (current) version.
This PR only adds the interface to detect if we are in a version pinned phase.
Handling of the version pinning will follow.
=> Add Rolling Upgrade detection capability in LR

corfudb-tools/src/main/java/org/corfudb/compactor/CorfuStoreCompactorConfig.java, runtime/src/main/java/org/corfudb/runtime/ServerTriggeredCheckpointer.java, test/src/test/java/org/corfudb/CorfuStoreCompactorConfigUnitTest.java
Error found in the checkpoint invocation where two different runtimes are used while opening the table and checkpointing.
Description:
=> Fix incorrect runtime passed to CheckpointWriter

runtime/src/main/java/org/corfudb/runtime/CheckpointLivenessUpdater.java, test/src/test/java/org/corfudb/integration/LivenessUpdaterIT.java
Description:
Creation of a txn context under another txn context in livenessUpdater. 
3047635
=> fix: Liveness Updater transaction failures

runtime/src/main/java/org/corfudb/runtime/CompactorMetadataTables.java
Description:
Changing the freeze-token name to what was used in compactor V1.
Checkpointer doesn't get frozen as LR uses "freezeCheckpointNS" and checkpointer currently checks for "freezeTokenNS"
=> Changing the string of LR checkpointer freeze-token

infrastructure/src/main/java/org/corfudb/infrastructure/CompactorLeaderServices.java, infrastructure/src/main/java/org/corfudb/infrastructure/CompactorService.java, infrastructure/src/main/java/org/corfudb/infrastructure/InvokeCheckpointingJvm.java, infrastructure/src/main/java/org/corfudb/infrastructure/LivenessValidator.java, test/src/test/java/org/corfudb/infrastructure/CompactorServiceUnitTest.java
When the scheduler in runOrchestrator encounters an uncaught exception, it stalls and no more tasks get added to it even though the thread seems to be alive. Hence wrapping this section of the code with a try...catch block.
Also added some logs for better debuggability
Description:
=> Fix runOrchestrator thread error

infrastructure/src/main/java/org/corfudb/infrastructure/CompactorLeaderServices.java, runtime/src/main/java/org/corfudb/runtime/CheckpointLivenessUpdater.java, runtime/src/main/java/org/corfudb/runtime/DistributedCheckpointer.java, runtime/src/main/java/org/corfudb/runtime/LivenessUpdater.java, test/src/test/java/org/corfudb/integration/LivenessUpdaterIT.java, test/src/test/java/org/corfudb/runtime/CheckpointLivenessUpdaterUnitTest.java, test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointLivenessUpdaterUnitTest.java, test/src/test/java/org/corfudb/runtime/checkpoint/MockLivenessUpdater.java
In liveness updater, due to different threads being able to handle the currentTable variable, there is a chance of it getting into a race condition. This change fixes it.
Description:
=> Handle potential race condition in LivenessUpdater

infrastructure/src/main/java/org/corfudb/infrastructure/CompactorLeaderServices.java, infrastructure/src/main/java/org/corfudb/infrastructure/CompactorService.java, infrastructure/src/main/java/org/corfudb/infrastructure/DynamicTriggerPolicy.java, infrastructure/src/main/java/org/corfudb/infrastructure/InvokeCheckpointingJvm.java, infrastructure/src/main/java/org/corfudb/infrastructure/LivenessValidator.java, infrastructure/src/main/java/org/corfudb/infrastructure/TrimLog.java, infrastructure/src/main/resources/compactor-logback.prod.xml, infrastructure/src/main/resources/corfu-compactor-config.yml, infrastructure/src/main/resources/logback.prod.xml, scripts/compactor_runner.py
Removing syslog based logging. The compactor related logs from corfu server would be logged in the server's logfile while that of the compactor jvm will be logged in another file.
Description:
=> Remove syslog based logging

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultSnapshotSyncPlugin.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java
The snapshot sync plugin will need to migrate any
freeze tokens placed in the old format into the new format so checkpointing freeze can be honored.
It needs the runtime at constructor to do so.
Description:
cherry-pick of https://github.com/CorfuDB/CorfuDB/pull/3437
=> Instantiate SnapSyncPlugin with runtime

runtime/src/main/java/org/corfudb/runtime/DistributedCheckpointerHelper.java
Description:
This is needed for cases like rolling upgrade where the freeze token needs to be examined and updated
transactionally with other operations.
So we need a variant of the api which allows the
caller to control the lifecycle of the transaction.
=> CompactorControls: Allow caller to start transaction

infrastructure/src/main/java/org/corfudb/infrastructure/CompactorLeaderServices.java, infrastructure/src/main/java/org/corfudb/infrastructure/CompactorService.java, runtime/proto/corfu_compactor_management.proto, runtime/src/main/java/org/corfudb/runtime/DistributedCheckpointer.java, test/src/test/java/org/corfudb/infrastructure/CompactorServiceTest.java, test/src/test/java/org/corfudb/runtime/checkpoint/DistributedCheckpointerUnitTest.java
+The leader initializes the compaction manager status with IDLE status. Otherwise the status remains null until the first compactor cycle.
+Rename epoch field of CheckpointStatus proto msg
Description:
=> Init manager status with IDLE status

runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java, runtime/src/main/java/org/corfudb/runtime/object/MVOCache.java, runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java, test/src/test/java/org/corfudb/integration/StreamAddressDiscoveryIT.java, test/src/test/java/org/corfudb/integration/StreamingIT.java, test/src/test/java/org/corfudb/integration/WorkflowIT.java, test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
Simplify the cache setting logic
Description:
1. 'disableCache' as a CorfuRuntime parameter should disable MVO Cache.
2. Today the cache size is set at multiple places - client property files, CorfuRuntimeParameters, and variables such as AddressSpaceView::DEFAULT_MAX_CACHE_ENTRIES. This change cleans up this logic.
=> Set MVO Cache size to 0 when disableCache is true

runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java, runtime/src/main/java/org/corfudb/runtime/object/MVOCache.java, runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java, test/src/test/java/org/corfudb/integration/StreamAddressDiscoveryIT.java, test/src/test/java/org/corfudb/integration/StreamingIT.java, test/src/test/java/org/corfudb/integration/WorkflowIT.java, test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
Backport of Simplify the cache setting logic 
Description:
1. 'disableCache' as a CorfuRuntime parameter should disable MVO Cache.
2. Today the cache size is set at multiple places - client property files, CorfuRuntimeParameters, and variables such as AddressSpaceView::DEFAULT_MAX_CACHE_ENTRIES. This change cleans up this logic.
=> Backport of Set MVO Cache size to 0 when disableCache is true (#3448)

corfudb-tools/src/main/java/org/corfudb/compactor/CorfuStoreCompactorMain.java, infrastructure/src/main/java/org/corfudb/infrastructure/CompactionTriggerPolicy.java, infrastructure/src/main/java/org/corfudb/infrastructure/DynamicTriggerPolicy.java, runtime/src/main/java/org/corfudb/runtime/CompactorMetadataTables.java, runtime/src/main/java/org/corfudb/runtime/DistributedCheckpointerHelper.java, runtime/src/main/java/org/corfudb/runtime/Restore.java, test/src/test/java/org/corfudb/infrastructure/CompactorServiceTest.java, test/src/test/java/org/corfudb/infrastructure/CompactorServiceUnitTest.java, test/src/test/java/org/corfudb/infrastructure/DynamicTriggerPolicyUnitTest.java
Description:
Corfu native restore requires no other writers. Disable compaction before Restore, and enable after Restore.
=> Disable compaction during Restore

infrastructure/src/main/java/org/corfudb/infrastructure/CompactorLeaderServices.java, infrastructure/src/main/java/org/corfudb/infrastructure/CompactorService.java, runtime/src/main/java/org/corfudb/runtime/ServerTriggeredCheckpointer.java, scripts/compactor_runner.py, test/src/test/java/org/corfudb/infrastructure/CompactorServiceTest.java, test/src/test/java/org/corfudb/infrastructure/CompactorServiceUnitTest.java
If disable key is added while the compaction cycle is ongoing, the leader needs to force complete the cycle and mark the status as COMPLETED/FAILED
Description:
=> Add check for disable compaction key

corfudb-tools/src/main/java/org/corfudb/compactor/CorfuStoreCompactorMain.java, infrastructure/src/main/java/org/corfudb/infrastructure/CompactionTriggerPolicy.java, infrastructure/src/main/java/org/corfudb/infrastructure/DynamicTriggerPolicy.java, runtime/src/main/java/org/corfudb/runtime/CompactorMetadataTables.java, runtime/src/main/java/org/corfudb/runtime/DistributedCheckpointerHelper.java, runtime/src/main/java/org/corfudb/runtime/Restore.java, test/src/test/java/org/corfudb/infrastructure/CompactorServiceTest.java, test/src/test/java/org/corfudb/infrastructure/CompactorServiceUnitTest.java, test/src/test/java/org/corfudb/infrastructure/DynamicTriggerPolicyUnitTest.java
* Disabled compaction during Restore
* Add wait after disable compactor key is written to controls table
* Abort retrying if update hits conflict
* fix Codacy failure
Description:
=> Disable compaction during Restore (#3452)

infrastructure/src/main/java/org/corfudb/infrastructure/CompactorLeaderServices.java, infrastructure/src/main/java/org/corfudb/infrastructure/CompactorService.java, runtime/src/main/java/org/corfudb/runtime/ServerTriggeredCheckpointer.java, scripts/compactor_runner.py, test/src/test/java/org/corfudb/infrastructure/CompactorServiceTest.java, test/src/test/java/org/corfudb/infrastructure/CompactorServiceUnitTest.java
If disable key is added while the compaction cycle is ongoing, the leader needs to force complete the cycle and mark the status as COMPLETED/FAILED
Description:
=> [Backport] Add check for disable compaction key (#3453)

runtime/src/main/java/org/corfudb/runtime/DistributedCheckpointerHelper.java
Description:
DistributedCheckpointerHelper:: updateCompactionControlsTable 
should be `public` since LR needs to directly call this method.
=> Make updateCompactionControlsTable public

infrastructure/src/main/java/org/corfudb/infrastructure/CompactorLeaderServices.java, runtime/src/main/java/org/corfudb/runtime/DistributedCheckpointer.java, test/src/test/java/org/corfudb/infrastructure/CompactorServiceTest.java
=> Mark compaction cycle status through finishCompactionCycle() only

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InitializedState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/StreamsSnapshotWriter.java
Description:
The Apply phase relies on replicatedStreamIds to filter out the shadow streams that has evidenced data from SOURCE. This is an issue when the leader changes or leader restarts between the Apply phase.
This change fixes the issue by not relying on the in-memory structure, but use the shadow streams themselves to determine if the stream has evidenced data.
=> LR: remove dependence of in-memory structure during Apply Phase

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InitializedState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/StreamsSnapshotWriter.java
Description:
cherry-pick: https://github.com/CorfuDB/CorfuDB/pull/3459
The Apply phase relies on replicatedStreamIds to filter out the shadow streams that has evidenced data from SOURCE. This is an issue when the leader changes or leader restarts between the Apply phase.
This change fixes the issue by not relying on the in-memory structure, but use the shadow streams themselves to determine if the stream has evidenced data.
=> LR: remove reliance on in-memory structure during Apply phase.

infrastructure/src/main/java/org/corfudb/infrastructure/BaseServer.java, runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java, runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
Log additional information, such as message type and the receiving endpoint when message delivery fails.
Description:
=> Imporve visability into failed message delivery

runtime/src/main/java/org/corfudb/runtime/DistributedCheckpointer.java, test/src/test/java/org/corfudb/runtime/DistributedCheckpointerUnitTest.java
This exception could be caused on txn.delete(activeCheckpointTable) as well. For this case, we need to retry. In case of TAE due to updating checkpoint status of the current table, retrying still won't cause an issue since we have the method protected with compactorCycleCount, managerStatus and the tableStatus.
Description:
=> Retry on TXnAbortedException during unlockTableAfterCheckpoint

corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditor.java
The logging level is currently ERROR which is inaccurate.  It can be WARN.
Why should this be merged: Null metadata does not indicate an error.
=> Use correct logging level when null metadata is detected during showTable().

runtime/src/main/java/org/corfudb/runtime/object/MultiVersionObject.java, test/src/test/java/org/corfudb/integration/ObjectsViewIT.java
This patch fixes a bug where the object layer may not provide the correct view of an object when a sequencer regression occurs. Instead of throwing an UnrecoverableCorfuError to the upper layers, a TrimmedException is thrown instead. The MVO catches this exception and handles resetting its in-memory state before reattempting the sync.
Description:
=> MVCC Consistency Fix

corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditor.java, runtime/src/main/java/org/corfudb/runtime/object/MultiVersionObject.java, test/src/test/java/org/corfudb/integration/ObjectsViewIT.java, test/src/test/java/org/corfudb/runtime/collections/PersistentCorfuTableTest.java
Description:
MVCC Consistency Fix (#3481)
This patch fixes a bug where the object layer may not provide the
correct view of an object when a sequencer regression occurs.
Instead of throwing an UnrecoverableCorfuError to the upper layers,
a TrimmedException is thrown instead. The MVO catches this exception
and handles resetting its in-memory state before reattempting the sync.
=> Backport MVCC consistency fix & logging level change

infrastructure/src/main/java/org/corfudb/infrastructure/CompactorService.java, test/src/test/java/org/corfudb/infrastructure/CompactorServiceUnitTest.java
Return on cases when managerStatus is unable to be acquires as the runOrchestrator method runs every 10s
Description:
=> Fix runOrchestrator when managerStatus is null

infrastructure/src/main/java/org/corfudb/infrastructure/CompactorLeaderServices.java, infrastructure/src/main/java/org/corfudb/infrastructure/InvokeCheckpointingJvm.java, runtime/src/main/java/org/corfudb/runtime/collections/TxnContext.java, test/src/test/java/org/corfudb/infrastructure/CompactorLeaderServicesUnitTest.java, test/src/test/java/org/corfudb/integration/CorfuStoreIT.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreShimTest.java
Description:
Backports ...
Add sudo to process builder
initCompactionCycle: Pick txn's snapshot as min point
TxnContext now returns the correct transaction timestamp
Co-authored-by: Zachary Frenette
=> Backport sudo Process builder & Min token on snapshot start to 4.1.0

infrastructure/src/main/java/org/corfudb/infrastructure/CompactorLeaderServices.java, runtime/src/main/java/org/corfudb/runtime/collections/TxnContext.java, test/src/test/java/org/corfudb/infrastructure/CompactorLeaderServicesUnitTest.java, test/src/test/java/org/corfudb/integration/CorfuStoreIT.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreShimTest.java
Description:
If there is a race between listTables() and the time the min token is computed, we could miss a table in the checkpoint cycle and trim it.
To avoid this race, use the transaction's snapshot timestamp.
Co-authored by: @zfrenette 
=> Use transaction snapshot as min address for compaction cycle start

infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java, infrastructure/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java
This patch addresses flakiness in the SequencerServerTest suite. Since the reportSequencerHealth method is executing on a separate thread, its periodic invocation can interfere with the mocked behaviour of other objects unpredictably. This issue is addressed by mocking the health report scheduler, making the tests deterministic.
Description:
Related issue(s) (if applicable): #3460 #3487
=> Fix Flaky SequencerServerTest Suite

runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java, runtime/src/main/java/org/corfudb/runtime/DistributedCheckpointer.java, runtime/src/main/java/org/corfudb/runtime/collections/ICorfuTable.java, runtime/src/main/java/org/corfudb/runtime/collections/PersistedStreamingMap.java, runtime/src/main/java/org/corfudb/runtime/collections/PersistentCorfuTable.java, test/src/test/java/org/corfudb/runtime/DistributedCheckpointerUnitTest.java, test/src/test/java/org/corfudb/runtime/collections/DiskBackedCorfuClientTest.java
Delete RocksDB files for every corfu table right after the checkpointing finishes.
Description:
Delete RocksDB files for every corfu table right after the checkpointing finishes.
=> Optimize disk usage for disk-backed compaction

test/src/test/java/org/corfudb/integration/CorfuReplicationMultiSourceSinkIT.java
LR currently has a limitation that the Snapshot Writers on Sink cannot differentiate between the replicated streams received from their own vs other sessions.  So if multiple writers find a stream in the global list of streams to be replicated, each will apply updates from the shadow stream of that stream, even though no data was received for it from the writer's own session.  The current PR is a workaround in the test to prevent it from failing while the real fix is under discussion.
Description:
Why should this be merged:  The test failure is blocking all checkins in the current branch.
=> Test Fix for redundant updates in Multi-Source -> Single Sink Topology.

runtime/proto/corfu_options.proto, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreShimTest.java, test/src/test/resources/proto/sample_schema.proto
Description:
This is to support the logical group replication usecase
where multiple tables need to be tagged to be replicated
over to one or more remote destinations.
=> corfu_options: SchemaOption for logical_group

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/LogReplicationConfig.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/LogReplicationContext.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/LogReplicationServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationAckReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationSourceManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/LogReplicationFSM.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogEntryWriter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/SinkWriter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/StreamsSnapshotWriter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/LogicalGroupLogEntryReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/LogicalGroupSnapshotReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/RoutingQueuesLogEntryReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/RoutingQueuesSnapshotReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/StreamsLogEntryReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/StreamsSnapshotReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/CorfuLogReplicationRuntime.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/utils/LogReplicationConfigManager.java, test/src/test/java/org/corfudb/infrastructure/logreplication/LogEntryWriterTest.java, test/src/test/java/org/corfudb/infrastructure/logreplication/LogReplicationFSMTest.java, test/src/test/java/org/corfudb/infrastructure/logreplication/MetadataManagerTest.java, test/src/test/java/org/corfudb/integration/LogReplicationIT.java, test/src/test/java/org/corfudb/integration/LogReplicationReaderWriterIT.java, test/src/test/java/org/corfudb/integration/SourceForwardingDataSender.java
Description:
Avoid passing LR config manager and config objects all over the places. They will be accessed via LogReplicationContext. Also, LogReplicationContext is now created for both Source and Sink. (It was only on Source side before this change)
Facilitate following PRs for log replication v2
=> Re-org/cleanup LogReplicationContext / LogReplicationConfig / LogReplicationConfigManager

test/src/test/java/org/corfudb/integration/CorfuReplicationLargeTxIT.java
Description:
With new schema options the default serialized size of table entries goes up causing tests that assumed a previous max write size to fail.
So correcting the write size for these tests to pass
=> LR-IT: Fix MaxWriteSize to account for serialized size increase

runtime/src/main/java/org/corfudb/security/tls/TlsUtils.java
This commit changes the DISABLE_CERT_EXPIRY_CHECK location to /usr/share/corfu/conf for a cleaner approach so that it doesn't get deleted during clean-ups.
Description:
=> Change default DISABLE_CERT_EXPIRY_CHECK location

cmdlets/src/main/clojure/org/corfudb/shell.clj
Description:
Correct syntactical errors -
1. Remove parentheses for the method's parameters.
2. Call the correct method getHostFromEndpointURL().
Why should this be merged: Fixes errors in the code.
=> Fix Clojure Script's Get Host Method

runtime/src/main/java/org/corfudb/runtime/LogReplicationLogicalGroupClient.java, test/src/test/java/org/corfudb/runtime/LogReplicationLogicalGroupClientTest.java
Description:
Added setDestination() api for the log replication client.
=> Additional APIs for LR Client: setDestination

runtime/src/main/java/org/corfudb/runtime/collections/Table.java, runtime/src/main/java/org/corfudb/runtime/collections/TableOptions.java, runtime/src/main/java/org/corfudb/runtime/collections/TableParameters.java, runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreSecondaryIndexTest.java, test/src/test/java/org/corfudb/runtime/collections/DiskBackedCorfuClientTest.java
In some cases, a client might choose to load a table without a secondary index support in order to reduce memory usage. This can be done by providing an appropriate flag in TableOptions.
Description:
=> Allow clients to disable secondary indexes

runtime/src/main/java/org/corfudb/runtime/collections/TableOptions.java, test/src/test/java/org/corfudb/runtime/collections/DiskBackedCorfuClientTest.java
For TableOptions, explicit null-checking is requred as javax.annotation.Nonnull does not enforce the check during runtime.
For DiskBackedCorfuClientTest::disableSecondaryIndexes negative test, open a seperate Corfu Table.
Description:
=> Fix failing unit tests.

runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreShimTest.java, test/src/test/resources/proto/sample_schema.proto
Registry table needs to be updated when the CorfuRecord for a table is changed, even if there is already an entry for that table.
Description:
=> [Backport] Update registry table when CorfuRecord is changed (#3270)

runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java, runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java, test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
The CheckpointWriter has a check for the max write size limit before calling the StreamsView.append() method. This check is sufficient for the compactor and hence skipping the additional check in StreamsView for CheckpointWriter.
Description:
=> Skip maxWriteSize check for CheckpointWriter

runtime/src/main/java/org/corfudb/runtime/DistributedCheckpointer.java, test/src/test/java/org/corfudb/runtime/DistributedCheckpointerUnitTest.java
The DistributedCheckpointer doesn't close the tables on exception thrown during
appendCheckpoint. With a retry in place for runtime exception, rocksdb throws
errors when it tries to open the table again.
This fix addresses the above issue and closes the opened tables in a finally block.
=> Close opened table in finally block

infrastructure/src/main/java/org/corfudb/infrastructure/CompactorService.java, test/src/test/java/org/corfudb/infrastructure/CompactorServiceUnitTest.java
When initializing optional variables in CompactorService, if there's any exception, it's not handled and hence results in the CompactorService thread being killed. This leads to the runOrchestrator not being invoked and so compactor never gets triggered. This commit fixes the above issue.
Description:
=> Handle exception thrown during init of CompactorService

codecov.yml
Description:
- Add a 0.2% code coverage threshold to account for flaky tests.
Due to Flaky tests, their coverage ends up missing or is reported incorrectly.
This leads to a negative coverage value in the aggregated report even when the PRs do not actually reduce the coverage. This erroneous diff usually is less than -0.2% (https://app.codecov.io/gh/CorfuDB/CorfuDB/commits).
- Configuration Reference: https://docs.codecov.com/docs/commit-status#threshold
> "Allow the coverage to drop by X%, and posting a success status."
Corrects check marks to green in GitHub Actions for code coverage.
=> Codecov: Allow 0.2% coverage threshold

infrastructure/src/main/java/org/corfudb/infrastructure/log/BoundedMap.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/Segment.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java, test/src/test/java/org/corfudb/infrastructure/log/BoundedMapTest.java, test/src/test/java/org/corfudb/infrastructure/log/SegmentIndexTest.java, test_checks.xml
This patch replaces the Segment's ConcurrentHashMap index with a
space-efficient index. Memory overhead is reduced from
943120 to 80856 bytes, ~11x.
=> Segment Space-Efficient Index

corfudb-tools/pom.xml, corfudb-tools/src/main/java/org/corfudb/browser/CorfuBrowserEditorCommands.java, corfudb-tools/src/main/java/org/corfudb/browser/CorfuOfflineBrowserEditor.java, corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditor.java, corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditorMain.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/Segment.java, runtime/src/main/java/org/corfudb/protocols/logprotocol/CheckpointEntry.java, runtime/src/main/java/org/corfudb/util/serializer/DynamicProtobufSerializer.java, test/src/test/java/org/corfudb/integration/AbstractIT.java, test/src/test/java/org/corfudb/integration/CorfuReplicationClusterConfigIT.java, test/src/test/java/org/corfudb/integration/CorfuStoreBrowserEditorIT.java, test/src/test/java/org/corfudb/integration/StreamingIT.java
Description:
It allows us to re-use the CorfuStoreBrowserEditor commands and validations so that we can build the offline tool.
Rebased from https://github.com/CorfuDB/CorfuDB/pull/3269
Extremely useful for offline debugging and triaging
Related issue(s) (if applicable): #
Offline Browser stores the transactions on memory, when a log file size goes beyond the memory size, the tool stalls.
A fix for this issue would be having an indexer and using the filesystem to store the transaction map on disk, which would take a toll on overall runtime, but would significantly reduce the memory footprint.
java -cp corfudb-tools/target/corfudb-tools-0.4.0-SNAPSHOT-shaded.jar org.corfudb.browser.CorfuStoreBrowserEditorMain --namespace=CorfuSystem --operation=showTable …
=> OfflineBrowser:Read/print tables from just corfu log files

infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java, infrastructure/src/main/java/org/corfudb/infrastructure/management/ClusterAdvisor.java, infrastructure/src/main/java/org/corfudb/infrastructure/management/ClusterAdvisorFactory.java, infrastructure/src/main/java/org/corfudb/infrastructure/management/CompleteGraphAdvisor.java, infrastructure/src/main/java/org/corfudb/infrastructure/management/failuredetector/FailureDetectorService.java, infrastructure/src/main/java/org/corfudb/infrastructure/management/failuredetector/FailuresAgent.java, infrastructure/src/main/java/org/corfudb/infrastructure/management/failuredetector/HealingAgent.java, infrastructure/src/test/java/org/corfudb/infrastructure/management/CompleteGraphAdvisorTest.java, infrastructure/src/test/java/org/corfudb/infrastructure/management/failuredetector/DecisionMakerAgentTest.java, infrastructure/src/test/java/org/corfudb/infrastructure/management/failuredetector/FailureDetectorServiceTest.java, infrastructure/src/test/java/org/corfudb/infrastructure/management/failuredetector/FailureDetectorTestContext.java, infrastructure/src/test/java/org/corfudb/infrastructure/management/failuredetector/FailuresAgentTest.java, infrastructure/src/test/java/org/corfudb/infrastructure/management/failuredetector/HealingAgentTest.java, it/src/test/java/org/corfudb/universe/scenario/HandOfGodIT.java
Fix nodes not healing when local endpoint IP address changes dynamically when multiple addresses are present.
cc: @xnull , @PavelZaytsev 
Description:
Due to the changes in the IPV6, the serverContext local endpoint can change from IPV6 to IPV4. This causes issues in FD. We refresh the local endpoint on every FD iteration to account for this.
=> FailureDetection: get dynamic localEndpoint

common/src/main/java/org/corfudb/common/metrics/micrometer/README.md, runtime/src/main/java/org/corfudb/runtime/LogReplicationListener.java, runtime/src/main/java/org/corfudb/runtime/LogReplicationUtils.java, runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java, runtime/src/main/java/org/corfudb/runtime/collections/streaming/DeltaStream.java, runtime/src/main/java/org/corfudb/runtime/collections/streaming/LRDeltaStream.java, runtime/src/main/java/org/corfudb/runtime/collections/streaming/LRStreamingTask.java, runtime/src/main/java/org/corfudb/runtime/collections/streaming/StreamPollingScheduler.java, runtime/src/main/java/org/corfudb/runtime/collections/streaming/StreamingManager.java, runtime/src/main/java/org/corfudb/runtime/collections/streaming/StreamingTask.java, test/src/test/java/org/corfudb/infrastructure/logreplication/LogReplicationUtilsTest.java, test/src/test/java/org/corfudb/infrastructure/logreplication/TestUtils.java, test/src/test/java/org/corfudb/integration/LogReplicationListenerIT.java, test/src/test/java/org/corfudb/runtime/collections/streaming/DeltaStreamTest.java, test/src/test/java/org/corfudb/runtime/collections/streaming/LRDeltaStreamTest.java, test/src/test/java/org/corfudb/runtime/collections/streaming/LRStreamingTaskTest.java, test/src/test/java/org/corfudb/runtime/collections/streaming/StreamPollingSchedulerLRTaskTest.java, test/src/test/java/org/corfudb/runtime/collections/streaming/StreamPollingSchedulerTest.java, test/src/test/java/org/corfudb/runtime/collections/streaming/StreamingTaskTest.java
Currently, stream subscription can be done on a single namespace.  This PR introduces a special LR-specific streaming subscription to receive ordered updates across namespaces.  This behavior is required by clients
of the Logical Group-based replication.
**Integration Tests**
Test the first 4 workflows with stream subscription done 1)when in log entry sync and 2)when in snapshot sync: 
- Test streaming updates received on the special LR Multi Namespace Listener.  Verify the order and actual data.
- Test the above with different Tx batch size
- Test the above with a custom buffer size of the LR Streaming Task
- Subscribe the special listener at a timestamp after data is written.  Write more data after subscription. …
=> Special LR Stream Listener across namespaces.

infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServerNode.java, infrastructure/src/main/java/org/corfudb/infrastructure/datastore/DataStore.java
Description:
When Corfu starts, it should retry creating the nodeID file in case of IOExceptions rather than exit
issue: #3577 
=> Keep trying to generate nodeId in case of DataCorruptionException

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationAckReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InSnapshotSyncState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InitializedState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/WaitSnapshotApplyState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java, test/src/test/java/org/corfudb/infrastructure/logreplication/LogReplicationFSMTest.java, test/src/test/java/org/corfudb/integration/LogReplicationIT.java, test/src/test/java/org/corfudb/runtime/collections/streaming/DeltaStreamTest.java
Description:
The lastSyncType init value was set to log entry which is not accurate, this change sets the field only after entering the next state. Added initialization of the status table on bootstrap, and modified the TsPollingingTask to only be used to update the remaining number of entries. Also fixes race condition from #3435.
When transitioning states there exists a window between the exit of InitializedState to the next state where the lastSyncType is marked as LOG_ENTRY regardless of the actual last sync type. This is due to the lastSyncType being set on entry of the next state. In this window any query to lastSyncType is not guaranteed to be accurate. This change adds the logic to set the lastSyncType only after entry to the next state, and initialize …
=> Fixes for initialization of sync status

infrastructure/src/main/resources/logback.prod.xml, runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java, runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java, runtime/src/main/java/org/corfudb/runtime/object/MVOCorfuCompileProxy.java, runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java, runtime/src/main/java/org/corfudb/runtime/view/SMRObject.java, runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java
Due to many of the unnecessary log lines invoked by the compactor the corfu.9000 log file becomes too chatty and also leads to quick rolling over. This fix helps with the above issue - uses markers to mark unimportant logs and then filter them out in the logback file.
Description:
=> Reduce unnecessary log lines from compactor

common/pom.xml, infrastructure/pom.xml, infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServerCmdLine.java, infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServerNode.java, it/src/main/java/org/corfudb/universe/node/server/AbstractCorfuServer.java
Description:
Add the metrics server that can be activated via command line and will provide metrics in a Prometheus format
=> Add metrics server

runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java, test/src/test/java/org/corfudb/integration/CorfuStoreIT.java
Description:
This allows a simple way for new code to make the serializer aware of the old schema without actually having to open and register the old schema.
Without this change the new data migration caller will be forced to register the old table with full old schemas.
=> Expose addTypeToMap for simplifying rolling upgrade schema migrations

runtime/src/main/java/org/corfudb/runtime/object/MultiVersionObject.java, test/src/test/java/org/corfudb/integration/ObjectsViewIT.java, test/src/test/java/org/corfudb/runtime/collections/PersistentCorfuTableTest.java
This patch fixes a bug where clients can observe stale or incomplete data when an exception occurs on some code paths during a sync. By resetting the state of the object and its SMR stream, subsequent reads will be served from an accurate view of the object.
Description:
Why should this be merged:  Bug fix during certain edge cases.
=> Reset object state on exceptions during sync

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InLogEntrySyncState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InSnapshotSyncState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InitializedState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/WaitSnapshotApplyState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/LogReplicationAckReader.java, test/src/test/java/org/corfudb/infrastructure/logreplication/LogReplicationFSMTest.java
Description:
LR sync status init value was set to log entry which is not accurate, this change sets the field dynamically.
When transitioning states there exists a window between the exit of InitializedState to the next state where the lastSyncType is marked as LOG_ENTRY regardless of the actual last sync type. This is due to the lastSyncType being set on or after entry of the next state and not on exit of InitializedState. In this window any query to lastSyncType is not guaranteed to be accurate. This change adds the logic to set the lastSyncType on exit of InitializedState since the information of the next state is already present at this point.
=> Fix Sync Status Initialization

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/sample/GRPCLogReplicationClientChannelAdapter.java, pom.xml, runtime/pom.xml
Description:
Bump netty versions to fix [CVE-2022-41881](https://nvd.nist.gov/vuln/detail/CVE-2022-41881).
Compatibility: https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty.
```
grpc.version 1.54.0
netty.version 4.1.89.Final
netty.tcnative.version 2.0.56.Final
```
grpc-java version upgrade PR: https://github.com/grpc/grpc-java/pull/9784
Why should this be merged: Fixes Vulnerabilities.
=> Bump netty version from 4.1.77 to 4.1.89

corfudb-tools/src/main/java/org/corfudb/compactor/CompactorBaseConfig.java, infrastructure/src/main/java/org/corfudb/infrastructure/CompactorLeaderServices.java, infrastructure/src/main/java/org/corfudb/infrastructure/CompactorService.java, infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java, infrastructure/src/main/java/org/corfudb/infrastructure/TrimLog.java, runtime/src/main/java/org/corfudb/runtime/CheckpointLivenessUpdater.java, runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java, test/src/test/java/org/corfudb/infrastructure/CompactorServiceTest.java, test/src/test/java/org/corfudb/infrastructure/CompactorServiceUnitTest.java, test/src/test/java/org/corfudb/integration/CompactorServiceIT.java
The CompactorService needs to register a systemDownHandler where the runtime is reinitialized on an unrecoverable exception. Since the CompactorService uses the same runtime as the other services part of the management server, we need an independent runtime for CompactorService.
Description:
=> Create new runtime for CompactorService

runtime/src/main/java/org/corfudb/runtime/view/workflows/AddNode.java
Existing pingRetries and pingInterval in AddNode give a 20-30s window. This windows is too short for a corfu server restart. Increase the pingRetries from 3 to 10 to allow ~60s timeout window.
=> Increase AddNode pingRetries to 10 to avoid failing too fast

.github/workflows/code-coverage.yml, .github/workflows/compatibility-test.yml, .github/workflows/injection-framework-test.yml, .github/workflows/integration-test.yml, .github/workflows/unit-test.yml, .github/workflows/universe-test.yml, infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServerCache.java, infrastructure/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java, test/src/test/java/org/corfudb/runtime/object/transactions/SequencerServerCacheTest.java
The sequencer cache implements a sliding window to help with cache eviction, which incorrectly assumes that conflict keys are unique. This can lead to a memory leak when the same keys are written over and over again. This patch also fixes a bug where the cache evicts partial conflicts keys for a particular timestamp. This can lead to incorrect resolutions and can cause data loss.
=> [Backport] Fix sequencer cache eviction policy (#3010)

test/src/test/java/org/corfudb/integration/CompactorServiceIT.java
Remove disableLogUnitServerCache arg to resolve build errors.
Description:
=> Remove disableLogUnitServerCache arg

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuInterClusterReplicationServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/LRRollingUpgradeHandler.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/LogReplicationEventListener.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultClusterManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java, runtime/src/main/java/org/corfudb/runtime/LogReplicationUtils.java, test/src/test/java/org/corfudb/integration/CorfuReplicationUpgradeIT.java, test/src/test/java/org/corfudb/integration/LogReplicationAbstractIT.java
Description:
This allows new code to open old schemas without actually registering the old types.
=> Migrate LR schemas from old types to new types

test/src/test/java/org/corfudb/runtime/clients/NettyCommTest.java, test/src/test/java/org/corfudb/runtime/collections/SMRMapEntrySetTest.java, test/src/test/java/org/corfudb/runtime/collections/streaming/DeltaStreamTest.java, test/src/test/java/org/corfudb/runtime/object/CompileProxyTest.java
Description:
- NettyCommTest: 
- Make `bootstrapServer()` wait for the server to be up and running before checking for ping messages.
- Move all combinations of ciphers and keystore args into separate tests to enable threads clean up after each test.
- CompileProxyTest: 
- Increase timeout for `executeScheduled` as it takes more than 1 second to execute the scheduled task in tests.
- DeltaStreamTest:
- In `concurrencyTest()`, increase the timeout for the `done` latch to 10 seconds to wait for the consumer to get all the updates.
Why should this be merged:  Fixes flakiness in the tests.
Issue: https://github.com/CorfuDB/CorfuDB/issues/3589
Issue: https://github.com/CorfuDB/CorfuDB/issues/3568
Issue: https://github.com/CorfuDB/CorfuDB/issues/3622 …
=> Fix Flaky Tests in NettyCommTest, CompileProxyTest, DeltaStreamTest

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuInterClusterReplicationServerNode.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java, test/src/test/java/org/corfudb/integration/CorfuReplicationUpgradeIT.java, test/src/test/java/org/corfudb/integration/LogReplicationAbstractIT.java
Listening for expected number of updates on the Replication Status table and SnapshotSync Plugin on the Sink can lead to intermittent failures if the Snapshot Sync is restarted by the Source due to a flaky network or out-of-order message delivery.  Verification of snapshot sync completion by listening on the Source replication status of COMPLETED avoids test failures in the above scenarios and is reliable.
Also reduced the overall test time by removing waits on the Sink Status table.
Description:
=> Upgrade tests must use the Source Status Listener to Avoid Intermittent Failures

infrastructure/src/main/java/org/corfudb/infrastructure/log/BoundedMap.java, test/src/test/java/org/corfudb/infrastructure/log/BoundedMapTest.java
Description:
Why should this be merged: StreamLog offsets can be 64 bits in size. This PR updates a pre-condition check to reflect this.
=> Update BoundedMap PreConditions

infrastructure/src/main/java/org/corfudb/infrastructure/CompactionTriggerPolicy.java, infrastructure/src/main/java/org/corfudb/infrastructure/CompactorService.java, infrastructure/src/main/java/org/corfudb/infrastructure/DynamicTriggerPolicy.java, runtime/src/main/java/org/corfudb/runtime/ServerTriggeredCheckpointer.java, test/src/test/java/org/corfudb/infrastructure/CompactorServiceTest.java, test/src/test/java/org/corfudb/infrastructure/CompactorServiceUnitTest.java, test/src/test/java/org/corfudb/infrastructure/DynamicTriggerPolicyUnitTest.java
When shouldTrigger initializes DistributedCheckpointerHelper on every call, it opens all the compactor metadata tables leading to excessive openTable logs. So init distributedCheckpointerHelper only if it's not done already
Description:
=> Avoid opening compactor metadata tables on every shouldTrigger call

runtime/src/main/java/org/corfudb/runtime/LogReplicationUtils.java
Defines the constants to be used for Queue Names and Stream Tags.
Description:
=> Add the Constants for Queueu Names and Tags.

infrastructure/proto/log_replication_metadata.proto, runtime/src/main/java/org/corfudb/runtime/LogReplicationRoutingQueueClient.java, runtime/src/main/java/org/corfudb/runtime/collections/LRMessageWithDestinations.java
Description:
Initial definition of the routing queue client interface, and addition of supporting enums for force sync operations.
=> Routing Queue Client Interface

infrastructure/src/main/java/org/corfudb/infrastructure/BatchProcessor.java, infrastructure/src/test/java/org/corfudb/infrastructure/BatchProcessorTest.java
Description:
Why should this be merged: Fixes a race condition in the BatchProcessorTest::testRestart unit test.
Related issue(s) (if applicable): #3669
=> Fix Flaky BatchProcessorTest::testRestart

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java
Description:
Some of our clients will query replication status from Sink side and `SnapshotSyncInfo` field will be consumed. We need to setup that field to avoid regression of FULL_TABLE use case 
=> Fix: Status query could come from Sink side

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/SessionManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/msghandlers/LogReplicationServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/LogReplicationFSM.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/LogReplicationSourceManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/CorfuLogReplicationRuntime.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/LogReplicationClientServerRouter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/LogReplicationFsmUtil.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/LogReplicationRuntimeEvent.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/NegotiatingState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/ReplicatingState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/VerifyingRemoteSinkLeaderState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/sample/GRPCLogReplicationClientChannelAdapter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/sample/GRPCLogReplicationServerHandler.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/utils/LogReplicationConfigManager.java, runtime/proto/service/corfu_message.proto, runtime/proto/service/log_replication.proto, runtime/src/main/java/org/corfudb/protocols/service/CorfuProtocolLogReplication.java, test/src/test/java/org/corfudb/integration/CorfuReplicationClusterConfigIT.java, test/src/test/java/org/corfudb/integration/CorfuStoreIT.java
Bug fixes: 
- Leadership_loss msg when Source, a connection endpoint, looses leadership
- Do not stop the server when leadership changes.
- Check the value of logicalGroup in the proto msgs to identify streamsToReplicate for LogicalGroup usecase
Description:
=> bug fixes: leadership_loss msg + logical group proto check

infrastructure/src/main/java/org/corfudb/infrastructure/CompactorLeaderServices.java, scripts/compactor_runner.py
1. On OutOfMemory or other errors, check_call method logs to the shell. Capture those logs in the compactor audit logfile.
2. When the leader marks the checkpoint status of a table as FAILED, retain the client that was responsible for checkpointing the table.
Description:
=> Add logging fixes for compactor

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/LogReplicationClientConfigListener.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/NegotiatingState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/utils/SnapshotSyncUtils.java
Description:
Snapshot Sync Data for Routing Queues Replication Model is computed by the Client and provided to LR.  On determining the need for a snapshot sync, LR must request for this data through the event table.
=> Request Snapshot Sync Data from Routing Queues Client After Negotiation.

runtime/src/main/java/org/corfudb/runtime/Backup.java, runtime/src/main/java/org/corfudb/runtime/Restore.java, test/src/test/java/org/corfudb/runtime/BackupRestoreIT.java
Description:
This PR changes the existing Backup API and allows to set a namespace, all tables belonging to which will be backed up. This also works with the existing 'requires_backup_support' tag.
Required by multi-tenancy.
=> Add support for backing up a given namespace

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultClusterConfig.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/BaseSnapshotReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/RoutingQueuesSnapshotReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/utils/LogReplicationConfigManager.java, runtime/proto/queue.proto, runtime/src/main/java/org/corfudb/runtime/LogReplicationUtils.java, test/src/test/java/org/corfudb/infrastructure/logreplication/RoutingQueuesSnapshotReaderTest.java
=> Snapshot Sync Readers must wait for Data of End Marker before considering sync complete for Routing Queues Model.

runtime/src/main/java/org/corfudb/runtime/RoutingQueueSenderClient.java
Description:
Adds sender side client implementation for routing queue use case.
=> Routing Queue Sender Client Implementation

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/LogReplicationEventListener.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/SessionManager.java
If a topology change is received where the Local cluster becomes a Source and is a leader, start the event listener.  Also consolidated the code in this part a bit.
Description:
Why should this be merged:  Bug Fix 
=> Start Event Listener on Receiving a Topology Change Where Local is Source and Leader

runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
When AddressSpaceView readCache is 0, do not reset batch read size to 1 as it will make the state transfer include only 1 address per batch partition instead of 100.
1 address per batch adds CPU and network overhead due to the increased number of threads and network calls across nodes. This further causes cluster instability and delay in join node operation which involves state transfer.
Description:
=> Do not set batch read size to 1 when cache is disabled or 0

.github/workflows/cloud-deployment-test.yml
Ability to trigger cloud deployment manually alone with automatic triggers
Description:
=> Ability to trigger cloud deployment manually

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/config/LogReplicationRoutingQueueConfig.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultClusterManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogEntryWriter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/StreamsSnapshotWriter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/RoutingQueuesLogEntryReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/RoutingQueuesSnapshotReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/NegotiatingState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/utils/SnapshotSyncUtils.java, runtime/src/main/java/org/corfudb/runtime/FullStateReplicationContext.java, runtime/src/main/java/org/corfudb/runtime/LiteRoutingQueueListener.java, runtime/src/main/java/org/corfudb/runtime/LogReplicationRoutingQueueListener.java, runtime/src/main/java/org/corfudb/runtime/LogReplicationUtils.java, runtime/src/main/java/org/corfudb/runtime/RoutingQueueSenderClient.java, runtime/src/main/java/org/corfudb/runtime/TransmitterReplicationModule.java, runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java, test/src/test/java/org/corfudb/infrastructure/logreplication/LogReplicationUtilsTest.java, test/src/test/java/org/corfudb/integration/LogReplicationRoutingQueueIT.java
* RoutingTableEntryMsg extension
* Fix for client sender stream tag and transmit methods
* Fix sink side routing queue stream tag + log msgs
* Fix Routing Queue LogEntryWriter stream id
* Log entry end-to-end IT + fix for replicated queue name
* Fix LogEntryReader isValidTxnEntry number of tables touched
* LiteRoutingQueueListener Imple + replicated name revise
Description:
=> Multiple fixes for routing queue log entry sync

.github/workflows/cloud-deployment-test.yml
Description:
Cloud Deployment: multi (jdk) version deployment.
Corfu master branch can be compiled with jdk-11 (the language level is still defined as java 8 in maven pom.xml, but we can use jdk-11 to compile corfu and use jdk-11 to run corfu).
With the changes from the pr we can easily check if corfu can be compiled against multiple versions of jdk and if it can be deployed and run on k8s right away during pre commit checks with github actions
=> Cloud Deployment: multi (jdk) version deployment

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/LogReplicationEventListener.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java
=> LogReplicationEventListener fix of using runtime event protos than infra events

runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
When AddressSpaceView readCache is 0, do not reset batch read size to 1 as it will make the state transfer include only 1 address per batch partition instead of 100.
1 address per batch adds CPU and network overhead due to the increased number of threads and network calls across nodes. This further causes cluster instability and delay in join node operation which involves state transfer.
Description:
=> Do not set batch read size to 1 when cache is disabled or 0 (#3693)

infrastructure/src/main/java/org/corfudb/infrastructure/log/statetransfer/StateTransferManager.java, infrastructure/src/test/java/org/corfudb/infrastructure/log/statetransfer/StateTransferManagerTest.java
Description:
There could be cases in which when state transfer retries and queries the unknown addresses in the range, these addresses are not sequential. 
This can happen, for example, when during transfer, the streamlog is about to write a batch that crosses the trim mark boundary. In that case, the batch will be rejected with OverwriteException. The subsequent batches after the trim mark will be written, but state transfer will fail. When it retries and retrieves all the unknown addresses in the range from [trim-marl:end-of-segment], it can retrieve two sequences of consecutive addresses (consecutive unwritten addresses from the first rejected batch + unwritten addresses from the previous round. As a result, a transfer batch can contain nonsequential addresses, which a stream log …
=> Addresses in a batch are sequential

scripts/compactor_utils.py
Return compactor status on wait_for_compactor_end method instead of forcing the user to get status using another api.
Description:
=> Fix compactor utils script

runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
Stream batch read only works when readCache is enabled. If readCache is disabled, stream batch read introduces wasteful reads because the results can't be cached.
=> Set stream batch size to 1 if readCache is disabled

scripts/compactor_utils.py
Return compactor status on wait_for_compactor_end method instead of forcing the user to get status using another api.
Description:
=> Fix compactor utils script (#3727)

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/TestDataSender.java, test/src/test/java/org/corfudb/infrastructure/logreplication/LogReplicationFSMTest.java
Addresses the test flakiness described https://github.com/CorfuDB/CorfuDB/issues/3648
Description:
Related issue(s) (if applicable): #3648
=> Fix the flakiness in LogReplicationFSMTest.cancelSnapshotSyncInProgressAndRetry

runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
Cherrypick from master to corfu-0.4.1.2
Stream batch read only works when readCache is enabled. If readCache is disabled, stream batch read introduces wasteful reads because the results can't be cached.
=> Set stream batch size to 1 if readCache is disabled (#3728)

infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServerNode.java
Description:
There is a race bug where the reset sometimes does not complete fully because the worker group executor is getting shutdown before the future that uses it to run requests closes:
`java.util.concurrent.RejectedExecutionException: event executor terminated`
Corfu is never brought up after the botched reset as the main thread awaits the latch. 
Submit the close tasks for the futures before shutting down the associated executors.
=> close futures before shutting down event loop groups

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SnapshotSender.java
Log the total message size sent in snapshot sync payload
Description:
Currently we print snapshot message size for each batch (shown below). But, lacking the total size sent. So, adding the support.
```
2023-07-31T17:22:25.437Z | INFO  | tate-machine-worker--363488543 | c.i.l.r.s.l.BaseSnapshotReader | Successfully generate a snapshot message for stream stream_tag$CorfuSystemlrq_snapsync_f2394ea8-5173-43d4-b20f-7c5f7d3ea17d with snapshotTimestamp=7511949, numEntries=20, entriesBytes=17697, streamId=add0db5a-6c9d-3cdf-bba8-dce08c7f55d3
2023-07-31T17:22:25.877Z | INFO  | tate-machine-worker--363488543 | c.i.l.r.s.l.BaseSnapshotReader | Successfully generate a snapshot message for stream stream_tag$CorfuSystemlrq_snapsync_f2394ea8-5173-43d4-b20f-7c5f7d3ea17d with snapshotTimestamp=7511949, …
```
=> Log the total message size sent in snapshot sync payload

common/src/main/java/org/corfudb/common/compression/ZSTDCompression.java, common/src/main/java/org/corfudb/common/metrics/micrometer/README.md, runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java, runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
Description:
Add new metrics in write path. These can be used for tuning maxWriteSize value and compactor's memory.
=> Add payload size based metrics in write path 

pom.xml, runtime/pom.xml, runtime/src/main/java/org/corfudb/util/serializer/ISerializer.java
- Upgrade versions to mitigate security vulnerabilities.
- Guava - https://nvd.nist.gov/vuln/detail/CVE-2023-2976
- Kryo - https://osskb.eng.vmware.com/api/v1/vulnerabilities/html?uid=BDSA-2016-1151
Description:
=> Upgrade Kryo to 5.5.0 and Guava to 32.1.2-jre

pom.xml, runtime/pom.xml, runtime/src/main/java/org/corfudb/util/serializer/ISerializer.java
- Upgrade versions to mitigate security vulnerabilities.
- Guava - https://nvd.nist.gov/vuln/detail/CVE-2023-2976
- Kryo - https://osskb.eng.vmware.com/api/v1/vulnerabilities/html?uid=BDSA-2016-1151
Description:
=> Upgrade Kryo to 5.5.0 and Guava to 32.1.2-jre (#3761)

infrastructure/src/main/java/org/corfudb/infrastructure/BatchProcessor.java, infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriterOperation.java, infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java, infrastructure/src/main/java/org/corfudb/infrastructure/datastore/DataStore.java, infrastructure/src/main/java/org/corfudb/infrastructure/datastore/KvDataStore.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/LogMetadata.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/LogMetadataRecorder.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLog.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogDataStore.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java, test/src/test/java/org/corfudb/infrastructure/DataStoreTest.java, test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
Log Unit Server bootstrap and reset workflows requires log metadata initialization which is based on scanning all log files. This can be a problem as the size of data grows. This PR addresses the slow LU initialization issue by periodically persisting log metadata, and speed up the initialization by reconstructing log metadata from it. Experiments on 16GB Corfu deployment on AWS shows that LU initialization time reduced from ~4 min to 5 seconds.
=> Add LogMetadataRecorder

runtime/src/main/java/org/corfudb/runtime/LogReplicationListener.java, runtime/src/main/java/org/corfudb/runtime/LogReplicationUtils.java, runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java, runtime/src/main/java/org/corfudb/runtime/collections/streaming/LRStreamingTask.java, runtime/src/main/java/org/corfudb/runtime/collections/streaming/StreamPollingScheduler.java, runtime/src/main/java/org/corfudb/runtime/collections/streaming/StreamingManager.java, runtime/src/main/java/org/corfudb/runtime/exceptions/SubscribeMaxRetryException.java, test/src/test/java/org/corfudb/infrastructure/logreplication/LogReplicationUtilsTest.java, test/src/test/java/org/corfudb/integration/LogReplicationListenerIT.java, test/src/test/resources/transport/pluginConfig.properties
Description:
Currently the subscription of an LR Listener involves a prerequisite full sync, this PR moves the full sync operation to a separate thread so the client can continue while the sync completes asynchronously.
=> Decouple LR listener subscribe and full sync

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/RoutingQueuesSnapshotReader.java
=> Avoid recreating an Opaque Stream every time when polling for data.

runtime/src/main/java/org/corfudb/runtime/collections/Table.java, runtime/src/main/java/org/corfudb/runtime/collections/TransactionCrud.java
Description:
An optimization that can avoid OOMs esp if very large number of entries are inserted into a Queue in a single transaction.
=> Amortize Q's precommit listener to avoid OOMs

infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/config/LogReplicationConfig.java
When we compute the 90% of this we were doing
an integer value of 64 MB times 90 which overflows and results in a value of 17MB computed max size.
This limits the amount of data that is batched and has performance ramifications.
Description:
=> Fix data overlow bug in maxMsgSize computation

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/StreamsSnapshotWriter.java, test/src/test/java/org/corfudb/integration/LogReplicationRoutingQueueIT.java
=> Write a dummy entry to log entry sync q in the end of snapshot sync for ROUTING_QUEUES model

infrastructure/src/main/java/org/corfudb/infrastructure/CompactorService.java, runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java, runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java, test/src/test/java/org/corfudb/infrastructure/CompactorServiceTest.java, test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
When the checkpointer writes cp continuation entries by batching multiple SMREntries
together, it's not sufficient to just have a check for the compressed size and batch size.
The maxUncompressedCpEntrySize will prevent the compactor jvm to go OOM while batching the entries.
Description:
=> Add maxUncompressedCpEntrySize check while writing a cpEntry

infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java, runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java, test/src/test/java/org/corfudb/integration/WorkflowIT.java
Description:
When invalidating the layout, if the shuffle selects an unresponsive server, the client will stall. This could affect the failure detection of sequencer failovers as the FailureDetectorAgents use their runtime to run FD workflows. 
This patch removes the unresponsive node from the fetchLayout.
=> Do not ping unresponsive nodes when invalidating layout

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/config/LogReplicationConfig.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/BaseLogEntryReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/BaseSnapshotReader.java, test/src/test/java/org/corfudb/integration/AbstractIT.java, test/src/test/java/org/corfudb/integration/LogReplicationIT.java
This is used to build LR msgs in snapshot and logEntry readers
Description:
=> make max-replication-data-message-size configurable.

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/LogReplicationEventListener.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/RoutingQueuesSnapshotReader.java, runtime/proto/queue.proto, runtime/src/main/java/org/corfudb/runtime/LRFullStateReplicationContext.java, runtime/src/main/java/org/corfudb/runtime/LogReplicationUtils.java, runtime/src/main/java/org/corfudb/runtime/RoutingQueueSenderClient.java, runtime/src/main/java/org/corfudb/runtime/collections/ScopedTransaction.java, test/src/test/java/org/corfudb/infrastructure/logreplication/RoutingQueuesSnapshotReaderTest.java
Description:
If LR server for any reason requested multiple full syncs from client then it is possible that
the client is providing multiple full syncs in the same stream at the same time.
To disambiguate one full sync response from another, stamp each full sync message 
with the LR Server's request (Destination+logTail at time of request)
=> RoutingQ: Stamp all full sync messages with requesting timestamp

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java
Description:
This change is improving an existing log. Instead of printing a stale value of a field, retrieve the value from the DB and print it.
The log will make debugging issues comfortable
=> LR: improve logging for lastSnapshotStart by reading from DB

corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditor.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/LogReplicationEventListener.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/RoutingQueuesSnapshotReader.java, runtime/proto/queue.proto, runtime/src/main/java/org/corfudb/runtime/RoutingQueueSenderClient.java, test/src/test/java/org/corfudb/integration/LogReplicationRoutingQueueIT.java
Description:
Prevents spawning another thread just to request a full sync
=> RQ: allow requestSnapshotSync in parent txn

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/RoutingQueuesSnapshotReader.java
=> Set RoutingQ full sync snapshot timeout to 40 minutes

pom.xml, runtime/pom.xml
Changes on the RocksDB side:
* Change the default Optimisitc Concurrency Control Validation Policy to kValidateSerial. This significantly reduces the amount of memory used by OptimisticTransactionDB.
Description:
=> @rocksdb: Consume internal fork of RocksDB

runtime/proto/corfu_options.proto, runtime/src/main/java/org/corfudb/runtime/collections/DiskBackedCorfuTable.java, runtime/src/main/java/org/corfudb/runtime/collections/Table.java, runtime/src/main/java/org/corfudb/runtime/object/PersistenceOptions.java
Allow clients to set the write buffer/memtable size via PersistenceOptions.
Description:
=> @rocksdb: Export write buffer size parameter

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/config/LogReplicationLogicalGroupConfig.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/exceptions/GroupDestinationChangeException.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/exceptions/MessageSizeExceededException.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/LogReplicationClientRegisterListener.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/LogReplicationContext.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/SessionManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogEntryWriter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/StreamsSnapshotWriter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/LogEntrySender.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/LogReplicationAckReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/LogReplicationError.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/BaseLogEntryReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/BaseSnapshotReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/LogicalGroupLogEntryReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/LogicalGroupSnapshotReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/utils/LogReplicationConfigManager.java, runtime/src/main/java/org/corfudb/runtime/LogReplicationLogicalGroupClient.java, runtime/src/main/java/org/corfudb/runtime/collections/CorfuStreamEntry.java, test/src/test/java/org/corfudb/infrastructure/logreplication/LogReplicationConfigManagerTest.java, test/src/test/java/org/corfudb/infrastructure/logreplication/LogReplicationFSMTest.java, test/src/test/java/org/corfudb/integration/LogReplicationIT.java, test/src/test/java/org/corfudb/integration/LogReplicationLogicalGroupIT.java, test/src/test/java/org/corfudb/integration/LogReplicationReaderWriterIT.java
Description:
Stream listener based logical group config updating could have race condition with the threads sending log entry data, which could break the happens-before relationship of the APIs exposed by LR logical group client.
typical example:
client.remove(group1, sink1)
client.writeData(group1) <- Current implementation could still replicate some data from this write. Although it could achieve eventual consistency by clearing the table at Sink side in next forced snapshot sync, the intermediate state is still undesired.
This PR will fix that issue and stop replicating any log entry data after the removal.
=> Stronger consistency guarantee for LR logical group client APIs & Sink data removal

pom.xml, runtime/pom.xml
Ubuntu 20.04.6 LTS (Focal Fossa) uses an older version of glibc, therefore, when compiling RocksDB JNI, use version 2.31 insated.
GNU C Library (Ubuntu GLIBC 2.31-0ubuntu9.12) stable release version 2.31.
Description:
=> @rocksdb: Compile against an older glibc version

runtime/src/main/java/org/corfudb/runtime/LogReplicationUtils.java, test/src/test/java/org/corfudb/infrastructure/logreplication/LogReplicationUtilsTest.java
- `openTable()` for LR Status Table occurs in a separate thread from subscribe, main thread may have progressed and the open may not have happened so adding supplemental open outside the thread.
Description:
=> LR listener task synchronization fix

runtime/src/main/java/org/corfudb/runtime/view/CorfuGuidGenerator.java
Description:
Missed instantiating the table for the old guid generator causing IT failures
=> Minor fix to CorfuQueueGuidGenerator for existing tests

test/src/test/java/org/corfudb/infrastructure/logreplication/LogReplicationConfigManagerTest.java
Description:
2 new streams will be added by default for the streams to drop of field of FULL_TABLE replication config
=> Minor unit test fix for LogReplicationConfigManagerTest

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InLogEntrySyncState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InSnapshotSyncState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InitializedState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/LogReplicationEvent.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/LogReplicationFSM.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/LogReplicationState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/WaitSnapshotApplyState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/LogReplicationEventMetadata.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/LogReplicationSourceManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SnapshotSender.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/BaseSnapshotReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/ReplicatingState.java, test/src/test/java/org/corfudb/infrastructure/logreplication/LogReplicationFSMTest.java, test/src/test/java/org/corfudb/integration/CorfuReplicationClusterConfigIT.java
This change aims to gate the transition of the replication FSM. Since the consumption of events and the processing of events are done by different threads concurrently, its possible to get an event from an old sync. In that case, we should ignore the event and not transition out of the current state.
**Example**: a snapshot-sync-1 is canceled and snapshot-sync-2 is triggered. Now snapshot-sync-2 is in WAIT_SNAPSHOT_APPLY state, and we receive sync_cancel event from snapshot-sync-1. 
With the current code, we will cancel snapshot-sync-2 because we blindly consume the event and transition to INITIALIZED state. 
This change introduces a check before before we consume the event. The check uses the sync-id to understand if the current event has been processed by the ongoing sync and not by a …
=> Gate FSM transition

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryServiceAdapter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/SessionManager.java
1. The data structures which contain sessions are all thread safe, sow writes are blocking but reads are non-blocking. And our logic takes care of scenarios where we are reading (iterator/get) in one thread and currently a session is updated (added/removed) by another thread.
2. the localNodeId is coming from the clusterManager plugin now. The removal of the member in the interface is a cleanup that was missed before
Description:
=> cleanup: remove a TODO + a variable that is no longer needed

infrastructure/proto/log_replication_metadata.proto, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java
In the Routing Queue model, the Event table is accessed by the client from the runtime package.  The protobuf schema was copied to the runtime package for PoC but it must instead be moved to this package and migrated on an upgrade.
Description:
=> Move the Event Table protobufs to the runtime package from infrastructure and handle its upgrade.

common/src/main/java/org/corfudb/common/metrics/micrometer/MeterRegistryProvider.java, common/src/main/java/org/corfudb/common/metrics/micrometer/registries/LoggingMeterRegistryWithHistogramSupport.java, scripts/compactor_runner.py
There's a race condition when two threads try to update and read the metrics suppliers map concurrently. To fix this issue make remove and reading from the map synchronous.
Description:
=> Fix race condition while logging metrics 

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
Description:
The method `cleanupResources()` in CorfuInterClusterReplicationServerNode is not idempotent. When local cluster is no longer connection receiver and there are multiple topology changes coming in, it will try to invoke `cleanupResources()` multiple times that could cause `RejectedExecutionException` on an already shutdown executor, which is further exposed to LR discovery service to make it crash.
=> Nullify CorfuInterClusterReplicationServerNode after closing

infrastructure/src/main/java/org/corfudb/infrastructure/management/failuredetector/FailureDetectorService.java
Sequencer bootstrap optimization: don't skip FD iterations of handling sequencer bootstrap. 
Currently, to bootstrap a new sequencer a node has to skip 3 iterations of failure detection, which is just waste of cycles and bring a lot of latency
Description:
=> Sequencer bootstrap optimization

runtime/src/main/java/org/corfudb/runtime/collections/DiskBackedCorfuTable.java
By default, there is no limit on how much space LOG files can occupy. Bound the maximum number of LOG files that can be created and the maximum size of any LOG file.
Description:
=> @rocksdb: Bound the size of LOG files

infrastructure/src/main/java/org/corfudb/infrastructure/RequestHandlerMethods.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/msghandlers/ReplicationHandlerMethods.java, runtime/src/main/java/org/corfudb/protocols/wireprotocol/IMetadata.java, runtime/src/main/java/org/corfudb/runtime/MultiCheckpointWriter.java, runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java, runtime/src/main/java/org/corfudb/runtime/view/LayoutView.java, runtime/src/main/java/org/corfudb/util/serializer/PrimitiveSerializer.java, test/src/test/java/org/corfudb/runtime/collections/CorfuQueueTest.java, test/src/test/java/org/corfudb/runtime/collections/CorfuTableTest.java, test/src/test/java/org/corfudb/runtime/collections/SMRMapTest.java, test/src/test/java/org/corfudb/runtime/object/CorfuSMRObjectProxyTest.java, test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java, test/src/test/java/org/corfudb/runtime/view/ChainReplicationViewTest.java, test/src/test/java/org/corfudb/runtime/view/ObjectsViewTest.java, test/src/test/java/org/corfudb/runtime/view/StreamViewTest.java, test/src/test/java/org/corfudb/runtime/view/replication/AbstractReplicationProtocolTest.java
Description:
Code clean-up: remove redundant suppression's
=> Code clean-up: remove redundant suppression's

common/src/main/java/org/corfudb/common/compression/ZSTDCompression.java, corfudb-tools/src/main/java/org/corfudb/compactor/CompactorBaseConfig.java, runtime/src/main/java/org/corfudb/protocols/wireprotocol/ILogData.java, runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java, runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java, runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java, runtime/src/main/java/org/corfudb/runtime/exceptions/WriteSizeException.java, runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java, runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java, test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java, test/src/test/java/org/corfudb/runtime/object/transactions/StreamTest.java
Limiting the LogData payload size after compression does not give a clear idea of the payload that is uncompressed as the compression ratio for each transaction data will be varied. This change avoids OOM issues in a client due to a single transaction exceeding the memory limits.
Description:
=> Validate maxWriteSize of a transaction before compression

runtime/src/main/java/org/corfudb/runtime/RoutingQueueSenderClient.java, runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java, runtime/src/main/java/org/corfudb/runtime/collections/Table.java, runtime/src/main/java/org/corfudb/runtime/collections/TransactionCrud.java, runtime/src/main/java/org/corfudb/runtime/collections/TxnContext.java, runtime/src/main/java/org/corfudb/runtime/view/CorfuGuidGenerator.java, test/src/test/java/org/corfudb/infrastructure/logreplication/RoutingQueuesSnapshotReaderTest.java, test/src/test/java/org/corfudb/runtime/collections/CorfuQueueTest.java
Description:
While simply opening the Queue does not materialize the contents in-memory or on disk, we can avoid the possbility all together by only relying on the Queue's stream id.
=> Avoid using Table object in logUpdateEnqueue

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/StreamsSnapshotWriter.java, runtime/proto/queue.proto, runtime/src/main/java/org/corfudb/runtime/LiteRoutingQueueListener.java, test/src/test/java/org/corfudb/integration/LogReplicationRoutingQueueIT.java
LAST_SNAPSHOT_SYNC_ENTRY is not being used as intended.  Cleanup its usage in the listener and use it to indicate Snapshot Sync completion.
Description:
=> Improve the usage of LAST_SNAPSHOT_SYNC_ENTRY in LiteRoutingQueueListener.

infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/config/LogReplicationConfig.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuInterClusterReplicationServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/StreamsSnapshotWriter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/BaseLogEntryReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/BaseSnapshotReader.java, runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java, test/src/test/java/org/corfudb/integration/AbstractIT.java, test/src/test/java/org/corfudb/integration/CorfuReplicationLargeTxIT.java, test/src/test/java/org/corfudb/integration/LogReplicationIT.java
Description:
PR [3828](https://github.com/CorfuDB/CorfuDB/pull/3828) introduces a limit of 100MB on the max uncompressed write size for a transaction.  Currently, Log Replicator receiver applies every batch of incoming Snapshot Sync data in a single transaction in the transfer phase.
Currently, LR's batch size for transfer is limited to 64MB which is well within the 100MB limit.  But it is customizable, so the limit of (100MB + some buffer for LR metadata and serialization) must be enforced to allow the replicated data to be applied atomically on the receiver.  This uncompressed transaction size must also be used when chunking the aggregated data in the apply phase.
Why should this be merged:  Enforces Corfu Runtime's max write size in LR
=> LR Changes to Support Uncompressed Max Write Size Change

pom.xml, runtime/src/main/java/org/corfudb/runtime/collections/PersistedStreamingMap.java
By default, there is no limit on how much space LOG files can occupy. Bound the maximum number of LOG files that can be created and the maximum size of any LOG file.
Description:
=> @rocksdb: Bound the size of LOG files (#3823)

pom.xml, runtime/pom.xml
Previous version of librocksdbjni was compiled against GBLIC that was not supported on older platforms.
root@bionic:~/rocksdb/java/target# ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1.6) 2.27
Description:
=> @RocksDB: Compile against GLIBC 2.27

runtime/src/main/java/org/corfudb/runtime/Restore.java, test/src/test/java/org/corfudb/runtime/BackupRestoreIT.java
Description:
When Restore is invoked with mode as FULL, compactor should be disabled before starting restore and also during restore.
Restore corfu tables happens the following way -
1. Disable compactor
2. Clear all tables - in a single txn
3. Restore tables one by one as found in the backup tar file passed - Non-transactionally
4. Enable compactor
There are 2 issues here - 
1. It is possible that between steps 2 & 3, the compactor orchestrator tries to trigger a compaction cycle. 
2. When the compaction metadata tables are restored in step c, it's possible that the status of CompactionManagerTable is STARTED leading to restore and checkpointing happening in parallel
This PR fixes this issue by not clearing/restoring compactor metadata tables ensuring that compactor is disabled before …
=> Do not restore some metadata tables to keep compactor disabled during restore

infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
This patch fixes a race between the BatchProcessor and BaseServer threads that induces a deadlock. The BatchProcessor thread persists log metadata via the synchronized ServerContext::setLogUnitMetadata method. However, if the seal protocol is in progress and the BaseServer thread calls the synchronized ServerContext::setServerEpoch method first, it will become blocked indefinitely waiting for a BatchProcessor future to complete.
Why should this be merged: Bug fix.
Related issue(s) (if applicable): #3862
=> Fix Deadlock Scenario Between Seal Protocol And Log Metadata Persistence

infrastructure/src/main/resources/logback.prod.xml
Optimize rolling policy values of log4j log files
to reduce overall disk space consumed
by log4j log files.
Description:
=> Optimize log4j rolling policy

runtime/src/main/java/org/corfudb/runtime/object/MVOCache.java, test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTest.java
This patch addresses a bug for DiskBacked tables where, after a TrimmedException from the streaming layer, EXPIRED snapshots in the MVOCache are not removed as expected. When these EXPIRED snapshots linger in the cache, after the state of the object is reset from the TrimmedException, they can no longer be released without causing a core dump since the underlying RocksDB reference is no longer valid.
Why should this be merged:  Bug fix for DiskBacked Corfu.
=> DiskBacked Snapshot Cache Cleanup Fix

runtime/src/main/java/org/corfudb/runtime/object/DiskBackedSMRSnapshot.java, runtime/src/main/java/org/corfudb/runtime/object/MultiVersionObject.java, runtime/src/main/java/org/corfudb/runtime/object/RocksDbStore.java, test/src/test/java/org/corfudb/runtime/collections/PersistedCorfuTableTest.java
Prevent the JVM from crashing in the event of an invalid RocksDB instance by performing validation beforehand.
Description:
=> Avoid SIGSEGV on an invalid RocksDB instance

.mvn/wrapper/maven-wrapper.properties
Description:
Bump maven version to 3.9.6
=> Bump maven version to 3.9.6

runtime/src/main/java/org/corfudb/util/Utils.java
Description:
Remove unused jdk.internal classes from Utils
=> Remove unused jdk.internal classes from Utils

.github/workflows/cloud-deployment-test.yml, common/src/main/java/org/corfudb/common/config/ConfigParamsHelper.java, pom.xml, test/pom.xml, test/src/test/java/org/corfudb/runtime/clients/NettyCommTestUtil.java
Description:
To prevent being locked by java 8 (cause sun.* packages) we need to migrate our cert tests to bouncy castle
=> Migrate NettyCommTestUtil to bouncycastle

runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java, runtime/src/main/java/org/corfudb/security/tls/ReloadableKeyManager.java, runtime/src/main/java/org/corfudb/util/FileWatcher.java, test/src/test/java/org/corfudb/runtime/clients/NettyCommTest.java
Description:
On Linux, Files.move(a,b) will trigger DELETE event on file a, and CREATE event on file b. Add CREATE event kind to the watch service to fix missing file change issue.
Fix missing file change notification issue.
=> FileWatcher watches all kinds of events

common/src/main/java/org/corfudb/common/metrics/micrometer/JVMMetrics.java
Description:
JDK 11 strongly pushes towards not using sun* packages, so we need to to discontinue using it, so we need to get rid safepoints in jvm metrics. I believe not having safepoits is manageable for us. At least we can bring them back in the future if strongly needed.
And in the end, we will have JVM logs in the 'jvm' directory, so we are good anyway
Some info: https://blanco.io/blog/jvm-safepoint-pauses/ 
=> Jvm metrics: safepoint decommission

runtime/proto/service/log_replication.proto
Description:
Released versions use 0 as the enum for FULL_TABLE, we should continue the same enum to not break upgrades
=> Restore FULL_TABLE's number to 0 for upgrade compatiblity

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/msghandlers/LogReplicationServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/CorfuLogReplicationRuntime.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/LogReplicationClientServerRouter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/LogReplicationFsmUtil.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/client/IClientChannelAdapter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/sample/GRPCLogReplicationClientChannelAdapter.java, infrastructure/src/test/java/org/corfudb/infrastructure/LogReplicationServerTest.java, runtime/proto/service/log_replication.proto
This PR contains the below fixes:
1. add retry logic to connectAsync while connecting to a particular remote node
2. Do not complete ack future on leadership loss. The prior logic was incorrect
3. integrate remoteLeaderLoss with transport layer : Some of the constructs need to be refreshed.
4. Do not try to connect to remote cluster when local node looses leadership. : We can get an onConnectionDown event, but if it is because the local node is no longer the leader,  we shouldn't try to reconnect.
5. When SOURCE is on an older version, stall the source during the VERIFY_LEADERSHIP state by sending a negative response until the SINK creates the default FULL_TABLE session
Description:
=> LR: fix issues around leader changing

infrastructure/src/main/java/org/corfudb/infrastructure/CompactorService.java, test/src/test/java/org/corfudb/integration/CompactorServiceIT.java
This patch addresses a bug where resources are leaked when the CompactorService is unable to connect to Corfu. By shutting down the CorfuRuntime on such failures, we prevent runtime threads and other resources from being leaked.
Description:
Why should this be merged: Bug fix.
=> Compactor CorfuRuntime Cleanup On Connection Failures

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/LogReplicationEventListener.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/SessionManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InSnapshotSyncState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/WaitSnapshotApplyState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/LogReplicationAckReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/LogReplicationEventMetadata.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SnapshotSender.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/NegotiatingState.java, test/src/test/java/org/corfudb/integration/CorfuReplicationClusterConfigIT.java, test/src/test/java/org/corfudb/integration/LogReplicationIT.java
This change includes the below 3 fixes:
1. Remove events after successfully processing them.
2. Do not try to subscribe to an already subscribed listener on topology/leadership acquire
3. On lock release, stop the listeners.
4. Take the syncID from the enqueued sync_cancel event when the cancelled sync is a force snapshot sync. This will help track if the force snapshot request was processed successfully or not and also help with keeping the metadata table clean
Description:
=> LR: fix event handling for eventTable

infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java, infrastructure/src/main/resources/compactor-logback.prod.xml, infrastructure/src/main/resources/logback.prod.xml, runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
This change is no longer needed.
This reverts commit 18a0f0d59dbe7230246ba5d6cebaa56e584c4742.
=> Revert "Logs optimization (#3836)"

runtime/src/main/java/org/corfudb/runtime/collections/CheckedRocksIterator.java, runtime/src/main/java/org/corfudb/runtime/collections/RocksDbEntryIterator.java, runtime/src/main/java/org/corfudb/runtime/object/DiskBackedSMRSnapshot.java, test/src/test/java/org/corfudb/integration/CorfuStoreIT.java, test/src/test/java/org/corfudb/runtime/collections/PersistedCorfuTableTest.java
While technically re-entrant, read locks will deadlock in case of a concurrent write lock acquisition. In order to prevent any future deadlocks, do not re-enter on both the write and the read lock.
Description:
=> Do not re-enter on a snapshot read lock

runtime/pom.xml, runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java, runtime/src/main/java/org/corfudb/util/FileWatcher.java, runtime/src/test/java/org/corfudb/runtime/utils/FileWatcherTest.java, runtime/src/test/resources/logback-test.xml, test/src/test/java/org/corfudb/integration/SecurityIT.java
- Make FileWatcher start only in connect()
- Avoid restarting FileWatcher on reconnecting client routers.
Description:
=> Refactor FileWatcher code in CorfuRuntime

runtime/src/main/java/org/corfudb/runtime/collections/TxnContext.java, runtime/src/main/java/org/corfudb/runtime/exceptions/TransactionAbortedException.java, runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java, test/src/test/java/org/corfudb/runtime/collections/CorfuStoreShimTest.java
Description:
Printing table name when available on conflict aborts makes it easy to debug.
Message now looks like this:
org.corfudb.runtime.exceptions.TransactionAbortedException: TX ABORT  | Snapshot Time = Token(epoch=0, sequence=5) |
Failed Transaction ID = 700d3670-3143-9e3b-5742-55185334442f | Offending Address = 6 | Conflict Key = A20813379EBBB6B9 | Conflict Stream = `some-namespace$ManagedMetadata` | Cause = CONFLICT | Time = 7 ms
=> Print conflict table name on Transaction aborts

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/msghandlers/LogReplicationServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/sample/GRPCLogReplicationServerHandler.java, test/src/test/java/org/corfudb/integration/CorfuReplicationClusterConfigIT.java
=> Fix: Ack for Async Leadership Loss on Non-connection Starter

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/SessionManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/msghandlers/LogReplicationServer.java, infrastructure/src/test/java/org/corfudb/infrastructure/LogReplicationServerTest.java
When the sink on the new version receives a request from source on older version, the sink creates a session object.
An assumption here was that the source embeds the clusterId in the header of the request, which is not true.
So, instead of relying on the incoming request, we can rely on the topology to be backward compatible. This is safe to do as the older versions of LR only supports the FULL_TABLE model. 
Description:
=> LR: fix getSession() when source is on older version

infrastructure/src/main/java/org/corfudb/infrastructure/BatchProcessor.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/FileSystemAgent.java, infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java, test/src/test/java/org/corfudb/infrastructure/log/FileSystemAgentTest.java, test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
Description:
Prior to this change the thread executor responsible for updating the PartitionAttribute values of the PartitionAgent was being shutdown immediately after initialization. This would allow the PartitionAttribute's BatchProcessorStatus to remain stale and cause the failure detector to miss the updates of the BatchProcessorStatus from the BatchProcessor.
=> Fix: Keep PartitionAgent Updater Thread Alive + Test

runtime/src/main/java/org/corfudb/util/serializer/DynamicProtobufSerializer.java
Description:
If a json string with incorrect data type or out-of-range values for a protobuf field is input to the Corfu Editor, parsing it into a protobuf object fails.  Currently, no error information is shown to the user, making it difficult to find the issue.
Making this error explicit will ease in debugging by showing the error:
```
2024-03-06T20:15:30.522Z | ERROR |                           main | .u.s.DynamicProtobufSerializer | Unable to Parse String {"lockId": {"lockGroup": "Log_Replication_Group","lockName": "Log_Replication_Lock"},"leaseOwnerId": {"msb": "2574355181226772460","lsb": "-4699585018479296088"},"leaseRenewalNumber": 1000} due to an invalid input
com.google.protobuf.InvalidProtocolBufferException: Out of range uint64 value: "-4699585018479296088"
at …
```
=> Print Error Information for Invalid Inputs to Corfu Editor.

runtime/src/main/java/org/corfudb/util/serializer/DynamicProtobufSerializer.java, runtime/src/main/java/org/corfudb/util/serializer/KeyDynamicProtobufSerializer.java
Protobuf message typeUrl can take lots of memory, especially in the use case where lots of small protobuf messages are deserialized. This PR uses String intern() to benefit from JVM-level String pooling to reduce memory footprint of Compactor.
=> Optimize typeUrl memory overhead in KeyDynamicProtobufSerializer

corfudb-tools/src/main/java/org/corfudb/compactor/CompactorCheckpointer.java, corfudb-tools/src/main/java/org/corfudb/compactor/CompactorController.java, infrastructure/src/main/resources/corfu-compactor-config.yml, scripts/compactor_runner.py, test/src/test/java/org/corfudb/compactor/CompactorClientUnitTest.java
1. Fix corfu runtime leak in the checkpointer jvm
2. Modify checkpointer jvm's memory allocation options
Description:
=> Graceful shutdown of corfu runtimes in checkpointer and modify compactor memory config

corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditor.java, corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditorMain.java, runtime/src/main/java/org/corfudb/runtime/collections/CorfuDynamicRecord.java, test/src/test/java/org/corfudb/integration/CorfuStoreBrowserEditorIT.java
Description:
If the table does not have a metadata section browser's addRecord fails with a NullPointerException
=> CorfuStoreBrowser: Allow addRecord on null metadata tables

scripts/compactor_runner.py
_rsync_log should only move rotated log files, but with Java 11 the log rotation naming scheme has changed causing it to move active logs. This patch fixes that by matching files against the new naming scheme.
Why should this be merged: Fixes the log archiving script
=> Java 11: Fix _rsync_log

test/src/test/java/org/corfudb/utils/LockStoreTest.java, utils/src/main/java/org/corfudb/utils/lock/persistence/LockStore.java
PR #3219 introduced a regression where no node can acquire a lock after the lock table gets cleared.
This is a rare scenario and can be addressed by restarting LR service on 1 or more nodes but good to fix as it's a regression.
Description:
=> Allow lock acquisition if the Lock Table is empty.

test/src/test/java/org/corfudb/integration/AbstractIT.java
Description:
Since Java 9 the Process class has had native support to get the process's id which we can now use to avoid the reflection and the warnings we see as a result.
=> Avoid reflection getting process pid

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationSourceManager.java, test/src/test/java/org/corfudb/integration/LogReplicationIT.java, test/src/test/java/org/corfudb/integration/SourceForwardingDataSender.java
This PR brings back the tests added in PR [3644](https://github.com/CorfuDB/CorfuDB/pull/3644) which got reverted as part of LR v2 revert ([PR 3922](https://github.com/CorfuDB/CorfuDB/pull/3922))
Description:
=> Add tests for dropped SNAPSHOT_START and out-of-order messages + Minor cleanup in LogReplicationIT.

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
Description:
Currently the listener is started on bootstrap on all the 3 nodes, but the events are processed only the leader node.
If an event arrives before a node becomes the leader, that event is notified to the listener, but since no one is the leader yet, that event gets ignored by all the nodes.
To fix this, we start the listener on leadershipAcquire
Test:
The CorfuReplicationClusterConfigIT.testEnforceSnapshotSync() test already covers a scenario where the event table contains a record before LR is started.
I tried to simulate the lock revoke (add an event when the cluster is not the leader and then make it a leader), but currently there is no way to deterministically stop the cluster from acquiring a lock. 
=> LR: start eventListener on leadershipAcq, and stop on leadershipRel

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/LogReplicationEventListener.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java, test/src/test/java/org/corfudb/integration/CorfuReplicationE2EIT.java, test/src/test/java/org/corfudb/integration/LogReplicationAbstractIT.java
This change is to automatically resubscribe to the event listener when the streaming task encounters an error.
Description:
=> LR: event listener resubscribe onError

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationAckReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InLogEntrySyncState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java, test/src/test/java/org/corfudb/infrastructure/logreplication/LogReplicationFSMTest.java
Entry into LOG_ENTRY_SYNC state can be after 1)completion of a Snapshot Sync OR 2)a simple LR restart or leadership change where a Snapshot Sync was not performed.  The status of the last completed Snapshot Sync must be updated in case 1 but not in case 2.
Description:
=> Fix the Inconsistency in LR Sync Status when entering LOG_ENTRY_SYNC State

scripts/compactor_runner.py
Description:
1. Remove -verbose:gc since JDK 11 uses -Xlog.
2. Added uptime,level to timestamp for consistency.
-verbose:gc writes to stdout which gets redirected to corfu-compactor-audit.log. 
From Java 8 onwards, it's a good pratice to use only '-Xlog' to configure GC logging.
=> Minor tweak on compactor GC logging

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/LogReplicationEventListener.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationAckReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InLogEntrySyncState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InSnapshotSyncState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/WaitSnapshotApplyState.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java, test/src/test/java/org/corfudb/infrastructure/logreplication/LogReplicationFSMTest.java, test/src/test/java/org/corfudb/integration/CorfuReplicationE2EIT.java, test/src/test/java/org/corfudb/integration/CorfuReplicationReconfigurationIT.java, test/src/test/java/org/corfudb/integration/LogReplicationAbstractIT.java
Description:
contains the following fixes:
[LR: remove stopSnapshotApply gating from WaitSnapshotApply]
[LR: start eventListener on leadershipAcq, and stop on leadershipRel]
[LR: event listener resubscribe onError]
[Fix the Inconsistency in LR Sync Status when entering LOG_ENTRY_SYNC]
[Clear Event Table on Force Sync Completion]
=> LR: few bug fixes on LR V1

common/src/main/java/org/corfudb/common/metrics/micrometer/JVMMetrics.java, generator/pom.xml, pom.xml, runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
In Java11, the JVM's safepoint logging is very verbose. Since we are only interested int stop-the-world (STW) pauses this patch tracks STW latencies with a micrometer gauge, which reports it as 2-log lines per 1min.
Why should this be merged: Required to help debug clustering/latency issues related to JVM pauses
=> JVM Safepoint Metrics

common/src/main/java/org/corfudb/common/metrics/micrometer/JVMMetrics.java
Needed to track off-heap memory usage.
Why should this be merged: Improves off-heap memory accounting
=> Metrics For Netty Memory Pools

test/src/test/java/org/corfudb/infrastructure/logreplication/LogReplicationFSMTest.java
Description:
Using `ReaderImplementation.STREAMS` can cause flakyness in the fsm tests where we just want to verify FSM transitions. Since a mock implementation for the data sender is used it is possible to get NPEs that can cause additional transitions that can throw off the checks in the test.  `ReaderImplementation.EMPTY` avoids this so just the transitions made in the test occur.
=> [Fix] Flakey tests in LogReplicationFSMTest

.github/workflows/cloud-deployment-test.yml, .github/workflows/compatibility-test.yml, .github/workflows/injection-framework-test.yml, .github/workflows/publish-corfu.yml, corfudb-tools/README, infrastructure/src/main/resources/corfu_plugin_config.properties, it/src/main/java/org/corfudb/universe/group/cluster/CorfuClusterParams.java, it/src/main/java/org/corfudb/universe/node/server/CorfuServerParams.java, pom.xml, test/src/test/resources/transport/grpcConfig.properties, test/src/test/resources/transport/nettyConfig.properties, test/src/test/resources/transport/nettyConfigUpgradeActive.properties, test/src/test/resources/transport/nettyConfigUpgradeStandby.properties
Description:
Increase the corfu version to `0.4.2.1-SNAPSHOT` for future releases.
Why should this be merged: Currently it has an outdated value - `0.4.0-SNAPSHOT`. This CL updates it.
=> Bump corfu version to 0.4.2.1

.github/workflows/cloud-deployment-test.yml, .github/workflows/compatibility-test.yml, .github/workflows/injection-framework-test.yml, .github/workflows/publish-corfu.yml, corfudb-tools/README, infrastructure/src/main/resources/corfu_plugin_config.properties, it/src/main/java/org/corfudb/universe/group/cluster/CorfuClusterParams.java, it/src/main/java/org/corfudb/universe/node/server/CorfuServerParams.java, pom.xml, test/src/test/resources/transport/grpcConfig.properties, test/src/test/resources/transport/nettyConfig.properties, test/src/test/resources/transport/nettyConfigUpgradeActive.properties, test/src/test/resources/transport/nettyConfigUpgradeStandby.properties
Description:
Increase the corfu version to 0.4.2.0-SNAPSHOT for the 420 release.
Why should this be merged: Currently it has an outdated value - 0.4.0-SNAPSHOT. This CL updates it.
Related issue(s) (if applicable): #
=> Bump corfu version to 0.4.2.0

infrastructure/Dockerfile
Description:
Create necessary directories and files -
/config
/var/log/corfu/
/var/log/corfu/corfu.jvm.gc.9000.log
Add the required args of the log path and port -
--log-path /config \
9000
Testing Done:
Verified that corfu servers runs with a docker image
```
.ci/infrastructure-docker-build.sh docker
docker run -ti --rm docker.io/corfudb-universe/corfu-server:0.4.0-SNAPSHOT
```
The current corfu server images fail to run a corfu server container due to runtime errors. This CL fixes these errors.
=> Fix Dockerfile to run Corfu Server from image.

.github/workflows/cloud-deployment-test.yml, .github/workflows/compatibility-test.yml, .github/workflows/injection-framework-test.yml, .github/workflows/publish-corfu.yml, .github/workflows/universe-test.yml, it/pom.xml
Spotify client doesn't work with the latest docker
as it gives an error -
Cannot construct instance of
`com.spotify.docker.client.messages.Image`,
problem: Null virtualSize
This commit pins the docker version to 24.0.9
temporarily until a permanent solution is in place
and also updates the Spotify docker client version to 8.16.0.
Description:
=> Pin Docker to 24.0.9

infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServerCmdLine.java, infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuInterClusterReplicationServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java, test/src/test/java/org/corfudb/integration/AbstractIT.java, test/src/test/java/org/corfudb/integration/CorfuReplicationReconfigurationIT.java, test/src/test/java/org/corfudb/integration/LogReplicationAbstractIT.java
Description:
If an existing snapshot sync is in the apply phase, a new incoming snapshot sync is rejected until the apply phase has completed.  This is because the 2 syncs can race when updating metadata and the shared shadow streams.
Background on Alternate Solution Considered:
An alternate solution is to halt the apply phase when a conflict is detected.  This is not ideal as data is already inconsistent during this phase, user APIs are blocked and there is no straightforward way to 'roll-back' a partial apply.  Besides, the apply phase was added by design to minimize keeping the state inconsistent(apply phase starts after all data is transferred so that network or infra glitches do not impact user apis).
Race …
=> A New Snapshot Sync is rejected on the Standby During Apply Phase of Current Sync

infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServerNode.java, runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java, runtime/src/main/java/org/corfudb/security/tls/ReloadableKeyManager.java
These statements are not that useful.
This avoids flooding logs during
initial netty connection or reconnections.
Description:
=> Remove additional logging in ssl ReloadableKeyManager

infrastructure/src/main/java/org/corfudb/infrastructure/LogReplicationServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/LogReplicationConfig.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/StreamsLogEntryReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/StreamsSnapshotReader.java, test/src/test/java/org/corfudb/infrastructure/logreplication/LogReplicationFSMTest.java, test/src/test/java/org/corfudb/integration/LogReplicationReaderWriterIT.java
Description:
- Added bounding for RPC queue on receiver
- Fix integer overflow when calculating max size for a log entry message, and usage of value
This PR attempts to fix the following problem:
The source has a set timeout period within the completable future for sent log entries.
In cases with larger batch sizes being sent to the sink, this timeout can repeatedly expire before an ack is received to complete the future.
This prompts the source to resend the entires that timed out which will then keep accumulating on the sink, in some cases resulting in an OOM.
=> Bound receiver RPC queue + fix max msg batch size

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/sample/GRPCLogReplicationClientChannelAdapter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/sample/GRPCLogReplicationServerChannelAdapter.java, pom.xml, runtime/pom.xml
- Also upgrade grpc, protobuf and netty-tcnative. 
```
grpc.version 1.65.1
netty.version 4.1.111.Final
netty.tcnative.version 2.0.61.Final
protobuf.version 3.21.12
```
Compatibility: https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty
- Fixes OSS-TP vulnerabilities - [CVE-2023-44487](https://nvd.nist.gov/vuln/detail/CVE-2023-44487), [CVE-2023-34462](https://nvd.nist.gov/vuln/detail/CVE-2023-34462), [CVE-2024-29025](https://nvd.nist.gov/vuln/detail/CVE-2024-29025)
Description:
=> Upgrade Netty from 4.1.89 to 4.1.111

infrastructure/Dockerfile
Avoid installation error enforced by PEP 668.
------
> [ 4/18] RUN python3 -m pip install pyyaml==6.0.1:
0.442 error: externally-managed-environment
0.442
0.442 × This environment is externally managed
0.442 ╰─> To install Python packages system-wide, try apt install
0.442     python3-xyz, where xyz is the package you are trying to
0.442     install.
0.442
0.442     If you wish to install a non-Debian-packaged Python package,
0.442     create a virtual environment using python3 -m venv path/to/venv.
0.442     Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
0.442     sure you have python3-full installed.
0.442
0.442     If you wish to install a non-Debian packaged Python application,
0.442     it may be easiest to use pipx install xyz, which will manage a
0.442     virtual …
=> Install python packages with apt

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
Description:
Fix: maps replication status to remote clusterId as opposed local. 
=> [PG] Remote status clusterId fix

infrastructure/src/main/resources/corfu-compactor-config.yml, scripts/compactor_runner.py
JRE17 introduced -Xlog:async which will write GC logs asynchronously and not pause the JVM during STW events if secondary storage is slow. This patch removes the previous process that copied and synced log files from /dev/shm to /var/log.
Why should this be merged: Simplifies logging
=> Remove GC Log Syncing

.github/workflows/code-coverage.yml, .github/workflows/compatibility-test.yml, .github/workflows/injection-framework-test.yml, .github/workflows/integration-test.yml, .github/workflows/publish-corfu.yml, .github/workflows/unit-test.yml, .github/workflows/universe-test.yml, it/pom.xml
Update image label to ubuntu-latest.
Fix https://github.com/actions/runner-images/issues/6002 to ensure continued support.
Description:
=> Upgrade GitHub Workflow to use latest Ubuntu (#3527)

common/src/main/java/org/corfudb/common/metrics/micrometer/MeterRegistryProvider.java, common/src/main/java/org/corfudb/common/metrics/micrometer/registries/RegistryLoader.java, common/src/main/java/org/corfudb/common/metrics/micrometer/registries/RegistryProvider.java
Description:
1. Create an ability to provide custom metadata for the provided registries loaded by ServiceLoader. 
2. Set common tags like id for the provided registries. 
3. Fix the CompositeRegistry cleanup bug (ConcurrentModificationException).
=> Metric registry provider metadata

infrastructure/src/main/resources/corfu-compactor-config.yml, scripts/compactor_runner.py
Reverts CorfuDB/CorfuDB#3995 to unblock artifacts from master until JRE 17 flags (`-Xlog:async`) are accepted completely.
=> Revert "Remove GC Log Syncing"

runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java, runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java
Some protobufs used by Corfu clients may change even when there is no change in corfu's source code itself.
To help identify these cases, let the caller supply their own source code version number to help identify if the protobuf files on Table opens need to be re-indexed.
Description:
=> Allow caller to specify a source version number

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/PgUtils/PostgresUtils.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, test/src/test/java/org/corfudb/integration/pg/PostgresUtilsTest.java
Description:
Ignore publications not created by LR + use DELETE instead of TRUNCATE since DDL statements are not replicated.
=> PG Utils Fixes

.github/workflows/compatibility-test.yml, .github/workflows/injection-framework-test.yml
GitHub Actions fail with deprecated upload-artifact-v2. 
Upgrading this version fixes it.
https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
Description:
=> Upgrade upload-artifact-v4 from v2

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogEntryWriter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/SinkBufferManager.java, test/src/test/java/org/corfudb/infrastructure/logreplication/LogEntryWriterTest.java, test/src/test/java/org/corfudb/integration/SourceForwardingDataSender.java
Validation logic in LogEntry writer is incorrect in the following scenario:
1. Source sends a batch with timestamp range [1, n]
2. This batch is applied on Sink
3. Before an ACK is received, Replication FSM on the Source stops due to
leadership loss, network blip or any such intermittent failure.
4. New data gets written to replicated streams.
5. Replication starts again.  As ACK from 1) was not received, a new
batch with timestamps [1, n+m] is constructed and sent.
The new 'm' entries must be applied on the Sink.  Instead, it currently
rejects the message.
=> Allow Apply of LogEntry Message Batch with New Entries In the Same Batch.

.github/workflows/publish-corfu.yml, generator/pom.xml, infrastructure/pom.xml
Docker login params are currently sourced from Actions and are passed into pom.xml.
They are useless in pom.xml as they cannot be individually run without the Actions. 
For someone to publish artifacts without Actions, they could do so with the command (as is the case currently)-
`docker login -u <username>` followed by a prompt for the password, and then 
execute prepare and publish commands -
```
.ci/infrastructure-docker-build.sh docker
.ci/generator-docker-build.sh
./mvnw clean deploy -s ./.mvn/settings.xml -DskipTests -Dmaven.javadoc.skip=true -Dcheckstyle.skip -T 1C
```
Description:
=> Move Docker Login to Actions

common/src/main/java/org/corfudb/common/metrics/micrometer/MeterRegistryProvider.java, common/src/main/java/org/corfudb/common/metrics/micrometer/registries/RegistryProvider.java
Description:
This CL does not change any existing functionality, it only makes the provided registry optional. Current mechanism of throwing the exception in the expected cases, introduces the harmless exception into logs, which potentially can redirect a lot of bugs towards our team.
=> Make provided registry optional

runtime/src/main/java/org/corfudb/runtime/collections/Table.java
Description:
Not all callers of Table have all the parameters setup. So this default constructor allows instantiating empty Table objects only for the purposes of extracting tableName and Namespace
=> Default constructor for instantiating empty Table objects

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java
Description:
* This patch disables caching across all the LR runtimes.
* Transactions that have updates to both application and LR metadata tables, as is the case with the snapshot and log entry writers, can introduce application data into LR's runtime cache. This has potential for OOMs in cases with large transaction sizes for application data. Since subsequent access of metadata will bring the application data as well in cases where it was part of the same txn. As access to metadata tables is single-threaded, caching is not critical for performance.
=> Disable all LR runtime caches

cmdlets/pom.xml, common/pom.xml, pom.xml
Description:
Fixes CVE-2023-6378 for logback
, and CVE-2017-20189 for clojure.
=> Update logback to 1.5.12 and clojure to 1.12.0

infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/health/HealthStatus.java, infrastructure/src/test/java/org/corfudb/infrastructure/health/HealthMonitorTest.java
Description:
There could be cases where the runtime issue for the sequencer health thread is reported before the init issue, which will result in the scheduled thread dying and not reporting the sequencer health correctly.
This patch wraps the scheduled thread in runSansThrow, rescheduling the thread and preventing this from happening.
=> Fix the sequencer health monitor bug

infrastructure/src/main/java/org/corfudb/infrastructure/LogReplicationServer.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/LogReplicationConfig.java
Description:
Reduce the batch and queue sizes for incoming and outgoing LR payload.  It was observed during scale testing that 10 messages of ~25MB of each(may include messages resent due to timeout) can cause certain configuration JVMs to go out-of-memory.  Tune these parameters to accommodate such scale.
In future, consider optimizations such as de-duplication of resent messages and/or using disk-backed receiver queue to avoid tuning for specific JVM sizes.
=> LR Batch+Queue Size Tuning

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/TestLogEntryReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/LogEntrySender.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/LogEntryReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/StreamsLogEntryReader.java, test/src/test/java/org/corfudb/infrastructure/logreplication/LogEntryReaderTest.java
Description:
Currently, LogEntryReader stops replication if the size of a transaction exceeds the max supported threshold(25 MB by default).  This is incorrect as the validation is done on uncompressed, serialized size over which Corfu does not put any restriction.  Replication must not be stopped in this case.
=> Remove TX Size Validation in LogEntryReader.

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/CorfuReplicationClusterManagerBaseAdapter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultClusterManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogEntrySinkBufferManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogEntryWriter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/StreamsLogEntryReader.java, test/src/test/java/org/corfudb/integration/CorfuReplicationClusterConfigIT.java
Description:
set LAST_LOG_ENTRY_APPLIED on snapshot completion - Without this change, on a backup/restore when the backup is old and the restore regresses the log sequence, the first log-entry record gets dropped silently (L124 in LogEntryWriter.java) because the last_log_entry_applied still has the info of the cycle before the restore. 
Example : 
1. Active has data until ts 100, and standby has processed 100, hence  the last_log_entry_applied is 100
2. Backup that was taken when sequencer was at ts 50 is now restored on active. So active has regressed to sequence 50.
3. Active enforces a Snapshot sync at 50, and standby clears all the existing data and processes the incoming snapshot data - Metadata Last_snapshot_applied and last_log_entry_batch_processed says 50 but the …
=> LR bugfix: set LAST_LOG_ENTRY_APPLIED on snapshot completion

.github/workflows/cloud-deployment-test.yml, .github/workflows/compatibility-test.yml, .github/workflows/injection-framework-test.yml, .github/workflows/publish-corfu.yml, corfudb-tools/README, infrastructure/src/main/resources/corfu_plugin_config.properties, pom.xml, test/src/test/resources/transport/grpcConfig.properties, test/src/test/resources/transport/nettyConfig.properties, test/src/test/resources/transport/nettyConfigUpgradeActive.properties, test/src/test/resources/transport/nettyConfigUpgradeStandby.properties
Description:
- Bump Corfu Version to 0.9.0.0
- Pin corfudb-cloud to 0.9.0.0
Currently, actions are broken on 9.0.0 due to jdk-17 changes on the master branch.
This CL pins everything to JDK-11 (9.0.0 stage).
=> Bump Corfu Version to 0.9.0.0

corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditor.java, runtime/src/main/java/org/corfudb/runtime/collections/Table.java, runtime/src/main/java/org/corfudb/runtime/exceptions/AbortCause.java
1. Set Table ForkJoinPool corePoolSize to 2 * parallelism as a workaround for
JDK-8330017.
This addresses a known ForkJoinPool bug (JDK-8330017) in JDK 11 and JDK 17,
where TC underflow can cause the pool to hang. The workaround increases
corePoolSize to 2 * parallelism, which ensures that TC (initialized as
-max(corePoolSize, parallelism)) starts at a lower absolute value. This reduces
the likelihood of TC reaching 0, which triggers the underflow.
The impact on performance and resource consumption is minimal because active
worker threads are still controlled by parallelism. A higher corePoolSize
primarily affects workloads with blocking tasks, where it helps retain more
worker threads.
This workaround does not completely prevent the TC underflow issue but makes it
less likely to occur. …
=> Multiple fixes

runtime/src/main/java/org/corfudb/runtime/collections/Table.java
Table fork join pool is a static variable. Although micrometer only [registerMeterIfNecessary](https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java#L613), it's better to make the registration in static code block.
=> Move Table fork join pool metrics creation to static code block

infrastructure/src/main/java/org/corfudb/infrastructure/LivenessValidator.java, test/src/test/java/org/corfudb/infrastructure/LivenessValidatorUnitTest.java
Description:
Existing use of executeQuery() was vulnerable to the FJP bug [JDK-8330017](https://bugs.openjdk.org/browse/JDK-8330017?jql=labels%20%3D%20reproducer-hard)
=> [4.2.2] Avoid FJP bug in Compactor's liveness validator

infrastructure/src/main/java/org/corfudb/infrastructure/LivenessValidator.java, test/src/test/java/org/corfudb/infrastructure/LivenessValidatorUnitTest.java
Description:
Existing use of executeQuery() was vulnerable to the FJP bug [JDK-8330017](https://bugs.openjdk.org/browse/JDK-8330017?jql=labels%20%3D%20reproducer-hard)
=> [9.0] Avoid FJP bug in Compactor's liveness validator

pom.xml
Fix CVEs -
- CVE-2024-12801 (logback-core)
- CVE-2024-12798 (logback-core)
- CVE-2024-47554 (commons-io)
- CVE-2020-13956 (httpclient)
Description:
=> Upgrade logback to 1.5.17, commons-io to 2.18.0, httpclient to 4.5.14

pom.xml
Fix CVEs -
- CVE-2024-12801 (logback-core)
- CVE-2024-12798 (logback-core)
- CVE-2024-47554 (commons-io)
- CVE-2020-13956 (httpclient)
(cherry picked from commit 72e11bb3d56c73bb0add845e24f14cc0c37b418b)
Description:
=> Upgrade logback to 1.5.17, commons-io to 2.18.0, httpclient to 4.5.14 (#4048)

runtime/src/main/java/org/corfudb/runtime/collections/Table.java
Given that the original JDK bug (https://bugs.openjdk.org/browse/JDK-8330017) has been fixed by https://github.com/openjdk/jdk/pull/24034, revert the temporary workaround.
=> Revert Table ForkJoinPool corePoolSize and metrics changes

runtime/src/main/java/org/corfudb/util/FileWatcher.java, runtime/src/test/java/org/corfudb/runtime/utils/FileWatcherTest.java, runtime/src/test/resources/logback-test.xml
Java NIO WatchService might fire events upon metadata changes on certain platforms, e.g. Linux inotify IN_ATTRIB. This could cause unnecessary cert hot-swapping workflows in both Corfu server and client, and cause connection interruptions.
This PR reduces unnecessary connection restarts by checking the hash code of the watched files to determine whether the file content has been changed.
=> Check file modification in FileWatcher before invoking callbacks

pom.xml
Fixes CVE-2024-47535.
This CL updates Netty alone without upgrading gRPC and protobuf versions.
I have tested that this newer version is compatible with the current gRPC and protobuf versions.
Description:
=> Upgrade Netty Version from 4.1.111.Final to 4.1.119.Final

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/CorfuReplicationClusterManagerBaseAdapter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultClusterManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogEntrySinkBufferManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogEntryWriter.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java, test/src/test/java/org/corfudb/integration/CorfuReplicationClusterConfigIT.java
Reverts CorfuDB/CorfuDB#4056
Reason: we are pushing it in `corfu-0.4.2.3` instead.
=> Revert "[Backport] LR bugfix: set LAST_LOG_ENTRY_APPLIED on snapshot completion (#4038)"

runtime/src/main/java/org/corfudb/util/serializer/DynamicProtobufSerializer.java, test/src/test/java/org/corfudb/integration/CorfuStoreBrowserEditorIT.java
Description:
This avoids having to duplicate code in other areas and makes this layer re-usable.
+Simple IT to validate the new exposed api.
=> Expose some essential functions from DynamicProtobufSerializer

runtime/src/main/java/org/corfudb/runtime/view/stream/StreamAddressSpace.java, test/src/test/java/org/corfudb/runtime/view/stream/StreamAddressSpaceTest.java
Description:
It is intended that cardinality cache of RoaringBitmap should be disabled by default in order to avoid non-theadsafe bitmap anomalies. This PR fixes the no-arg constructor of StreamAddressSpace to disable the cache.
Read operations of Roaring64NavigableMap could mutate internal cache states if cardinality cache is enabled. This leads to undefined exceptions including IllegalStateException and ArrayIndexOutOfBoundsException.
=> Disable RoaringBitMap cardinality cache in StreamAddressSpace no-arg constructor

corfudb-tools/src/main/java/org/corfudb/browser/CorfuBrowserEditorCommands.java, corfudb-tools/src/main/java/org/corfudb/browser/CorfuOfflineBrowserEditor.java, corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditor.java, corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditorMain.java, test/src/test/java/org/corfudb/integration/CorfuStoreBrowserEditorIT.java
This allows triaging tools to simultaneously dump
several tables at once and re-use the connection made by the tool to CorfuServer saving time in setup & teardown.
Also make the output in full parseable json format for easy tooling. For example, it is now possible to check if a big table dump carries a record with something like `jq '.[] | select(.key == "foo")' tableName.json`
Description:
=> Dump multiple tables at once reusing connection

pom.xml
Fixes CVE-2024-47535.
This CL updates Netty alone without upgrading gRPC and protobuf versions.
I have tested that this newer version is compatible with the current gRPC and protobuf versions.
Description:
=> Upgrade Netty Version from 4.1.111.Final to 4.1.119.Final (#4053)

pom.xml
Reverts CorfuDB/CorfuDB#4061
Reason: Postponed to next release - corfu-0.4.2.4.
=> Revert "Upgrade Netty Version from 4.1.111.Final to 4.1.119.Final (#4053)"

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationAckReader.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java, infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/NegotiatingState.java, test/src/test/java/org/corfudb/integration/AbstractIT.java, test/src/test/java/org/corfudb/integration/CorfuReplicationClusterConfigIT.java
Description:
Mark previous snapshot info as completed when transitioning from INITIALIZED -> LOG_ENTRY_SYNC
In cases where the reception of the snapshot apply ack was interrupted on source but the apply had completed on the sink, ex. during a network blip and we start negotiation, we will know to continue to log entry from the sinks negotiation response but will never mark the prior snapshot sync's info as complete. 
=> Update prior snapshot sync info on LOG_ENTRY_SYNC_REQUEST
