- bin/corfuDBLaunch.sh
- bin/corfuDBStreamSingle.sh
- conf/streaming_configmaster.yml
- conf/streaming_sequencer.yml
- src/main/java/org/corfudb/infrastructure/wireprotocol/NettyCorfuMessageDecoder.java
This pull-request contains these changes:
- changing conf/streaming_configmaster and conf/logunit scripts to use netty logunit server and netty protocol. Without this change, streaming sequencer server will cause client to throw error "java.lang.RuntimeException: NewStreamingSequencer only supports INewStreamSequencer, primary sequencer is of type class org.corfudb.runtime.protocols.sequencers.CorfuDBStreamingSequencerProtocol".
- change NettyCorfuMessageDecoder to handle EmptyByteBuf message injected by Netty after each burst of incoming messages. Without this change, the changes made by one client on a corfuDB object shared by another client can't be sync-ed by the other client, the infinite loop of error caused is "io.netty.handler.codec.DecoderException: …
> handling EmptyByteBuf injected by Netty and add debug options to some scripts

- src/main/java/org/corfudb/runtime/CorfuDBRuntime.java
- src/main/java/org/corfudb/runtime/view/IStreamAddressSpace.java
- src/main/java/org/corfudb/runtime/view/LocalCorfuDBInstance.java
- src/main/java/org/corfudb/runtime/view/StreamAddressSpace.java
- src/test/java/org/corfudb/runtime/view/StreamAddressSpaceIT.java
This fix should prevent a lockup issue when resetAll() is called.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/56)
> detect when the UUID of the instance changes and reset all local caches when that occurs.

- pom.xml
- src/main/java/org/corfudb/infrastructure/ConfigMasterServer.java
The frontend code is currently not used and increasing build times due to bower and gulp build.
This pull request disables the frontend code from the build.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/61)
> remove frontend, which should improve build times

- src/main/java/org/corfudb/runtime/CorfuDBRuntime.java
- src/main/java/org/corfudb/runtime/smr/SimpleSMREngine.java
- src/main/java/org/corfudb/runtime/view/StreamAddressSpace.java
- src/test/java/org/corfudb/runtime/view/StreamAddressSpaceIT.java
Converts a call of propose to complete in the same thread, which might significantly affect performance, but ensures propose completes before sync is called.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/64)
> Adds additional tracing messages, turns caching back on and possibly fixes a case where propose completes before sync.

- src/deb/control/postinst
currently the postinst package doesn't work on some versions of bash due to parameter expansion issues.
this fix uses basename isntead.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/78)
> fix broken debian package

- .travis_scripts/push_deb.sh
In order for jdeb to complete successfully, mvn deploy needs to be run.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/80)
> Fixes empty deb files being put in the repository.

- src/main/java/org/corfudb/cmdlets/corfu_as.java
- src/main/java/org/corfudb/infrastructure/CorfuServer.java
- src/main/java/org/corfudb/protocols/logprotocol/TXEntry.java
- src/main/java/org/corfudb/protocols/wireprotocol/ILogUnitEntry.java
- src/main/java/org/corfudb/protocols/wireprotocol/LogUnitReadResponseMsg.java
- src/main/java/org/corfudb/runtime/CorfuRuntime.java
- src/main/java/org/corfudb/runtime/view/AbstractReplicationView.java
- src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- src/main/java/org/corfudb/util/CFUtils.java
- src/test/java/org/corfudb/runtime/collections/SMRMapTest.java
- src/test/java/org/corfudb/runtime/object/CorfuSMRObjectProxyTest.java
- src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
- src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
- src/test/java/org/corfudb/runtime/view/StreamViewTest.java
This pull request implements address space caching,
which improves the performance of the local client
significantly.
Currently, version messages always show commitid-dirty since the repo 
will be dirty after build. This change inserts the correct build string.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/83)
> Address space cache, nicer version messages.

- src/main/java/org/corfudb/infrastructure/CorfuServer.java
- src/main/java/org/corfudb/infrastructure/IServer.java
- src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- src/main/java/org/corfudb/infrastructure/SequencerServer.java
- src/main/java/org/corfudb/util/Utils.java
- src/test/java/org/corfudb/infrastructure/SequencerServerAssertions.java
- src/test/java/org/corfudb/infrastructure/SequencerServerTest.java
- src/test/java/org/corfudb/runtime/view/ChainReplicationViewTest.java
This patch implements sequencer recovery via checkpointing. 
The sequencer periodically checkpoints its state to a file, and
recovers from that state during a cold start unless initial-token is set.
The checkpoint rate can be set via the --checkpoint command
line option.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/86)
> Implement sequencer recovery

- src/main/java/org/corfudb/runtime/object/CorfuSMRObjectProxy.java
- src/main/java/org/corfudb/runtime/view/StreamView.java
- src/test/java/org/corfudb/AbstractCorfuTest.java
- src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java
- src/test/java/org/corfudb/runtime/object/CorfuSMRObjectProxyTest.java
Due to a concurrency bug, the accessormutator would sometimes return an incorrect result. This
patch fixes that bug by using completablefutures to wrap results.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/90)
> fix concurrency bug in objectproxy

- src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- src/test/resources/logback-test.xml
Previously we were creating a new mapping per entry, which invoked a system call and was expensive. This patch creates a single large (2GB) mapping per file.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/91)
> Use only a single file mapping per file.

- src/main/java/org/corfudb/protocols/logprotocol/LogEntry.java
- src/main/java/org/corfudb/protocols/logprotocol/StreamCOWEntry.java
- src/main/java/org/corfudb/runtime/object/CorfuSMRObjectProxy.java
- src/main/java/org/corfudb/runtime/object/DontInstrument.java
- src/main/java/org/corfudb/runtime/view/ObjectOpenOptions.java
- src/main/java/org/corfudb/runtime/view/ObjectsView.java
- src/main/java/org/corfudb/runtime/view/StreamView.java
- src/main/java/org/corfudb/runtime/view/StreamsView.java
- src/test/java/org/corfudb/runtime/collections/SMRMapTest.java
- src/test/java/org/corfudb/runtime/object/CorfuSMRObjectProxyTest.java
- src/test/java/org/corfudb/runtime/object/TestClassWithPrimitives.java
- src/test/java/org/corfudb/runtime/view/ObjectsViewTest.java
- src/test/java/org/corfudb/runtime/view/StreamsViewTest.java
Primitive serializer enables faster serialization but only supports primitive types.
CoW objects enable copying an object quickly by referencing a snapshot on the stream.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/97)
> CoW Objects, Primitive Serializer support

- src/main/java/org/corfudb/runtime/object/CorfuSMRObjectProxy.java
- src/main/java/org/corfudb/runtime/object/TransactionalContext.java
- src/main/java/org/corfudb/runtime/view/ObjectsView.java
- src/main/java/org/corfudb/util/serializer/PrimitiveSerializer.java
- src/main/java/org/corfudb/util/serializer/Serializers.java
- src/test/java/org/corfudb/runtime/collections/SMRMapTest.java
- src/test/java/org/corfudb/runtime/object/CorfuSMRObjectProxyTest.java
- src/test/java/org/corfudb/runtime/view/ObjectsViewTest.java
When an object is first read in a transaction, this patch stores the first read to be
sync, and all subsequent reads to respect that sync.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/99)
> Sync object on first tx read. Improvements to primtive serializer.

- scripts/corfu_server.sh
Partially addresses #98.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/100)
> Fix a bug where JVMFLAGS was not being passed by the startup script

- src/main/java/org/corfudb/runtime/object/CorfuSMRObjectProxy.java
- src/main/java/org/corfudb/runtime/object/TransactionalContext.java
- src/test/java/org/corfudb/runtime/collections/SMRMapTest.java
Previously, during first sync, sometimes updates would be applied to the
transactional clone object, which would cause updates to be lost. This
patch redirects updates to the underlying smrobject if in a sync.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/101)
> Fix transaction sync.

- pom.xml
- src/main/java/org/corfudb/util/serializer/ISerializer.java
- src/main/java/org/corfudb/util/serializer/JSONSerializer.java
- src/test/java/org/corfudb/runtime/collections/SMRMapTest.java
Previously, we were cloning by serializing and then deserializing objects, 
which caused an issue due to type erasure. We now use Kryo to do cloning,
which comes with its own quirks.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/102)
> Clone using Kryo.

- src/main/java/org/corfudb/infrastructure/CorfuServer.java
- src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsg.java
Previously some options for Netty were being incorrectly applied to the acceptor channel instead of the new channel (via childOption). This change fixes that bug. In addition, a marker field has been added to CorfuMsg.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/106)
> Fix childoptions for Netty, add a marker field

- src/main/java/org/corfudb/protocols/logprotocol/TXEntry.java
Fixes #105, where read-after-read requests were being detected as a conflict
and aborted. This is fixed by making sure read only operations were not added into the writeSet
and counted as a mutation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/107)
> Fix an issue where read-after-read was resolved as a conflict

- src/main/java/org/corfudb/cmdlets/corfu_as.java
- src/main/java/org/corfudb/cmdlets/corfu_stream.java
- src/main/java/org/corfudb/protocols/logprotocol/LogEntry.java
- src/main/java/org/corfudb/protocols/logprotocol/TXEntry.java
- src/main/java/org/corfudb/protocols/wireprotocol/ILogUnitEntry.java
- src/main/java/org/corfudb/protocols/wireprotocol/LogUnitReadResponseMsg.java
- src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
- src/main/java/org/corfudb/runtime/object/CorfuSMRObjectProxy.java
- src/main/java/org/corfudb/runtime/view/AbstractReplicationView.java
- src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- src/main/java/org/corfudb/runtime/view/ChainReplicationView.java
- src/main/java/org/corfudb/runtime/view/ObjectsView.java
- src/main/java/org/corfudb/runtime/view/StreamView.java
- src/test/java/org/corfudb/runtime/clients/LogUnitClientTest.java
- src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
- src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
- src/test/java/org/corfudb/runtime/view/ChainReplicationViewTest.java
- src/test/java/org/corfudb/runtime/view/ObjectsViewTest.java
- src/test/java/org/corfudb/runtime/view/StreamViewTest.java
- src/test/java/org/corfudb/runtime/view/StreamsViewTest.java
This patch refactors the log entry implementation for clarity
and fixes #111, a bug where TXes were sometimes aborted due to
intervening aborts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/112)
> Improve and refactor log entry implementation, fix TX resolution.

- src/main/java/org/corfudb/infrastructure/SequencerServer.java
- src/main/java/org/corfudb/runtime/view/StreamView.java
- src/main/java/org/corfudb/runtime/view/StreamsView.java
- src/test/java/org/corfudb/runtime/view/SequencerViewTest.java
Due to a bug in the backpointer implementation, the system would
sometime read past the start of the stream in order to resolve it.
This patch tells the sequencer to issue a -1 token the first time a stream
is written to, which denotes the start of the stream.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/116)
> Don't read past start of the stream

- src/main/java/org/corfudb/protocols/logprotocol/LogEntry.java
- src/main/java/org/corfudb/protocols/logprotocol/TXEntry.java
- src/main/java/org/corfudb/protocols/wireprotocol/ILogUnitEntry.java
- src/main/java/org/corfudb/protocols/wireprotocol/LogUnitPayloadMsg.java
- src/main/java/org/corfudb/protocols/wireprotocol/LogUnitWriteMsg.java
- src/main/java/org/corfudb/runtime/object/CorfuSMRObjectProxy.java
- src/main/java/org/corfudb/runtime/object/ICorfuSMRObject.java
- src/main/java/org/corfudb/runtime/object/TransactionalContext.java
- src/main/java/org/corfudb/runtime/view/AbstractReplicationView.java
- src/main/java/org/corfudb/runtime/view/ObjectsView.java
- src/main/java/org/corfudb/runtime/view/StreamView.java
- src/test/java/org/corfudb/runtime/view/ObjectsViewTest.java
- src/test/java/org/corfudb/runtime/view/StreamViewTest.java
This patch fixes a concurrency bug where the firstReadTimestamp was being set to the 
latest stream pointer and possibly overwritten by concurrent invocations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/118)
> Fix a concurrency bug where a broken the firstReadTimestamp was not properly updated

- src/main/java/org/corfudb/protocols/logprotocol/TXEntry.java
- src/main/java/org/corfudb/runtime/collections/FGMap.java
- src/main/java/org/corfudb/runtime/object/ConstructorType.java
- src/main/java/org/corfudb/runtime/object/CorfuObject.java
- src/main/java/org/corfudb/runtime/object/CorfuObjectProxy.java
- src/main/java/org/corfudb/runtime/object/CorfuProxyBuilder.java
- src/main/java/org/corfudb/runtime/object/CorfuSMRObjectProxy.java
- src/main/java/org/corfudb/runtime/object/ICorfuObject.java
- src/main/java/org/corfudb/runtime/object/ICorfuSMRObject.java
- src/main/java/org/corfudb/runtime/object/ObjectType.java
- src/main/java/org/corfudb/runtime/object/StaticMappingObject.java
- src/main/java/org/corfudb/runtime/object/TransactionalContext.java
- src/main/java/org/corfudb/runtime/object/TransactionalMethod.java
- src/main/java/org/corfudb/runtime/view/ObjectsView.java
- src/main/java/org/corfudb/util/serializer/JSONSerializer.java
- src/main/java/org/corfudb/util/serializer/PrimitiveSerializer.java
- src/test/java/org/corfudb/runtime/collections/FGMapTest.java
This patch refactors the SMR Proxy into a non-SMR Proxy and an SMR proxy.
In addition, the transactionalMethod annotation is improved and nested TXs are
fully supported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/123)
> Refactor SMR Proxy into Proxy and SMR Proxy, fix for nested TX

- src/main/java/org/corfudb/runtime/collections/FGMap.java
Currently, we directly use the Java hashCode to divide into buckets, which
can cause poor distributions (for example, if the hashCode is of an int, and
the items being inserted are multiples of 10). This patch uses
a Luby-Rakoff transform to randmozie the distributions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/125)
> For the FG map, use a Luby-Rackoff transform to randomize the hashCode

- src/main/java/org/corfudb/runtime/collections/FGMap.java
- src/main/java/org/corfudb/runtime/object/CorfuProxyBuilder.java
- src/main/java/org/corfudb/runtime/object/CorfuSMRObjectProxy.java
- src/main/java/org/corfudb/runtime/view/ObjectsView.java
- src/main/java/org/corfudb/runtime/view/StreamView.java
- src/main/java/org/corfudb/util/ReflectionUtils.java
- src/test/java/org/corfudb/runtime/collections/FGMapTest.java
- src/test/java/org/corfudb/runtime/collections/SMRMapTest.java
This patch add supports for persisting arguments to a constructor. 
This allows for example, the FGMap to be parameterized.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/127)
> Add support for persisting constructor arguments.

- src/main/java/org/corfudb/runtime/object/transactions/TransactionalContext.java
- src/main/java/org/corfudb/runtime/view/ObjectsView.java
- src/test/java/org/corfudb/runtime/object/transactions/TransactionalContextTest.java
- src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
This patch adds support for transaction notifications, which fire at the end of a successful locally proposed transaction
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/138)
> Transaction notifications support

- src/main/java/org/corfudb/infrastructure/LayoutServer.java
Fixes CorfuDB/CorfuDB#143 by writing the `layout` file when a bootstrap operation is successful.  
I don't have a unit test at this time to provoke the bug inside of the Maven test framework, sorry.  See the bug report for a reproducing shell script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/144)
> Fix CorfuDB/CorfuDB#143

- src/main/java/org/corfudb/cmdlets/corfu_layouts.java
- src/main/java/org/corfudb/infrastructure/LayoutServer.java
- src/main/java/org/corfudb/infrastructure/NettyServerRouter.java
- src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsg.java
- src/main/java/org/corfudb/runtime/clients/LayoutClient.java
- src/main/java/org/corfudb/runtime/exceptions/AlreadyBootstrappedException.java
- src/test/java/org/corfudb/infrastructure/LayoutServerTest.java
- src/test/java/org/corfudb/runtime/clients/LayoutClientTest.java
Previously, calling bootstrap would just return NACK, which is 
passed to the client as false. This patch causes it to return an
exception instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/149)
> Throw an exception when bootstrapped servers are re-bootstrapped

- src/main/java/org/corfudb/runtime/object/CorfuProxyBuilder.java
- src/test/java/org/corfudb/runtime/object/CorfuSMRObjectProxyTest.java
- src/test/java/org/corfudb/runtime/object/TestClass.java
- src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
- src/test/resources/logback-test.xml
An unknown bug was introduced in the legacy instrumentation code which caused the proxy code to default to providing MutatorAccessors instead of Accessors. This would cause automatic instrumentation to fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/153)
> Fix a bug where the legacy object proxy code was defaulting to Accessors instead of MutatorAccessors

- src/main/java/org/corfudb/infrastructure/BaseServer.java
- src/main/java/org/corfudb/infrastructure/CorfuServer.java
- src/main/java/org/corfudb/infrastructure/IServerRouter.java
- src/main/java/org/corfudb/infrastructure/LayoutServer.java
- src/main/java/org/corfudb/infrastructure/NettyServerRouter.java
- src/main/java/org/corfudb/infrastructure/SequencerServer.java
- src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsg.java
- src/test/java/org/corfudb/infrastructure/AbstractServerTest.java
- src/test/java/org/corfudb/infrastructure/LayoutServerTest.java
- src/test/java/org/corfudb/infrastructure/TestServerRouter.java
- src/test/java/org/corfudb/runtime/clients/AbstractClientTest.java
- src/test/java/org/corfudb/runtime/clients/LayoutClientTest.java
- src/test/java/org/corfudb/runtime/clients/TestClientRouter.java
- src/test/java/org/corfudb/runtime/collections/SMRMapTest.java
- src/test/java/org/corfudb/runtime/object/CorfuSMRObjectProxyTest.java
- src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
- src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
- src/test/java/org/corfudb/runtime/view/ChainReplicationViewTest.java
- src/test/java/org/corfudb/runtime/view/LayoutViewTest.java
- src/test/java/org/corfudb/runtime/view/StreamViewTest.java
- src/test/java/org/corfudb/runtime/view/StreamsViewTest.java
- src/test/resources/logback-test.xml
Previously, the unit testing framework did not check for epochs in messages, which let a few bugs related to epoch checking slip through. This has been added now.
In addition, previously, after a layout change, the ACK message from a layout server in the wrong epoch would be dropped, causing communication issues with clients in the wrong epoch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/154)
> new unit testing framework which accounts for epochs. Fix issue where ACK message in wrong epoch is ignored.

- src/main/java/org/corfudb/runtime/CorfuRuntime.java
- src/test/java/org/corfudb/runtime/CorfuRuntimeTest.java
Fixed a race condition where a thread can access an incompletely
initialized layout while CorfuRuntime is fetching a new layout.
> Fix CorfuDB/CorfuDB#141

- pom.xml
- src/main/java/org/corfudb/runtime/object/CorfuProxyBuilder.java
- src/main/java/org/corfudb/runtime/object/CorfuSMRObjectProxy.java
- src/test/java/org/corfudb/runtime/object/CorfuSMRObjectProxyTest.java
- src/test/java/org/corfudb/runtime/object/TestClassUsingAnnotation.java
In the annotation framework, methods which were not annotated were not being instrumented by default. This patch fixes this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/159)
> fix a bug in the annotation framework where unannotated methods were not instrumented

- pom.xml
- src/main/java/org/corfudb/runtime/CorfuRuntime.java
- src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
- src/test/java/org/corfudb/runtime/clients/NettyCommTest.java
- src/test/java/org/corfudb/runtime/clients/TestClientRouter.java
- src/test/java/org/corfudb/runtime/view/LayoutViewTest.java
Previously, if the router fails on start(), it throws an exception which causes the generation of a client layout view to fail. This patch makes the router retry.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/156)
> Retry if netty router connection fails

- src/main/java/org/corfudb/runtime/CorfuRuntime.java
This patch exposes the version information in CorfuRuntime, which should help with debugging. It also prints the runtime version as a debug message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/164)
> Expose version info in CorfuRuntime

- src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- src/main/java/org/corfudb/protocols/wireprotocol/LogUnitReadResponseMsg.java
- src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java
Since the LogUnitEntry is part of the LogUnitServer internal
representation, I grouped them together. Also, I added a address
field in LogUnitEntry because that information was only retained
in the datacache map.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/181)
> Re-organization and clean up

- src/main/java/org/corfudb/infrastructure/LayoutServer.java
- src/main/java/org/corfudb/infrastructure/Rank.java
- src/main/java/org/corfudb/util/JSONUtils.java
- src/test/java/org/corfudb/infrastructure/AbstractServerTest.java
- src/test/java/org/corfudb/infrastructure/LayoutServerAssertions.java
- src/test/java/org/corfudb/infrastructure/LayoutServerTest.java
Fixes to Paxos protocol in Layout Server
- Phase1 and Phase2 data is now persisted to disk.
- ClientId now part of the Rank in the protocol.
- Last known accepted value is part of phase1 response.
- Class level synchronization for methods. Needs to be made finer
grained.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/183)
> Paxos branch

- src/main/java/org/corfudb/infrastructure/CorfuServer.java
- src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
- src/test/java/org/corfudb/runtime/clients/NettyCommTest.java
I've only been bitten by port reuse problems during manual testing and not during automated tests ... but it'll eventually happen.  Let's avoid the easy stuff now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/192)
> Add SO_REUSEADDR to avoid socket binding reuse problems during rapid process restarts

- src/main/java/org/corfudb/cmdlets/corfu_layout.java
- src/main/java/org/corfudb/infrastructure/LayoutServer.java
- src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsg.java
- src/main/java/org/corfudb/runtime/clients/LayoutClient.java
- src/main/java/org/corfudb/runtime/clients/LayoutPrepareResponse.java
- src/main/java/org/corfudb/runtime/view/Layout.java
- src/main/java/org/corfudb/runtime/view/LayoutView.java
- src/test/java/org/corfudb/infrastructure/LayoutServerTest.java
- src/test/java/org/corfudb/infrastructure/TestServerRouter.java
- src/test/java/org/corfudb/runtime/clients/LayoutClientTest.java
LAYOUT_PREPARE_ACK message was being incorrectly instantiated by
layoutServer. Fixed the issue and also added Message
Serialization/Deserialization to Server Tests to catch this problem
in automated testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/200)
> Fix: Client can deserialize LAYOUT_PREPARE_ACK

- src/main/java/org/corfudb/infrastructure/AbstractServer.java
- src/main/java/org/corfudb/infrastructure/BaseServer.java
- src/main/java/org/corfudb/infrastructure/NettyServerRouter.java
- src/main/java/org/corfudb/util/CorfuMsgHandler.java
- src/test/java/org/corfudb/infrastructure/BaseServerTest.java
- src/test/java/org/corfudb/runtime/clients/NettyCommTest.java
- src/test/java/org/corfudb/runtime/clients/TestClientRouterTest.java
- src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
This patch adds CorfuMsgHandler, which routes messages via a functional 
interface. This removes the need for large switch statements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/203)
> Add a new message handler which routes messages

- src/main/java/org/corfudb/cmdlets/corfu_layout.java
- src/main/java/org/corfudb/infrastructure/CorfuServer.java
- src/main/java/org/corfudb/infrastructure/DataStore.java
- src/main/java/org/corfudb/infrastructure/IDataStore.java
- src/main/java/org/corfudb/infrastructure/LayoutServer.java
- src/main/java/org/corfudb/infrastructure/NettyServerRouter.java
- src/main/java/org/corfudb/infrastructure/Phase2Data.java
- src/main/java/org/corfudb/infrastructure/Rank.java
- src/main/java/org/corfudb/runtime/clients/LayoutClient.java
- src/main/java/org/corfudb/runtime/view/LayoutView.java
- src/test/java/org/corfudb/infrastructure/DataStoreTest.java
- src/test/java/org/corfudb/infrastructure/LayoutServerAssertions.java
- src/test/java/org/corfudb/infrastructure/LayoutServerTest.java
- src/test/java/org/corfudb/runtime/clients/LayoutClientTest.java
- src/test/java/org/corfudb/runtime/clients/NettyCommTest.java
- src/test/java/org/corfudb/runtime/view/LayoutViewTest.java
- Implemented node level datastore to persist Layouts and data related to Paxos phases.
- Refactored Layout server code
- Implemented committed phase of the paxos protocol
- Added persistence so that Server Epoch does not reset on node restart
- Added basic tests for datastore implementation
- Fixed existing tests to work with reconfiguration changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/208)
> Improvements to reconfig protocol implementation

- src/main/java/org/corfudb/infrastructure/log/RollingLog.java
- src/main/java/org/corfudb/protocols/logprotocol/SMREntry.java
- src/main/java/org/corfudb/protocols/logprotocol/StreamHintEntry.java
- src/main/java/org/corfudb/protocols/logprotocol/TXEntry.java
- src/main/java/org/corfudb/protocols/logprotocol/TXLambdaReferenceEntry.java
- src/main/java/org/corfudb/protocols/wireprotocol/CorfuRangeMsg.java
- src/main/java/org/corfudb/runtime/object/CorfuObjectProxy.java
- src/main/java/org/corfudb/runtime/object/CorfuProxyBuilder.java
- src/main/java/org/corfudb/runtime/object/CorfuSMRObjectProxy.java
- src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java
- src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
- src/main/java/org/corfudb/runtime/view/ChainReplicationView.java
- src/main/java/org/corfudb/runtime/view/ObjectBuilder.java
- src/main/java/org/corfudb/util/serializer/SerializerType.java
- src/main/java/org/corfudb/util/serializer/Serializers.java
- src/test/java/org/corfudb/runtime/collections/SMRMapTest.java
- src/test/java/org/corfudb/runtime/object/CorfuSMRObjectProxyTest.java
- src/test/java/org/corfudb/runtime/view/ObjectsViewTest.java
This patch enables the client to register and use a custom serializer
with the ObjectBuilder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/218)
> Custom Serialization

- pom.xml
Find-bugs dependency to not be included in the final consumable jar. It uses struts jars that are not security compliant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/231)
> Find-bugs dependency to not be included in jar

- src/main/java/org/corfudb/infrastructure/IFailureDetectorPolicy.java
- src/main/java/org/corfudb/infrastructure/PeriodicPollPolicy.java
- src/main/java/org/corfudb/runtime/clients/IClientRouter.java
- src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
- src/test/java/org/corfudb/infrastructure/PeriodicPollPolicyTest.java
- src/test/java/org/corfudb/runtime/clients/TestClientRouter.java
PeriodicPollingPolicy added.
executePolicy : Pings all the servers in the layout once and updates their status.
Marks them failed if pings fail more than 2 times in a row.
get ServerStatus : Fetches the latest server status.
This resets the status of the failed servers so that they are not shown in the next result. Thus a failed node will only appear once in the result after failedPollLimit which is 3 polls by default.
> Failure Detection Policy

- src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java
- src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- src/main/java/org/corfudb/protocols/wireprotocol/FillHoleRequest.java
- src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
- src/main/java/org/corfudb/runtime/exceptions/LogUnitException.java
- src/test/java/org/corfudb/runtime/clients/LogUnitClientTest.java
The logunit was not properly detecting address overwrites for
hole filling requests. Also, fixed the write handler. It was conflating
runtime and overwrite exceptions. The server was returning an overwrite
error code on runtime exceptions that are not related to overwriting.
> Fixed the fillHole and write handlers

- src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
This patch increases the cache miss time in the cacheMissTimesOut test to 1s,
which reduces the chance that the test will fail in Travis due to a slow container.
In the future, we will need to have a variable timeout, since increasing the 
timeout time increases local execution time as well.
> increase cache miss test wait time, addresses #268

- .travis_scripts/mvnrepo.sh
- .travis_scripts/push_deb.sh
Currently artifacts are being stored in this repo, causing checkouts to take
a long time. This modifies the scripts to store the artifacts in another repo.
> Move artifacts to Corfu-Repo repo

- .travis_scripts/javadocs.sh
- .travis_scripts/mvnrepo.sh
- .travis_scripts/push_deb.sh
This pull request fixes an issue with deb and mvn build generation, due to incorrect maven
version and eliminates a redundant test run when javadocs are generated.
> skip tests on javadoc generation, set maven version to 3.3.9 on debian/mvn build

- .travis_scripts/mvnrepo.sh
- .travis_scripts/push_deb.sh
This pull request fixes an issue with deb and mvn builds
not using the maven wrapper, and thus getting the wrong mvn revision.
> force mvnw use

- src/test/java/org/corfudb/runtime/clients/AbstractClientTest.java
In the AbstractClientTest, the client/server should not use NettyClientRouter in CorfuRuntime.
My specific use case:
Testing ManagementClient which tries to connect to the ManagementServer.
The management server uses the corfuRuntime to stay updated with the latest layout.
We need to use the testClientRouter instead of the NettyClientRouter to test this functionality.
> Use testClientRouters in CorfuRuntime for client tests

- src/main/java/org/corfudb/runtime/object/CorfuSMRObjectProxy.java
- src/test/java/org/corfudb/runtime/object/CorfuSMRObjectProxyTest.java
CorfuSMRObjectProxy uses reentrant locks and synchronized methods. As a
consequence, code paths can aquire the locks in reverse order can
cause a deadlock. For example, thead1(t1) acquires a synchronized method
lock, thread2(t2) acquire a reentrant lock, then t1 tries to acquire the
same method's lock while t2 is trying to acquire the reentrant lock.
> CorfuSMRObjectProxy Deadlock

- src/main/java/org/corfudb/runtime/CorfuRuntime.java
Invalidating a layout can result in multiple background layout fetch
tasks, this can cause race conditions when setting the layout because
the fetchLayout method is not thread safe. This is a quick fix until
the fetch layout mechanism is redone.
> Synchronize invalidateLayout

- src/main/java/org/corfudb/infrastructure/CorfuServer.java
In the "learn something new every day" department, it looks like the docopt parsing won't create a default value for a flag if that flag isn't mentioned in the 1-line summary.  Fixes #292.
> Fix for #292: add 'n' option to 1-line usage summary

- infrastructure/src/main/java/org/corfudb/infrastructure/LayoutServer.java
**Removing configMgr code from the layout Server.**
This code functionality has been moved to the following as a part of the failure detector: 
PeriodicPollPolicy #255 
Management Server #261 
@slfritchie Please have a look at this to make sure this is no longer required and I am not breaking any QuickCheck tests.
> Removing configMgr. Moved to Failure Detector

- test/src/test/java/org/corfudb/runtime/clients/ManagementClientTest.java
This fixes the deadlock created by the "handleFailures" test in ManagementClientTest.
The CorfuRuntime in the managementServer is stuck endlessly trying to connect to the layout server mentioned in the layout with which it is bootstrapped.
This causes a weird bug by blocking the main thread of the ManagementServer and disallowing it to accept any new messages even the FailureDetected message.
Thus by now giving this runtime a new bootstrapped layout server it connects to and returns and the rest of the messages are then accepted just fine.
I am not using defaultServerContext as I need to start the servers in single mode. (avoid having to bootstrap layout server separately).
> Test deadlock fix

- runtime/src/main/java/org/corfudb/util/serializer/CorfuSerializer.java
- test/src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java
- test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
This patch fixes bug #305. This bug is caused by a classic encoding
typo, where a control byte(i.e. CorfuPayloadMagic) can be part of the
data segment. Writing a byte array where the first byte is equal to
CorfuPayloadMagic would cause a NullPointerException.
> Stream Read NullPointerException Fix

- .travis_scripts/mvnrepo.sh
Splitting the project up into modules means that the runtime needs to be copied
as from its own module target directory. This patch fixes the Travis script to
do the copy.
> copy runtime during mvn deploy.

- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
Previously, the sequencer would automatically decide on commit if the
transaction timestamp was -1L, which is incorrect because the read timestamp
could be -1L for two transactions on a stream that has never been read.
@amytai, could you check if this is correct?
> Don't automatically commit when TX read timestamp is -1L

- cmdlets/src/main/clojure/org/corfudb/shell.clj
The (get-address-space-view) function was mis-named (get-address-space), this patch
fixes it.
> fix address space typo

- cmdlets/src/main/clojure/org/corfudb/shell.clj
This PR adds a network REPL for the shell, via the -p option.
You can connect to this REPL from a client like lein:
```lein repl :connect localhost:<port>```
> adds a network REPL for the shell

- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
- runtime/src/main/java/org/corfudb/runtime/clients/ManagementClient.java
- test/src/test/java/org/corfudb/infrastructure/ManagementServerTest.java
- test/src/test/java/org/corfudb/runtime/clients/ManagementClientTest.java
Preventing bootstrapping the management server multiple times.
Added 2 messages:
MANAGEMENT_ALREADY_BOOTSTRAP: Returned if the server is already bootstrapped.
MANAGEMENT_NOBOOTSTRAP: Returned if received any message before being bootstrapped.
Added test cases to support above cases.
Resolving #322
> Prevent multiple bootstrap Management Server

- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
On a write operation, the set of known addresses is updated before
the write operate completes. The problem is, if the write fails
then the logunit will rejected writes to that address because it
thinks that address has already been written.
> Add Address After Writing

- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- test/src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java
- test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
Since we are writing to an append only file, we are not benefiting
from memory mapped files. Also using many small memory mapped buffers
poses a problem when trying to unmap the buffers, because System.gc
needs to be called every time we need to unmap a buffer.
Addresses #294
> Removed Memory Mapped Buffers

- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLog.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
- test/src/test/java/org/corfudb/runtime/clients/LogUnitClientTest.java
Added support for multiple streams in StreamLog, so that we don't
have to create a StreamLog per stream.
This pull request has a dependency on https://github.com/CorfuDB/CorfuDB/pull/317, that patch needs to be committed before we can commit this one.
> Support Multiple Streams in StreamLog

- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
This variable was used as a hack to have a large memory window
since we didn't know how much memory to map per file because
entries are of arbitrary length. Since we don't use memory
mapped io anymore, then we don't require this file.
> Removed maxLogFileSize

- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
- test/src/test/java/org/corfudb/runtime/clients/LogUnitClientTest.java
StreamLogFiles.append() was throwing an `OverwriteException` inside of a catch-all try block.  Move the throw outside of the catch-all to match original caller's expectation.
I've also patched up the unit tests to expect the shape of the `OverwriteException`.  Reviewer: please double-check.  The execution passes, but a sanity check from someone else would be good, thanks.
Fixes #273.
> StreamLogFiles: Move throw of OverwriteException outside of catch-all

- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
- test/src/test/java/org/corfudb/infrastructure/ManagementServerTest.java
- test/src/test/java/org/corfudb/runtime/clients/TestClientRouter.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Removing extra server from scenario to speed up test and prevent time out.
Attempting to recreate failure on travis env.
> Fixing failing invokeFailureHandler test

- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
Commit f087f5c9ff8af604552d68c6de65251ea7d68d22 changed file system paths for persistent log files.  This patch adapts to the new naming convention, including removing a loop that's no longer required for wildcard matching.
> LogUnitServer.reset(): adapt to new log file paths

- test/src/test/java/org/corfudb/infrastructure/AbstractServerTest.java
- test/src/test/java/org/corfudb/infrastructure/ManagementServerTest.java
Resolving #352 
Forcing CorfuRuntime to use testRouters in AbstractServerTest.
Runtime is used by Management Server.
Added Layout Server in ManagementServerTest for the management server runtime to connect to.
> fixed failing managementServerTest

- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLog.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- test/src/test/java/org/corfudb/runtime/object/CorfuSMRObjectConcurrencyTest.java
- test/src/test/java/org/corfudb/runtime/object/CorfuSharedCounter.java
For some reason, Caffeine may invoke handleEviction multiple times on the same
entry. Added check that refCnt() > 0 before calling release().
> Fixed a concurrency issue in LogUnitServer.

- infrastructure/src/main/java/org/corfudb/infrastructure/FailureHandlerDispatcher.java
- infrastructure/src/main/java/org/corfudb/infrastructure/IFailureHandlerPolicy.java
- infrastructure/src/main/java/org/corfudb/infrastructure/PurgeFailurePolicy.java
- test/src/test/java/org/corfudb/infrastructure/FailureHandlerDispatcherTest.java
Moving generateLayout to PurgeFailurePolicy.
PurgeFailurePolicy
Simple policy to remove all failures from the layout.
> Added failure handling policies

- .travis.yml
- pom.xml
- test/src/test/java/org/corfudb/AbstractCorfuConcurrencyTest.java
- test/src/test/java/org/corfudb/AbstractCorfuTest.java
- test/src/test/java/org/corfudb/CorfuTestParameters.java
- test/src/test/java/org/corfudb/runtime/collections/FGMapTest.java
- test/src/test/java/org/corfudb/runtime/collections/SMRMapTest.java
- test/src/test/java/org/corfudb/runtime/object/CorfuSMRObjectConcurrencyTest.java
- test/src/test/java/org/corfudb/runtime/object/CorfuSMRObjectProxyTest.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
- test/src/test/java/org/corfudb/runtime/view/StreamViewTest.java
This PR moves timeouts to constants, so that in the future different timeouts can be
set in Travis. It also forces the user to select from a set of four timeout lengths.
> Move test timeouts to constants.

- test/src/test/java/org/corfudb/runtime/clients/TestClientRouter.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
* Add `TestClientRouter` timeouts to the test parameter scheme created by #367.
* Add aggressive polling timeouts to `ManagementViewTest.invokeFailureHandler` to reduce test execution time.
Prior to this PR, I've observed on my local machine that the `invokeFailureHandler` test could take anywhere from 6-27 seconds to run, with 15-18 seconds being typical.  This PR cuts that time to about 8 seconds max.
% sh -c 'for i in `seq 1 10`; do mvn -Dtest="ManagementViewTest" test -pl test ; if [ $? -ne 0 ]; then echo FAILED; exit 1; fi done' | & egrep 'Time el'
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.598 sec - in org.corfudb.runtime.view.ManagementViewTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.372 sec - in …
> Bug369 management server timeouts

- pom.xml
After moving to a multi-module build, javadoc production in travis stopped working. This patch turns on javadoc aggregation, which should make the script work again.
> fix javadocs for multi-module build

- test/src/test/java/org/corfudb/AbstractCorfuTest.java
- test/src/test/java/org/corfudb/CorfuTestParameters.java
- test/src/test/java/org/corfudb/infrastructure/DataStoreTest.java
- test/src/test/java/org/corfudb/infrastructure/LayoutServerTest.java
- test/src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java
- test/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java
- test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
- test/src/test/java/org/corfudb/runtime/clients/LogUnitClientTest.java
This patch introduces a new temporary directory parameter
which ensures the same temporary directory is used 
throughout the entire test.
> New temp dir parameter and print of parameters during test

- test/src/test/java/org/corfudb/AbstractCorfuTest.java
- test/src/test/java/org/corfudb/runtime/collections/ReplexSMRMapTest.java
- test/src/test/java/org/corfudb/test/DisabledOnTravis.java
This patch introduces the `@DisabledOnTravis` annotation, which allows us to temporarily disable tests
on Travis. This should be used when a test has transient issues which may be due to timeouts, allow
development of the test to continue without breaking the build.
> Add an annotation to disable tests on Travis.

- test/src/test/java/org/corfudb/AbstractCorfuTest.java
This patch adds support to print the name of the exception and the line number
of the assertion or exception which causes a failure in a test.
For example, if there was a comparisonException on line 32 of a test class
while running sampleTest, the output would be:
sampleTest			[FAIL - comparisonException:L32]
> Print exception name and line number on failure

- cmdlets/pom.xml
- infrastructure/pom.xml
- pom.xml
The maven dependency plugin appears to be doing something on top of
what maven-shade was doing. This patch removes the dependency plugin
and cleans up some dependencies to provide smaller JARs.
> remove maven-dependency from build

- infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriter.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- runtime/src/main/resources/logback.xml
Three commits, to make logging changes after merges of batch writer & annotation processor branches.
1. Severity change from error -> trace for `OverwriteException` case, e.g. in an honest race with hole fill.  (There isn't a safety violation in this case, so error severity is too strong.)
2. Reset the <append-ref> entity in `runtime`'s `logback.xml` file
3. Move BatchWriter and StreamLogFiles priorities info -> trace to match priority for other write-related events.
> Logging changes (after batch writer & annotation processor merges)

- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
I've noticed that with transactionless client code (i.e. optimistic transactions), I could quite frequently run into the 1 second sleep & retry on a txn abort.  This patch switches to exponential backoff, up to a maximum of one second.  In light concurrency tests, I rarely see a 2nd retry.
Also, change the severity of the log message in this method to `trace`, to match some use for txn abort events in `ObjectsView.java`.
> Add exponential backoff to CorfuCompileProxy.TXExecute()

- annotationProcessor/src/main/java/org/corfudb/annotations/ObjectAnnotationProcessor.java
- annotations/src/main/java/org/corfudb/annotations/ConflictParameter.java
- annotations/src/main/java/org/corfudb/runtime/object/IConflictFunction.java
- annotations/src/main/java/org/corfudb/runtime/object/ICorfuSMR.java
- runtime/src/main/java/org/corfudb/runtime/collections/ISMRMap.java
- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileWrapperBuilder.java
- test/src/test/java/org/corfudb/runtime/object/CompileProxyTest.java
- test/src/test/java/org/corfudb/runtime/object/ConflictParameterClass.java
- test/src/test/java/org/corfudb/runtime/view/ObjectsViewTest.java
- test/src/test/resources/logback-test.xml
This patch adds the @ConflictParameter annotation, which indicates to the runtime
that a parameter should be used to generate objects for fine-grained conflict
resolution. 
This patch does not implement fine-grained conflict resolution, which will have to
be implemented in both the transactional context and the sequencer.
> Add conflict parameter annotation and a map for accessing the conflict objects

- .travis.yml
After the switch to multi-module artifacts, travis started caching
multi-module artifacts. This patch fixes that by deleting them before
running the cache step.
> stop travis from caching multi-module artifacts

- .gitignore
- infrastructure/src/main/java/org/corfudb/infrastructure/AbstractServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/BaseServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriter.java
- infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/DataStore.java
- infrastructure/src/main/java/org/corfudb/infrastructure/IDataStore.java
- infrastructure/src/main/java/org/corfudb/infrastructure/LayoutServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/NettyServerRouter.java
- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
- test/src/test/java/org/corfudb/infrastructure/DataStoreTest.java
- test/src/test/java/org/corfudb/infrastructure/LayoutServerTest.java
- test/src/test/java/org/corfudb/infrastructure/LogUnitServerAssertions.java
- test/src/test/java/org/corfudb/infrastructure/SequencerServerAssertions.java
- test/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java
- test/src/test/java/org/corfudb/infrastructure/ServerContextBuilder.java
- test/src/test/java/org/corfudb/runtime/clients/LogUnitClientTest.java
- test/src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
- test/src/test/java/org/corfudb/util/quickcheck/QCLayout.java
- test/src/test/java/org/corfudb/util/quickcheck/QCSMRobject.java
This branch introduces several important cleanups to the sequencer and to the caching-layer supporting serverContext.
* Previously, the in-memory version of the dataStore cache would lose data if the cache was ever evicted. Now, the in-memory version grows without a bound, and panics if putting more data into it fails.
* Previously, the reboot/reset mechanism removed persistent store from under the dataStore cache, which is a really bad idea. I replaced reboot with a mechanism to re-attach newly constructed services to the main CorfuServer router. Reset is no longer supported from internally, and should be discussed if we want it in the future.
* Previously, there was no way to recover the sequencer. Now, the sequencer works by a lease. This allows a recovered sequencer to start at the …
> Finegrainedconflictresolution

- annotationProcessor/src/main/java/org/corfudb/annotations/ObjectAnnotationProcessor.java
- annotations/src/main/java/org/corfudb/runtime/object/ICorfuSMR.java
- annotations/src/main/java/org/corfudb/runtime/object/ICorfuSMRProxy.java
- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileWrapperBuilder.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/ReadSetEntry.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/SnapshotTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteAfterWriteTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteSetEntry.java
- test/src/test/java/org/corfudb/runtime/object/CompileProxyTest.java
- test/src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
Modify the interface in ISMRProxy to take conflict parameters, and save the
conflict parameters in both transactional read sets and write sets.
This patch provides most of the client-side code needed to do fine-grained
conflict resolution. What is left is for the sequencer to perform 
fine-grained conflict resolution - which means the client will 
have to send the fine-grained read and write sets.
Without this information, the sequencer will fall back to using
versions to do conflict resolution.
> Provide conflict parameters in access, logUpdate and getUpcallResult calls

- runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
- runtime/src/main/java/org/corfudb/runtime/view/StreamView.java
This function adds a function to reset the stream view, and changes the compile
proxy to use it. It also eliminates the use of setLogPointer, which
was unsafe to use with concurrency.
> Add a function to reset the stream view

- runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteAfterWriteTransactionalContext.java
- test/src/test/java/org/corfudb/runtime/object/transactions/AbstractTransactionContextTest.java
- test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTransactionContextTest.java
Previously, if a write set was empty, the transaction context would
commit an empty write set to the log. This patch fixes that behavior,
adding a new return value (ADDRESS_NOWRITE) to indicate that
the transaction completed successfully but nothing was
committed into the log.
> Don't commit empty write sets

- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- runtime/src/main/java/org/corfudb/protocols/logprotocol/LogEntry.java
- runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiObjectSMREntry.java
- runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiSMREntry.java
- runtime/src/main/java/org/corfudb/protocols/logprotocol/TXEntry.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/ICorfuPayload.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/InMemoryLogData.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
- runtime/src/main/java/org/corfudb/runtime/object/CorfuProxyBuilder.java
- runtime/src/main/java/org/corfudb/runtime/object/CorfuSMRObjectProxy.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/java/org/corfudb/runtime/view/StreamView.java
- test/src/test/java/org/corfudb/infrastructure/LogUnitServerAssertions.java
- test/src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java
- test/src/test/java/org/corfudb/integration/StreamIT.java
- test/src/test/java/org/corfudb/runtime/object/transactions/AbstractTransactionContextTest.java
- test/src/test/java/org/corfudb/runtime/object/transactions/WriteAfterWriteTransactionContextTest.java
- test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
- test/src/test/java/org/corfudb/runtime/view/ObjectsViewTest.java
This patch replaces the Netty bytebuf in LogData with a standard byte array, reducing the dependency on 
Netty bytebufs throughout the code
> eliminate use of netty bytebuf in logdata

- runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
Due to a small bug, optimistic rollback was always aborting,
even if undo information was available. This patch fixes that
bug.
> Fix issue with optimistic rollback

- corfu_scripts/corfu_layouts.clj
- infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
- runtime/src/main/java/org/corfudb/runtime/clients/ManagementClient.java
- test/src/test/java/org/corfudb/infrastructure/ManagementServerTest.java
- test/src/test/java/org/corfudb/infrastructure/ServerContextBuilder.java
- test/src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Failure Handling ( #237 Failure Detector )
- Prevent user from modifying epoch field.
- Added a new flag -M or --mgmt taking <address>:<port> which would be an endpoint for the Management server to connect to. Thus another explicit bootstrap message is not required.
(We still keep the bootstrap message for now. In case the user forgets to pass this flag and still needs to spawn the Management Server.)
- Removed the config mngr poll interval flag as the config manager has been removed.
- Bootstraps now using the flag --mgmt passed by the corfu server.
- Failure Handler now in place. The failure handler currently is defaulted to using the PurgeFailurePolicy.
( #360 This policy removes any failure detected from the layout.)
- Failure handler not activated unless an explicit trigger message …
> Bootstrap Management Server

- README.md
While adding the second layout server, the Readme doesn't mention that we need to bootstrap it before changing layout on the master server. 
Changing layout on the master server without bootstrapping the replica, kept replica waiting for bootstrap. Also, the master layout could not be changed back as it violated quorum requirement (as replica is not responding)
> Readme update for replica bootstrapping

- bin/corfu_handle_failures
- corfu_scripts/corfu_handle_failures.clj
- corfu_scripts/corfu_management_bootstrap.clj
- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
- In a cluster of 3 nodes, PORT_0, PORT_1 and PORT_2, we fail PORT_1 and wait until the new layout is proposed with epoch incremented and PORT_1 removed.
- This test takes an average of 10secs.
- Providing the user an interface to turn on failure handling capability.
- (Without executing. Failures are only detected and logged but **not** handled.
> Failure handler testing

- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Fix for a rarely occurring test failure.
Wait for the failure handling signal to be sent successfully.
> Fixing ManagementViewTest

- runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/TransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteAfterWriteTransactionalContext.java
this patch removes unnecessary object rollbacks of transactions which already committed; and also reduces contention when one transaction needs to rollback a
running one.
> remove unnecessary rollbacks

- bin/corfu_bootstrap_cluster
- corfu_scripts/corfu_bootstrap_cluster.clj
- corfu_scripts/corfu_handle_failures.clj
Simple cmdlet to setup a cluster required by the fault injection framework. 
Performs the following:
- bootstrap all nodes.
- bootstrap the management servers.
- initiate the failure handler of all these nodes.
NOTE: All nodes in the layout need to be non-bootstrapped.
Example:
```
./corfu_server -m 9000
./corfu_server -m 9001
./corfu_server -m 9002
./corfu_bootstrap_cluster -l <layout_file_path>
```
Example layout:
```
{
"layoutServers": [
"localhost:9000",
"localhost:9001",
"localhost:9002"
],
"sequencers": [
"localhost:9000"
],
"segments": [
{
"replicationMode": "CHAIN_REPLICATION",
"start": 0,
"end": -1,
"stripes": [
{
"logServers": [
"localhost:9000"
]
}
]
}
],
"epoch": 0
}
```
> Setup cluster cmdlet

- runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/TransactionalContext.java
rollback wrongly placed outside 'if' statement
> minor fix - rollback unnecessarily performed because placed outside 'if' statement

- runtime/src/main/java/org/corfudb/runtime/collections/SMRMap.java
Previously, SMRMap would return a view of the map, which would
allow a Corfu client to directly access the state of the object.
This patch fixes that bug to prevent clients from being able to 
access the state of the object directly.
> Return immutables instead of of views for SMRMap

- test/src/test/java/org/corfudb/runtime/object/transactions/WriteWriteTXConcurrencyTest.java
This patch removes an old test which was faulty, and corrects the spelling of concurrencytest
> Remove faulty test and rename test class

- corfu_scripts/corfu_layouts.clj
Issue #240
Basic abortion of the bootstrap process of a node if the node is already bootstrapped.
> Abort bootstrap layout when node already bootstrapped

- runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java
- test/src/test/java/org/corfudb/integration/SealIT.java
When a layout change is triggered by a client, this client will drive
paxos to run on the servers to establish a new layout in a new epoch. It will
also update itself to the new layout/epoch since he is the driver of it.
Other clients (other runtimes) will not be signaled of the changes. The next time
they will ask for a token or try to read/write, they will receive a WrongEpoch
exception.
This fix will implement the logic that bring the runtime to the new epoch/layout.
Before the fix, other runtimes where stuck in a infinite loop of receiving WrongEpoch
exception.
> Getting other runtimes to the correct epoch/layout after a layout change

- infrastructure/src/main/java/org/corfudb/infrastructure/AbstractServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriter.java
- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/WriteOperation.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
- runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
- runtime/src/main/java/org/corfudb/runtime/view/Layout.java
This call would block until the server has successfully flushed its current state to disk.
Every time we need to seal the epoch, we need to flush the queues of all log unit servers.
> Flush log unit servers

- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractContextStreamView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/IStreamView.java
This patch moves the implementation of remainingUpTo into the AbstractContextStreamView,
allowing subclasses to implement bulk reads by implementing getNextEntries. 
AbstractContextStreamView continues to manage copy-on-write contexts.
This paves the way for bulk reads to be supported by the address view, and eventually,
the log-unit/log unit client.
> Support bulk read for abstractQueuedStreams

- test/src/test/java/org/corfudb/runtime/clients/TestClientRouter.java
Completed requests were not being released upon completion.
> Fix a memory leak in TestClientRouter

- infrastructure/src/main/java/org/corfudb/infrastructure/AbstractServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriter.java
- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/WriteOperation.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
- runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
- runtime/src/main/java/org/corfudb/runtime/view/Layout.java
Reverts CorfuDB/CorfuDB#448
It seems the flush is not required for the normal operation of the layout update.
Since its not a current requirement and adds to the code complexity it is best we revert this for now.
> Revert "Flush log unit servers"

- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
- runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/TransactionalContext.java
- test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTransactionContextTest.java
This PR reopens #416, which adds per-object undo log support as well as rollback support.
> Undo log for objects

- runtime/pom.xml
- runtime/src/main/java/org/corfudb/util/Utils.java
This patch removes the byte buddy agent, which was causing a depedency
on the JDK. Fixes #454.
> remove bytebuddy agent

- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
Fix a bug which would occur during hole fill where unsuccessful
hole fill attempts would fail to read the correctly written
entry. 
This patch forces the client to re-read on the overwrite exception
of a hole fill, correctly reading failed hole-fills.
In addition, it also cleans up AbstractQueuedStreamView::getNextEntries
so that it is more readable.
> fix stream bug

- runtime/src/main/java/org/corfudb/runtime/view/QuorumFutureFactory.java
- runtime/src/main/java/org/corfudb/util/CFUtils.java
- test/src/test/java/org/corfudb/runtime/view/QuorumFutureFactoryTest.java
Started to split https://github.com/CorfuDB/CorfuDB/pull/449 into incremental builds
> A thread safe future that will complete only when n/2+1 futures complete

- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
- test/src/test/java/org/corfudb/runtime/clients/TestClientRouter.java
Intent is to update maxConflictWildcard when an
eviction event occurs. Earlier, we would update
even when a put was performed for a key that already
existed in the cache.
> Do not update maxConflictWildcard for mere overwrites

- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
During object reset, the version was being erroneously reset to 0
which caused the object to skip the first update. This patch
fixes that bug by setting the address to NEVER_READ instead.
> when resetting the object, start from Address.NEVER_READ

- runtime/src/main/java/org/corfudb/runtime/collections/ISMRMap.java
Conflict parameters were missing for some common functions in map such 
as containsKey. This patch adds conflict parameters to these functions
to enable fine-grain conflict resolution on them.
> add conflict parameters for additional functions in map

- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractContextStreamView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractStreamContext.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
- test/src/test/java/org/corfudb/runtime/object/transactions/StreamTest.java
Previously, whenever a stream is reset, all backpointer information was lost.
This patch enables the queued stream to save the "resolved" stream, improving
performance when reset is called.
A future update should enable seeking within a previously resolved stream.
> save stream on reset

- runtime/src/main/java/org/corfudb/runtime/collections/ISMRMap.java
- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
- runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
- test/src/test/java/org/corfudb/runtime/collections/FGMapTest.java
- test/src/test/java/org/corfudb/runtime/object/transactions/UndoTest.java
- test/src/test/resources/logback-test.xml
This branch contains several tests that validate undo-correctness. 
One test -- UndoTest::canUndoAfterNoUndo -- is about performance, not correctness. It verifies that VersionLockedObject::optimisitcallyUndoable is properly reset (currently, it is not). 
This PR contains a fix to setting the optimistic flag properly, as well as some cleanups around the logic of optimistic undo/redo.
> adding undo tests and some fixes and cleanups to it

- annotationProcessor/src/main/java/org/corfudb/annotations/ObjectAnnotationProcessor.java
- annotations/src/main/java/org/corfudb/annotations/MutatorAccessor.java
- annotations/src/main/java/org/corfudb/runtime/object/ICorfuSMR.java
- runtime/src/main/java/org/corfudb/protocols/logprotocol/SMREntry.java
- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileWrapperBuilder.java
- runtime/src/main/java/org/corfudb/runtime/object/ICorfuSMRProxyInternal.java
- runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/SnapshotTransactionalContext.java
This patch enables undo of mutators (and mutatorAccessors) which
contain the reset=true parameter. When this parameter is encountered,
the runtime saves the version itself as the undo information, and 
creates a new empty object for further modifications to be made.
Eventually, when the undo record is no longer needed, garbage
collection will free the undo record from memory, as it will
be removed from the undo log.
> support undoing resets

- runtime/src/main/java/org/corfudb/protocols/logprotocol/SMREntry.java
- runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
This patch extracts a performance fix from #474 which
fixes a performance regression.
The regression was caused by the elimination of the undoable
flag, which was necessary because some undo records could
be null (for example, in a map the previous value of the map
could have been not set). This would cause many 
unneeded rollbacks based on the content of the 
undo record.
> Fix undo log rollback

- runtime/src/main/java/org/corfudb/protocols/wireprotocol/ILogData.java
- runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteAfterWriteTransactionalContext.java
Previously, tx commit skipped an entry in the stream view,
which may not have been correct in some cases. This patch
selects the tryCommitAllProxies change from #474 to fix
transaction commit
> patch tx commit

- annotations/src/main/java/org/corfudb/runtime/object/ICorfuSMRProxy.java
- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
- runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java
This patch adds a sync interface to objects view, which 
enables objects to be sync'd without calling an
accessor. Note that sync can also be called from
within a transaction, which will actually force a
sync (undoing optimistic updates if necessary).
> Sync interface - update objects without an access

- annotationProcessor/src/main/java/org/corfudb/annotations/ObjectAnnotationProcessor.java
- annotations/src/main/java/org/corfudb/runtime/object/ICorfuSMRProxy.java
- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
logUpdate currently saves upcalls whether they are needed or not,
which is unnecessary in the case of mutators or mutatorAccessors
which return void.
This causes a very small amount of memory to leak, since the
result of an upcall that is not needed is probably null.
This patch fixes logUpdate by adding a keepUpcallResult parameter,
which controls whether or not an upcall is added to the pendingUpcalls
list or not.
> dont save upcalls if they are not needed

- infrastructure/src/main/java/org/corfudb/infrastructure/log/MultiReadWriteLock.java
- test/src/test/java/org/corfudb/infrastructure/log/MultiReadWriteLockTest.java
Next independent/incremental submission for the quorum replication, based on  https://github.com/CorfuDB/CorfuDB/pull/449 
This is a small request, while waiting decision how to proceed with the overwrite on the server.
This utility class is self explanatory, it allows multiple R/W locks identified by a long value.
One example when we will need it:  in quorum replication we need to read the result from phase 1 from the disk and then to take decision on writing based on the data,  we need this operation to be done only by a single thread, per log position. We don't want a global lock, this is very ineffective.
> Utility class - Multi read write lock

- infrastructure/src/main/java/org/corfudb/infrastructure/log/AddressMetaData.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
When a segment is opened its address space is read into memory
along with the file offsets that correspond to log entries.
As a consequence, record reads do not linearly scan the log
file anymore, instead the record is directly read from
the log file using its offset.
> Avoid Scanning When Reading A Record

- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/TransactionalContext.java
I added logging messages on all corfu-object operations.
On every mutator call, you get 
- the method-name, 
- its arguments, 
- the conflict-parameters, 
- if it is invoked within a transactional context, a TX-mark and the TX-id.
On every accessor call, you cannot get the method-name (because it is a lambda built on-the-fly), but you get as a hint the conflict-parameters. so you get
- the conflict-parameters, 
- if it is invoked within a transactional context, a TX-mark and the TX-id.
> added a few more details to object logging messages

- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
if the sequencer is reset, then we can't know when was the latest update to any stream or conflict parameter.
hence, we want to conservatively abort any transaction with snapshot
time preceding the reset-time of this sequencer.
This PR is an add-on over #485 , to merged into it.
> reset TX resolution information on sequencer-reset

- test/src/test/java/org/corfudb/runtime/collections/SMRMapEntrySetTest.java
- test/src/test/java/org/corfudb/runtime/concurrent/MultipleNonOverlappingTest.java
Reminder: All three of the methods of SMRMap ,
SMRMap::keyset
SMRMap::valueSet
SMRMap::entitySet
currently return -immutable copies- of the underlying map. As in Java, taking
the key/value/entry-set over a map which is concurrently being manipulated yield
undefined results. Any manipulation to the map –after- the set was snapshot does
not affect it. And operations like add/remove are not supported (it is
immutable).
This PR also fixes MultipleOverlappingConcurrent, to address note by @slfritchie
> added a test of map 'set' operations

- test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTXConcurrencyTest.java
- test/src/test/java/org/corfudb/runtime/object/transactions/TXConflictScenariosTest.java
- test/src/test/java/org/corfudb/runtime/object/transactions/TXsFromTwoRuntimesTest.java
- test/src/test/java/org/corfudb/runtime/object/transactions/WriteWriteTXConcurrencyTest.java
These two classes contain @Test annotations that aren't being run by typical unit test executions, including TravisCI's runs.  Renaming with a `Test` suffix should get them run regularly again.
> Rename TXConflictScenarios & TXsFromTwoRuntimes with 'Test' suffix

- annotationProcessor/src/main/java/org/corfudb/annotations/ObjectAnnotationProcessor.java
- annotations/src/main/java/org/corfudb/annotations/Mutator.java
- runtime/src/main/java/org/corfudb/runtime/collections/SMRMap.java
SMRObjects can overload methods via annotations. For example,
methods that are annotated will be persisted with the annotation
name instead of the actual method name. In certain cases, this
allows some types to escape the java typing system and thus
method collisions that could have been detected during compile
time would surface at runtime.
Since annotation overloading can only affect the method name,
only two cases need to be verified during processing. In order
to detect if there is a collision, we need to check if two
methods have the same signature, but different return type and
two methods with the same signature and same return type.
> Properly Resolve Overloaded Methods

- runtime/src/main/java/org/corfudb/runtime/view/QuorumFuturesFactory.java
- test/src/test/java/org/corfudb/runtime/view/QuorumFuturesFactoryTest.java
The client changes requre QuorumFuture to permit:
* collection of all exceptions (not only the last). We need it when
there is existing value from the server,in order to collect the one
with highest rank.
* fail fast exceptions that will cause the future to return result imediately
(DataOutrankedException is such example)
(cherry picked from commit d6c2eec)
> Improvements in QuorumFuture exception management

- infrastructure/src/main/java/org/corfudb/infrastructure/FailureHandlerDispatcher.java
- infrastructure/src/main/java/org/corfudb/infrastructure/IFailureDetectorPolicy.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/PeriodicPollPolicy.java
- infrastructure/src/main/java/org/corfudb/infrastructure/PollReport.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/FailureDetectorMsg.java
- runtime/src/main/java/org/corfudb/runtime/clients/ManagementClient.java
- test/src/test/java/org/corfudb/infrastructure/ManagementServerTest.java
- test/src/test/java/org/corfudb/infrastructure/PeriodicPollPolicyTest.java
- test/src/test/java/org/corfudb/infrastructure/TestServerRouter.java
- test/src/test/java/org/corfudb/runtime/clients/ManagementClientTest.java
- test/src/test/java/org/corfudb/runtime/view/LayoutSealTest.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Fixes #491 
Consider the following scenario:
3 Servers
SERVER_0, 
SERVER_1,
SERVER_2
Log Unit Servers (quorum replicated): SERVER_0, SERVER_1, SERVER_2
For convenience assume that only SERVER_0 manages and corrects failures.
SERVER_2 stops responding. SERVER_0 detects this and attempts to seal the current layout and mark the failed node unresponsive.
During seal we are able to seal SERVER_0. Seal for SERVER & SERVER_2 fails. A seal failure causes the Management server to retry polling and check if failures are still present.
Now all the three servers are up and running. (SERVER_0, SERVER_1 and SERVER_2)
When the management server polls again it does not see the failure.
The data path is now blocked as SERVER_0 has been sealed while the others are not.
To correct this issue we make the …
> Handling transient node failure by management server

- runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteSetSMRStream.java
- test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTransactionContextTest.java
This fix ensures that upon consecutive nested transactions, latest transactions can see optimistic updates from previous ones.
This commit introduces various fixes:
1. When accessing/modifying an object, we need to verify that its WriteSetSMRStream correctly reflects the current transactions
that modified this object. WriteSetSMRStream contains a list of transaction context that have modified this stream.
Upon access/modification of an object, we would check if the object's WriteSetSMRStream was the correct one by
comparing if the root transaction context of the WriteSetSMRStream was the same than the root transaction
context of the thread.
In the case of consecutive nested transactions, when entering subsequent nested tx, the root tx would still
be the same, but the WriteSetSMRStream of …
> Fix for consecutive nested transactions

- format/proto/types.proto
- infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriter.java
- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/MultiReadWriteLock.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogWithRankedAddressSpace.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/DataType.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/ICorfuPayload.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/IMetadata.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/WriteRequest.java
- runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/DataOutrankedException.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/DataRejectedException.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/OverwriteException.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/ValueAdoptedException.java
- runtime/src/main/java/org/corfudb/runtime/view/ChainReplicationView.java
- runtime/src/main/java/org/corfudb/runtime/view/ReplexReplicationView.java
- test/src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java
- test/src/test/java/org/corfudb/infrastructure/log/StreamLogWithRankedAddressSpaceTest.java
- test/src/test/java/org/corfudb/runtime/clients/LogUnitClientTest.java
* Rank is a separate class, with basic part and UUID.
* New DataType PROPOSAL and write operations based on rank and data type only when a rank is given (for quorum).
* Using the new read/write locks in StreamLogFiles (deadlock protection and multiple readers)
* Single address from the global space for the compact operation
* Bugfixes relatred to closing of  streams and channels (more to come)
> Ranked address space support.

- runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteSetSMRStream.java
- test/src/test/java/org/corfudb/runtime/object/transactions/AbstractObjectTest.java
- test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTransactionContextTest.java
The issue was that we were using the same validation function for 2 different conditions.
When we test if the optimisticStream of the underlying object is the correct one for our current transaction, we need to check that current context of the optimisticStream is the same as the current context of the thread.
When we test if the thread owns the optimisticStream of the underlying object, we need to check if the root context of the optimisticStream is the same as the root context of the current thread. 
Usually, on context switch (or on starting nested transaction), we will have the optimisticStream at it's root context. (We unrolled optimistic updates pertaining to the thread we are coming from). This is expected. The current thread, though, is in the nested transaction context. In that …
> Proper synchronization of optimistic updates in nested transactions.

- runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
- test/src/test/java/org/corfudb/runtime/collections/SMRMultiLogunitTest.java
Temporary fix for #522.
In BackpointerStreamView.fillReadQueue reads block for writer or hole
fill to commit. This prevents the BackpointerStreamView to create EMPTY
entries for reads from uncommitted entries.
> Reads block for data to commit.

- pom.xml
Updated dependencies:
lombok: 1.16.16
caffeine: 2.4.0
guava: 21.0
netty: 4.1.9
> update lombok, caffeine and netty versions

- runtime/src/main/java/org/corfudb/protocols/logprotocol/StreamedLogData.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/HoleFillRequiredException.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/RecoveryException.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/AbstractReplicationProtocol.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/AlwaysHoleFillPolicy.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/ChainReplicationProtocol.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/IHoleFillPolicy.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/IReplicationProtocol.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/NeverHoleFillPolicy.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/ReadWaitHoleFillPolicy.java
- runtime/src/main/java/org/corfudb/util/AutoClosableByteBuf.java
This PR implements a basic chain replication protcol on top of the new 
replication protocol abstraction. 
The implementation is not yet fully functional, since the log unit
client needs to be modified to not perform serialization or
handle metadata.
Also, bulk operators for read and peek are added (but not implemented
in chain replication, only default implementations are added).
> chain replication implementation

- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- logReader/pom.xml
- logReader/src/main/java/org/corfudb/logReader/LogEntryExtended.java
- logReader/src/main/java/org/corfudb/logReader/Operation.java
- logReader/src/main/java/org/corfudb/logReader/logHeader.java
- logReader/src/main/java/org/corfudb/logReader/logReader.java
- logReader/src/test/java/org/corfudb/logReader/logReaderTest.java
- pom.xml
The features supported so far are:
1.  Report number of log entries found (default)
2.   Flag incorrect delimiter (does not exit)
3.   Report data checksum error (log entries; does not exit)
4.   Display (all) log entries without data
5.   Display (all) log entries with binary data
6.   Erase single log entry (parameter: global address; wipe the data and convert to HOLE)
7.   Erase log entries from a point forward to end of file
(In case of erase the length of the log in entries is not changed)
> Log reader tool

- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/TokenResponse.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/TokenType.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/TxResolutionInfo.java
- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/AbortCause.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/TransactionAbortedException.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/view/MultiStreamView.java
- runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java
- test/src/test/resources/logback-test.xml
This is a small patch, that lets the sequencer return information on the cause for transaction abort. 
I also took the opportunity to rename StreamsView -> MultiStreamView
> This patch adds abort information to token-response

- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- runtime/src/main/java/org/corfudb/protocols/logprotocol/StreamData.java
- runtime/src/main/java/org/corfudb/protocols/logprotocol/StreamedLogData.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/WriteRequest.java
- runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/ChainReplicationProtocol.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/IReplicationProtocol.java
- test/src/test/java/org/corfudb/infrastructure/LogUnitServerAssertions.java
This PR introduces the first round of changes which will
expose the contents of each stream to the logging units.
The log unit interface has been simplified to take a
single parameter, which is the log data itself.
Managining serialization during a write to multiple
logging units has also been enhanced.
> first round of changes to expose streams to the log unit

- annotationProcessor/src/main/java/org/corfudb/annotations/ObjectAnnotationProcessor.java
Mutator methods that require noUpCalls must specify a reference
to a mutator method that has an upCall.
> Check noUpCall References

- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
- runtime/src/main/java/org/corfudb/protocols/logprotocol/StreamedLogData.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/ILogData.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/IMetadata.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/IToken.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/InMemoryLogData.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/Token.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/TokenResponse.java
- runtime/src/main/java/org/corfudb/runtime/view/Address.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/java/org/corfudb/runtime/view/Layout.java
- runtime/src/main/java/org/corfudb/runtime/view/MultiStreamView.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/AbstractReplicationProtocol.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/ChainReplicationProtocol.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/IReplicationProtocol.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/ReplexStreamView.java
- test/src/test/java/org/corfudb/runtime/collections/ReplexSMRMapTest.java
- test/src/test/java/org/corfudb/runtime/object/transactions/AbstractTransactionContextTest.java
- test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
- test/src/test/java/org/corfudb/runtime/view/ChainReplicationViewTest.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
- test/src/test/java/org/corfudb/runtime/view/ReplexStreamViewTest.java
- test/src/test/java/org/corfudb/runtime/view/replication/AbstractReplicationProtocolTest.java
- test/src/test/java/org/corfudb/runtime/view/replication/ChainReplicationProtocolTest.java
This PR integrates the previous patches which introduced a new
replication protocol abstraction into the address space,
and modifies the stream view to use it.
To support this change, the replex tests have been disabled.
> Integration of the replication protocol into the address space

- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
In the readRecord function (that is called when we fetch the entry from the file in the cache on the logUnitServer) we never close the FileChannel.
This problem got exposed on longevity testing. After a while, performance dropped completely and I had ~ 300'000 File Descriptor open on the same log file.
#548
> Clean up FileChannel leak

- infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriter.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLog.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
In certain situations it might be fine to acknowledge writes
without forcing the write to secondary storage.
> Option To Disable Force Sync

- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
- test/src/test/java/org/corfudb/runtime/clients/LogUnitClientTest.java
This patch introduces a loading cache to cache the segment handles.
One consequence of not having all segment handles in memory is
compaction can only compact segments that are visible from the
cache.
> Cache Segment Handles

- infrastructure/src/deb/init.d/corfu-server
Address issue #542 
Corfu server daemon uses a shell script wrapper to launch the Java
program. When the daemon exits, the Java program is still running,
so the init script can't stop corfu server.
This patch tries to find and terminate the Java program so corfu
server will be stopped properly.
> Fix /etc/init.d/corfu-server stop

- infrastructure/src/main/java/org/corfudb/infrastructure/FailureHandlerDispatcher.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- test/src/test/java/org/corfudb/integration/ServerRestartTest.java
- Saving sequencer state on every stream and globalTail update.
- Added integration tests to reproduce the scenario.
> Fixing sequencer recovery on restart.

- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
On a server restart opening a segment will cause the header to
be written multiple times which breaks readAddressSpace. This
patch will only write the header if the file size is zero.
> Fix getSegmentHandleForAddress

- runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
When the client deserialize an object, it keeps the byte buffer.
This causes bloating in cache, but the buffer is also never used.
> Discard Buffer After De-serialization

- runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteSetSMRStream.java
- test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTXConcurrencyTest.java
This PR fixes #570, which was occurring when a nested transaction
existed that did modify the TX was present, for example:
TX1:
modifies a
TX2:
modifies b
TX3:
modifies a
A call to previous on  would crash with a NPE because TX2 did
not contain a. This patch fixes the logic to skip over empty
sets.
> fix issue with nested TX with no stream present

- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
The readRecord method was returning null when it sees a bad
delimiter. This is incorrect because it can cause the logging unit
to accept writes to addresses that have already been written. The
correct behavior is to throw a DataCorruption Exception.
> Throw DataCorruption Exception on Bad Delimiter

- README.md
The problem at #578 appeared due to both using an older version of Maven and also an apparent JDK version mismatch used by that version of Maven.  I've updated the prerequisites & installation instructions for Maven 3.3 and work-around installation instructions for older Debian/Ubuntu distros.
> Update README.md for Maven 3.3 prerequisites and installation instructions

- .travis_scripts/mvnrepo.sh
Fixes #567.
Changes to SMR object annotations compilation also created
dependencies on Corfu JAR files outside of runtime's.
I'm not 100% sure that this small patch is sufficient; a Maven
repo wizard (@no2chem?) should review.
Prior to this patch, when using a `pom.xml` file as described
in the README (such as
https://gist.github.com/slfritchie/c02493a9aad7e69b143208148ba2b959)
results in the following Maven messages:
[WARNING] The POM for org.corfudb:annotations:jar:0.1-2762 is missing, no dependency information available
[WARNING] The POM for org.corfudb:annotationProcessor:jar:0.1-2762 is missing, no dependency information available
... and then ending with:
[ERROR] Failed to execute goal on project test: Could not resolve dependencies for project org.corfudb.gh567:test:jar:0.01: The …
> Add runtime's dependencies to Corfu-Repos Maven repo

- runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java
- runtime/src/main/java/org/corfudb/runtime/view/Layout.java
layoutHelper only throws Exceptions that are extended from
RuntimeException(s), so this patch makes the layoutHelper
to only throw exceptions extended from RuntimeException.
> Make Throwables More Specific

- README.md
- corfu_scripts/corfu_stream.clj
The clojure scripts have went out of sync after the recent clean
up and refactoring. This patch syncs the corfu_stream.
> Fix clojure CLI

- annotationProcessor/src/main/java/org/corfudb/annotations/ObjectAnnotationProcessor.java
- annotations/src/main/java/org/corfudb/annotations/Accessor.java
- annotations/src/main/java/org/corfudb/annotations/Mutator.java
- annotations/src/main/java/org/corfudb/annotations/MutatorAccessor.java
- runtime/src/main/java/org/corfudb/runtime/collections/ISMRMap.java
- runtime/src/main/java/org/corfudb/runtime/collections/ISMRObject.java
This PR is a cherry pick of #508, which implements conflict paramter
resolution for bulk operations such as putAll, which is calculated
using a custom conflict parameter function.
This PR closes #574.
> Implement conflict paramters for bulk operations

- .travis.yml
- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
- pom.xml
- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
- test/src/test/java/org/corfudb/integration/AbstractIT.java
- test/src/test/java/org/corfudb/integration/AbstractIntegrationTest.java
- test/src/test/java/org/corfudb/integration/SealIT.java
- test/src/test/java/org/corfudb/integration/ServerRestartIT.java
- test/src/test/java/org/corfudb/integration/ServerRestartTest.java
- test/src/test/java/org/corfudb/integration/StreamIT.java
- test/src/test/resources/CorfuDB.properties
- Cleanup AbstractIT class. Addressing review comments.
- By default only running unit tests.
- Running integration tests only in travis or by running them on demand. Fixing #580 
Note: Disabling StreamIT #520 
- Graceful shutdown of netty client routers threads.
> Recovery tests cleanup

- runtime/src/main/java/org/corfudb/runtime/view/ObjectBuilder.java
- test/src/test/java/org/corfudb/runtime/object/CompileProxyTest.java
- test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTransactionContextTest.java
We no longer have runtime instrumentation, so this flag is not
needed.
> Remove The useCompiledClass Flag

- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/TokenResponse.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/TxResolutionInfo.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/TransactionAbortedException.java
- runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java
- runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
Currently it is very difficult for the consumer of CorfuClient to
troubleshoot an aborted transaction since no useful information is
being provided. This patch addresses this by providing additional
information to TransactionAbortedException. Namely two items:
* TxResolutionInfo: Information that is provided to the Sequencer when
we ask for a new token.
* ConflictKey: A key that was part of the conflict set that caused the
transaction to be aborted.
> Percolate additional data during Transaction Abort

- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java
- test/src/test/java/org/corfudb/runtime/CorfuRuntimeTest.java
- test/src/test/java/org/corfudb/runtime/view/QuorumReplicationStreamViewTest.java
- test/src/test/java/org/corfudb/runtime/view/ReplexStreamViewTest.java
This patch introduces a less verbose interface to the runtime, dropping
the "get" prefix and the "view" suffix. The old interface is retained
but marked for deprecation. In addition, the layout "future" has been
renamed to distinguish it from the layout view.
> Cleanup of runtime interface

- runtime/src/main/java/org/corfudb/runtime/collections/SMRMap.java
- test/src/test/java/org/corfudb/runtime/collections/SMRMapTest.java
- Introducing a scanAndFilter method into SMRMap which avoids the cost
in performance when using iterators for queries over large maps.
> Scan & Filter for SMRMap Queries

- format/proto/types.proto
- infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriter.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- logReader/src/main/java/org/corfudb/logReader/logReader.java
- runtime/src/main/java/org/corfudb/protocols/logprotocol/CheckpointEntry.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/DataType.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/ICorfuPayload.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/IMetadata.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
- runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
- runtime/src/main/java/org/corfudb/runtime/object/StreamViewSMRAdapter.java
- runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractContextStreamView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
- runtime/src/main/java/org/corfudb/util/Utils.java
- test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
I've eliminated (I hope) the double-serialization, added a wrapper class that writes all checkpoint records for a given stream & SMRMap, updated unit tests, rebased to master (and compensated for the Spliterator refactoring), and fixed all other failing unit tests (which had been disturbed by serialization changes).
API for checkpoint dumping is currently via Java or Clojure.  For Clojure, use the following to set a runtime that connects to `localhost:9000` and uses an SMRMap on top of a stream called `my-stream`.  First, run `bin/shell`, then enter at the prompt:
(get-runtime "localhost:9000")
(.connect *r)
(def my-stream "my-stream")
(def my-stream-id (uuid-from-string my-stream))
(def m (.. *r getObjectsView build (setType org.corfudb.runtime.collections.SMRMap) (setStreamName …
> Introduce SMRMap state in-stream checkpoint writer

- infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriter.java
- infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriterOperation.java
- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLog.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
- runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
This patch introduces the ability to trim the global log up to
a certain address (i.e. [0, prefixAddress). A prefix trim
followed by a compact will deleted the underlaying files that
correspond to that prefix.
> Prefix Implementation

- runtime/src/main/java/org/corfudb/protocols/logprotocol/CheckpointEntry.java
- runtime/src/main/java/org/corfudb/protocols/logprotocol/LogEntry.java
- runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/java/org/corfudb/runtime/view/LayoutView.java
- runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java
- runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
This PR changes the readCache from being static (global) to a final instance
field, preventing possible odd behaviors from occurring and runtimes sharing
caches (which they shouldn't, as they should operate independently).
In addition, this patch now also contains a fix to the checkpoint entry type, and
since we have sort of a chicken-and-egg problem of unit tests and fixes
(the unit tests are "fixed" by this PR, but the code is "fixed" by fixes to the 
checkpointing entries), they are all in this PR.
> change readCache to final

- debian/pom.xml
- debian/src/deb/systemd/corfu-server.service
Add a systemd service file to corfu-server. Set corfu to restart
on failure automatically (effective on wrapper file). The systemd
service reuses sysv init script so we don't need to repeat code.
Related: #497 
Need review: @zalokhan 
This change doesn't ready add a watchdog to corfu-server, but it
provides the potential with the help of systemd. When the corfu
wrapper script `/usr/local/bin/corfu_server` exits in abnormal way,
systemd can detect the situation, terminate the whole process tree,
and restart script after a period of time. With the ability to assure
the aliveness of wrapper script, watchdog is easy to implement by
monitoring the exit code of java process.
> Add systemd support for corfu-server

- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
In certian cases, the full size of the cache is only utilized
during object initialization, then only a small part of the
cache is used. The timer will evict un-used entries after a
period of time.
> Add Cache Eviction Timer

- test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
Remove @SuppressWarnings annotations, missed by my final test overhaul, sorry.
> Remove magic number work-around during CheckpointSmokeTest development

- debian/pom.xml
In current debian packaging stage, systemd service file has
been assigned with executable permission. Which will cause
the following warning:
> Configuration file /usr/lib/systemd/system/corfu-server.service
> is marked executable. Please remove executable permission bits.
> Proceeding anyway.
Review needed: @zalokhan 
This patch removes the executable permission to suppress the warning.
> Suppress systemd warning

- runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
- runtime/src/main/java/org/corfudb/runtime/object/ISMRStream.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/SnapshotTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
- test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
This PR moves checkpoints to another stream, with the UUID generated
from a string <stream id>_cp. This prevents steady state clients
from incurring the cost of reading checkpoints.
> move checkpoints to other stream

- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
The interplay between trimming, writing and reading can result
in miscalculating boundaries on the address space. This patch
corrects calculations for initializing first unwritten address,
tail address and last segment.
> Correct LogUnit State

- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
This PR patches the compile proxy to get the version from the version
locked object, which is an unsafe call, under a lock.
> Get the version under a lock

- runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java
- test/src/test/java/org/corfudb/runtime/object/transactions/SnapshotTransactionContextTest.java
Implicit nested transaction from transactional methods inherit
transactional context parent type.
> Fix nested transaction default type

- runtime/src/main/java/org/corfudb/protocols/logprotocol/CheckpointEntry.java
- runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/LogUnitException.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/TrimmedException.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/TrimmedUpcallException.java
- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
- test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTest.java
- test/src/test/resources/logback-test.xml
This PR addrsses two issues with checkpoints:
The first is that if there is a new stream, but no checkpoint, a stack overflow error would be encountered because a trim would be encountered while trying to find the checkpoint,
this patch tells the implementation to continue searching for regular entries on trimmed exception.
The second is that sometimes an implementation could try to seek before the snapshot the checkpoint was taken at, but after the version of the object at the snapshot (say, object@6, snapshot@10). The trim would be taken at 10, but the implementation would sometimes seek to say 9, due to holes for example, and end up trying forever with TrimmedException. I added a snapshot address field to the checkpoint so this no longer happens.
> keep track of snapshot addresses, fix issue with fresh streams

- runtime/src/main/java/org/corfudb/runtime/MultiCheckpointWriter.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
* Add a retry loop to MultiCheckpointWriter to handle cases of
TransactionAbortedException during a checkpoint.
* This error was quite rare during 100's of runs of the stressful unit test `periodicCkpointTest`, appearing roughly 1% of the time.
* Fix comment in AbstractQueuedStreamView::getNextEntry that has
drifted from actual implementation.
> Part 1 of splitting apart PR #670: non-unit-test stuff

- infrastructure/src/main/java/org/corfudb/infrastructure/NettyServerRouter.java
- runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
Guarding logging from evaluating statement.
Even if tracing is not enabled, this is evaluated though not logged resulting in CPU utilization.
Note: Consider moving to Log4j to incorporate lambda based logging which avoids need for such guarding and is evaluated only if logging level is satisfied.
> guarding logging from evaluation

- checks.xml
Adding two modules to checks.xml file to suppress checkstyle abbreviation and
member pattern warnings.
For use, add to the top of the class/method/field:
@SuppressWarnings("checkstyle:abbreviationaswordinname")
@SuppressWarnings("checkstyle:membername")
> Add module suppress check abbreviation warning

- checks.xml
This PR enables the @SuppressWarnings annotations for checkstyle, enabling turning off warnings for deprecated code.
> Allow suppression of checkstyle warnings for deprecated classes

- runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
- test/src/test/java/org/corfudb/runtime/checkpoint/CPSerializer.java
- test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
- test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTest.java
- test/src/test/java/org/corfudb/runtime/object/AbstractObjectTest.java
The CP implementation used to create an SMREntry for each key,
this patch changes that behavior. Now multiple keys are grouped
into a single SMREntry as a putAll.
> Optimize Checkpoint Batching

- runtime/src/main/java/org/corfudb/runtime/view/replication/AbstractReplicationProtocol.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/AlwaysHoleFillPolicy.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/ChainReplicationProtocol.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/IHoleFillPolicy.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/IReplicationProtocol.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/NeverHoleFillPolicy.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocol.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/ReadWaitHoleFillPolicy.java
Checkstyle error fixes: comments, indentation, etc. for org.corfudb.view.replication.*
> Checkstyle fixups for org.corfudb.runtime.view.replication.*

- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/ChainReplicationProtocol.java
- test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
Issue #724 
Only implemented ChainReplicationProtocol for now.
Couple of issues/questions:
1. API currently supports ranged read, not random reads
2. Method signatures need to be changed when 1) is resolved. Either user of these methods need to supply list of ranges (user do more work), or readAll() needs to be able to properly compile a list of ranges.
3. Is this the right way to handle hole filling?
4. In cacheFetch(), can these different address have different replication protocols?
> change cache readAll() to utilize ranged read instead of single reads

- debian/src/deb/init.d/corfu-server
This patch re-implements the logic to kill java process when corfu server
is told to exit by systemd. The new logic is much cleaner and easier
to understand.
Note this patch breaks the support to kill java process properly for
non-systemd environments, which are mostly obsolete in debian ecosystem.
> Terminate corfu java process in a cleaner way

- runtime/src/main/java/org/corfudb/runtime/view/Layout.java
- runtime/src/main/java/org/corfudb/runtime/view/StreamOptions.java
- runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
- test/src/test/java/org/corfudb/runtime/view/StreamViewTest.java
This patch introduces options that can be passed when a stream
is opened. One such option is to ignore addresses when
backpointers are traversed.
> Introduce Stream Options

- runtime/src/main/java/org/corfudb/recovery/FastSmrMapsLoader.java
- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
- runtime/src/main/java/org/corfudb/util/Utils.java
- test/src/test/java/org/corfudb/recovery/FastSmrMapsLoaderTest.java
First version of the FastSmrMapsLoader that will reconstruct all the SMR
Maps present in the log in one pass. It reads sequentially all entries
from 0 to log tail and dispatch the SMREntries to its map backed by a
Corfu stream. Every time it encounters a new stream, it creates a new Corfu
Object.
> FastSmrMapsLoader without support of checkpoints/trim

- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/ILogData.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
- test/src/test/java/org/corfudb/runtime/clients/LogUnitClientTest.java
Instead of throwing an exception on reading trimmed addresses,
this changes makes the logging unit return a trimmed entry.
> Return DataType.TRIMMED

- runtime/src/main/java/org/corfudb/runtime/collections/SMRMap.java
- test/src/test/java/org/corfudb/runtime/collections/SMRMapTest.java
Modifying scanAndFilter method for SMRMaps to filter on map.entries
(keys and/or values) instead of values ONLY (as initial implementation).
This will provide a more generic interface to suit different types of
queries.
> ScanAndFilter to Filter by Map.Entries

- runtime/src/main/java/org/corfudb/runtime/collections/SMRMap.java
- test/src/test/java/org/corfudb/runtime/collections/SMRMapTest.java
- Returning Collection of map entries over maps, because of verified performance improve. 
- No deprecation of old scanAndFilter, both methods add value to clients---depending on usage.
> Performance Improve to scanAndFilter Method

- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/TokenResponse.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/TxResolutionInfo.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/TransactionAbortedException.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/ReadSetInfo.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteSetInfo.java
- test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTransactionContextTest.java
This PR partially addresses #753 and reduces the number of
false conflicts. 
It introduces a two-level conflict map, the first level
maps stream ids to a new per-stream data class. The 
per-stream data class contains a map of conflict parameters
(which now can be longs) to addresses, as well as a
single long which represents a minimum "poisoned" value.
The implementation still uses a Java hashCode, (32 bits),
but this is much improved over the previous implementation
which attempted to squeeze the stream ID and a java hashCode
of the conflict param into 32 bits. In order to use a
longer hash code, we'll need to find a generic way to
generate a long hashCode from an object without serializing
it.
Poisoned streams are streams affected by operations with
fine-grained conflict information, …
> Use a two-level map for conflicts, support poisoning

- format/proto/types.proto
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- logReader/src/main/java/org/corfudb/logReader/logReader.java
- runtime/src/main/java/org/corfudb/protocols/logprotocol/CheckpointEntry.java
- runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiObjectSMREntry.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/IMetadata.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
- runtime/src/main/java/org/corfudb/recovery/FastSmrMapsLoader.java
- runtime/src/main/java/org/corfudb/recovery/RecoveryUtils.java
- runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
- runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
- runtime/src/main/java/org/corfudb/util/Utils.java
- test/src/test/java/org/corfudb/recovery/FastSmrMapsLoaderTest.java
- test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
The FastSmrMapLoader is now able to load trimm/checkpoint. Here are the 3 steps of
the recovery:
1. Search for the checkpoints (for now, we have to read the whole log to find them)
2. Apply the checkpoints update in parallel
3. Go through the the whole log and apply only the entries after the checkpoints
> FastSmrMapLoader checkpoint/trim support

- infrastructure/src/main/java/org/corfudb/infrastructure/FailureHandlerDispatcher.java
- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/SequencerTailsRecoveryMsg.java
- runtime/src/main/java/org/corfudb/runtime/clients/SequencerClient.java
- test/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java
- test/src/test/java/org/corfudb/integration/ServerRestartIT.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Reset the Sequencer Server state using the FastSMRLoader during the recovery phase.
Steps:
- Server starts, client connects and performs reads and writes.
- Server shuts down/crashes.
- On recovery all the servers start in "not ready state" (PR #762 )
- The management server then seals the servers, runs reconfiguration with the fastSMRLoader and resets the sequencer with the tails.
- After the paxos round, the data path is open to the clients.
> Reset Sequencer state during recovery

- runtime/src/main/java/org/corfudb/runtime/MultiCheckpointWriter.java
- runtime/src/main/java/org/corfudb/runtime/clients/BaseClient.java
- runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
- runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
- runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java
- runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
Changing log level to warn/error for exception handling. We are missing out on relevant/critical information when certain exceptions are raised.
> Set proper exception log levels for fast-tracking

- debian/src/deb/init.d/corfu-server
- runtime/src/main/resources/logback.xml
Ref: #781
- Avoid erase logging file when server is started or restarted
- Include date in logback to help debugging
> Persist logging after server reboot (#773)

- runtime/src/main/java/org/corfudb/runtime/exceptions/AbortCause.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/TransactionAbortedException.java
- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/SnapshotTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
- test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTXConcurrencyTest.java
- Adding descriptive cause to TransactionAbortedException in order to have more information of the cause of the transaction abort.
- Adding new abortCause = 'Unsupported' for UnsupportedOperationException
types raised whenever an operation is not supported (e.g, attempting to do a write operation --logUpdate--- in the context of a Snapshot Transaction).
> Add cause description for TX Aborted Exceptions

- format/proto/types.proto
- infrastructure/src/main/java/org/corfudb/infrastructure/FailureHandlerDispatcher.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/IMetadata.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
- runtime/src/main/java/org/corfudb/recovery/FastSmrMapsLoader.java
- runtime/src/main/java/org/corfudb/recovery/RecoveryUtils.java
- runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java
- test/src/test/java/org/corfudb/recovery/FastSmrMapsLoaderTest.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
This patch moves important data for checkpoint entries from the payload into the metadata map. This is neaded because when the corfu server restart, it may not be able to deserialize the payload.
> Fix sequencer recovery with fastSMRLoader

- runtime/src/main/java/org/corfudb/runtime/MultiCheckpointWriter.java
- test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
This patch changes the MultiCheckpointWriter so that it doesn't
generate checkpoint entries for empty maps.
> Don't CP Empty Maps

- runtime/src/main/java/org/corfudb/runtime/exceptions/NoRollbackException.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/TransactionAbortedException.java
- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
- runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/SnapshotTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java
- runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
This PR introduces additional logging, for TransactionAbortedException
the id of the stream is added whenever possible, for NoRollbackException
the cause of the failed undo is added to the exception message.
1
> Increase logging for NoRollbackException and TransactionExceptions

- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/TrimmedException.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/SnapshotTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
- test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTest.java
This patch fixes a race when a transaction starts with a time
stamp that is greater than the checkpoint snapshot time, but
then fails with a TrimmedException.
> Fix Version Object Trim Race

- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
On a write request, the client puts entries in the cache before
they are serialized, this results in incorrectly calculating the
object's size when it enters the cache, as a result client
leaks memory through admitting more entries into the cache.
> Fix Client Leak

- runtime/src/main/java/org/corfudb/runtime/MultiCheckpointWriter.java
- test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
This patch logically revers PR#808 and adds a new test case
which encodes an edge case where accessing an empty map
doesn't cause a StackOverflowException.
> CP Empty Maps

- infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
- test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTest.java
This patch changes the behavior of prefixTrim, instead of throwing
an exception on prefix trimming a trimmed address, it just ignores
the request.
> Ignore Trimming Trimmed Addresses

- runtime/src/main/java/org/corfudb/runtime/exceptions/TransactionAbortedException.java
Fixed the string message that is created during the construction
of the exception.
> TransactionAbortedException String

- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
- test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTransactionContextTest.java
This PR is a slight improvement over #829. It uses a string consisting
of the hash code plus the stream ID as a key, we will have to monitor
it carefully to see if this causes additional GC pressure or performance
regression.
> 32 bit sequencer hash

- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/TxResolutionInfo.java
This PR introduces a new conflict data class, which replaces the conflict
"string" hash. Since this class just refers to the conflict byte array by
reference, it should result in significantly lower memory pressure.
> Introduce a conflict data class, replacing the conflict string "hash"

- runtime/src/main/java/org/corfudb/runtime/object/transactions/ConflictSetInfo.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteSetInfo.java
This PR makes the conflict and write set classes publicly accessible so the methods can
be accessed by external applications.
> Make conflict and write set public

- runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
- runtime/src/main/java/org/corfudb/runtime/MultiCheckpointWriter.java
Toggle Checkpoint Optimization
Allow the checkpoint writer to enable/disable optimized
checkpoints (i.e. putAll per SMREntry).
> Toggle put all

- infrastructure/src/main/java/org/corfudb/infrastructure/AbstractServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/BaseServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/FailureHandlerDispatcher.java
- infrastructure/src/main/java/org/corfudb/infrastructure/LayoutServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/SequencerTailsRecoveryMsg.java
- runtime/src/main/java/org/corfudb/runtime/clients/SequencerClient.java
- test/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java
- test/src/test/java/org/corfudb/integration/AbstractIT.java
- test/src/test/java/org/corfudb/integration/SealIT.java
- test/src/test/java/org/corfudb/runtime/clients/SequencerClientTest.java
- test/src/test/java/org/corfudb/runtime/collections/SMRMapEntrySetTest.java
- test/src/test/java/org/corfudb/runtime/object/CompileProxyTest.java
- test/src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
- test/src/test/java/org/corfudb/runtime/view/LayoutViewTest.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
- test/src/test/java/org/corfudb/runtime/view/QuorumReplicationStreamViewTest.java
Sequencer returns NOT_READY Exception if it is NOT_READY state and receives any message other than the SEQUENCER_RESET message (Marks server as READY).
The sequence of operations is as follows:
- Seal
- If primary sequencer has changed, mark all sequencers as NOT_READY.
- Run paxos
- Reset sequencers using stream tails from fastLoader. (The reset call marks the sequencer as ready.)
Possible race condition:
Since SET_NOT_READY message is epoch UNAWARE, the following scenario can occur:
ManagementServers 1 & 2 are trying to reset sequencer 3. 1 sends SET_NOT_READY but doesn't receive a response so aborts. 2 sends the SET_NOT_READY, receives response proceeds and succeeds with reconfiguration. 3 now receives 1's SET_NOT_READY and accepts it. Who should detect and mark 3 as READY now?
> Sequencer reset after paxos & protected by ready/not-ready state

- runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiObjectSMREntry.java
- runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiSMREntry.java
- runtime/src/main/java/org/corfudb/recovery/FastSmrMapsLoader.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteSetSMRStream.java
- runtime/src/main/java/org/corfudb/util/Utils.java
- test/src/test/java/org/corfudb/runtime/object/transactions/WriteAfterWriteTransactionContextTest.java
- test/src/test/java/org/corfudb/runtime/view/ObjectsViewTest.java
Use synchronized collections for MultiObjectSMREntry and
MultiSMREntry. This fixes a race condition, where while a thread
is writing another thread can observe stale reads.
> Collection sync

- runtime/src/main/java/org/corfudb/recovery/FastSmrMapsLoader.java
- test/src/test/java/org/corfudb/recovery/FastSmrMapsLoaderTest.java
When we do a checkpoint of an empty stream, the start
address of the stream will be -1 (don't exist). When
we reconstruct the tails, if we encounter a checkpoint
of an empty stream, we should not reconstruct its tail.
> Do not reconstruct tail of empty streams

- runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
When sequencer addresses were refactored to type Token, getTokenValue
was not correctly called when removing the address from the upcall list,
so the type inserted (long) did not match the type being removed (Token)
causing the upcall list to never be freed. This patch fixes this bug.
> Fix bug preventing pending upcalls from being cleared

- runtime/src/main/java/org/corfudb/runtime/exceptions/StaleTokenException.java
- runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
- test/src/test/java/org/corfudb/integration/CmdletIT.java
- test/src/test/java/org/corfudb/integration/ServerRestartIT.java
This branch exposes a bug on sequencer epoch change (#865): 
AddressSpaceView.write() may be handed a token with a stale epoch, and it will then loop forever trying to get the token and the layout to be the same epoch.
The fix is to throw a new exception type, staleTokenException, and let the streams layer decide if and how to obtain a new token. This depends on who invokes AddressSpaceView.write() : 
* on a regular stream write, simply discard the old token and grab a new one
* on a transactions write, throw a transactionAborted exception, because the conflict parameters on the sequencer may be messed up
* on a multi-stream COW, simply discard the old token and grab a new one.
> Stale token bug fix

- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
This PR cleans up some of the paths in StreamLogFiles where channels may not be closed,
or in some cases where a file may not be present and a channel would be accessed causing
a NPE.
> Cleanup channel release, protect from NPE

- .travis_scripts/verify.sh
This PR addresses the case when encrypted env variables
are unavailable in travis due to an external PR (from a fork).
> Handle case when sonar env vars are not available

- .travis_scripts/verify.sh
This PR addresses an issue where sonarqube SECURE_ENV_VARS checked for
the wrong value.
> fix a boolean mismatch for sonar scripts

- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
- test/src/test/java/org/corfudb/integration/CmdletIT.java
- test/src/test/java/org/corfudb/integration/ServerRestartIT.java
- test/src/test/java/org/corfudb/runtime/clients/ManagementClientTest.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
- Retry node recovery if recovery failed the first time.
- Converting AtomicBoolean to simple boolean.
- The management server retries bootstrapping the sequencer implicitly every second since the flag remains unset until the bootstrap is successful. 
- So explicit retries are not required and I have removed them.
- Waiting for management servers to stabilize and realize that the sequencer has been bootstrapped. This makes it quicker for them to detect failures if any and also reduce repeated attempts on bootstrapping the sequencer.
- Disabled cmdletIt for now as they are very slow and are not as significant. We can work around later to speed up these tests or run them in parallel.
> Retry recovery if failed and reduce testing times

- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
- test/src/test/java/org/corfudb/runtime/object/TransactionalObject.java
- test/src/test/java/org/corfudb/runtime/object/transactions/ImplicitTransactionsTest.java
If we already are in a transaction when we call implicit
transactional method, we don't have to nest it. The transactional
method will be executed in the current transactional context.
Since Nested Transaction code path is not very stable yet, let's minimize the risk and not use them implicitly.
> Implicit transactional methods are not Nested

- runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiObjectSMREntry.java
- runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiSMREntry.java
Maps were being serialized/deserialized incorrectly because their
sizes was being casted from an int to a short. As a consequence,
transactions can successfully commit data, but fail to read them
back.
> Serialization Bug

- runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java
- runtime/src/main/java/org/corfudb/runtime/view/ObjectBuilder.java
- test/src/test/java/org/corfudb/runtime/collections/CorfuTableTest.java
- test/src/test/java/org/corfudb/runtime/collections/SMRMapTest.java
Main change is that we can modify the indexer of an existing
CorfuTable. This enable FastObjectLoader to reload the maps in
memory and postpone the computation of the index at instatiation
time. Also include minor fixes.
> CorfuTable can modify the indexer at runtime

- runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java
This patches getByIndexAndFilter to collect using ArrayList::new, which performs significantly
better than Collections.toList.
> Use ArrayList::new in CorfuTable

- runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java
- runtime/src/main/java/org/corfudb/runtime/collections/SMRMap.java
per @annym's comment, replaceAll had a bug where it was trying to update the entry,
but the entry was coming from a immutable set, therefore no update to the mapping
would occur, and replaceAll would do nothing.
This PR fixes that bug by forcing an update on the map. This is broken in
CorfuTable and SMRMap.
> replaceAll fix

- runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java
- runtime/src/main/java/org/corfudb/recovery/RecoveryUtils.java
- runtime/src/main/java/org/corfudb/runtime/view/ObjectBuilder.java
- test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
- test/src/test/java/org/corfudb/runtime/collections/CorfuTableTest.java
For special type (such as CorfuTable), they need a custom builder
to recreate correclty the object upon loading phase.
> FastLoader can provide custom object builders

- .gitignore
This PR introduces debian support for Gradle, which may
not be working due to change from -shaded to -all.
It also generates an uberjar, which includes
all dependencies.
> Debian build for gradle

- annotationProcessor/src/main/java/org/corfudb/annotations/ObjectAnnotationProcessor.java
- annotations/src/main/java/org/corfudb/runtime/object/ICorfuSMR.java
- annotations/src/main/java/org/corfudb/runtime/object/ICorfuSMRProxy.java
- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/TokenResponse.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/TxResolutionInfo.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/TransactionAbortedException.java
- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileWrapperBuilder.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/ConflictSetInfo.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/TransactionBuilder.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteAfterWriteTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteSetInfo.java
- runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
- test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTXConcurrencyTest.java
- test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTransactionContextTest.java
- test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
- test/src/test/resources/logback-test.xml
This PR cleans up the sequencer transactional token allocation path,
and adds additional information for debug purposes.
1. If the transaction is aborted, the address of the conflict is
returned if possible
2. A new token type, TX_ABORT_CONFLICT_STREAM used when a tx is aborted
due to a stream update is added to diffrentiate against TX_ABORT_CONFLICT_KEY, 
which is used when an abort was due to fine-grained conflict information in use.
3. The txCanCommit method is removed and inserted into handleTxToken,
removing unnecessary AtomicReferences being generated just to pass variables,
since handleTxToken only needs to check if a tx can commit, and tx commit
checks are not performed elsewhwre in the code.
> Cleanup sequencer tx token path

- runtime/src/main/java/org/corfudb/util/GitRepositoryState.java
This PR makes a minor change to allow the default repository to be served
on any exception, not just an IO Exception.
> Commit on any repository state exception

- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractOptimisticTransaction.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransaction.java
When no conflict resolution is neccessary, the conflict set
does not need to be hashed, and the sequencer does not
need to resolve conflicts. This PR enables the sequencer
to handle conflict-free transactions.
> Optimize case when no conflict resolution is necesssary

- cmdlets/pom.xml
Cmdlets module has a dependency on the commons-fileupload package. Updating version 1.2.1 -> 1.3.3
<pre><code>
mvn dependency:tree
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ cmdlets ---
[INFO] org.corfudb:cmdlets:jar:0.1-SNAPSHOT
...snip...
[INFO] +- org.clojure:clojure:jar:1.8.0:compile
[INFO] +- jline:jline:jar:2.14.2:compile
[INFO] +- reply:reply:jar:0.3.7:compile
[INFO] |  +- org.thnetos:cd-client:jar:0.3.6:compile
[INFO] |  |  +- clj-http-lite:clj-http-lite:jar:0.2.0:compile
[INFO] |  |  |  \- slingshot:slingshot:jar:0.10.3:compile
[INFO] |  |  \- cheshire:cheshire:jar:4.0.3:compile
[INFO] |  |     +- com.fasterxml.jackson.core:jackson-core:jar:2.0.6:compile
[INFO] |  |     \- com.fasterxml.jackson.dataformat:jackson-dataformat-smile:jar:2.0.6:compile
[INFO] |  +- …
> Update commons-fileupload to version 1.3.3

- runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
This experimental patch adds a cache to store the last known stream
position for streams involved in a given transaction. In some
cases, where the SMR stream has not actually contained modification
for some time, the optimistic try-lock path will still succeed even
after a context switch.
> Store known stream position in TransactionContext

- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
- test/src/test/java/org/corfudb/runtime/view/stream/BackpointerStreamViewTest.java
A bug in the implementation of previous could result in incorrect data being returned by a stream, if previous is called right after a seek.
This PR fixes this issue and adds a unit test which demonstrates the bug.
> Fix stream previous/seek calls

- runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java
Retain the generic return type for getByIndex.
> Retain Projection Return Type

- test/src/test/java/org/corfudb/runtime/clients/TestChannelContext.java
Create a new ForkJoinPool for all parallelStream usages in SMRMap and CorfuTable.
This avoids thread contention in the commonPool.
Also using a new ExecutorService for runAsync tasks in the TestChannelHandlerContext to avoid the same thread contention.
> ExecutorService for TestChannelContext

- runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
Fixing NullPointerException.
Race condition where Thread 1 sets data to null, while another Thread 2, which has acquired the lock tries to get data.length resulting in a NullPointerException.
Release data buffer only after deserialization.
> Release data buffer only after deserialization

- infrastructure/src/main/java/org/corfudb/infrastructure/LayoutServer.java
- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/view/LayoutView.java
- runtime/src/main/java/org/corfudb/runtime/view/SealServersHelper.java
- test/src/test/java/org/corfudb/integration/SealIT.java
- test/src/test/java/org/corfudb/runtime/CorfuRuntimeTest.java
- test/src/test/java/org/corfudb/runtime/view/LayoutViewTest.java
- Now sending prepare and propose messages to members of the current layout only and NOT members of the proposed layout.
- Apart from the Timeout Exception also handle wrong epoch exception for the case where a layout server may be left behind and may reject the prepare or propose message.
- Fixes a few unhandled network exceptions in the consensus and the seal phase. This unblocks the testing-framework fault tests effort.
- Changed from getLayoutClientStream.count -> getLayoutServers.size
- getLayoutClientStream attempts to create client routers to connect to the endpoints which can result in unhandled network exceptions causing reconfiguration to abort.
> Paxos on current layout members

- generator/src/main/resources/logback-test.xml
- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
This breaks MP dependency. Let's try not to break existing client applications if we can avoid to.
> Using slf4j interface logger instead of logback implementation

- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/resources/logback.xml
- test/src/test/resources/logback-test.xml
The current initialization order of the AddressSpaceView causes
the cache configuration by the runtime to be ignored. This patch
fixes this order so that the numCacheEntries config is picked up
by the cache.
> AddressSpaceView Initialization Bug

- infrastructure/src/main/java/org/corfudb/infrastructure/NettyServerRouter.java
Only emit thread termination logs on errors.
> Change Loggingn Level

- generator/src/main/java/org/corfudb/generator/operations/SnapshotTxOperation.java
- infrastructure/pom.xml
- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/BackpointerResponse.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/ICorfuPayload.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/ILogData.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/TokenRequest.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/TokenResponse.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/TxResolutionInfo.java
- runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java
- runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
- runtime/src/main/java/org/corfudb/runtime/clients/SequencerClient.java
- runtime/src/main/java/org/corfudb/runtime/object/LinearizableStateMachineStream.java
- runtime/src/main/java/org/corfudb/runtime/object/VersionedObjectManager.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractOptimisticTransaction.java
- runtime/src/main/java/org/corfudb/runtime/view/SequencerView.java
- runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
- test/src/test/java/org/corfudb/infrastructure/SequencerServerAssertions.java
- test/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java
- test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
- test/src/test/java/org/corfudb/runtime/collections/FGMapTest.java
- test/src/test/java/org/corfudb/runtime/object/transactions/SequencerCacheTest.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
This PR refeactors the sequencer and makes the following major changes:
- Support concurrency. At some point the handler to the sequencer token
function was marked synchronized, so that token issuance was no longer
concurrent. This PR changes the sequencer to use a StampedLock. Queries
for the tail require no lock, while tokens use an optimistic lock if
possible to check for abort, and obtain a write lock to update the
streamTails map.
- Remove support for multiple tokens. Issuing multiple tokens was
never used, and was untested. Rather than continue to support
this unnecessary feature, it was removed.
- Eliminate use of boxed primitives. Due to the use of java collections,
boxing on insert/and removal was occuring all over the place. This
PR uses the Eclipse collections ObjtoLong map to …
> Refactor of the sequencer, support optimism and reduce boxed conversions

- infrastructure/src/main/java/org/corfudb/infrastructure/AbstractServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/BaseServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/CorfuMsgHandler.java
- infrastructure/src/main/java/org/corfudb/infrastructure/LayoutServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/NettyServerRouter.java
- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ServerHandler.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/UnrecoverableCorfuException.java
- test/src/test/java/org/corfudb/infrastructure/TestServerRouter.java
- test/src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
This PR cleans up the server message handler and metrics related infrastructure:
- Metrics are no longer exposed to servers. The CorfuMsgHandler class now instruments
messages automatically based on whether metrics are enabled and uses the message 
type as the timer name.
- Handler maps have been changed from being ConcurrentHashMaps to EnumMaps, which
should reduce lookup time.
- Server routers now install a handle to the handler directly, instead of only
a reference to the server. This should reduce a lookup on the server message
handling path.
> Cleanup message handler and metrics

- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/DataType.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
- test/src/test/java/org/corfudb/runtime/clients/LogUnitClientTest.java
This patch populates the global address for all entry types on
reads.
> Populate LogData Entries

- runtime/src/main/java/org/corfudb/runtime/object/IStateMachineStream.java
- runtime/src/main/java/org/corfudb/runtime/object/LinearizableStateMachineStream.java
- runtime/src/main/java/org/corfudb/runtime/object/VersionedObjectManager.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractOptimisticStateMachineStream.java
This PR addresses an issue where versionedObjectManager would call
consumeEntry multiple times because an upcall was not present.
However, consumeEntry removes the entry from the entry map, 
which caused the second call to return a runtime exception. 
This PR changes the behavior of consumeEntry to only return
an entry is an upcall is present, and modifies VersionedObjectManager
to expect this new behavior.
> Fix issue where upcall result is sometimes consumed

- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/management/FailureHandlerDispatcher.java
- runtime/src/main/java/org/corfudb/runtime/view/LayoutView.java
Fixing kill/remove node scenario.
Committed phase after paxos should block until responses from all nodes have been received.
Currently we hit the following scenario where the failures are not removed while iterating in the while loop and the same response is accounted for multiple iterations. After exit, when we poll for the layout we can still get the old layout as the new one has not been committed yet.
> Block layout commit until completion

- annotationProcessor/src/main/java/org/corfudb/annotations/ObjectAnnotationProcessor.java
- annotations/src/main/java/org/corfudb/runtime/object/IObjectManager.java
- runtime/pom.xml
- runtime/src/main/java/org/corfudb/protocols/logprotocol/SMREntry.java
- runtime/src/main/java/org/corfudb/recovery/FastLoadedStateMachineStream.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/TrimmedUpcallException.java
- runtime/src/main/java/org/corfudb/runtime/object/IStateMachineOp.java
- runtime/src/main/java/org/corfudb/runtime/object/IStateMachineStream.java
- runtime/src/main/java/org/corfudb/runtime/object/LinearizableStateMachineStream.java
- runtime/src/main/java/org/corfudb/runtime/object/VersionedObjectManager.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractOptimisticStateMachineStream.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/SnapshotTransaction.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteAfterWriteTransaction.java
This PR eliminates the use of getUpcallResult by passing the
result as an optional CompletableFuture to logUpdate, instead
of returning the address.
In addition, primitive maps are now used to keep track of
upcalls that need to be saved, and upcalls are only saved
when requested.
> Eliminate getUpcallResult, use primitive maps in stream

- runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
- runtime/src/main/java/org/corfudb/util/CFUtils.java
This PR eliminates the creation of a description string for the TimeoutException
used in CFUtils, and uses a single Duration instance in the Netty client for
determining the timeout instead of creating a Duration object for each 
RPC call, reducing GC pressure.
> Avoid stringBuilder and object creation overheads for timeouts

- runtime/src/main/java/org/corfudb/protocols/wireprotocol/ICorfuPayload.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/IMetadata.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/ITypedEnum.java
This PR addresses an issue where ICorfuPayload's enumMapFromBuffer
was using a expensive resolve call from the typetoken in order
to determine the type parameters of a map that could be held
in the data. The type information in ITypedEnum is now
determined when the enum is constructed.
> Eliminate expensive typetoken resolve call

- runtime/src/main/java/org/corfudb/protocols/wireprotocol/NettyCorfuMessageDecoder.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/NettyCorfuMessageEncoder.java
This PR converts the ByteToMessage/MessageToByte encoder/decoders
to MessageToMessage encoder/decoders. Since our messages are
framed by the LengthField encoder/decoder, there is no need
for extra state logic to determine how many messages there are,
and this enables these channels to be implemented as sharable.
> Implement Netty message-to-message encoders/decoder

- runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java
Description: Change CorfuTable getByIndexAndFilter logging from WARN to DEBUG.
Why should this be merged: CorfuTable can now be used with a single index only, so emitting a warn message is excessive.
> CorfuTable getByIndexAndFilter logging

- generator/src/main/java/org/corfudb/generator/LongevityApp.java
- generator/src/main/java/org/corfudb/generator/State.java
- generator/src/main/java/org/corfudb/generator/operations/OptimisticTxOperation.java
- generator/src/main/java/org/corfudb/generator/operations/ReadOperation.java
- generator/src/main/java/org/corfudb/generator/operations/RemoveOperation.java
- generator/src/main/java/org/corfudb/generator/operations/SnapshotTxOperation.java
- generator/src/main/java/org/corfudb/generator/operations/WriteOperation.java
Description: Liveness criteria was not catching all liveness issues
Why should this be merged: Key to proper fault-injection pass/fail criteria
Related issue(s) (if applicable): #1033
> Fix Liveness Criteria for Longevity

- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLog.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
- runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
- test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
Description: Resets the log unit server by clearing all data and persisted state.
Why should this be merged: This is a requirement to heal failed nodes.
The healing nodes need to be added back to the chain and this can only be done once the state
on the log unit server on the healing node is reset.
> Reset logunit server

- test/src/test/java/org/corfudb/integration/ServerRestartIT.java
Description: Added an IT to test the index reconstruction on client and server restart. 
Why should this be merged: No existing test for index reconstruction.
> Test corfuTable index reconstruction

- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/unrecoverable/SystemUnavailableError.java
- runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- test/src/test/java/org/corfudb/integration/ServerRestartIT.java
- test/src/test/java/org/corfudb/runtime/CorfuRuntimeTest.java
- test/src/test/java/org/corfudb/runtime/clients/TestClientRouter.java
- test/src/test/java/org/corfudb/runtime/object/transactions/StreamTest.java
- test/src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
The Runtime has a settable timeout for how long it will wait for
an unavailable system. If we are not able to progress (due to NetworkExcpetion)
during the timeout, the handler provided by the client (or default handler,
that shutdown the Runtime) will be triggered.
Fixes #974
> Prevent NetworkException from causing a double-write

- runtime/src/main/java/org/corfudb/util/CFUtils.java
Description: This PR changes the behavior of the ```CFUtils::failAfter``` function to not generate a new exception (and stack trace). Instead, it uses a statically generated exception. This statically generated exception does not have useful stack trace information (but arguably, the dynamically generated exception did not either).
Why should this be merged: Currently, every RPC generates this exception and string whether or not it times out, which is significant time overhead to generate the stack trace (via ```fillInStackTrace```). This benchmark: https://shipilev.net/blog/2014/exceptional-performance/ places the cost of the exception at 10-100ns/op depending on stack depth. While that might be too small to affect our benchmarks directly currently (we probably have a lot of other …
> Don't generate an exception for each RPC

- .travis.yml
- .travis_scripts/verify.sh
- pom.xml
- test/pom.xml
Description: This PR enables codecov instead of coveralls
Why should this be merged: Code coverage on coveralls is currently broken (#1065). Codecov may provide better results.
Related issue(s) (if applicable): Fixes #1065
> Switch to CodeCov

- test/src/test/java/org/corfudb/security/tls/TlsUtilsTest.java
Description: This PR fixes an issue where TlsUtilsTest prints stack traces even though the tests pass.
Why should this be merged: Tests should not print stack traces - this PR resolves the issue with the test.
Related issue(s) (if applicable): #1063
> Fix stack trace print during TlsUtilsTest

- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- test/src/test/java/org/corfudb/runtime/CorfuRuntimeTest.java
- test/src/test/java/org/corfudb/runtime/clients/TestClientRouter.java
- test/src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
Description: CorfuRuntime: fetchLayout fetches the latest layout from a random layout server and sets the client router epochs to the newer, higher epoch number in a loop.
However, if the first router in the loop throws a network exception the loop is aborted and the other router epochs remain unset.
Why should this be merged: To avoid wrong epoch exceptions and set the router epochs correctly. 
Related issue(s) (if applicable): #1044
> Fix set router epoch on runtime invalidate.

- infrastructure/src/main/java/org/corfudb/infrastructure/log/SegmentHandle.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
Use a single channel per segment for uncached reads.
> Optimize Read Channels

- format/proto/types.proto
- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/Orchestrator.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/CreateWorkflowResponse.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/OrchestratorResponse.java
- runtime/src/main/java/org/corfudb/runtime/clients/ManagementClient.java
- test/src/test/java/org/corfudb/integration/AddNodeIT.java
- test/src/test/java/org/corfudb/runtime/clients/ManagementClientTest.java
Properly add/remove workflow ids when tracking workflows.
Description:
This PR fixes a bug introduced in #940. Workflows were being added by a different key than they were being removed, as a consequence querying a workflow's id would always return "active" even if the workflow wasn't running.
Fixes CI on master.
> Fix Orchestrator Query

- infrastructure/src/main/java/org/corfudb/infrastructure/BaseServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/NettyServerRouter.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/VersionInfo.java
- runtime/src/main/java/org/corfudb/util/UuidUtils.java
- test/src/test/java/org/corfudb/infrastructure/BaseServerTest.java
- test/src/test/java/org/corfudb/infrastructure/ManagementServerTest.java
- test/src/test/java/org/corfudb/runtime/clients/BaseClientTest.java
- test/src/test/java/org/corfudb/runtime/clients/ManagementClientTest.java
- test/src/test/java/org/corfudb/runtime/clients/NettyCommTest.java
- test/src/test/java/org/corfudb/runtime/clients/TestClientRouterTest.java
- test/src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
- test/src/test/java/org/corfudb/util/UuidUtilsTest.java
Description: This PR introduces a node Id field, which is generated on first start and stored in the data store. The node Id is a 128-bit UUID which is represented as a Base64 URL-safe string. The planned use of a base64 string is to append it to a server url, in the form ```<host>:<port>:<node-id>```, which will enable the node id to be checked at connection time during a handshake to be implemented in the future. Currently, the Node Id can be retrieved in using a versionRequest call to a server, and the server can retrieve the node Id from a serverContext.
Why should this be merged: This PR makes it possible to disambiguate servers which have failed, but restarted at the same IP address, eliminating configuration errors from allowing clients to connect to incorrect servers.
Related …
> Implement Node Id on Server

- runtime/src/main/java/org/corfudb/security/tls/TlsUtils.java
Description:
Removes usage of common-lang package from TlsUtils.
This commons-lang package is used by findbugs-maven-plugin dependency, which has the scope of provided (hence commons-lang also has the scope of provided), meaning it should be provided, but it's not actually provided when we use corfu anywhere.
Needed for TLS, otherwise it's broken.
> Removed usage of commons-lang package

- runtime/src/main/java/org/corfudb/runtime/view/ConservativeFailureHandlerPolicy.java
Description: Removes log unit while handling failures.
Why should this be merged: Without this the chain still contains a failed node which blocks all subsequent writes.
Related issue(s) (if applicable): Resolves #1036
> Remove log unit while handling failures

- runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java
- test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
Description: Fastloader has an api to provide indexer for specific streams
Why should this be merged: Decrease MP exposure to race conditions.
> Fastloader has an api to provide indexer for specific streams

- runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java
- runtime/src/main/java/org/corfudb/runtime/view/ObjectBuilder.java
- test/src/test/java/org/corfudb/runtime/collections/CorfuTableTest.java
Description:
When an object is opened, it is added to the cache right after
its creation, as a consequence other threads can retreive the object
from the object cache after its creation and before additional
initialization. For example, register index. This patch moves
the extra initialization into an atomic operation (i.e. computeIfAbsent.
Fixes a race bug in object open
> Object Open Race

- docs/NODE_FORMAT.md
Description: This documentation only PR describes the format of Node IDs in Corfu.
Why should this be merged: This simple PR describes only the Node ID format and does not contain code. It is required to safely enable all the clustering features in Corfu.
Related issue(s) (if applicable): Partially addresses #1051
> Describe the Node ID format

- runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java
- test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
Ensure that custom types are built correctly in the FastLoader.
When passing customType objects to the fastloader, upon creation of the tables, it checks if it needs to reconstruct the table using the custom object loader or using the default one. The check used to be if the custom constructor is different than the default constructor.
Since now the default type used in MP is CorfuTable, when we were passing a custom constructor that happens to also be of CorfuTable type, we would just used the default type. Because of this, we were losing the indexer passed in the custom object builder.
This change the condition for constructing a table with the custom object builder. If the stream ID is in customTypes, we will reconstruct the table with the custom object builder.
Why should this be …
> Custom type initialization fix

- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
- runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/ReadWaitHoleFillPolicy.java
Description: This PR improves error and exception handling by throwing ```UnrecoverableCorfuError``` whenever an unexpected exception is caught, and sleeping using the ```Utils.sleepUninterruptibly``` helper, which throws a ```UnrecoverableCorfuInterruptedError``` when interrupted.
Why should this be merged: This PR addresses several cases where catching all ```Exception``` types masked errors which should have been passed on to the application. In particular, this type of handling was causing ```InterruptedException``` to not shutdown threads on application termination.
Related issue(s) (if applicable): #1033
> Improve exception/error handling

- test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
In our corfu-0.1.2 branch of corfu, Helpers class doesn't exist. This will
remove the forward dependency.
We are breaking corfu-0.1.2 .
> Remove usage of Helpers.trim for compatibilty with corfu-0.1.2

- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/NetworkException.java
- runtime/src/main/java/org/corfudb/util/NodeLocator.java
- runtime/src/main/java/org/corfudb/util/UuidUtils.java
- test/src/test/java/org/corfudb/runtime/CorfuRuntimeTest.java
- test/src/test/java/org/corfudb/runtime/clients/NettyCommTest.java
- test/src/test/java/org/corfudb/runtime/clients/TestClientRouter.java
- test/src/test/java/org/corfudb/runtime/utils/NodeLocatorTest.java
Description:This PR introduces a NodeLocator class, which enables the Node ID to be accessed from the client side. The format of NodeLocators are described in PR #1069. A layout with a properly formatted NodeID string will be propagated to the server.
Why should this be merged: This PR is required to fully support clustering, and to prevent clients from connecting to nodes with incorrect state.
Related issue(s) (if applicable): Partially fixes #1051. What's left is to have layouts to be generated with the correct node id during bootstrap.
> Introduce Node Id on the client side.

- README.md
Description: Replace coveralls badge with new plugin to show accurate code coverage.
Why should this be merged: Show accurate coverage on README.
Also removing waffle.io badge as its no longer used.
Related issue(s) (if applicable):
> Replace coverage tool github badge

- pom.xml
- runtime/pom.xml
Description: This PR changes the ```git-commit-id-plugin``` to only run for the runtime package.
Why should this be merged: This PR should slightly improve build times. The commit id is only necessary for the runtime package, and takes a few seconds as it must scan the repository every time it is invoked.
> Only run git plugin on runtime

- infrastructure/src/main/java/org/corfudb/infrastructure/BaseServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/LayoutServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/NettyServerRouter.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
- logReader/src/test/java/org/corfudb/logReader/logReaderTest.java
- test/src/test/java/org/corfudb/infrastructure/BaseServerTest.java
- test/src/test/java/org/corfudb/infrastructure/ServerContextBuilder.java
- test/src/test/java/org/corfudb/runtime/clients/BaseClientTest.java
- test/src/test/java/org/corfudb/runtime/clients/NettyClientRouterTest.java
- test/src/test/java/org/corfudb/runtime/clients/NettyCommTest.java
- test/src/test/java/org/corfudb/runtime/clients/TestClientRouterTest.java
- test/src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
Description: This PR refactors CorfuServer so that code for instantiating the server and binding to a port can be reused in tests.
Why should this be merged: Previously, most CorfuServer code was untested because it required running from CorfuServer's ```main``` function. This resulted in a lot of code duplication in tests, and ultimately led to the test code deviating from the CorfuServer code. This change consolidates the test code (especially in ```NettyCommTest```) into CorfuServer, and the test code now re-uses the CorfuServer code. This change should increase coverage significantly and pave the way towards actually using Netty during tests instead of the simulated TestRouter framework.
> Refactor CorfuServer so that code can be reused in tests

- infrastructure/src/main/java/org/corfudb/infrastructure/BaseServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/LayoutServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
- test/src/test/java/org/corfudb/infrastructure/LayoutServerTest.java
Description: Moves the seal functionality to the Base Server from the Layout Server.
Why should this be merged: This allows corfu servers with log unit component to function independent of a layout server.
Related issue(s) (if applicable): Fixes #1012
> Move seal epoch to Base Server

- generator/src/main/java/org/corfudb/generator/LongevityApp.java
- infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ServerHandshakeHandler.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/ClientHandshakeHandler.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/HandshakeMsg.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/HandshakeResponse.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/HandshakeState.java
- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
- runtime/src/main/java/org/corfudb/security/sasl/plaintext/PlainTextSaslNettyClient.java
- test/src/test/java/org/corfudb/infrastructure/ServerContextBuilder.java
- test/src/test/java/org/corfudb/runtime/clients/NettyCommTest.java
Description:
An implementation of Corfu client-server handshaking. Overall:
- Upon connection, the client will initiate a handshake.
- Both (server and client) will start a handshake timeout timer.
- The client sends a message that contains its own id and the (asserted) server's id.
- The server validates the handshake message and replies with its own server id
and corfu version.
- The client makes its own validation and in case of is success,
message exchange is enabled.
- If any validation fails client/server will close the connection.
Why should this be merged:  This is a Feature Request. The fact that a node is no longer tied to an IP and instead is uniquely identified by a 16Byte Identifier raises the need of actually validating upon connection that we are connected to the right …
> Handshaking

- format/proto/types.proto
- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/Orchestrator.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/OrchestratorMsg.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/OrchestratorRequestType.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/RemoveNodeRequest.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/RemoveNodeWorkflow.java
- runtime/src/main/java/org/corfudb/runtime/clients/ManagementClient.java
- runtime/src/main/java/org/corfudb/runtime/view/LayoutBuilder.java
- runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
- test/src/test/java/org/corfudb/infrastructure/LayoutBuilderTest.java
- test/src/test/java/org/corfudb/integration/WorkflowIT.java
- test/src/test/java/org/corfudb/runtime/view/LayoutManagementViewTest.java
Description:
An implementation of a remove node workflow. This workflow extends the system's capability to downsize the cluster by removing nodes.
This PR and is needed to complete the clustering effort.
Related issue: https://github.com/CorfuDB/CorfuDB/issues/1039
> Remove node

- infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
- pom.xml
- test/src/test/java/org/corfudb/infrastructure/ServerContextBuilder.java
- test/src/test/java/org/corfudb/runtime/clients/NettyCommTest.java
Description: This PR builds on top of #1061 to support Epoll/Kqueue server channel types. 
Why should this be merged: This relatively simple addition on top of #1061 allows the use of native Netty transports, which should be more performant than the default NIO channel type. In addition, this change paves the way to use the built-in Local channel type, which will allow us to use Netty for all tests.
> Support EPoll/KQueue

- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/Orchestrator.java
The Orchestrator creates a new runtime for each workflow, this PR
makes the orchestrator use the same CorfuRuntimeParameters as the
management server's runtime. As a result, the security and auth
settings are carried over.
Related issue(s) (if applicable): #1106
> Use same CorfuRuntimeParameters

- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
safeUpdateLayout is called frequently on "no-ops" but, it emits
a log which pollutes the server logs.
Improves server logs readability.
> Changed Log Level

- infrastructure/src/main/java/org/corfudb/infrastructure/BaseServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/LayoutServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/NettyServerRouter.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
- runtime/src/main/java/org/corfudb/runtime/clients/BaseClient.java
- scripts/corfu_server.sh
- test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
Description: On node reset, all data log files and all meta data is deleted.
Why should this be merged: Required to reset a bootstrapped node before merging it into a different cluster.
> Cleanup after node reset.

- checks.xml
- runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
- test/src/test/java/org/corfudb/integration/AbstractIT.java
- test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
- test/src/test/java/org/corfudb/integration/ServerRestartIT.java
- test/src/test/java/org/corfudb/integration/WorkflowIT.java
Description: Fixes the kill node scenario and introduces an IT to test the same.
Issue: Writes blocked when a node containing a logunit and the primary sequencer crashes.
Fix: The maxGlobalTail fetch relied on fetching the tail from the crashed server. This caused failure in bootstrapping the new sequencer. So no new writes could get through.
Now the maxGlobalTail relies on fetching the global tail from the head of the chain of the new proposed layout. This ensures availability of the server and successfully bootstraps the sequencer.
Why should this be merged: Fixes kill node scenario and cleans up IT.
Related issue(s) (if applicable): Fixes #1074
> Kill node fix and IT

- runtime/src/main/java/org/corfudb/protocols/wireprotocol/ClientHandshakeHandler.java
- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
- test/src/test/java/org/corfudb/runtime/clients/NettyCommTest.java
Description: This PR changes the behavior of NettyClientRouter so that the a created router is automatically started, and that stopping a router automatically shuts it down. This prevents a deadlock cycle that could occur due to retry holding the monitor lock on the router.
Why should this be merged: Fixes deadlock bug, needed for reconfiguration to be robust.
> Fix router deadlock

- infrastructure/src/main/java/org/corfudb/infrastructure/AbstractServer.java
- test/src/test/java/org/corfudb/integration/AbstractIT.java
- test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
- test/src/test/java/org/corfudb/integration/ServerRestartIT.java
- test/src/test/java/org/corfudb/runtime/clients/NettyCommTest.java
Description: Fixes 3 intermittent test failures:
Shutdown Exceptions in sequencerTailsRecoveryTest and restartTest. Fixed by rechecking client connection after restart.
Time out in testTlsUpdateServerTrust. Fixed by stopping the existing the client and restarting it after trust reload.
Why should this be merged: Fixes broken tests.
> Fixing intermittent test failures

- runtime/src/main/java/org/corfudb/util/concurrent/SingletonResource.java
- test/src/test/java/org/corfudb/AbstractCorfuTest.java
- test/src/test/java/org/corfudb/infrastructure/ServerContextBuilder.java
- test/src/test/java/org/corfudb/test/concurrent/TestThreadGroups.java
- test/src/test/java/org/corfudb/test/logging/MemoryAppender.java
- test/src/test/java/org/corfudb/test/logging/TestLogger.java
Description: Initialize test thread groups in their own class instead of inside AbstractCorfuTest. This removes the dependency of ServerContextBuilder on AbstractCorfuTest.
Why should this be merged: The ServerContextBuilder, which is used by other test frameworks unnecessarily loads in all of AbstractCorfuTest, which may require conflicting classes. This test framework change fixes that issue.
> Init test groups outside of AbstractCorfuTest

- generator/src/main/java/org/corfudb/generator/operations/OptimisticTxOperation.java
- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
- runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
The version of a non-transactional access needs
to be reported from within the lock. Because of
specific timing (and optimization) we might access
the object to a later version than the timestamp
we linearized this access against.
Stop reporting false positive in consistency correctness verification.
> Fixing Correctness report

- format/proto/types.proto
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/ILogData.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/IMetadata.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- test/src/test/java/org/corfudb/runtime/clients/LogUnitClientTest.java
In order to validate that the entry that was persisted is
indeed the entry that the client wrote, we need to add an
id field for the LogData. The id is a compound id of
CorfuRuntime id and thread id.
Why should this be merged: This is a Consistency/Isolation issue that needs to be addressed.
Related issue(s) (if applicable): #1172
> LogData has now an id (clientId/ThreadId)

- runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
Description: When a channel is connected, there is a race in NettyClientRouter between when the channel is connected and when the completionFuture for the channel is fulfilled. As a result, a client can call sendMessageAndGetCompletableFuture() and encounter a NullPointerException if the channel is set after the completionFuture is fulfilled.
This PR also removes a deprecated ChannelHandlerContext that was being passed around, which is also vulnerable to the same race.
Why should this be merged: Resolves a NPE bug in NettyClientRouter.
> Fix channel race

- runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
- runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java
- runtime/src/main/java/org/corfudb/util/ImmuableListSetWrapper.java
- test/src/test/java/org/corfudb/runtime/collections/CorfuMapTest.java
On very large maps the checkpointing thread competes with other threads
that try to access the VLO as a result response times can be on the
magnitude of hours.
> Avoid Access During CP

- infrastructure/src/main/java/org/corfudb/infrastructure/LayoutServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/Orchestrator.java
- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/ForceRemoveWorkflow.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/LayoutCommittedRequest.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/ForceRemoveNodeRequest.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/OrchestratorRequestType.java
- runtime/src/main/java/org/corfudb/runtime/clients/LayoutClient.java
- runtime/src/main/java/org/corfudb/runtime/clients/ManagementClient.java
- runtime/src/main/java/org/corfudb/runtime/view/Layout.java
- runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
- runtime/src/main/java/org/corfudb/runtime/view/LayoutView.java
- runtime/src/main/java/org/corfudb/runtime/view/ManagementView.java
- runtime/src/main/java/org/corfudb/runtime/view/workflows/AddNode.java
- runtime/src/main/java/org/corfudb/runtime/view/workflows/ForceRemoveNode.java
- runtime/src/main/java/org/corfudb/runtime/view/workflows/HealNode.java
- runtime/src/main/java/org/corfudb/runtime/view/workflows/RemoveNode.java
- runtime/src/main/java/org/corfudb/runtime/view/workflows/WorkflowRequest.java
- test/src/test/java/org/corfudb/integration/WorkflowIT.java
This PR implements an API to bypass layout consensus and force
a layout on the cluster. This capability is used to implement force
remove node workflow.
Required for to complete clustering
> Force Remove Node

- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/AddNodeWorkflow.java
- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/HealNodeWorkflow.java
- runtime/src/main/java/org/corfudb/runtime/view/Layout.java
- runtime/src/main/java/org/corfudb/runtime/view/LayoutBuilder.java
- runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
- runtime/src/main/java/org/corfudb/runtime/view/workflows/AddNode.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Description:
Addressing the following issues. #1178 
Modifying the add node workflow to replace the state transfer and merge segment Actions with the RestoreRedundancy Action.
This action takes the new endpoint to be added and restores its redundancy across all segments.
This is done by transferring the state of each of these segments to the new node. The end result is that now the new node is added as a part of all these segments. (Side effect: 1 epoch change.)
Note: After an add node, there will be multiple segments. The merging of segments will now only be handled by the Heal node workflow.
Modifying the heal node workflow to replace the state transfer and merge segment Actions with the RestoreRedundancyAndMergeSegments Action.
This action attempts to merge all the existing segments. …
> Fix stateTransfer and mergeSegment

- infrastructure/src/main/java/org/corfudb/infrastructure/BaseServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
- scripts/corfu_server.sh
Description: Base server now triggers a cleanup and reset asynchronously using a thread in the CorfuServer. This removes the dependency on the wrapper script.
Why should this be merged: Apps do not need to depend on the script.
Related issue(s) (if applicable): #1193
> Reset and restart without wrapper script

- test/src/test/java/org/corfudb/infrastructure/HealingDetectorTest.java
- test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Description:
Fixing intermittently failing killAndHealNode IT.
Reducing waiting times on unit tests.
Fixes intermittent failures.
> Fixing intermittently failing killAndHealNode

- runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
- test/src/test/java/org/corfudb/runtime/clients/TestClientRouter.java
Description: A client does not need to validate the epoch of the response message on reception from the server.
Server epoch: 1
Client epoch: 0
The client sends a write message stamped with epoch 0. The server rejects this and sends back a WrongEpochException message stamped with epoch 1. The client on reception, validates the epoch and rejects this message and throws a WrongEpochException with expected epoch as 0. Whereas,  the expected epoch should be 1.
Why should this be merged: Avoid redundant check.
> Do not validate epoch on client msg reception

- runtime/src/main/java/org/corfudb/runtime/view/workflows/WorkflowRequest.java
- test/src/test/java/org/corfudb/integration/WorkflowIT.java
Avoid rounding to zero by using the smallest time unit when
calculating number of times to poll in waitForWorkflow.
Fixes #1200
> ArithmeticException Fix

- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java
- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/AddNodeWorkflow.java
- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/HealNodeWorkflow.java
- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
- runtime/src/main/java/org/corfudb/runtime/view/LayoutView.java
- runtime/src/main/java/org/corfudb/runtime/view/SequencerView.java
- runtime/src/main/java/org/corfudb/runtime/view/workflows/WorkflowRequest.java
- test/src/test/java/org/corfudb/integration/AbstractIT.java
- test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
- test/src/test/java/org/corfudb/integration/SealIT.java
- test/src/test/java/org/corfudb/integration/ServerRestartIT.java
- test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
- test/src/test/java/org/corfudb/runtime/CorfuRuntimeTest.java
- test/src/test/java/org/corfudb/runtime/object/transactions/StreamTest.java
- test/src/test/java/org/corfudb/runtime/view/LayoutSealTest.java
- test/src/test/java/org/corfudb/runtime/view/LayoutViewTest.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
- test/src/test/java/org/corfudb/runtime/view/QuorumReplicationStreamViewTest.java
- test/src/test/java/org/corfudb/runtime/view/replication/AbstractReplicationProtocolTest.java
- test/src/test/java/org/corfudb/runtime/view/replication/ChainReplicationProtocolTest.java
Description: Renames the getEpochedClient to getRuntimeLayout
Why should this be merged: The method fetches the RuntimeLayout. Hence should be named accordingly.
> Rename getEpochedClient to getRuntimeLayout

- infrastructure/src/main/java/org/corfudb/infrastructure/DataStore.java
- test/src/test/java/org/corfudb/infrastructure/DataStoreTest.java
Added integrity checks on the local data store, now partial writes
are not possible and data corruption is detectable.
Partially addresses #1187
> Added Integrity Checks

- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
- test/src/test/java/org/corfudb/runtime/object/CompileProxyTest.java
Description:
This fix will throw a TrimmedException after a number of retries
when it non-transactionally tries to access an object, as opposed
to the previous behavior where it fails with a StackOverflowError.
fixes  #1185
> StackOverflow Fix

- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/WriteSizeException.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/java/org/corfudb/runtime/view/RuntimeLayout.java
- test/src/test/java/org/corfudb/integration/StreamIT.java
Added the ability to enforce a max write limit for the client.
Related Issue: #928
For some applications clients would like to set a max write limit. This PR will reject writes greater than the limit if its configured.
> Set Max Write Limit

- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
- test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java
Removed a redundant delimiter in the log file format.
Why should this be merged: Enhances log file format.
Related issue(s) (if applicable): addresses #978
> Remove Redundant Delimiter

- runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java
- runtime/src/main/java/org/corfudb/runtime/view/RuntimeLayout.java
Description:
Fixing performance. Instead of creating deep copies of the layout, reusing the layout reference in the RuntimeLayout constructor.
In the AbstractView, we now keep an atomic reference of the RuntimeLayout used and create new only if there is an epoch change. 
Why should this be merged: Fixes performance drop introduced by #1192
> Fix object creation performance regression #1192

- migration/src/main/java/org/corfudb/migration/LogFormat1to2.java
Description: Introduction of network interface binding by #1209 allows the user to bind to a specific IP address. To support migration from version 0.1.1, we should transform the layout configuration files (LAYOUT_CURRENT and MANAGEMENT_LAYOUT) so that they replace the old ip:port with the new binding ip:port.
Why should this be merged: To allow the user to migrate from 0.1.1 to the latest build.
> Layout migration

- runtime/src/main/java/org/corfudb/util/MetricsUtils.java
Description:
This PR adds the ability of reporting the currently collected metrics to MBeans. In addition some refactoring is done to improve the clarity of metrics utility.
- Reported metrics to MBeans can be conveniently examined and monitored live using the tools conforming to JMX api such as jConsole and jVisualVM which are already bundled with standard JDK. This enables both users and developers of Corfu to easily access Corfu metrics.
- In regards to refactoring, the changes are steps toward improving metrics infrastructure to better address the metrics collection and reporting requirement.  
Related issue(s) (if applicable): #1243
> Reporting Corfu metrics to MBeans

- runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
To avoid waiting for RPC calls to be executed under the VLO lock,
snapshot timestamp can be obtained right before acquiring the lock.
Description: Get Snapshot Timestamp before the lock is acquired. This typically represents a single RPC call per transaction, therefore, the performance gains are higher for smaller transactions. 
Why should this be merged: depending on the workload pattern we have found performance improvements of up to 44%. Performance outperforms as the transaction size decreases and the number of threads in the client increases. This percentage (44%) was found for the case of Single Write Transactions and 40 client threads. We have also tested this thoroughly on Rishi's System and not found any regression. 
Related issue(s) (if applicable): #1207
> Optimisitic TX RPC Call out of the lock

- cmdlets/src/main/java/org/corfudb/metrics/MBeanDumperApp.java
- cmdlets/src/main/java/org/corfudb/metrics/MBeanUtils.java
- scripts/metrics_dumper.sh
Description: This commit implements an standalone app for taking snapshot of MBeans in a JMX server and dumping them to a file. It is accompanied by a shell script that facilitates passing the parameters and executing the app. The app is separated from the custom client so if there is a need, the current MBeanUtils can be leveraged to access the MBeans and their attributes programmatically.
This tool enables accessing MBeans, taking snapshot of corfu metrics published to a JMX server, and exporting them to file. These can be used as a troubleshooting/monitoring mechanism for CorfuDB. The tool is also flexible enough to dump other published environmental metrics in addition to corfu ones.
Related issue(s) (if applicable): #1251
> Implementing JMX MBean dumper

- infrastructure/src/main/java/org/corfudb/infrastructure/DataStore.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- infrastructure/src/main/java/org/corfudb/infrastructure/utils/Persistence.java
Fsync the parent directory of newly created files.
Why should this be merged: Fixes #433
> Sync Directory

- migration/src/main/java/org/corfudb/migration/EndpointMigration.java
- migration/src/main/java/org/corfudb/migration/LogFormat1to2.java
Description: Separate the endpoint migration to a standalone tool. Allow users to modify the endpoint in the layout files. However, to use this the tool, the user first needs to shut down the server.
Why should this be merged: To allow users to modify the endpoint in the layout files.
> Separate endpoint migration to different class

- cmdlets/pom.xml
Description:
Related issue(s) (if applicable): 
[Bug 2077892: Build and Packaging: Build] [OSS/TP] Outdated version of jackson 2.0.6 found in Corfu
https://bugzilla.eng.vmware.com/show_bug.cgi?id=2077892#c15
> Upgraded jackson packages in cmdlets pom.xml

- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java
Description: Retry a configurable number of times before invoking the systemDownHandler on Network Exceptions. This allows the system to detect and reconfigure in the event of a failure.
The failure detector takes at least 3 seconds to detect the failure after which it proposes the new layout.
Why should this be merged: This allows the user to configure a retry timeout before which the client can take appropriate action to shut down the client due to system unavailability.
> SystemDownHandler invocation trigger threshold

- infrastructure/src/main/java/org/corfudb/infrastructure/CorfuMsgHandler.java
- runtime/src/main/java/org/corfudb/util/MetricsUtils.java
Description:
This commit, implements the option of reporting corfu metrics to CSV files.
Creating CSV files for different metrics facilitates users' investigation of Corfu performance by analyzing and aggregating different metrics offline. Similarly developers can assess the performance implication of introduced changes by crunching results capturing different Corfu performance indicators along side each other.
Related issue(s) (if applicable): #1262
> Implements possibility of exporting corfu metrics to CSV files.

- runtime/src/main/java/org/corfudb/runtime/clients/SequencerClient.java
Description: Providing backward compatibility of the sequencer bootstrap API.
Why should this be merged: For backward compatibility of a public API.
> Backward compatible sequencer bootstrap API.

- runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java
- test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
Description: Invoke the systemDownHandler when the client is unable to reach the server after a certain number of retries. This should be invoked regardless of the exception in connecting to the server.
Why should this be merged: The systemDownHandler is not invoked if 2/3 servers are down as it throws a TimeoutException rather than a NetworkException.
> Invoke systemDownHandler on cluster unreachability.

- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/NetworkMetrics.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/NodeView.java
- runtime/src/main/java/org/corfudb/runtime/view/ClusterStatusReport.java
- runtime/src/main/java/org/corfudb/runtime/view/Layout.java
- runtime/src/main/java/org/corfudb/runtime/view/ManagementView.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Description: API to request for cluster status and client connectivity.
The Management Agents exchange their view of the cluster through the failure and healing detectors. This view is relayed via the Heartbeat Responses. The Client cluster status query API also uses this heartbeat requests to ping and query the cluster view.
Why should this be merged: Required to query the status of client's connectivity to the cluster and the health of the cluster.
Related issue(s) (if applicable): #1272
> Cluster status query API

- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/clients/ClientMsgHandler.java
- runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
- runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/java/org/corfudb/util/CorfuComponent.java
- runtime/src/main/java/org/corfudb/util/MetricsUtils.java
- test/src/test/java/org/corfudb/runtime/clients/TestClientRouter.java
Description:
This commit implements collection of client side metrics on different Corfu _messages_ from the _runtime_ point of view. In other words these added metrics, measure the round trip life of the messages from when Netty client starts processing a message until when the request is completed. 
Being able to access the metrics from server and client sides is required for monitoring of CorfuDB behavior in response to different workloads as well as for comparison of performance and debugging of the code.
Related issue(s) (if applicable): #1273
> Implement round trip timing of Corfu Messages from client

- infrastructure/src/main/java/org/corfudb/infrastructure/DataStore.java
- infrastructure/src/main/java/org/corfudb/infrastructure/IDataStore.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
- test/src/test/java/org/corfudb/runtime/view/LayoutViewTest.java
The local datastore cache used to cache a key to the serialized
form of the value, as a result every get was desrializing the
object. This is inefficient, this PR maps a key to the deserilized
form of the object.
Why should this be merged: Improves contention on the local datastore
> Datastore Performance Issue

- infrastructure/src/main/java/org/corfudb/infrastructure/AbstractServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/NettyServerRouter.java
- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ServerThreadFactory.java
Allow different servers to use their own thread pools, with that, the Sequencer requests are now serviced on a different thread pool.
Why should this be merged: This allows us to dedicate threads for particular servers without having the negative effects of sharing same thread pool. Having granular control over each server threading will also pave the way for future optimizations. 
> Seperate Sequencer Threads

- runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
- test/src/test/java/org/corfudb/integration/WorkflowIT.java
Description: Skip sequencer bootstrap in force remove node. Allow the management server to detect and bootstrap the sequencer.
Why should this be merged: Allows 2 out of 3 nodes to be forcibly removed in case of 2/3 failures.
Related issue(s) (if applicable): #1244
> Skip sequencer bootstrap on ForceRemove

- generator/src/main/java/org/corfudb/generator/StringIndexer.java
- runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java
- test/src/test/java/org/corfudb/integration/ServerRestartIT.java
- test/src/test/java/org/corfudb/runtime/collections/CorfuTableTest.java
- test/src/test/java/org/corfudb/runtime/collections/StringIndexer.java
- test/src/test/java/org/corfudb/runtime/collections/StringMultiIndexer.java
Description:
This commit enables multi value indexing by enabling CorfuTable of having indexes with mono index function or multi-index function. In other words, when a {K, V} being indexed by a multi index function, it will emit multiple index mappings.
This features is going to be used by clients (e.g. management plane) to emit multiple index mappings for each key/value pair.
Related issue(s) (if applicable): #1285
> Enabling multi indexing

- infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java
Description: Move SSL initialization to channel implementation. This allows the user the replace the SSL credentials on demand without restarting the server.
Why should this be merged: Prevents server crash on SSL Exception.
> Fix crash on SSLException.

- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
The shared pool size accounts for the logunit(LU) batch size, the LU
doesn't need a separate thread pool.
Why should this be merged: The LU thread pool was incorrectly cherry-picked from another PR, I didn't intend to have a separate thread pool for the LU in #1281
> Remove Extra LU Thread Pool

- generator/src/main/java/org/corfudb/generator/operations/SnapshotTxOperation.java
- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/TokenRequest.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/TokenResponse.java
- runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java
- runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
- runtime/src/main/java/org/corfudb/runtime/clients/SequencerClient.java
- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/view/SequencerView.java
- runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
- test/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java
- test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
- test/src/test/java/org/corfudb/integration/CmdletIT.java
- test/src/test/java/org/corfudb/integration/SealIT.java
- test/src/test/java/org/corfudb/integration/ServerRestartIT.java
- test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
- test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
- test/src/test/java/org/corfudb/runtime/clients/SequencerHandlerTest.java
- test/src/test/java/org/corfudb/runtime/collections/SMRMapEntrySetTest.java
- test/src/test/java/org/corfudb/runtime/object/CompileProxyTest.java
- test/src/test/java/org/corfudb/runtime/object/transactions/StreamTest.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
- test/src/test/java/org/corfudb/runtime/view/SequencerViewTest.java
- test/src/test/java/org/corfudb/runtime/view/StreamViewTest.java
- test/src/test/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocolAdditionalTests.java
- test/src/test/java/org/corfudb/runtime/view/stream/BackpointerStreamViewTest.java
Enbales the sequencer to query the tails of multiple streams in
one call.
Why should this be merged: Fixes the stream query API  and will be used by #1278 and #1277
> Fix The Multi-Stream Query API

- runtime/src/main/java/org/corfudb/runtime/view/Layout.java
- runtime/src/main/java/org/corfudb/runtime/view/LayoutBuilder.java
- test/src/test/java/org/corfudb/infrastructure/LayoutBuilderTest.java
- test/src/test/java/org/corfudb/runtime/view/LayoutManagementViewTest.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Description: Change the min replication factor for Chain replication to 1.
Also corrects the Quorum replication min factor to calculate the quorum based on log servers in each stripe.
Why should this be merged: Resolves liveness issue caused by #1325
Related issue(s) (if applicable): Resolves #1325 and #1322
> Chain min replication factor set to 1.

- runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java
Description:
Using named generic instead of wildcard generic of Comparable in IndexRegistry to address casting issues on the client side.
> Using named generic instead of wildcard generic of Comparable for IndexRegistry

- infrastructure/src/main/java/org/corfudb/infrastructure/ServerHandshakeHandler.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/ClientHandshakeHandler.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/MultipleReadRequest.java
Description of refactoring:
This is a refactoring on Server and Client HandshakeHandlers and MultipleReadRequest for the following purposes:
- Removing messages from queue at the time of writing and flushing them by the HandshakeHandlers
- Fixing unchecked assignment
- Replacing implementation of Queue (from ArrayDeque to LinkedList) for memory allocation and consistent o(1) 
- Using singleton instead of creating a list of one
- Avoiding to unnecessarily keep messages in queue of HandshakeHandler
- Consistent o(1) add/remove from queue and avoiding ArrayDeque's memory overhead
- Replacing unchecked assignment
- Avoiding list creation for one member
Related issue(s) (if applicable): #1316
> Refactoring: emptying handler's queues and using singleton instead of list

- runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/java/org/corfudb/runtime/view/CacheOption.java
- runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
- test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
Description:
Now appends can specify a caching option per append. Also, changed
the CheckpointWriter to no cache checkpoint entries.
Why should this be merged: This helps relieve memory pressure.
Related issue(s) (if applicable): #1329
> Added Cache Options Per Write

- infrastructure/src/main/java/org/corfudb/infrastructure/LayoutServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
Description: The local datastore passes references of objects on `get()`. A lot of code paths assume that the object fetched from the datastore is a copy and make modifications to it. This now causes inconsistencies in the object itself.
Why should this be merged: To maintain consistency a copy of the layout needs to be propagated rather than the reference.
This bug was caught by an intermittently failing test: `removeSingleNodeFailure`
> Copy layout on daatastore access

- infrastructure/pom.xml
- runtime/pom.xml
- runtime/src/main/java/org/corfudb/util/MetricsUtils.java
Description:
Adding the ability to collect and report JVM and troubleshooting metrics. These metrics include: gc, memory, thread, and logger stats.
The collection and reporting is disabled by default.
By passing the corresponding flags, JVM metrics including gc, memory, thread, and logger stats will be included in collected and reported metrics.
Related issue(s) (if applicable): #1300
> Adding JVM and troubleshooting metrics

- infrastructure/src/main/java/org/corfudb/infrastructure/CorfuMsgHandler.java
- runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
- runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/java/org/corfudb/util/CorfuComponent.java
- test/src/test/java/org/corfudb/runtime/clients/TestClientRouter.java
Description:
This PR modifies the code on CorfuMsgHandler in order to simplify the logic for adding metrics context so that checking the configuration (for metrics being enabled) is delegated to MetricsUtil rather than being done in CorfuMsgHandler. Also the metrics name for timers are been reused in case they have already been created.
-Simplifying the unnecessary complexity of evaluating metrics configuration on the the handler side.
Related issue(s) (if applicable): #1311
> Simplifying adding metrics context to handlers on CorfuMsgHandler

- pom.xml
- runtime/src/main/java/org/corfudb/security/tls/SslContextConstructor.java
This patch changes the ssl context constructor to use a native
engine implementation. My test show 4.5x improvement on server
and client restart.
Why should this be merged: Addresses client/server restart performance 
Related issue(s) (if applicable): #1343
> Faster ssl

- runtime/src/main/java/org/corfudb/runtime/view/LayoutBuilder.java
- test/src/test/java/org/corfudb/infrastructure/LayoutBuilderTest.java
Description: 
This PR includes:
-Changed the logic to only select a responsive sequencer server on failover.
-Added UT to show that unresponsive sequencer servers won't be picked on failover.
-Clean up in test (restricting visibility and modifier of test parameters)
Why should this be merged: In the current code, we do not check for the unresponsive servers list and can failover to an unresponsive sequencer which can lead to a cluster liveness issue.
Related issue(s) : Resolves #1339
> Select responsive failover sequencer.

- runtime/src/main/java/org/corfudb/runtime/view/ClusterStatusReport.java
Description: Change the access modifiers for  Node and Cluster status enums to public.
Why should this be merged: Status not accessible by clients.
> Expose the node and cluster status.

- infrastructure/pom.xml
- runtime/pom.xml
- runtime/src/main/java/org/corfudb/util/MetricsUtils.java
Description:
Removing the logback statistic.
This removes the dependency on logback as it might be undesirable for some clients.
> Removing logback analyzer

- infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriter.java
- infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriterOperation.java
- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/HealNodeWorkflow.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/IMetadata.java
- runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
- runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
- test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
Description: Reset the logunit node while `HealNodeWorkflow` after we have sealed. Also, make the reset epoch unaware to allow a stale node to recover. The reset epoch is persisted by the node to prevent multiple resets from wiping the data on the same epoch.
Why should this be merged: A node with a very old epoch can never heal as it fails on reset with a wrong epoch exception.
Related issue(s) (if applicable): Resolves #1340
> Seal before reset of healing node.

- runtime/src/main/java/org/corfudb/runtime/clients/ManagementClient.java
- runtime/src/main/java/org/corfudb/runtime/view/workflows/AddNode.java
- runtime/src/main/java/org/corfudb/runtime/view/workflows/ForceRemoveNode.java
- runtime/src/main/java/org/corfudb/runtime/view/workflows/HealNode.java
- runtime/src/main/java/org/corfudb/runtime/view/workflows/RemoveNode.java
- runtime/src/main/java/org/corfudb/runtime/view/workflows/WorkflowRequest.java
The client workflows were recasting TimeoutException to
RuntimeException as a result retries don't get triggered.
Why should this be merged: Makes workflow retries more robust.
> Surface Timeout Exceptions

- runtime/src/main/java/org/corfudb/runtime/view/workflows/WorkflowRequest.java
Description:
After a Network/Timeout Exception, the runtime should veirfy
the result of the workflow before retrying.
Why should this be merged: After a timeout exception, the action might have completed, so verifying the result before retrying is more efficient.
> Fixed Verify Order

- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/AddNodeWorkflow.java
- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/HealNodeWorkflow.java
Description: Avoid creating multiple actions on every`getActions` invocation.
Related issue(s) (if applicable): Resolves #1357
> Create Actions once - HealNodeWorkflow

- runtime/src/main/java/org/corfudb/runtime/object/transactions/TransactionalContext.java
- test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
- test/src/test/java/org/corfudb/runtime/view/ObjectsViewTest.java
Prevent transactions from different runtimes to be nested.
Why should this be merged: If this condition is not prevented then transactional consistency can be broken.  
Related issue(s) (if applicable): #1366
> Prevent Incorrect Nesting

- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java
- infrastructure/src/main/java/org/corfudb/infrastructure/NettyServerRouter.java
Initializes the router's epoch to the last epoch it received
(through set_epoch), defaulting to 0 can cause deadlocks.
Why should this be merged: Fixes a deadlock scenario 
Related issue(s) (if applicable): #1372
- [] Change is covered by automated tests
> Initialize Router Epoch

- infrastructure/src/main/java/org/corfudb/infrastructure/CorfuMsgHandler.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
- runtime/src/main/java/org/corfudb/runtime/clients/BaseHandler.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/UnavailableServerException.java
- runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java
- test/src/test/java/org/corfudb/infrastructure/BaseServerTest.java
This fix addresses the case when an rpc fails without retrying
when it reaches a server that is shutting down.
Why should this be merged: Prevents rpc failure some nodes are unavailable. 
Related issue(s) (if applicable): #1371
> RPC Failure On Unavailable Servers

- pom.xml
Description:
Related issue(s) (if applicable): 
[Bug 2124747: Build and Packaging: Build] [OSS/TP] Outdated version of slf4j 1.7.6 found
https://bugzilla.eng.vmware.com/show_bug.cgi?id=2124747#c9
> Upgraded slf4j-api from 1.7.6 to 1.7.25

- pom.xml
- runtime/src/main/java/org/corfudb/security/tls/SslContextConstructor.java
This patch changes the ssl context constructor to use a native
engine implementation. My test show 4.5x improvement on server
and client restart.
Why should this be merged: Improves client/sequencer reboot performance when TLS is used.
> Use Native Implementation for SSL

- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
- runtime/src/main/java/org/corfudb/runtime/BootstrapUtil.java
- runtime/src/main/java/org/corfudb/runtime/clients/ManagementClient.java
- test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
Description: If layout server bootstrap attempt times out due to a late bootstrap response and is retried, it results in an AlreadyBootstrappedException. This needs to be asserted that it was initially bootstrapped with the same layout and if yes, the exception should be ignored.
Why should this be merged: Late response of Layout bootstrap can cause BootstrapUtil unusability.
Related issue(s) (if applicable): #1386
> Ignore already bootstrapped nodes if BootstrapUtil retried.

- runtime/src/main/java/org/corfudb/runtime/view/workflows/AddNode.java
- runtime/src/main/java/org/corfudb/runtime/view/workflows/ForceRemoveNode.java
- runtime/src/main/java/org/corfudb/runtime/view/workflows/HealNode.java
- runtime/src/main/java/org/corfudb/runtime/view/workflows/RemoveNode.java
- runtime/src/main/java/org/corfudb/runtime/view/workflows/WorkflowRequest.java
- test/src/test/java/org/corfudb/integration/AbstractIT.java
- test/src/test/java/org/corfudb/integration/Harness.java
- test/src/test/java/org/corfudb/integration/WorkflowIT.java
The workflow requests should select a random orchestrator to prevent
selecting dead nodes (in the case of a stale layout).
Why should this be merged: Fixes a bug that blocks force remove requests
Related issue(s) (if applicable): #1384
> Force remove bug

- README.md
Hi, I just started to have a try CorfuDB, and found some minor typo when reading introduction.
* `seperately` to `separately`
* `starts a in-memory single node` to `starts an in-memory single node`
* `Now lets add that layout server` to `Now let's add that layout server`
> [Readme][Minor] fix readme typo

- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/AddNodeWorkflow.java
- test/src/test/java/org/corfudb/integration/Harness.java
- test/src/test/java/org/corfudb/integration/WorkflowIT.java
- test/src/test/java/org/corfudb/integration/cluster/Harness/Node.java
Description: Transfer the trim-mark during state transfer
Why should this be merged: The new/healed nodes will not have the trim mark. A new CorfuRuntime does not realize this and attempts to hole fill all the trimmed entries.
Related issue(s) (if applicable): Resolves #1395
> Transfer trimMark on stateTransfer.

- migration/src/main/java/org/corfudb/migration/LayoutReset.java
Description: Tool to reset layout and epoch binding. This allows the application to migrate from version 0.2.0 (single node deployment) to version 0.3.0 clearing all the layout bindings and re-bootstrap the node with a clustered configuration.
Why should this be merged: Utility to assist in migration to a clustered configuration.
Related issue(s) (if applicable): Resolves #1407
> Migration: Tool to reset layout binding.

- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLog.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogWithRankedAddressSpace.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
- runtime/src/main/java/org/corfudb/runtime/clients/LogUnitHandler.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/AbortCause.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/OverwriteCause.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/OverwriteException.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocol.java
- test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java
- test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTransactionContextTest.java
The cause CONFLICT is reported whenever two transaction conflict over
the same keys for a given stream(s). This change corrects the overload
of this abort cause for the case of slow writers, i.e., whenever a
writer fails to write given that the designated address is continuously
overwritten (perhaps hole filled) by a faster reader. This is due to the
fact that it is not really conflicting with any other stream, the cause
of abort is that you are overwritten by a fast reader in the system.
Why should this be merged: this is an issue that has been reported by the Application Layer as conflicting keys/streams show up being NULL which makes no sense out of a Conflicting Transaction for upper layers.
Related issue(s) (if applicable): #1399
> Transaction Abort Exception Cause for slow writers

- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
The tcp connection can get in a state where the client doesn't
receive a termination signal, but the server dies abruptly. In this
case, the client can hang until the OS times out the connection.
This can take a very long time (in our case 15min) until the system
becomes available again.
Why should this be merged: Fixes a bug where the system can hang indefinitely
> Force Timeout On Connection

- runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
Description: Added RPC type on timeout.
Why should this be merged: Makes logs and timeouts easier to debug.
Related issue(s) (if applicable):Resolves #1409
> Add RPC request type on timeout

- infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/java/org/corfudb/runtime/view/Layout.java
- runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
- runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
- runtime/src/main/java/org/corfudb/util/Utils.java
- test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
- test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Description: Now the FastObjectLoader will obtain the log globalTail by polling the Log Unit servers instead of relying on the sequencers view, which in turn needs to wait for the sequencer to
recover. This will allow clients and servers restarting at the same time to run in parallel rather than having to wait for the sequencer to totally recover.
Why should this be merged: This fixes a performance issue (#1389) and is required also in the effort of optimizing the stream tail recreation on sequencer bootstrap, which is currently lead by the Layout Servers and will be moved into the sequencer server.
Related issue(s) (if applicable): #1389
> Remove FastObjectLoader Dependency on Sequencer

- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/SequencerTailsRecoveryMsg.java
- test/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Description: Reject empty/delta sequencer bootstrap messages on the failover sequencer.
Why should this be merged: Causes a correctness issue where the sequencer dispatches stale tokens and regresses the token count.
> Reject empty seq bootstrap msg on failover.

- runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java
Description: Rethrow SystemDownHandler Exceptions in AbstractView thrown by fetchLayout.
Why should this be merged: AbstractView gets stuck in an infinite loop if `layout.get()` is unable to fetch a layout.
Related issue(s) (if applicable): Fixes #1433
> Rethrow systemDownHandler exceptions

- runtime/src/main/java/org/corfudb/util/concurrent/SingletonResource.java
Description: SingletonResource does not release the correct lock in case of lock upgrade from readLock to writeLock.
Why should this be merged: Lock is never released and thread crashes.
Related issue(s) (if applicable): Fixes #1446
> Fix singleton resource locking.

- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java
Description: Submitting sequencer bootstrap tasks to the detectionWorker thread pool instead of ForkJoinPool to better control the termination of this task.
Why should this be merged: On shut down the task runs asynchronously. 
Related issue(s) (if applicable): Fixes #1439
> Terminating sequencerBootstrap thread on shutdown

- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
- test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
Description: Learns the trim mark from @cjqhenry14 's PR #1448 and trimming the resolved queue after a considerable amount of time.
However, this should be replaced by the introduction of the new StreamLayer.
Why should this be merged: Causes a memory leak as the resolvedQueue is never trimmed.
> Learn trim mark and trim resolvedQueue.

- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/view/ClusterStatusReport.java
- runtime/src/main/java/org/corfudb/runtime/view/ManagementView.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Description: Add an intermediate node status- DB_SYNCING to denote that the node is recovering and does not have full redundancy.
Why should this be merged: Provides better visibility to the users.
Related issue(s) (if applicable): Resolves #1415 and #1416
> Add DB_SYNCING Node status

- runtime/pom.xml
- runtime/src/main/java/org/corfudb/util/MetricsUtils.java
- test/src/test/java/org/corfudb/integration/AbstractIT.java
- test/src/test/java/org/corfudb/integration/MemoryFootprintIT.java
- test/src/test/java/org/corfudb/util/MemoryFootprintMeasurerIT.java
Description:
This enables MetricsUtil to collect and report on memory footprint of objects. The objects can be registered to Metrics registry for measurement and reporting of their memory footprints.
This provides a tool that facilitates debugging and monitoring of memory size of objects as this has been a concern and evaluating such measures has not been straightforward. 
Related issue(s) (if applicable): #1315
> Ability to measure and collect memory consumptions metrics of corfu objects

- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java
- test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
Description:
Invalidate layout when invoking systemDownHandler. Else the layout completable future is stuck with the systemDownHandlerException forever.
Why should this be merged: The layout completable future is stuck with the systemDownHandlerException forever.
Related issue(s) (if applicable): Fixes #1466
> Invalidate Layout on SystemDownHandler trigger

- infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
Description: Crash with an error code if cannot bind to address.
Why should this be merged: The server does not shut down gracefully in case there is a router instantiation error.
Related issue(s) : Fixes #1470
> Exit with error code on crash.

- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java
- test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
Description:
Invalidate layout when invoking systemDownHandler. Else the layout completable future is stuck with the systemDownHandlerException forever.
Backported to 0.2.1 in #1465 
The layout completable future is stuck with the systemDownHandlerException forever.
Related issue(s) (if applicable): Fixes #1466
> Invalidate layout on systemDownHandler.

- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java
- test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
- test/src/test/java/org/corfudb/runtime/CorfuRuntimeTest.java
Description:
Moving the systemDownHandler to CorfuParameters. Making it volatile and adding additional logging.
Why should this be merged: Adding logging for debuggability.
> Move systemDownHandler to CorfuRuntimeParameters.

- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ServerHandshakeHandler.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/ClientHandshakeHandler.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Description: 
Fix partially sealed cluster by filling the epoch slot.
Close unused netty pipeline duplex handlers which timeout every 30 seconds even if the channel is used.
Why should this be merged: Resolves liveness issue.
Related issue(s) (if applicable): Fixes #1478
> Fix partially sealed cluster and close handlers.

- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/NodeRouterPool.java
- runtime/src/main/java/org/corfudb/util/NodeLocator.java
Description:
Duplicate routers cause unexpected ShutdownExceptions or NetworkExceptions.
Why should this be merged: Uses NodeLocators legacyEndpoint in the NodeRouterPool until NodeLocator is used everywhere.
Related issue(s) (if applicable): Fixes #1487
> NodeRouterPool indexes routers on NodeLocator.

- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
When a CorfuRuntime idles, the channel becomes inactive after a
certain amount time, this can close the connection prematurely,
so I added a keep-alive message that keeps the channel active.
Prevents connections from closing prematurely. 
Related issue(s) (if applicable): #1425
> Implemented Channel Keep-Alive

- infrastructure/src/main/resources/logback.prod.xml
- infrastructure/src/main/resources/logback.xml
Description:
Setup logging in corfu db. `Infrastructure`/resource directory contains two logback configs:
- logback.xml - for development purposes
- logback.prod.xml - production config
This PR provides logging config for production and development environments. The production config missing on prod environment.
> Corfu db logging

- infrastructure/src/main/java/org/corfudb/infrastructure/ServerHandshakeHandler.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/ClientHandshakeHandler.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/HandshakeState.java
Removed redundant channel close calls in client and server handshake handlers.
> Handshake handler cleanup, remove redundant channel close

- runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/TransactionAbortedException.java
- test/src/test/java/org/corfudb/runtime/collections/CorfuTableTest.java
- test/src/test/java/org/corfudb/runtime/object/transactions/StreamTest.java
The use of the getByIndex API should fail whenever the index has not
been specified for the given table. This should be followed by the
proper exception and logging. In addition we add a message field to
the transaction aborted exception info in case a message for the cause
of abort is available.
> Lookup by Index when Index is not specified

- infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/DataStore.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
- test/src/test/java/org/corfudb/infrastructure/DataStoreTest.java
- test/src/test/java/org/corfudb/infrastructure/ServerContextBuilder.java
Description:
- Some local DataStore files are created on very epoch change, and we never remove them, which could take much extra spaces when server is running for a long time and changing layouts.
- This patch adds a new CorfuServer option, which allows user to specify number of these DataStore file to be retained, and delete the files with lower epochs when the cache is written through.
- The reason to add the new CorfuServer option is to keep some DataStore files for debugging.
Related issue: #1000
> Cleanup growing datastore files with a new CorfuServer option

- test/src/test/java/org/corfudb/integration/WorkflowIT.java
Removing WorkflowIT.forceRemoveTwoDeadNodes because it is failing
intermittently and the same test is implemented in
HandOfGodIT.handOfGodTest
Why should this be merged: Redundant test that is failing intermittently.
> Remove A Faulty Test

- infrastructure/src/main/resources/logback.prod.xml
- infrastructure/src/main/resources/logback.xml
- test/src/test/resources/logback-test.xml
Description:
Change the date format for the production log, change extension from `tar.gz` to `gz` for log files, improve message format in logback-test.xml
Improve logging format for log messages
> Change date format in production logger

- test/src/test/java/org/corfudb/infrastructure/log/StreamLogCompactionTest.java
Description:
Wait until gc happens more than 2 times
Fix StreamLogCompactionTest
Related issue(s) (if applicable): #1537
> Fix StreamLogCompactionTest

- infrastructure/src/main/java/org/corfudb/infrastructure/management/ClusterRecommendationEngine.java
- infrastructure/src/main/java/org/corfudb/infrastructure/management/ClusterRecommendationEngineFactory.java
- infrastructure/src/main/java/org/corfudb/infrastructure/management/ClusterRecommendationStrategy.java
Description:
This commit provides the interface which will be used for providing recommendation on whether a node is suspected of Failed or Healed status. The recommendation will be made based on the cluster view and underlying policy.
The introduced policy enables plugging different concrete algorithms for making the aforementioned recommendations.
Required for failure detection and tolerance in case of link failures.
> Interface for Cluster Recommendation Engine

- corfu_scripts/corfu_layouts.clj
- infrastructure/src/main/java/org/corfudb/infrastructure/AbstractServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/BaseServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriter.java
- infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriterOperation.java
- infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/IServerRouter.java
- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java
- infrastructure/src/main/java/org/corfudb/infrastructure/NettyServerRouter.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
- runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
- runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
- runtime/src/main/java/org/corfudb/runtime/view/RuntimeLayout.java
- runtime/src/main/java/org/corfudb/runtime/view/SealServersHelper.java
- test/src/test/java/org/corfudb/infrastructure/TestServerRouter.java
- test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
- test/src/test/java/org/corfudb/integration/SealIT.java
- test/src/test/java/org/corfudb/runtime/CorfuRuntimeTest.java
- test/src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
- test/src/test/java/org/corfudb/runtime/view/LayoutSealTest.java
- test/src/test/java/org/corfudb/runtime/view/LayoutViewTest.java
- test/src/test/java/org/corfudb/runtime/view/LogUnitSealTest.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
- test/src/test/java/org/corfudb/runtime/view/replication/ChainReplicationProtocolTest.java
The current seal logic is not correct as described in #1528. This patch fix this issue by setting remote epoch on all servers and execute correct sealing logic on each server types. For now only the log unit servers has the needs to do the additional sealing logic, which flushes all the operations before the seal and fail all the operations after this, but stamped with an older epoch.
This patch also fix the incorrect behavior when flushing and failing operations on log unit servers with BatchWriter, which could cause tests to fail intermittently.
Related issue(s) (if applicable): #1528
> Correctly seal servers on epoch change

- pom.xml
Description:
Update netty version to 4.1.27
Netty version 4.1.18 has a number of memory leaks in it (see https://bugzilla.eng.vmware.com/show_bug.cgi?id=2183135#c32 for a list).
> bump netty version

- it/src/main/java/org/corfudb/universe/group/Group.java
- it/src/main/java/org/corfudb/universe/group/cluster/AbstractCorfuCluster.java
- it/src/main/java/org/corfudb/universe/group/cluster/CorfuCluster.java
- it/src/main/java/org/corfudb/universe/group/cluster/CorfuClusterParams.java
- it/src/main/java/org/corfudb/universe/group/cluster/docker/DockerCorfuCluster.java
- it/src/main/java/org/corfudb/universe/group/cluster/vm/VmCorfuCluster.java
- it/src/main/java/org/corfudb/universe/node/Node.java
- it/src/main/java/org/corfudb/universe/node/client/ClientParams.java
- it/src/main/java/org/corfudb/universe/node/client/CorfuClient.java
- it/src/main/java/org/corfudb/universe/node/client/LocalCorfuClient.java
- it/src/main/java/org/corfudb/universe/node/server/AbstractCorfuServer.java
- it/src/main/java/org/corfudb/universe/node/server/CorfuServer.java
- it/src/main/java/org/corfudb/universe/node/server/CorfuServerParams.java
- it/src/main/java/org/corfudb/universe/node/server/ServerUtil.java
- it/src/main/java/org/corfudb/universe/node/server/docker/DockerCorfuServer.java
- it/src/main/java/org/corfudb/universe/scenario/fixture/Fixtures.java
- it/src/main/resources/logback.xml
- it/src/test/java/org/corfudb/universe/group/CorfuClusterParamsTest.java
- it/src/test/java/org/corfudb/universe/node/server/CorfuServerParamsTest.java
- it/src/test/java/org/corfudb/universe/scenario/AllNodesPartitionedIT.java
- it/src/test/java/org/corfudb/universe/scenario/ClusterResizeIT.java
- it/src/test/java/org/corfudb/universe/scenario/ConcurrentClusterResizeIT.java
- it/src/test/java/org/corfudb/universe/scenario/HandOfGodIT.java
- it/src/test/java/org/corfudb/universe/scenario/NodesDownAndPartitionedIT.java
- it/src/test/java/org/corfudb/universe/scenario/NodesPausedAndPartitionedIT.java
- it/src/test/java/org/corfudb/universe/scenario/OneNodeDownIT.java
- it/src/test/java/org/corfudb/universe/scenario/OneNodePartitionedIT.java
- it/src/test/java/org/corfudb/universe/scenario/OneNodePausedIT.java
- it/src/test/java/org/corfudb/universe/scenario/TwoNodesDownIT.java
- runtime/src/main/java/org/corfudb/runtime/BootstrapUtil.java
Description:
Make integration tests more generic:
- open random `open` port for a corfu server, which allows running integration tests in parallel in the future
- get rid of hard-coded names for nodes in tests
- allows running integration tests in parallel in the future
> Make integration tests more generic

- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/FillHoleRequest.java
- runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/ChainReplicationProtocol.java
- test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
- test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java
Hole fill methods were using the TrimRequest type to send rpcs
to the server, since they share the same number of fields and types
this issue is not detected at compile/runtime.
Why should this be merged: Fixes an rpc bug
> Hole Fill RPC Bug

- .travis_scripts/verify.sh
- it/pom.xml
- it/src/main/java/org/corfudb/universe/UniverseFactory.java
- it/src/main/java/org/corfudb/universe/group/Group.java
- it/src/main/java/org/corfudb/universe/group/cluster/AbstractCorfuCluster.java
- it/src/main/java/org/corfudb/universe/group/cluster/docker/DockerCorfuCluster.java
- it/src/main/java/org/corfudb/universe/group/cluster/vm/VmCorfuCluster.java
- it/src/main/java/org/corfudb/universe/node/client/ClientParams.java
- it/src/main/java/org/corfudb/universe/node/client/LocalCorfuClient.java
- it/src/main/java/org/corfudb/universe/node/server/AbstractCorfuServer.java
- it/src/main/java/org/corfudb/universe/node/server/CorfuServerParams.java
- it/src/main/java/org/corfudb/universe/node/server/docker/DockerCorfuServer.java
- it/src/main/java/org/corfudb/universe/node/server/vm/VmCorfuServer.java
- it/src/main/java/org/corfudb/universe/universe/vm/ApplianceManager.java
- it/src/main/java/org/corfudb/universe/util/DockerManager.java
- it/src/main/java/org/corfudb/universe/util/IpTablesUtil.java
- it/src/test/java/org/corfudb/universe/group/CorfuClusterParamsTest.java
- it/src/test/java/org/corfudb/universe/node/server/CorfuServerParamsTest.java
- it/src/test/java/org/corfudb/universe/scenario/ClusterResizeIT.java
- it/src/test/java/org/corfudb/universe/scenario/NodesDownAndPartitionedIT.java
- it/src/test/java/org/corfudb/universe/scenario/OneNodePartitionedIT.java
- pom.xml
Description:
- Run integration tests in parallel
- deactivate integration tests by default
- use `-Pit` profile to run integration tests. By default, it uses 3 forks
- improves stability and performance for `it` module
> It profile

- generator/src/main/java/org/corfudb/generator/operations/CheckpointOperation.java
- infrastructure/src/main/java/org/corfudb/infrastructure/BaseServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriter.java
- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/AddNodeWorkflow.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/TrimRequest.java
- runtime/src/main/java/org/corfudb/runtime/MultiCheckpointWriter.java
- runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- test/src/test/java/org/corfudb/infrastructure/TestServerRouter.java
- test/src/test/java/org/corfudb/integration/ServerRestartIT.java
- test/src/test/java/org/corfudb/integration/WorkflowIT.java
- test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
- test/src/test/java/org/corfudb/recovery/Helpers.java
- test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
- test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTest.java
- test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTrimTest.java
- test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java
- test/src/test/java/org/corfudb/runtime/object/CompileProxyTest.java
- test/src/test/java/org/corfudb/runtime/object/transactions/SequencerCacheTest.java
- test/src/test/java/org/corfudb/runtime/object/transactions/StreamTest.java
- test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
- test/src/test/java/org/corfudb/runtime/view/LogUnitSealTest.java
- test/src/test/java/org/corfudb/runtime/view/StreamViewTest.java
- test/src/test/java/org/corfudb/runtime/view/ViewsGarbageCollectorTest.java
Makes prefix trim epoch aware.
Why should this be merged: Prevents stray prefix trims from truncating uncheckpointed data
Related issue(s) (if applicable): #1513
> Prefix Trim On Token

- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/RetryExhaustedException.java
- runtime/src/main/java/org/corfudb/runtime/view/Layout.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/ReadWaitHoleFillPolicy.java
- runtime/src/main/java/org/corfudb/util/retry/ExponentialBackoffRetry.java
- test/src/test/java/org/corfudb/util/retry/IRetryTest.java
Description:
The default HoleFill wait duration is currently 1 second and the Write timeout is 5 seconds. This inconsistency results in pre-mature timeouts and hole-fills.
Why should this be merged: To avoid pre-mature hole-fills.
Related issue(s) : Fixes #1471
> Exponential back-off before address holefill.

- infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriter.java
- infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriterOperation.java
- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/LogMetadata.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLog.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/TailsResponse.java
- runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java
- runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
- runtime/src/main/java/org/corfudb/runtime/clients/LogUnitHandler.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
- runtime/src/main/java/org/corfudb/util/Utils.java
- test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
- test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
- test/src/test/java/org/corfudb/integration/WorkflowIT.java
- test/src/test/java/org/corfudb/recovery/Helpers.java
- test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
This patch enables the logging units to track the stream tails
and expose that via rpc. Also, changed the sequencer recovery
logic to consume the new rpc in order to greatly reduce the
failover time.
Why should this be merged: Significantly improves the time it takes for the sequencer to failover. 
Related issue(s) (if applicable): #1504 and #1503
> Sequencer Recovery Enhancement

- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
Description:
Only shutdown the event loop once and don't wait for the shut
down future to complete.
Why should this be merged: the shutdown method is called from both the application side and our servers, if this method never return it can block the server from cleanly shutting down restart (i.e partial shutdown)
Related issue(s) (if applicable): #1575
> Shutdown EventLoop Once

- runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java
- runtime/src/main/java/org/corfudb/runtime/ViewsGarbageCollector.java
- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/java/org/corfudb/runtime/view/Layout.java
- runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/ThreadSafeStreamView.java
- test/src/test/java/org/corfudb/runtime/view/stream/BackpointerStreamViewTest.java
Made all raw streams (i.e. streams that are not consumed by the VLO)
thread-safe and extended the garbage collection process to include
the CorfuRuntime::StreamView.
Why should this be merged: Fixes memory leaks created by streams that don't belong to SMRObjects (i.e. transaction stream and any stream created by the CorfuRuntime consumer directly). 
Related issue(s) (if applicable): #1573
> Raw Streams Garbage Collection

- it/src/main/java/org/corfudb/universe/node/server/CorfuServer.java
- it/src/main/java/org/corfudb/universe/node/server/docker/DockerCorfuServer.java
- it/src/main/java/org/corfudb/universe/node/server/vm/VmCorfuServer.java
- it/src/main/java/org/corfudb/universe/util/IpTablesUtil.java
- it/src/test/java/org/corfudb/universe/scenario/NodeDownAndLinkFailureIT.java
- it/src/test/java/org/corfudb/universe/scenario/OneLinkFailureIT.java
Make both docker and VM capable of creating partial partition in testing framework.
First step of adding new test scenarios  for the new fault detector.
> Add partial partition fault to test framework for both docker and VM.

- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Description: Cleanup sequencer cache before we set the new bootstrapped values on the sequencer.
Why should this be merged: The invalidate cache is async and is not same as cache eviction. The Eviction should take place before the value of maxConflictWildcard is set.
> Cleanup seq cache before setting maxConflictWildcard.

- pom.xml
Description:
Upgrading Corfu's Google Guava to 23.0.
Upgrading the Guava version to 23.0 as some clients of CorfuDB (NSX) have issues with older 21.0.
> Upgrade the Google Guava's Version

- runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java
Description:
Remove unnecessary lombok annotation.
Remove unused import.
Get rid of warnings.
> Remove unnecessary lombok toString annotation, clean up imports.

- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
- test/src/test/java/org/corfudb/runtime/view/StreamViewTest.java
Fixes a bug in the stream view where when iterating backwards,
the stream pointer gets stuck at incorrect positions, which
triggers a NoRollBackException that causes a complete object
rebuild.
Why should this be merged: Improves performance for some pathological access patterns by 20x +
Related issue(s) (if applicable): #1625
> StreamView Bug Fix

- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/management/FullyConnectedClusterRecommendationEngine.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/ILogData.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/Token.java
- runtime/src/main/java/org/corfudb/runtime/MultiCheckpointWriter.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/ChainReplicationProtocol.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
ILogData::useToken wasn't setting the epoch field properly.
Also, added extra logging pretaining to hole filling
and stream single stepping.
Why should this be merged: bug fix and improves logging.
> ILogData Token Fix + Logging

- infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriter.java
- infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriterOperation.java
- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/SegmentHandle.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLog.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
- runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
- test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
We currently only support prefix trimming, removed all the logic
related to sparse trimming, which will also prevent the related
metadata files from being created.
Why should this be merged: Prevents unnecessary metadata from being generated.
> Remove Parse Trimming Logic

- runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/FastObjectLoaderException.java
- test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
When the untrimmed range of the address space is large, the FastObjectLoader
can run out of memory, because it keeps submitting read requests without
taking into account the number of pending jobs. This patch adds a limit
on the number of pending jobs.
Why should this be merged: Fixes an issue where the fast loader can't load a very large address space, because it runs out of memory
> Bounded Reads

- infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriter.java
- infrastructure/src/main/java/org/corfudb/infrastructure/NettyServerRouter.java
- runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTrimTest.java
If client is in a stale epoch, prefixTrim is retried after a layout
invalidate.
Why should this be merged: prevents prefixTrim tasks failing due to clients on the wrong epoch. This is relevant as trimming is an operation typically performed periodically, if we do not retry, trim will have to wait for the next cycle unnecessarily. 
Related issue(s) (if applicable): #1673
> Retry prefixTrim for Runtime on wrong epoch

- runtime/src/main/java/org/corfudb/protocols/wireprotocol/Token.java
- runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
- runtime/src/main/java/org/corfudb/runtime/MultiCheckpointWriter.java
- runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java
- test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
- test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
- test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTest.java
Instead of using the same snapshot to checkpoint all the maps
to be checkpointed, this patch makes the CheckpointWriter
use increasing checkpoint snapshots for every map and
therefore decreasing the probability of rolling back the stream.
Because multiple increasing snapshots are used, only the smallest
snapshot is used for trimming.
Why should this be merged: Improves the currently broken compaction design by a "bit"
Related issue(s) (if applicable): #1681
> MultiVersion Checkpoints

- generator/src/main/java/org/corfudb/generator/LongevityApp.java
- generator/src/main/java/org/corfudb/generator/operations/SleepOperation.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java
- infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogCompaction.java
- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/Orchestrator.java
- runtime/src/main/java/org/corfudb/runtime/ViewsGarbageCollector.java
- runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/unrecoverable/UnrecoverableCorfuInterruptedError.java
- runtime/src/main/java/org/corfudb/runtime/view/ManagementView.java
- runtime/src/main/java/org/corfudb/util/Sleep.java
- samples/src/main/java/org/corfudb/samples/WriteWriteTXs.java
- test/src/test/java/org/corfudb/runtime/CorfuRuntimeTest.java
Ensure that all code paths that deal with interrupts re-enable the interrupt flag. In order to solve this issue systematically, during the construction of UnrecoverableCorfuInterruptedError we call Thread.currentThread().interrupt().
After capturing InterruptedException, we need to re-enable the interrupt
flag, since InterruptedException is wrapped in an unchecked exception.
Related issue(s) (if applicable): #1668
> Restore the interrupted status

- runtime/src/main/java/org/corfudb/runtime/view/workflows/WorkflowRequest.java
Since the layout's view can reflect incorrect state (i.e. responsive
servers marked as unresponsive), all nodes should be considered
when selecting an orchestrator, not just responsive ones (based
on the layout)
Why should this be merged: Unblocks the cluster when the layout has marked all the responsive nodes as unresponsive and the unresponsive node as responsive. 
Related issue(s) (if applicable): #1576
> getOrchestrator Bug

- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- infrastructure/src/main/resources/logback.prod.xml
Description:
Reducing log emission
There is a lot of noise in the corfu logs that makes it difficult to investigate the logs. Further more it causes the size of collected log to grow ver quickly.
> Reducing log emission

- infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
- test/src/test/java/org/corfudb/infrastructure/ServerContextBuilder.java
Description:
Increasing the number of metadata retention default in order to keep more layouts. 
This is helpful for debugging the history of layout changes when investigating the bugs.
> Increasing default retention to keep more layout change history

- infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java
- infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java
- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/Action.java
- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/Orchestrator.java
- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/RestoreRedundancyMergeSegments.java
- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/AddNodeWorkflow.java
- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/HealNodeWorkflow.java
- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/RestoreRedundancyMergeSegmentsWorkflow.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/OrchestratorRequestType.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/RestoreRedundancyMergeSegmentsRequest.java
- runtime/src/main/java/org/corfudb/runtime/clients/ManagementClient.java
- runtime/src/main/java/org/corfudb/runtime/view/Layout.java
- runtime/src/main/java/org/corfudb/runtime/view/ManagementView.java
- runtime/src/main/java/org/corfudb/runtime/view/workflows/RestoreRedundancyMergeSegments.java
- test/src/test/java/org/corfudb/integration/AbstractIT.java
- test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
- test/src/test/java/org/corfudb/integration/TransactionAbortedIT.java
- test/src/test/java/org/corfudb/integration/WorkflowIT.java
Description: Detect split segments, restore redundancy and merge the segments.
Why should this be merged: If the heal/add node workflow crashes midway, the state transfer is never completed and the newly added nodes stay with reduced redundancy.
Related issue(s) (if applicable): Fixes #1390
> Handle restore redundancy and merge segments.

- runtime/src/main/java/org/corfudb/runtime/ViewsGarbageCollector.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractContextStreamView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractStreamContext.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
- test/src/test/java/org/corfudb/integration/AbstractIT.java
- test/src/test/java/org/corfudb/integration/WorkflowIT.java
- test/src/test/java/org/corfudb/runtime/view/stream/BackpointerStreamViewTest.java
Description: Whenever there is an ongoing transaction which snapshot (version) falls in the space of addresses that has already been trimmed from the log and the runtime GC kicks in, we might have "temporal loss" of data, given that the resolvedQueues are trimmed even when we have pointers in this space, meaning that the object loses all updates from this position until the trim mark. This is recovered on resets when the stream is loaded from the checkpoint. 
Why should this be merged: 'apparent' data loss.
- [X ] There are no TODOs left in the code
- [X ] [Coding conventions](https://github.com/CorfuDB/CorfuDB/wiki/Corfu-Style-Guidelines) (e.g. for logging, unit tests) have been followed
- [X ] Change is covered by automated tests
- [X ] Public API has Javadoc
> Fix Runtime GC Bug

- runtime/src/main/java/org/corfudb/runtime/ViewsGarbageCollector.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractContextStreamView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractStreamContext.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
- test/src/test/java/org/corfudb/integration/AbstractIT.java
- test/src/test/java/org/corfudb/integration/WorkflowIT.java
- test/src/test/java/org/corfudb/runtime/view/stream/BackpointerStreamViewTest.java
Description: Whenever there is an ongoing transaction which snapshot (version) falls in the space of addresses that has already been trimmed from the log and the runtime GC kicks in, we might have "temporal loss" of data, given that the resolvedQueues are trimmed even when we have pointers in this space, meaning that the object loses all updates from this position until the trim mark. This is recovered on resets when the stream is loaded from the checkpoint.
Why should this be merged: data loss
> Runtime gc fix corfu 0.2.2

- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
When global pointer is set from checkpoint, GC trim validation should
not be triggered.
> Remove GC Trim mark validation from CP

- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractContextStreamView.java
- test/src/test/java/org/corfudb/integration/AbstractIT.java
- test/src/test/java/org/corfudb/integration/WorkflowIT.java
The nextUpTo method should not perform globalPointer validation at the beginning, this was supposed to be an optimization but actually can lead to trim exceptions on non-transactional reads. Non-transactional accesses to a stream are linearized against the stream tail. If this tail is in the trimmed space, this validation will make it fail. But yet it can be read from the checkpoint and still point to this position.
> Non-Transactional Reads after GC Fix

- runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
- runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/java/org/corfudb/runtime/view/RuntimeLayout.java
- runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
Description:
The max write size is checked at the LogUnitClient after obtaining a token. This causes us to create a lot of holes in case the payload size is large.
Thus the check has been moved to the stream layer.
Why should this be merged: This creates a lot of holes due to large payload sizes.
> Check max write size in stream layer.

- runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
- runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/java/org/corfudb/runtime/view/RuntimeLayout.java
- runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
Description:
The max write size is checked at the LogUnitClient after obtaining a token. This causes us to create a lot of holes in case the payload size is large.
Thus the check has been moved to the stream layer.
Why should this be merged: This creates a lot of holes due to large payload sizes.
> Check max write size

- infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Description:
Prevent layout commit by updateTrailingLayoutServers on new epoch.
Why should this be merged: Causes layout inconsistency.
> Fix layout commit by updateTrailingLayoutServers.

- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/view/Layout.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/ChainReplicationProtocol.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
Description:
Wait for only one address in range before hole fills instead of all addresses.
Change hole fills timeout from 5 to 10 seconds.
Why should this be merged: Time spent after acquiring the token and before writing was not considered in hole fill timeout.
> Avoid wait after holeFill in range read.

- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Description:
In some cases we could have multiple segments but all segments have same
number of servers. The current code will still start stateTransfer in
this case and result in unnecessary reads of data.
Avoid unnecessary reads which causes performance overheads
> Avoid stateTransfer when adjacent segments have same number of servers

- test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTransactionContextTest.java
Description: Fixes slow unit test due to increasing hole fill timeout.
Why should this be merged: Fixes unit test.
Related issue(s) (if applicable): Fixes #1761
> Fixes slow hole fill test.

- infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/DataStore.java
- infrastructure/src/main/java/org/corfudb/infrastructure/IDataStore.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogDataStore.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- infrastructure/src/test/java/org/corfudb/infrastructure/log/StreamLogDataStoreTest.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/DataCorruptionException.java
- runtime/src/main/java/org/corfudb/runtime/exceptions/LogUnitException.java
Description:
- If can't create stream log directory then throw UnrecoverableException 
- extract StreamLogDataStore 
- get  rid of unnecessary variables
Improving StreamLogFiles by better exception handling, improving/extracting StreamLogDataStore.
> StreamLog refactoring/simplification, exception handling

- infrastructure/src/main/java/org/corfudb/infrastructure/LocalMonitoringService.java
- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/AddNodeWorkflow.java
- runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
- runtime/src/main/java/org/corfudb/runtime/view/LayoutView.java
- runtime/src/main/java/org/corfudb/runtime/view/ManagementView.java
- runtime/src/main/java/org/corfudb/util/CFUtils.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Description: Fixes partial bootstraps in case of already bootstrapped components.
Why should this be merged: The management server remains un-bootstrapped forever.
Related issue(s) (if applicable): Fixes #1725 
Tests affecting this:
testPartialBootstrapNodeSuccess
testPartialBootstrapNodeFailure
> Fix partial bootstraps during AddNode.

- infrastructure/src/main/java/org/corfudb/infrastructure/AbstractServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/CorfuMsgHandler.java
- infrastructure/src/test/java/org/corfudb/infrastructure/AbstractServerTest.java
- infrastructure/src/test/java/org/corfudb/infrastructure/CorfuAbstractServerTest.java
- test/pom.xml
- test/src/test/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocolAdditionalTests.java
Description:
Simplify shutdown checks in AbstractServer
It makes shutdown checks easier to understand
AbstractServer doesn't expose internal state which makes it more reliable
> Simplify shutdown checks in AbstractServer

- infrastructure/src/main/java/org/corfudb/infrastructure/BaseServer.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/clients/BaseClient.java
- runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
Description:
- Create a new KeepAlive message which is basically a ping but ignores epoch.
- Fix CompletableFuture exception handling in NettyClientRouter when the exception
is not due to timeout, which results in handling same exception twice.
- Removed client side SO_KEEPALIVE socket option since we already have keep alive mechanism in client side.
Fixed two issues:
- Keep alive message gets WrongEpochException
- Same CompletableFuture exception handled twice in NettyClientRouter
Related issue(s) (if applicable): #1743
> Make Netty keep alive message ignore epoch, fix Future handling in NettyClientRouter

- test/src/test/java/org/corfudb/infrastructure/BaseServerTest.java
- test/src/test/java/org/corfudb/infrastructure/TestServerRouter.java
- test/src/test/java/org/corfudb/runtime/clients/TestClientRouter.java
The TestServerRouter should use server executors to handle requests in
order to simimulate the actual handling logic. Without this, changes
like changing number of server executor threads will not be reflected
in unit tests.
> Use server executor in TestServerRouter

- infrastructure/src/main/java/org/corfudb/infrastructure/management/FailureDetector.java
- runtime/src/main/java/org/corfudb/runtime/BootstrapUtil.java
- runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
- runtime/src/main/java/org/corfudb/runtime/view/LayoutView.java
- runtime/src/main/java/org/corfudb/runtime/view/ManagementView.java
- runtime/src/main/java/org/corfudb/runtime/view/SealServersHelper.java
- test/src/test/java/org/corfudb/integration/AbstractIT.java
- test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
- test/src/test/java/org/corfudb/integration/CmdletIT.java
- test/src/test/java/org/corfudb/integration/CorfuMsgFilterIT.java
- test/src/test/java/org/corfudb/integration/Harness.java
- test/src/test/java/org/corfudb/integration/LargeWriteIT.java
- test/src/test/java/org/corfudb/integration/MemoryFootprintIT.java
- test/src/test/java/org/corfudb/integration/SealIT.java
- test/src/test/java/org/corfudb/integration/SecurityIT.java
- test/src/test/java/org/corfudb/integration/ServerRestartIT.java
- test/src/test/java/org/corfudb/integration/WorkflowIT.java
- Properly shutdown the netty routers in BootstapUtil when exception
happens. This prevents channel leakage, which may cause an issue that
after the boostrap finishes and then some server goes down, the leaked
channels are constantly reconnecting every second.
- Integrations tests are not shutting down runtime after tests finish,
which is also leaking channels.
- Removed all NetworkExceptions catches when creating NettyClientRouter,
since it is needed only for legacy versions.
Related issue(s) (if applicable): #1788
> Prevent netty channel leak

- infrastructure/src/main/java/org/corfudb/infrastructure/AbstractServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/BaseServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/CorfuMsgHandler.java
- infrastructure/src/main/java/org/corfudb/infrastructure/LayoutServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
- infrastructure/src/test/java/org/corfudb/infrastructure/CorfuAbstractServerTest.java
Description:
A corfu netty server could be in various states. Exposing those states make a server lifecycle unambiguous.  
Improving/clarify a server lifecycle.
> Abstract server state

- runtime/src/main/java/org/corfudb/runtime/object/transactions/Transaction.java
- test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTransactionContextTest.java
- Currently when starting nested transactions, client can bypass the txn
type inheritance, and start nested transactions with different types,
which could violate txn semantics. This patch enforces a txn type check
upon transaction start.
Related issue(s) (if applicable): #1796
> Check nested transaction type mismatch upon txn begin

- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java
- runtime/src/main/java/org/corfudb/recovery/RecoveryUtils.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/ChainReplicationProtocol.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/IReplicationProtocol.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocol.java
- test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
- test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
While a thread writes (i.e. replicate), other threads within the
same client can read the write from the server before it gets
cached. This results in losing undo records and thus causes
objects to experience NoRollBackException.
Why should this be merged: Fixes a cache race bug that causes
objects to resync (i.e. NoRollBackException)
Related issue(s) (if applicable): #1798
> Cache Race Fix

- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java
- runtime/src/main/java/org/corfudb/recovery/RecoveryUtils.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/ChainReplicationProtocol.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/IReplicationProtocol.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocol.java
- test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
- test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
While a thread writes (i.e. replicate), other threads within the
same client can read the write from the server before it gets
cached. This results in losing undo records and thus causes
objects to experience NoRollBackException.
Porting #1805 from master to corfu-0.2.2
Furthermore, this patch also fixes a correctness bug introduced
in 2ab39da845ba3e40a66e31ad550d54d59e3db103 where empty log
slots are ignored and not hole filled.
> Cache-After-Write Race + Data Loss Bug (#1805)

- runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java
- test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
Description:
If FastObjectLoader face TRIMMED message, it starts loading trimmed data again.
updates logHead up to `trimMark` then the loading process continues from trim mark position
> FastObjectLoader fix nextRead offset

- infrastructure/src/main/java/org/corfudb/infrastructure/BaseServer.java
Description:
Why should this be merged: Debugging patch to help diagnose epoch changes. Logging who changed an epoch saves time by pinpointing which cluster node to look at next.
> Log who changed the epoch

- pom.xml
Description:
Updates the Netty Version to 4.1.33.Final.
To match the version used by CorfuDB's clients.
Related issue(s) (if applicable): #1826
> Update Netty Version to 4.1.33.Final

- runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
- test/src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
Description:
Add log to print size of map which was checkpointed. This will help detect keys leaking in CorfuTable.
Shut down server thread pools after tests.
Why should this be merged: Debuggability and test performance.
> Add checkpointed map size log and fix unit tests.

- .travis_scripts/settings.xml
- annotationProcessor/pom.xml
- annotations/pom.xml
- cmdlets/pom.xml
- debian/pom.xml
- format/pom.xml
- generator/pom.xml
- infrastructure/pom.xml
- it/pom.xml
- pom.xml
- runtime/pom.xml
- samples/pom.xml
- test/pom.xml
Description:
Deploy Corfu jar artifacts to bintray maven repository.
This change allows using Corfu easily. 
Can help improve automation and also helps in the following issues/improvements:
- achieving CD
- together with "versioning" improves CI and also helps in achieving CD
- reuse "universe" framework
- dockerize Corfu
- get rid of "private" version of Corfu, which simplifies a lot of in a build process 
> Deploy corfu artifact into bintray maven repository

- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java
Restore fault detection interval to 1 second which was previously using.
> Restore fault detection interval to 1 second

- runtime/src/main/java/org/corfudb/runtime/exceptions/SerializerException.java
- runtime/src/main/java/org/corfudb/util/serializer/Serializers.java
Description:
If a client does not have the serializer required to access data from a given map, it would currently throw a NullPointerException and fail to open a map with no clear cause.
Why should this be merged: this change set properly handles this error and informs the client on the missing serializer.
Related issue(s) (if applicable): #1835
> Handle Serializer not present

- runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
Description: Unwrap the ExecutionException before completing the Future exceptionally.
Why should this be merged: Network Exceptions are not recognized as they are wrapped in ExecutionExceptions further wrapped in RuntimeExceptions causing transactions to fail unexpectedly.
Related issue(s) (if applicable): #1863
> Unwrap ExecutionException before re-throwing.

- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
- test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
It seems like once we switched to asMap().computeIfAbsent we
started seeing spurious AssertionError. Although the problem
is not completely understood this change is being reverted
until it is investigated further.
Related issue(s) (if applicable): #1878
> Reintroducing the Loading Cache

- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- test/src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java
LogUnitServer should not come up on a read-only directory, because
it would later fail log writes. This could result in clustering
and availability issues.
Co-authored-by: xnull <xrw.null@gmail.com>
Issue: #1859
Description:
> Fail LogUnitServer startup if log directory is read-only

- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/StreamAddressSpace.java
- test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTest.java
Description: when attempting to trim the bitmaps on a negative value, the rankLong function will return the cardinality of infinity, i.e., the complete address map, thus trimming all addresses from the sequencer (when non should've been trimmed as trim mark was -1). This can lead to potential issues in which a stream cannot be rebuilt as all addresses appear to be trimmed and not covered by a checkpoint. This PR fixes this issue.
Why should this be merged: fix a potential bug detected on an intermittent test failure.
> Fix PrefixTrim Bug on Address Maps

- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
- test/src/test/java/org/corfudb/integration/TransactionStreamIT.java
- test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
The purpose of this patch is to load values into the cache without
overwriting existing values (if they are already cached). Overwriting
cache entries can result in a loss of undo records; this patch
attempts to address that issue.
Why should this be merged: hopefully addresses #1878 and improves the bitset implementation of the stream layer
> Remove load all

- .travis.yml
CI jobs that run on the master branch are failing on the universe
tests because the docker image doesn't exist. This patch adds
a package command before the test runs.
Why should this be merged: Fixs CI
Related issue(s) (if applicable):  #1890
> Fix CI Failures for Master

- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
Synchronizing on evictions is not necessary and StreamLogFiles::read
is thread-safe.
Why should this be merged: The eviction handler just logs and doesn't require synchronization  
> Remove Unnecessary Synchronization

- .travis.yml
Make travis send email notifications to the corfu-dev mailing lists
when CI fails on the master branch. Also, update the distro to xenial. 
Why should this be merged: Will make it easier to monitor the master branch.
> Travis CI Changes

- infrastructure/src/main/java/org/corfudb/infrastructure/management/CompleteGraphAdvisor.java
- infrastructure/src/main/java/org/corfudb/infrastructure/management/failuredetector/ClusterGraph.java
- infrastructure/src/test/java/org/corfudb/infrastructure/management/ClusterGraphTest.java
- infrastructure/src/test/java/org/corfudb/infrastructure/management/CompleteGraphAdvisorTest.java
- infrastructure/src/test/java/org/corfudb/infrastructure/management/NodeStateTestUtil.java
Description:
Failed connection(s) between unresponsive and fully connected node(s) can't be used to determine if a fully connected node is failed. 
If a failed node already added in the unresponsive list then a fully connected node can't be added into the unresponsive list because we cannot believe to the cluster state, based on information about the connection between the failed node and fully connected node. 
Which means the failed node is already in the unresponsive list, we don't need to add the fully connected node also into the unresponsive list.  
> Don't add fully connected node into unresponsive list if there is failed node

- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
Description: retry on trim exceptions for non-tx operations (e.g., remove / put)
Why should this be merged: for non-tx operations we directly throw TrimmedExceptions instead of attempting to rebuild from checkpoint.
> Support retries on TrimmedExceptions for non-tx operations

- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/view/ObjectBuilder.java
- runtime/src/main/java/org/corfudb/runtime/view/OrderedGuidGenerator.java
- runtime/src/main/java/org/corfudb/runtime/view/SnowflakeGuidGenerator.java
- test/src/test/java/org/corfudb/runtime/view/SnowflakeGuidGeneratorTest.java
+ OrderedGUIDGenerator
|-> SnowflakeGuidGenerator which does a best effort generation of
globally unique and ordered ids.
Description:
Why should this be merged: This is a prerequisite for building collections like CorfuQueue.
> SnowflakeGuidFactory: Generates unique Ids with global ordering

- .travis.yml
Upgarde from trust to xenial.
Why should this be merged:  
Xenial has open ssl 2.0.1+ which is required by netty-tcnative
> Upgrade Travis Image

- test/src/test/java/org/corfudb/integration/MemoryFootprintIT.java
Sometimes GC kicks in the middle of the loading in the test causing the after load memory use to show a smaller value than before.
Forcing GC before the test can prevent this discrepancy.
Description:
Related issue(s) (if applicable): #1922
> Make MemoryFootprintIT more reliable by forcing GC first

- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
It seems like its possible that FileChannel::write might not write
the complete source buffer, so subsequent write calls should be
called on the remaining bytes in the buffer.
Why should this be merged: A partial buffer write can result in acknowledging a write, we need to make sure to flush the whole buffer before returning. 
> Flush Write Buffer

- infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java
- infrastructure/src/main/java/org/corfudb/infrastructure/management/FailureDetector.java
- infrastructure/src/main/java/org/corfudb/infrastructure/management/NetworkStretcher.java
- infrastructure/src/main/java/org/corfudb/infrastructure/management/PollReport.java
- infrastructure/src/test/java/org/corfudb/infrastructure/management/FailureDetectorTest.java
- infrastructure/src/test/java/org/corfudb/infrastructure/management/NetworkStretcherTest.java
- it/src/test/java/org/corfudb/universe/scenario/HandOfGodIT.java
- it/src/test/java/org/corfudb/universe/scenario/NodeDownAndPartitionedIT.java
- it/src/test/java/org/corfudb/universe/scenario/RotateLinkFailureIT.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Add NetworkStretcher unit tests.
Co-authored-by: xnull <xrw.null@gmail.com>
Description:
Why should this be merged: Refactors the NetworkStretcher out of FailureDetector since it allows better unit testing.
Related issue(s) (if applicable): #1846
> Refactor Network Stretching logic out of FailureDetector

- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/LogMetadata.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/StreamAddressSpace.java
- test/src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java
- test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java
Description:
Rebuild streams address space from log units assuming data can
be randomly written (i.e., not written in sequential order).
Why should this be merged: This removes the assumption that data is retrieved in order and fixes the issue of false trim marks, which lead to trimmed exceptions, when data is actually present.
> Log Unit Trim Mark Rebuilt Fix

- infrastructure/src/main/java/org/corfudb/infrastructure/management/failuredetector/ClusterGraph.java
- infrastructure/src/test/java/org/corfudb/infrastructure/management/ClusterStateAggregatorTest.java
- infrastructure/src/test/java/org/corfudb/infrastructure/management/ClusterStateCollectorTest.java
- infrastructure/src/test/java/org/corfudb/infrastructure/management/ClusterStateTest.java
- infrastructure/src/test/java/org/corfudb/infrastructure/management/CompleteGraphAdvisorTest.java
- infrastructure/src/test/java/org/corfudb/infrastructure/management/NodeStateTestUtil.java
- infrastructure/src/test/java/org/corfudb/infrastructure/management/PollReportTest.java
- it/src/test/java/org/corfudb/universe/scenario/NodePausedAndPartitionedIT.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/ClusterState.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/NodeState.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/failuredetector/NodeConnectivity.java
- runtime/src/test/java/org/corfudb/protocols/wireprotocol/NodeStateTest.java
- test/src/test/java/org/corfudb/CorfuTestParameters.java
For proper validation of cluster state in failure detector, ensure that the epoch is uniform
Co-authored-by: xnull xrw.null@gmail.com
Description:
Related issue(s) (if applicable): #1846
> Validate epoch in FailureDetector

- runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
- test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
Description: Make ping epoch unaware.
A wrongEpochException means the node is reachable.
Why should this be merged: ForceRemoveNode is not able to find an orchestrator if the only remaining live node is sealed. Making the ping epoch unaware makes it possible to choose an orchestrator and hence trigger the workflow.
Related issue(s) (if applicable): Fixes #1917
> Make ping epoch unaware.

- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLog.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/RestoreRedundancyMergeSegments.java
- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/AddNodeWorkflow.java
- infrastructure/src/test/java/org/corfudb/infrastructure/management/PollReportTest.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/KnownAddressRequest.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/KnownAddressResponse.java
- runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
- runtime/src/main/java/org/corfudb/runtime/clients/LogUnitHandler.java
- test/src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
- test/src/test/java/org/corfudb/runtime/view/StateTransferTest.java
- test/src/test/java/org/corfudb/test/TestUtils.java
Description:
Transfer delta in state transfer.
If transfer range overlaps with previous transfer, overwrite exceptions are thrown and state transfer fails.
Related issue(s) (if applicable): Fixes #1910
> Transfer delta in state transfer.

- test/src/test/java/org/corfudb/integration/AbstractIT.java
- test/src/test/java/org/corfudb/integration/MemoryFootprintIT.java
- test/src/test/java/org/corfudb/integration/SecurityIT.java
- test/src/test/java/org/corfudb/integration/ServerRestartIT.java
- test/src/test/java/org/corfudb/integration/StreamAddressDiscoveryIT.java
- test/src/test/java/org/corfudb/integration/TransactionStreamIT.java
- test/src/test/java/org/corfudb/util/MemoryFootprintMeasurerIT.java
Description:
Shutdown stale runtimes.
Stale threads affect other tests.
> Shutdown stale CorfuRuntimes in ITs.

- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServerCache.java
- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/ILogData.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/MultipleReadRequest.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/ReadRequest.java
- runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java
- runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/ChainReplicationProtocol.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/IReplicationProtocol.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocol.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
- test/src/test/java/org/corfudb/infrastructure/LogUnitCacheTest.java
- test/src/test/java/org/corfudb/infrastructure/LogUnitServerAssertions.java
- test/src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java
- test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java
- For batch read scenarios like state transfer and fast loader, caching
the read results on log unit server would pollute the cache. This patch
adds the capability of not caching the read results in these situations.
- Separates log unit cache into a new class for more readability and
testability.
Improve performance on log unit server by preventing cache pollution.
Related issue(s) (if applicable): #1841
> Introducing non-cacheable reads on log unit server.

- pom.xml
Junit5 can provide additional powerful features https://developer.ibm.com/dwblog/2017/top-five-reasons-to-use-junit-5-java/
At least https://www.baeldung.com/junit-5-repeated-test
Also, we have some unit tests written for junit5, they will be added into Corfu very soon 
Description:
> Migrate to a new version of Junit (Junit5)

- infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java
- runtime/src/main/java/org/corfudb/util/result/Result.java
Allows managing exceptions and operation results in a better way,
makes the code more resilient and simple
Description:
> Bring Operation Result wrapper

- runtime/src/main/java/org/corfudb/runtime/view/SequencerView.java
- test/src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
- test/src/test/java/org/corfudb/runtime/view/SequencerViewTest.java
Description:
Retry getStreamAddressSpace if client disconnected from cluster, stamped with an incorrect epoch or server not ready.
We should not expose exceptions to the client and retry until systemDownHandler is invoked (if registered) or indefinitely.
Added a test ```checkStreamAddressSpaceAcrossEpochs``` to check streamAddressSpace accross epochs.
> Retry getStreamAddressSpace if disconnected from cluster.

- runtime/src/main/java/org/corfudb/protocols/logprotocol/ISMRGarbageInfo.java
- runtime/src/main/java/org/corfudb/protocols/logprotocol/LogEntry.java
- runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiObjectSMREntryGarbageInfo.java
- runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiSMREntryGarbageInfo.java
- runtime/src/main/java/org/corfudb/protocols/logprotocol/SMREntryGarbageInfo.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/DataType.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
- runtime/src/test/java/org/corfudb/protocols/logprotocol/LogEntryTest.java
- runtime/src/test/java/org/corfudb/protocols/logprotocol/MultiObjectSMREntryGarbageInfoTest.java
- runtime/src/test/java/org/corfudb/protocols/wireprotocol/LogDataTest.java
Add data structure to represent which SMREntries in the AddressSpaceView are identified as garbage. 
Description:
The data structure would be used by the runtime to send garbage information to the LogUnit servers.
> Add SMREntry garbage pointer types

- common/pom.xml
- common/src/main/java/org/corfudb/common/result/Result.java
- infrastructure/pom.xml
- infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java
- pom.xml
A `common` Corfu module contains common and generic functionality which can be used by any other module.
It should be used to keep classes like:
1. Utility classes, like DateUtils, UUIDUtils, JsonUtils, CFUtils, Result and so on.
2. Common communication primitives, like netty client handler specific to Corfu
3. Common enums used on infrastructure and client side.
4. Common classes used by corfu-client-api and corfu-runtime 
and so on.
Description:
> Creating a common corfu module

- runtime/src/main/java/org/corfudb/runtime/collections/CorfuCounter.java
- runtime/src/main/java/org/corfudb/runtime/view/CorfuGuidGenerator.java
- test/src/test/java/org/corfudb/runtime/view/CorfuGuidGeneratorTest.java
A simple counter within the Sequence server that issues
ordered guids (OGUIDs) tokens by simply incrementing a counter
and shipping it with the epoch.
If the Sequence server restarts or regresses, the epoch will tick up
to guarantee ordering and global uniqueness.
Description:
> CorfuGuidGenerator: Use SequencerServer to make unique ordered tokens

- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServerCache.java
- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/ILogData.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/MultipleReadRequest.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/ReadRequest.java
- runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java
- runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/ChainReplicationProtocol.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/IReplicationProtocol.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocol.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
- test/src/test/java/org/corfudb/infrastructure/LogUnitCacheTest.java
- test/src/test/java/org/corfudb/infrastructure/LogUnitServerAssertions.java
- test/src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java
- test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java
- For batch read scenarios like state transfer and fast loader, caching
the read results on log unit server would pollute the cache. This patch
adds the capability of not caching the read results in these situations.
- Separates log unit cache into a new cache class for more readability
and testability.
> Introducing non-cacheable reads on log unit server. (#1901)

- infrastructure/pom.xml
- it/src/main/java/org/corfudb/universe/node/server/docker/DockerCorfuServer.java
Description:
We need to create a separate docker image for universe testing because the docker hub image might collide with the locally cached one. It makes it hard to understand what image is exactly used for universe testing. 
> Create a separate docker image for universe solely for testing

- runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
- test/src/test/java/org/corfudb/integration/ServerRestartIT.java
- test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
Introduce a fix on how to resolve the checkpoint for a given stream
based on the fact that multiple checkpointers could be running at
the same time.
> Fix to Concurrent Checkpointers

- runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java
Modify log levels for trimmed messages that are not really critical until they lead to a TAE which is already logged as an error. It is common for trim message "warnings" to happen once before a valid checkpoint is loaded.
> Change Log Level for Trim messages in Stream View

- runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
- test/src/test/java/org/corfudb/runtime/view/LayoutManagementViewTest.java
Description:
In RemoveNode workflow, when proposing a new layout to be committed, a
server that was marked unresponsive might be elected as the new primary
sequencer, which is incorrect. This patch fixes this issue.
Related issue(s) (if applicable): #1992
> RemoveNode: prevent unresponsive node elected as new primary sequencer.

- runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
- test/src/test/java/org/corfudb/runtime/view/LayoutManagementViewTest.java
Porting #1993 
In RemoveNode workflow, when proposing a new layout to be committed, a
server that was marked unresponsive might be elected as the new primary
sequencer, which is incorrect. This patch fixes this issue.
> [Corfu-0.2.3] RemoveNode: prevent unresponsive node elected as new primary sequencer.

- infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java
- runtime/src/main/java/org/corfudb/runtime/BootstrapUtil.java
- runtime/src/main/java/org/corfudb/runtime/RebootUtil.java
- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
- runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java
- runtime/src/main/java/org/corfudb/runtime/view/replication/NeverHoleFillPolicy.java
- runtime/src/main/java/org/corfudb/util/Sleep.java
- runtime/src/main/java/org/corfudb/util/retry/ExponentialBackoffRetry.java
- runtime/src/main/java/org/corfudb/util/retry/IntervalRetry.java
- test/src/test/java/org/corfudb/integration/AbstractIT.java
- test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
- test/src/test/java/org/corfudb/integration/TransactionStreamIT.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
- test/src/test/java/org/corfudb/runtime/view/stream/AbstractStreamViewTest.java
org.corfudb.util.Sleep:
- doesn't provide any advantages over TimeUnit.
- it throws an UnrecoverableCorfuInterruptedError which extends `java.lang.Error` - which is error prone and very bad practice.
- A lot of useless boilerplate (entire functionality already implemented in TimeUnit, `Sleep` just copy\paste some methods from TimeUnit).
- it brings additional complexity and confusion
Description:
> org.corfudb.util.Sleep refactoring/deprecation

- infrastructure/src/main/java/org/corfudb/infrastructure/BatchProcessor.java
- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/LogMetadata.java
- infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/StreamAddressSpace.java
- test/src/test/java/org/corfudb/integration/ServerRestartIT.java
- test/src/test/java/org/corfudb/integration/StreamAddressDiscoveryIT.java
- test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
Simplifying stream address rebuilt on log unit restart. This change also considers the case of multiple checkpoints running at the same time for address space rebuilt.
> Build stream trim mark from checkpoint

- checks.xml
- pom.xml
I notice a very weird error, I suspect `checkstyle` plugin doesn't work if a module contains source code and proto files. 
Since we are going to bring `corfu-client-api` it's time to update checkstyle.
The current version of checkstyle is very old(4 years), it's good to update it.
Description:
> Checkstyle update

- infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
Print startup message in the log also. Right now we print the message only in the console and it can be found in tanuki.log. In our logs we have lack of information when Corfu was started.
Description:
> Print startup message in logs

- runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java
- test/src/test/java/org/corfudb/runtime/collections/CorfuTableTest.java
- test/src/test/java/org/corfudb/runtime/collections/StringIndexer.java
This patch simplifies the logic associated with secondary index
extraction. It also makes failures that arise due to improper index
function implementation more explicit.
Description:
> Revamp secondary index logic

- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/java/org/corfudb/util/MetricsUtils.java
- test/src/test/java/org/corfudb/integration/TransactionStreamIT.java
- test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
Added weight(i.e. in-memory size) based eviction for the
AddressSpaceView cache.
Why should this be merged: Makes it easier to tune the cache for some workloads 
Related issue(s) (if applicable): #1980
> Memory Size Based Eviction

- infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java
- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
Description:
The way how we invalidate (update) the layout right now is pretty inconvenient and completely synchronous (if you want to get updated layout).
This change enables us to invalidate layout asynchronously.
P.S. the old way also still working
> Invalidate layout returns CompletableFuture 

- infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java
Description:
Railure detector generates a lot of messages in the log: `Cannot initiate new failure detection task...`
which is not useful. So, lowered to trace level
> Decrease log level for RemoteMonitoringService failure detector task

- runtime/src/main/java/org/corfudb/protocols/logprotocol/CheckpointEntry.java
- runtime/src/main/java/org/corfudb/protocols/logprotocol/ISMRConsumable.java
- runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiObjectSMREntry.java
- runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiSMREntry.java
- runtime/src/main/java/org/corfudb/protocols/logprotocol/SMREntry.java
- runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
- runtime/src/main/java/org/corfudb/runtime/collections/FGMap.java
- runtime/src/main/java/org/corfudb/runtime/collections/ISMRMap.java
- runtime/src/main/java/org/corfudb/runtime/collections/ISMRObject.java
- runtime/src/main/java/org/corfudb/runtime/collections/SMRMap.java
- runtime/src/main/java/org/corfudb/runtime/object/AbstractCorfuWrapper.java
- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileWrapperBuilder.java
- runtime/src/main/java/org/corfudb/runtime/object/ICorfuSMRProxyInternal.java
- runtime/src/main/java/org/corfudb/runtime/object/ISMRStream.java
- runtime/src/main/java/org/corfudb/runtime/object/StreamViewSMRAdapter.java
- runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteSetSMRStream.java
- test/src/test/java/org/corfudb/runtime/object/CompileProxyTest.java
Description:
Un-deprecate SMR layer, VLO clean up
> Un-deprecate SMR layer, VLO clean up

- infrastructure/src/main/java/org/corfudb/infrastructure/LocalMonitoringService.java
Description:
`sequencerMetricsHolder` can potentially return null. Added predefined value in a constructor 
Related issue(s) (if applicable): #2035
> Prevent NPE in LocalMonitoringService

- runtime/src/main/java/org/corfudb/runtime/collections/CorfuQueue.java
- runtime/src/main/java/org/corfudb/runtime/view/CorfuGuidGenerator.java
- test/src/test/java/org/corfudb/runtime/concurrent/CorfuQueueTxTest.java
We don't allow nesting transactions of different types.
To get around this,
+ use parent transaction type if in one.
+ Separate test cases to validate different transaction types.
+ In CorfuQueue, remove comment that says getEntryId() and getOrdering() should only be used for testing since they are valid uses of the API.
Related issue(s) (if applicable): #2038
> CorfuGuidGenerator: Use Parent TransactionType if nested

- infrastructure/src/main/resources/logback.prod.xml
Description:
Average compression ration for our logs is 1:20.
Change max file size to make average gzipped logs size equals 35mb.
Math:
When log file comes 700mb it gets compressed to ~35-40mb
We can have up to 30 compressed log files
Max total disk space consumed by gzipped logs: 40*30 = 1.2GB
And one, not compressed log file: 700mb.
Total number of uncompressed logs: 700 * 30 + 700 = 22GB.
Previous parameters for a total number of uncompressed logs: 100*30 + 100 = 3GB which is ~ 9 hours in a prod environment.
The diff: 22GB - 3GB = 18GB which is ~ 54 hours in a prod environment.
New settings, total time: ~70 hours. 
P.S. if we get rid of log messages:
1. `Trying connection to layout server...`
2. `log write...`
It should reduce logs about 60-80%.
Then we can count on ~ 300-500 hours of …
> Console logging compression

- runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
Improved Logging
Added extra stats(i.e. in-memory size, CP size in bytes) logging
for the checkpoint writer.
Why should this be merged: Porting 6d13acee7fbaa59a17a34c6a2245618c844b090c from master
> Improved CheckpointWriter Logging

- infrastructure/src/main/java/org/corfudb/infrastructure/BatchProcessor.java
Description:
Descrease log level for OverwriteException
> Decrease log level for OverwriteException

- infrastructure/src/main/java/org/corfudb/infrastructure/BatchProcessor.java
Description:
Descrease log level for OverwriteException 2
> Decrease log level for OverwriteException 0.2.3

- runtime/src/main/java/org/corfudb/runtime/exceptions/NoRollbackException.java
- runtime/src/main/java/org/corfudb/runtime/object/StreamViewSMRAdapter.java
- runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java
- runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteSetSMRStream.java
Description:
VLO clean up: return an empty list instead of null
> VLO clean up: return an empty list instead of null

- infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java
- infrastructure/src/main/java/org/corfudb/infrastructure/management/ClusterStateCollector.java
- infrastructure/src/main/java/org/corfudb/infrastructure/management/FailureDetector.java
- infrastructure/src/main/java/org/corfudb/infrastructure/management/PollReport.java
- infrastructure/src/test/java/org/corfudb/infrastructure/CorfuAbstractServerTest.java
- infrastructure/src/test/java/org/corfudb/infrastructure/management/ClusterStateCollectorTest.java
- infrastructure/src/test/java/org/corfudb/infrastructure/management/ClusterStateTest.java
- infrastructure/src/test/java/org/corfudb/infrastructure/management/PollReportTest.java
- it/src/test/java/org/corfudb/universe/scenario/ClusterEdgeCases.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/ClusterState.java
Rather than relying on a responsive server set, base the decision
on the latest committed layout and the highest WrongEpochException.
Description:
> Change how we detect unfilled slots/registers

- infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java
- runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java
- runtime/src/main/java/org/corfudb/recovery/RecoveryUtils.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
- runtime/src/main/java/org/corfudb/runtime/view/ReadOptions.java
- runtime/src/main/java/org/corfudb/runtime/view/StreamOptions.java
- runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
- test/src/test/java/org/corfudb/runtime/view/StreamViewTest.java
- test/src/test/java/org/corfudb/runtime/view/stream/AbstractStreamViewTest.java
Allow certain streams to not be cached.
Why should this be merged: Some access patterns are pure consumers, once a stream entry is read it is no longer needed, if its cached it can pollute the AddressSpace cache and compete with transaction workloads ( that need the cache).   
> Non-Cachable Streams

- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServerCache.java
Instead of converting the conflictParams to strings, its better to
keep them as byte arrays, its more compact.
Why should this be merged: Reduces the sequencer's memory footprint by ~4x
> Reduced The Sequencer's Memory Overhead

- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServerCache.java
Porting from master
Reduced The Sequencer's Memory Overhead
Instead of converting the conflictParams to strings, its better to
keep them as byte arrays, its more compact.
commit bb154e5d0cab965bd0f174896107892ee1c1799d
> Seq mem improvement

- runtime/src/main/java/org/corfudb/protocols/wireprotocol/TokenType.java
- runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
- test/src/test/java/org/corfudb/runtime/object/transactions/AbstractTransactionContextTest.java
- test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTransactionContextTest.java
- On OverwriteException, StreamsView::append will grab a new token and
retry, but it was still using the conflictKey/conflictStream info from
the stale tokeResponse. In case of transactions and there is a conflict
when we try to re-requst the token, the stale conflictKey/conflictStream
is empty. This patch directly uses the new token and retry.
- Some clean up in StreamsView and TokenType.
Related issue(s) (if applicable): #2042
> Do not use stale conflictKey/conflictStream on overwritten for TXNs.

- runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java
- test/src/test/java/org/corfudb/runtime/view/StreamViewTest.java
The transaction stream it not checkpoint aware, thus, we need to ensure
that address space discovery mechanism takes into account.
Description:
> Port: Change how we deal with the transaction stream

- runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java
- test/src/test/java/org/corfudb/runtime/view/StreamViewTest.java
The transaction stream it not checkpoint aware, thus, we need to ensure
that address space discovery mechanism takes into account.
Description:
> Change how we deal with the transaction stream

- runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java
- test/src/test/java/org/corfudb/integration/StreamAddressDiscoveryIT.java
- test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
Whenever the last address of a stream is a hole (right before the checkpointer is triggered)
We build the checkpoint start log address based on the wrong start of the stream,
this is because we discard holes and hence set the start to the previous DATA entry.
This will diverge from the state kept by the sequencer for this stream on trims (trim mark).
> MultiCheckpointWriter Bug Fix

- runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java
- test/src/test/java/org/corfudb/integration/StreamAddressDiscoveryIT.java
- test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
Whenever the last address of a stream is a hole (right before the checkpointer is triggered)
We build the checkpoint start log address based on the wrong snapshot of the stream,
this is because we discard holes and hence set the start to the previous DATA entry.
This will diverge from the state kept by the sequencer for this stream on trims (trim mark).
> MultiCheckpointWriter Bug Fix - 0.2.3

- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
Added a parameter to configure the cache's concurrency level.
Why should this be merged: Ability to tune the cache's performance
> Cache Concurrency

- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
- test/src/test/java/org/corfudb/runtime/collections/CorfuMapTest.java
- test/src/test/java/org/corfudb/runtime/collections/SMRMapTest.java
- test/src/test/java/org/corfudb/runtime/view/QuorumReplicationStreamViewTest.java
- test/src/test/java/org/corfudb/runtime/view/StreamViewTest.java
Only one variable is needed to toggle backpointers, so I removed
backpointersDisabled for followBackpointersEnabled.
Why should this be merged: Removes a redundant and confusing option.
> Remove backpointersDisabled

- runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java
Description:
Change log level from WARN to INFO and do not print stack trace, as this exception
is properly handled by upper layers and accordingly printed if leading to an actual exception.
> TrimmedException log level message

- runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java
Change log level from WARN to INFO and do not print stack trace, as this exception
is properly handled by upper layers and accordingly printed if leading to an actual exception.
Port to corfu-0.2.3
> TrimmedException log level message - 0.2.3

- infrastructure/src/main/java/org/corfudb/infrastructure/LayoutServer.java
- test/src/test/java/org/corfudb/infrastructure/LayoutServerAssertions.java
- test/src/test/java/org/corfudb/infrastructure/LayoutServerTest.java
Within Paxos, avoid relying on mutable state (server epoch to be more
precise), since this can lead to wrong data being persisted and agreed
upon.
Description:
> Do not depend on mutable state for Paxos

- runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
When client sending keep alive message, it is possible that the channel
is still not established, which causes a NullPointerException. This patch
adds an additional check to fix NPE.
Why should this be merged: Fix NPE
Related issue(s) (if applicable):
> Fix Netty channel keep alive NPE.

- runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
Porting #2083
When client sending keep alive message, it is possible that the channel
is still not established, which causes a NullPointerException. This patch
adds an additional check to fix NPE.
Why should this be merged: Fix NPE
Related issue(s) (if applicable): #2083
> [Corfu-0.2.3] Porting: Fix Netty channel keep alive NPE

- infrastructure/src/main/java/org/corfudb/infrastructure/BaseServer.java
- infrastructure/src/main/java/org/corfudb/infrastructure/LayoutServer.java
- it/src/test/java/org/corfudb/universe/scenario/ClusterEdgeCases.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
- runtime/src/main/java/org/corfudb/runtime/clients/BaseClient.java
- runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
- runtime/src/main/java/org/corfudb/runtime/view/SealServersHelper.java
- test/src/test/java/org/corfudb/infrastructure/LayoutServerTest.java
- test/src/test/java/org/corfudb/runtime/clients/TestClientRouterTest.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
The set epoch operation is in fact a seal operation. Set epoch
might imply arbitrarily setting an epoch, which is not the case.
Why should this be merged: Improves the nomenclature
> Rename SET_EPOCH to SEAL

- infrastructure/pom.xml
- infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
- test/pom.xml
Jansi has to extract libjansi-64.so native library in order work
properly, which can cause security concerns in production. There is
really no good reason for Corfu to depend on Jansi in production code.
Description:
> Make Jansi a test-only dependancy

- runtime/src/main/java/org/corfudb/protocols/logprotocol/LogEntry.java
- runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiObjectSMREntry.java
- runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiSMREntry.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/ILogData.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/IMetadata.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
- runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java
- runtime/src/main/java/org/corfudb/runtime/object/StreamViewSMRAdapter.java
- runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
- LogEntry is the payload of LogData, however LogEntry also contains a
reference to LogData, which undermines readability and is error prone.
This is also unnecessary because the only reason to have this backward
dependency is LogEntry needs to know about the global address inside
LogData, which is consumed by VLO. This patch removed this dependency
by setting globalAddress directly.
- This is also a prerequisite a following patch that unifies SMREntry, MultiSMREntry
and MultiObjectSMREntry.
Related issue(s) (if applicable): #2080
> ILogData: Get rid of backward dependency on LogEntry.

- runtime/src/main/java/org/corfudb/protocols/wireprotocol/TokenResponse.java
Change it to a more sensible value byte[]{ 0 }.
Description:
> Change default NO_CONFLICT_KEY constant -- Port

- infrastructure/pom.xml
- infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
- test/pom.xml
Jansi has to extract libjansi-64.so native library in order work
properly, which can cause security concerns in production. There is
really no good reason for Corfu to depend on Jansi in production code.
Description:
> Make Jansi a test-only dependancy (#2091) -- Port

- infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
- runtime/src/main/java/org/corfudb/runtime/clients/LogUnitHandler.java
Why should this be merged: if we receive a DataCorruptionException on the client side, we are unable to track the actual address that led to this exception.
> Add logging for Data Corruption Exceptions

- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/TokenResponse.java
- runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/MultiCheckpointWriter.java
- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
- runtime/src/main/java/org/corfudb/runtime/view/SequencerView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
- test/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java
- test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
- test/src/test/java/org/corfudb/integration/CmdletIT.java
- test/src/test/java/org/corfudb/integration/ServerRestartIT.java
- test/src/test/java/org/corfudb/integration/StreamAddressDiscoveryIT.java
- test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
- test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
- test/src/test/java/org/corfudb/runtime/clients/SequencerHandlerTest.java
- test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTransactionContextTest.java
- test/src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
- test/src/test/java/org/corfudb/runtime/view/LayoutViewTest.java
- test/src/test/java/org/corfudb/runtime/view/SequencerViewTest.java
- test/src/test/java/org/corfudb/runtime/view/StateTransferTest.java
- test/src/test/java/org/corfudb/runtime/view/StreamViewTest.java
Description:
Return snapshot address at the time of checkpoint instead of stream tail address.
Why should this be merged: The checkpointing task will limit the trim task for those cases in which a stream has not observed updates for a while. In other words, the checkpointWriter token could remain the same for multiple checkpoint cycles if the tail has not progressed, preventing trim from happening. In this change, we correctly retrieve the actual snapshot as the checkpoint token and set the start log address as the stream's latest observed tail.
> Correct CheckpointWriter return Token

- infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
- runtime/src/main/java/org/corfudb/protocols/wireprotocol/TokenResponse.java
- runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
- runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
- runtime/src/main/java/org/corfudb/runtime/MultiCheckpointWriter.java
- runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
- runtime/src/main/java/org/corfudb/runtime/view/SequencerView.java
- runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
- runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
- test/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java
- test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
- test/src/test/java/org/corfudb/integration/CmdletIT.java
- test/src/test/java/org/corfudb/integration/ServerRestartIT.java
- test/src/test/java/org/corfudb/integration/StreamAddressDiscoveryIT.java
- test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
- test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
- test/src/test/java/org/corfudb/runtime/clients/SequencerHandlerTest.java
- test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTransactionContextTest.java
- test/src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
- test/src/test/java/org/corfudb/runtime/view/LayoutViewTest.java
- test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
- test/src/test/java/org/corfudb/runtime/view/SequencerViewTest.java
- test/src/test/java/org/corfudb/runtime/view/StateTransferTest.java
- test/src/test/java/org/corfudb/runtime/view/StreamViewTest.java
Description: Return snapshot address at the time of checkpoint instead of stream tail address.
> [0.2.3] Correct CheckpointWriter return Token

- runtime/src/main/java/org/corfudb/protocols/logprotocol/SMRLogEntry.java
- runtime/src/main/java/org/corfudb/protocols/logprotocol/SMRRecord.java
Add trimmed fields in SMRRecord to indicate being trimmed by LogUnit servers.
> Add trimmed fields in SMRRecord

- infrastructure/src/main/resources/logback.prod.xml
Description:
Asynchronous appender is very helpful in case of a slow disk (critical for us) or other cases (see https://logback.qos.ch/manual/appenders.html#AsyncAppender).
> Logback: migrate to an asynchronous appender

- runtime/src/main/java/org/corfudb/protocols/logprotocol/SMRLogEntry.java
- runtime/src/main/java/org/corfudb/protocols/logprotocol/SMRRecord.java
- runtime/src/main/java/org/corfudb/protocols/logprotocol/SMRRecordLocator.java
- runtime/src/test/java/org/corfudb/protocols/logprotocol/SMRRecordLocatorTest.java
Description:
SMRRecordLocator is used to denote the location of a SMRRecord in the global SpaceAddressView.
SMRRecordLocator will be used by GC to denote the where the garbage is in the global SpaceAddressView. It could also be used by runtime to retrieve data from LogUnit.
> Add SMRRecordLocator

- runtime/src/main/java/org/corfudb/protocols/logprotocol/SMRRecord.java
- runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java
- runtime/src/main/java/org/corfudb/runtime/collections/FGMap.java
- runtime/src/main/java/org/corfudb/runtime/collections/ILocatorStore.java
- runtime/src/main/java/org/corfudb/runtime/collections/ISMRMap.java
- runtime/src/main/java/org/corfudb/runtime/collections/MapLocatorStore.java
- runtime/src/main/java/org/corfudb/runtime/collections/SMRMap.java
- runtime/src/main/java/org/corfudb/runtime/object/StreamViewSMRAdapter.java
- test/src/test/java/org/corfudb/integration/LogSizeQuotaIT.java
- test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
Add a locator field into SMREntry such that the consumer of the SMREntry, i.e. the Object Layer, is able to identify the location of garbage. 
This patch is stacked atop another PR: https://github.com/CorfuDB/CorfuDB/pull/1911 and https://github.com/CorfuDB/CorfuDB/pull/2014.
> Add locator field into SMREntry

- runtime/src/main/java/org/corfudb/protocols/logprotocol/SMRRecord.java
- runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java
- runtime/src/main/java/org/corfudb/runtime/collections/FGMap.java
- runtime/src/main/java/org/corfudb/runtime/collections/ILocatorStore.java
- runtime/src/main/java/org/corfudb/runtime/collections/ISMRMap.java
- runtime/src/main/java/org/corfudb/runtime/collections/MapLocatorStore.java
- runtime/src/main/java/org/corfudb/runtime/collections/SMRMap.java
- runtime/src/main/java/org/corfudb/runtime/object/StreamViewSMRAdapter.java
- test/src/test/java/org/corfudb/integration/LogSizeQuotaIT.java
- test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
Add a locator field into SMREntry such that the consumer of the SMREntry, i.e. the Object Layer, is able to identify the location of garbage.
Related issue(s) (if applicable): #
This patch is stacked atop another PR: #1911 and #2014.
> Add locator field into SMRRecord

- it/src/main/java/org/corfudb/universe/group/Group.java
- it/src/main/java/org/corfudb/universe/group/cluster/AbstractCluster.java
- it/src/main/java/org/corfudb/universe/group/cluster/AbstractCorfuCluster.java
- it/src/main/java/org/corfudb/universe/group/cluster/AbstractSupportCluster.java
- it/src/main/java/org/corfudb/universe/group/cluster/Cluster.java
- it/src/main/java/org/corfudb/universe/group/cluster/CorfuClusterParams.java
- it/src/main/java/org/corfudb/universe/group/cluster/SupportClusterParams.java
- it/src/main/java/org/corfudb/universe/group/cluster/docker/DockerCorfuCluster.java
- it/src/main/java/org/corfudb/universe/group/cluster/docker/DockerSupportCluster.java
- it/src/main/java/org/corfudb/universe/group/cluster/vm/VmCorfuCluster.java
- it/src/main/java/org/corfudb/universe/node/Node.java
- it/src/main/java/org/corfudb/universe/node/client/ClientParams.java
- it/src/main/java/org/corfudb/universe/node/client/LocalCorfuClient.java
- it/src/main/java/org/corfudb/universe/node/server/AbstractCorfuServer.java
- it/src/main/java/org/corfudb/universe/node/server/SupportServer.java
- it/src/main/java/org/corfudb/universe/node/server/SupportServerParams.java
- it/src/main/java/org/corfudb/universe/node/server/docker/DockerCorfuServer.java
- it/src/main/java/org/corfudb/universe/node/server/docker/DockerSupportServer.java
- it/src/main/java/org/corfudb/universe/node/server/vm/VmCorfuServer.java
- it/src/main/java/org/corfudb/universe/universe/AbstractUniverse.java
- it/src/main/java/org/corfudb/universe/universe/docker/DockerUniverse.java
- it/src/main/java/org/corfudb/universe/universe/vm/VmUniverse.java
Augment the Universe Framework to support additional cluster types that
can be used for deploying support components, such as monitoring,
tracing and metrics.
Description:
> Add an additional cluster type to Universe
