CorfuDB/CorfuDB

src/main/java/org/corfudb/infrastructure/AbstractNettyServer.java
src/main/java/org/corfudb/runtime/WrongEpochException.java
src/main/java/org/corfudb/runtime/protocols/NettyRPCChannelInboundHandlerAdapter.java
src/main/java/org/corfudb/runtime/view/ICorfuDBInstance.java
src/main/java/org/corfudb/runtime/view/LocalCorfuDBInstance.java
src/main/java/org/corfudb/runtime/view/NewStreamingSequencer.java
src/main/java/org/corfudb/runtime/view/StreamAddressSpace.java
src/test/java/org/corfudb/runtime/view/ICorfuDBInstanceTest.java
src/test/java/org/corfudb/runtime/view/LocalCorfuDBInstanceTest.java

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/59)

Fix bug in epoch change code

---

README.md

References was pointing to a 404 -- fixed.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/68)

Fix "references" pointer

---

README.md
src/main/java/org/corfudb/cmdlets/corfu_stream.java
src/main/java/org/corfudb/runtime/CorfuRuntime.java
src/test/java/org/corfudb/runtime/collections/SMRMapTest.java

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/74)

updated readme.

---

.travis.yml
.travis_scripts/setup_env.sh

This pull request would add build numbers based on builds in Travis-CI
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/76)

Support build numbers based on Travis-CI builds

---

.travis_scripts/mvnrepo.sh
.travis_scripts/push_deb.sh

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/77)

Fix bug during deb build and don't build twice in mvnrepo.

---

src/deb/control/postinst

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/79)

More fixes to broken debian package

---

.travis_scripts/mvnrepo.sh
.travis_scripts/push_deb.sh
README.md
src/main/java/org/corfudb/cmdlets/corfu_as.java
src/main/java/org/corfudb/cmdlets/corfu_logunit.java
src/main/java/org/corfudb/protocols/wireprotocol/LogUnitReadResponseMsg.java
src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
src/main/java/org/corfudb/runtime/view/AbstractReplicationView.java
src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
src/main/java/org/corfudb/runtime/view/ChainReplicationView.java
src/main/java/org/corfudb/runtime/view/StreamView.java
src/main/java/org/corfudb/runtime/view/StreamsView.java
src/test/java/org/corfudb/runtime/clients/LogUnitClientTest.java
src/test/java/org/corfudb/runtime/view/ChainReplicationViewTest.java

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/81)

Backpointers and Debian fixes

---

.travis_scripts/mvnrepo.sh
.travis_scripts/setup_env.sh
src/main/java/org/corfudb/infrastructure/CorfuServer.java
src/main/java/org/corfudb/runtime/view/StreamsView.java
src/main/java/org/corfudb/util/Version.java

The maven repository was not getting the project version variable.
This fixes it by creating a file.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/82)

Fix maven repository

---

src/main/java/org/corfudb/infrastructure/LogUnitServer.java

Currently the log unit eviction has issues due to unsafe accesses on the file channel.
This patch adds synchronization around the channel to fix it.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/84)

Synchronize the file channel

---

.travis.yml
pom.xml
src/main/java/org/corfudb/infrastructure/LayoutServer.java
src/main/java/org/corfudb/infrastructure/LogUnitServer.java
src/main/java/org/corfudb/protocols/wireprotocol/LogUnitPayloadMsg.java
src/main/java/org/corfudb/runtime/view/Layout.java
src/test/java/org/corfudb/infrastructure/AbstractServerTest.java
src/test/java/org/corfudb/infrastructure/LayoutServerAssertions.java
src/test/java/org/corfudb/infrastructure/LayoutServerTest.java
src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java
src/test/java/org/corfudb/infrastructure/SequencerServerTest.java

This server persists data stored in the layout server, reading
from a json file at startup.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/87)

Persist layout server data.

---

src/main/java/org/corfudb/infrastructure/LogUnitServer.java

This comment describes how the log unit operates.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/89)

Add comments describing log unit operation.

---

src/main/java/org/corfudb/runtime/object/CorfuSMRObjectProxy.java
src/test/java/org/corfudb/AbstractCorfuTest.java

The system classloader may cause some issues with spring frameworks.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/92)

use a proxy classloader instead of system classloader

---

pom.xml
src/main/java/org/corfudb/runtime/object/CorfuSMRObjectProxy.java
src/main/java/org/corfudb/util/serializer/JSONSerializer.java
src/main/java/org/corfudb/util/serializer/Serializers.java

This patch adds JSON serialization support and makes JSON the default serialization method
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/93)

Support JSON

---

README.md
src/main/java/org/corfudb/cmdlets/corfu_layouts.java
src/main/java/org/corfudb/runtime/object/Accessor.java
src/main/java/org/corfudb/runtime/object/CorfuSMRObjectProxy.java
src/main/java/org/corfudb/runtime/object/Instrumented.java
src/main/java/org/corfudb/runtime/object/InstrumentedCorfuObject.java
src/main/java/org/corfudb/runtime/object/Mutator.java
src/main/java/org/corfudb/runtime/object/MutatorAccessor.java
src/main/java/org/corfudb/util/Utils.java
src/main/java/org/corfudb/util/serializer/JSONSerializer.java

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/96)

Add striping UI and some fixes to the object proxy.

---

src/main/java/org/corfudb/infrastructure/NettyServerRouter.java
src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsg.java
src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
src/main/java/org/corfudb/util/serializer/ISerializer.java

Fixes #103, which is an issue with buffers being released during exceptions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/104)

Fix buffer release during exceptions

---

src/main/java/org/corfudb/runtime/view/ChainReplicationView.java

In chain replication, the serialization code was placed inside the loop, which caused serialization to occur multiple times.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/108)

Fix a bug where serialization occurs multiple times

---

src/main/java/org/corfudb/runtime/view/ChainReplicationView.java
src/main/java/org/corfudb/util/AutoCloseableByteBuf.java

An autocloseablebytebuf implements AutoClosable, which will release a ByteBuf when it exits a try-catch block.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/109)

Implement AutoCloseableByteBuf, a wrapper around bytebuf which uses the autocloseable interface

---

src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsg.java
src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
src/test/java/org/corfudb/runtime/clients/TestClientRouter.java

This patch fixes a bug with the outstanding request table and 
makes some small improvements to the message format
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/113)

Fix outstanding request table, small changes to message format

---

src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java

Fixes #117
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/119)

Fix the wrong server used by the test.

---

.travis.yml
src/main/java/org/corfudb/runtime/collections/FGMap.java
src/main/java/org/corfudb/runtime/collections/SMRMap.java
src/main/java/org/corfudb/runtime/exceptions/TransactionAbortedException.java
src/main/java/org/corfudb/runtime/object/CorfuSMRObjectProxy.java
src/main/java/org/corfudb/runtime/object/ICorfuSMRObject.java
src/main/java/org/corfudb/runtime/object/MutatorAccessor.java
src/main/java/org/corfudb/runtime/object/StaticMappingObject.java
src/main/java/org/corfudb/runtime/object/TransactionalContext.java
src/main/java/org/corfudb/runtime/view/ObjectsView.java
src/main/java/org/corfudb/util/Utils.java
src/test/java/org/corfudb/runtime/collections/FGMapTest.java
src/test/java/org/corfudb/runtime/collections/SMRMapTest.java

This is an implementation of a simple fine grained map. It divides the keyspace into several partitions using the hashCode of the key. Some operations (clear, keySet, size, etc) require contacting all partitions and therefore use a transaction.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/120)

A simple fine-grained map

---

src/main/java/org/corfudb/protocols/logprotocol/TXEntry.java
src/main/java/org/corfudb/runtime/object/CorfuSMRObjectProxy.java
src/test/java/org/corfudb/AbstractCorfuTest.java
src/test/java/org/corfudb/runtime/collections/FGMapTest.java
src/test/java/org/corfudb/runtime/collections/SMRMapTest.java

This adds data about abort rates and a small framework for showing additional statistics calculated during unit tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/121)

Add a framework to show abort rates

---

src/main/java/org/corfudb/runtime/collections/FGMap.java
src/main/java/org/corfudb/runtime/object/CorfuSMRObjectProxy.java
src/main/java/org/corfudb/runtime/object/ICorfuSMRObject.java
src/main/java/org/corfudb/runtime/object/TransactionalMethod.java
src/main/java/org/corfudb/runtime/view/ObjectsView.java
src/main/java/org/corfudb/util/ReflectionUtils.java
src/main/java/org/corfudb/util/serializer/JSONSerializer.java

Simplify the SMRProxy interface by eliminating inner classes and dynamic field definitions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/122)

Simplify the SMRProxy interface

---

src/main/java/org/corfudb/infrastructure/LogUnitServer.java

To prevent against concurrent JVMs from using the same logfiles, we should lock each filechannel. Closes #124.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/126)

Lock each FileChannel to protect against concurrent runs.

---

pom.xml
src/main/java/org/corfudb/protocols/logprotocol/TXEntry.java
src/main/java/org/corfudb/protocols/wireprotocol/LogUnitReadResponseMsg.java
src/main/java/org/corfudb/runtime/object/CorfuObjectProxy.java
src/main/java/org/corfudb/runtime/object/CorfuSMRObjectProxy.java
src/main/java/org/corfudb/runtime/object/TransactionalContext.java
src/test/java/org/corfudb/AbstractCorfuTest.java
src/test/java/org/corfudb/runtime/collections/FGMapTest.java
src/test/java/org/corfudb/runtime/collections/SMRMapTest.java

This patch improves the transactional layer to use a single timestamp.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/128)

Improvements to the transactional layer

---

src/test/java/org/corfudb/runtime/collections/PutIfAbsentMapTest.java
src/test/java/org/corfudb/runtime/object/CorfuSMRObjectProxyTest.java

This new test creates a new custom map which implements putIfAbsent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/130)

Create a new test which implements putIfAbsent and custom objects

---

src/test/java/org/corfudb/runtime/collections/FGMapTest.java
src/test/java/org/corfudb/runtime/collections/PutIfAbsentMapTest.java

We need to slowly transition all SMR interfaces to use the
@CorfuObject annotation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/132)

Update the PutIfAbasent map to use the new interface

---

src/main/java/org/corfudb/infrastructure/LayoutServer.java
src/test/java/org/corfudb/infrastructure/LayoutServerAssertions.java
src/test/java/org/corfudb/infrastructure/LayoutServerTest.java

Rebased
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/135)

Fix:Server bootstrap fails to read in layout file in in-memory

---

src/main/java/org/corfudb/runtime/object/CorfuProxyBuilder.java
src/main/java/org/corfudb/runtime/object/CorfuSMRObjectProxy.java
src/main/java/org/corfudb/runtime/object/ICorfuSMRObject.java
src/main/java/org/corfudb/util/ReflectionUtils.java
src/test/java/org/corfudb/runtime/object/CorfuSMRObjectProxyTest.java

This patch adds support for a change handler, which is called every time after an object has 
been changed by the SMR infrastructure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/137)

Basic support for change handler

---

src/main/java/org/corfudb/cmdlets/CmdletRouter.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/139)

Changing array indexes to make cmdlets work.

---

src/main/java/org/corfudb/infrastructure/LogUnitServer.java
src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java

The LogUnitServer handler uses a direct ByteBuf view from an underlying
buffer allocated by the decoder. Although only the payload is persisted and
kept in memory, the capacity of the buffer is usually much larger than payload.
This fix copies the data buffer (i.e. a view of a ByteBuf) into a new buffer
and releases the underlaying buffer, as a result of the copy, extra bytes
are truncated and freed back to the direct memory pool.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/140)

Fixed a direct memory ByteBuf leak

---

src/test/java/org/corfudb/runtime/object/CorfuSMRObjectProxyTest.java
src/test/java/org/corfudb/runtime/object/TestClassUsingAnnotation.java

This adds a unit test for the annotation framework.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/157)

test using anotations

---

src/main/java/org/corfudb/cmdlets/CmdletRouter.java

This reverts commit d1567a3d5a541338033bd1667db82d5c5123013f.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/163)

Revert "Changing array indexes to make cmdlets work." as it actually breaks the cmdlets.

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/178)

Fix readme to reflect new API, fixes #176

---

src/main/resources/logback.xml
src/test/resources/logback-test.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/179)

reduce stack trace length in logback configuration, fixes #145

---

src/main/java/org/corfudb/runtime/CorfuRuntime.java
src/main/java/org/corfudb/runtime/view/ObjectsView.java
src/main/java/org/corfudb/runtime/view/StreamsView.java
src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
src/test/java/org/corfudb/runtime/view/ObjectsViewTest.java

CorfuRuntime can now enbale logging of all transactions to a
transaction stream. This will enable other clients to be able to
query this transaction stream and detect transactions from other
clients.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/195)

Transaction Logging

---

src/main/java/org/corfudb/infrastructure/LogUnitServer.java
src/main/java/org/corfudb/infrastructure/log/AbstractLocalLog.java
src/main/java/org/corfudb/infrastructure/log/InMemoryLog.java
src/main/java/org/corfudb/infrastructure/log/LogRange.java
src/main/java/org/corfudb/infrastructure/log/LogUnitEntry.java
src/main/java/org/corfudb/infrastructure/log/RollingLog.java
src/main/java/org/corfudb/protocols/wireprotocol/LogUnitReadResponseMsg.java
src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java

Abstracted the log from the logging units. Now the logging units
can consume multiple LocalLogs with different address spaces.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/198)

LocalLog Implementation

---

src/main/java/org/corfudb/infrastructure/BaseServer.java
src/main/java/org/corfudb/infrastructure/CorfuServer.java
src/main/java/org/corfudb/infrastructure/LayoutServer.java
src/main/java/org/corfudb/infrastructure/LogUnitServer.java
src/main/java/org/corfudb/infrastructure/NettyServerRouter.java
src/main/java/org/corfudb/infrastructure/SequencerServer.java
src/main/java/org/corfudb/infrastructure/ServerContext.java
src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsg.java
src/test/java/org/corfudb/infrastructure/LayoutServerTest.java
src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java
src/test/java/org/corfudb/infrastructure/SequencerServerTest.java
src/test/java/org/corfudb/infrastructure/ServerContextBuilder.java
src/test/java/org/corfudb/infrastructure/TestServerRouter.java
src/test/java/org/corfudb/runtime/clients/AbstractClientTest.java
src/test/java/org/corfudb/runtime/clients/LayoutClientTest.java
src/test/java/org/corfudb/runtime/clients/LogUnitClientTest.java
src/test/java/org/corfudb/runtime/clients/NettyCommTest.java
src/test/java/org/corfudb/runtime/clients/SequencerClientTest.java
src/test/java/org/corfudb/runtime/clients/TestClientRouterTest.java
src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
src/test/java/org/corfudb/runtime/view/SequencerViewTest.java

* Create Server Context responsible for common Server Operations:
- Common node level data store
- Persistence of SERVER EPOCH
* Moved the SET_EPOCH message handler to LayoutServer.
* Created a ServerContextBuilder and changed all the tests to use it
instead of ServerConfigBuilder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/210)

Created and integrated Server Context

---

pom.xml
src/main/java/org/corfudb/cmdlets/corfu_as.java
src/main/java/org/corfudb/infrastructure/LogUnitServer.java
src/main/java/org/corfudb/infrastructure/SequencerServer.java
src/main/java/org/corfudb/protocols/wireprotocol/CommitRequest.java
src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
src/main/java/org/corfudb/protocols/wireprotocol/IMetadata.java
src/main/java/org/corfudb/protocols/wireprotocol/TokenRequest.java
src/main/java/org/corfudb/protocols/wireprotocol/TokenResponse.java
src/main/java/org/corfudb/protocols/wireprotocol/TrimRequest.java
src/main/java/org/corfudb/protocols/wireprotocol/WriteRequest.java
src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
src/main/java/org/corfudb/runtime/clients/SequencerClient.java
src/main/java/org/corfudb/runtime/exceptions/ReplexOverwriteException.java
src/main/java/org/corfudb/runtime/view/AbstractReplicationView.java
src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
src/main/java/org/corfudb/runtime/view/ChainReplicationView.java
src/main/java/org/corfudb/runtime/view/Layout.java
src/main/java/org/corfudb/runtime/view/ReplexReplicationView.java
src/main/java/org/corfudb/runtime/view/SequencerView.java
src/main/java/org/corfudb/runtime/view/StreamView.java
src/main/java/org/corfudb/runtime/view/StreamsView.java
src/test/java/org/corfudb/infrastructure/SequencerServerTest.java
src/test/java/org/corfudb/runtime/clients/LogUnitClientTest.java
src/test/java/org/corfudb/runtime/collections/SMRMapTest.java
src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
src/test/java/org/corfudb/runtime/view/ChainReplicationViewTest.java
src/test/java/org/corfudb/runtime/view/ReplexStreamViewTest.java
src/test/java/org/corfudb/runtime/view/StreamViewTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/220)

Implemented basic Replex commit protocol + hole filling. StreamView is updated to use Replex, if that is the replication view selected.

---

scripts/cmdlet.sh
scripts/corfu_server.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/corfudb/corfudb/245)

handle strange dir names with spaces, etc.

---

src/main/java/org/corfudb/infrastructure/LayoutWorkflowManager.java
src/main/java/org/corfudb/runtime/exceptions/LayoutModificationException.java
src/test/java/org/corfudb/infrastructure/LayoutWorkflowManagerTest.java

Workflow manager to modify the layout.
Currently only removes nodes.
Throws error if removal of node results in invalid layout.

Created LayoutWorkflowManager to modify the layout

---

test/src/test/java/org/corfudb/infrastructure/PeriodicPollPolicyTest.java
test/src/test/java/org/corfudb/runtime/clients/ManagementClientTest.java
test/src/test/java/org/corfudb/runtime/view/AbstractViewTest.java

Giving more time and multiple to check if this was a timing issue and the failure persists.
(Need to check multiple times on travis env so please do not merge)

Resolving timing issue test

---

infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java

Unlike the layout server, when the corfu server is started as a
single instance, the management isn't bootstrapped with the single
server layout.

Management Server -s Bootstrap

---

.travis_scripts/mvnrepo.sh

Fixes the deploy phase to copy the contents of the mvn-repo directory for the runtime,
not the mvn-repo itself.

fix mvn-repo directory, should actually fix #283

---

README.md
bin/README.md
bin/corfu_multiping
bin/shell
cmdlets/pom.xml
cmdlets/src/main/clojure/org/corfudb/shell.clj
cmdlets/src/main/clojure/org/corfudb/shell_main.clj
cmdlets/src/main/java/org/corfudb/shell/ShellMain.java
corfu_scripts/corfu_as.clj
corfu_scripts/corfu_layouts.clj
corfu_scripts/corfu_logunit.clj
corfu_scripts/corfu_ping.clj
corfu_scripts/corfu_sequencer.clj
corfu_scripts/corfu_smrobject.clj
runtime/src/main/java/org/corfudb/runtime/view/Layout.java
runtime/src/main/java/org/corfudb/runtime/view/LayoutView.java
runtime/src/main/java/org/corfudb/util/JSONUtils.java
scripts/cmdlet.sh

This pull request restores all the missing cmdlets by providing clojure versions of each cmdlet. In addition, the readme is updated to reflect the new cmdlets as well.

Clojure Cmdlets

---

README.md
infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
test/src/test/java/org/corfudb/infrastructure/SequencerServerAssertions.java
test/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java

minor stylistic changes to new sequencer, and added one more unit test on it

updated corfu-repos on readme

---

cmdlets/pom.xml
infrastructure/pom.xml
pom.xml
runtime/pom.xml

This moves several dependencies which only the runtime needs into the
runtime's pom.xml, and also updates the version of several 
dependencies (Guava, Netty, Caffeine).

Refactor dependencies, update versions of several dependencies

---

pom.xml
test/src/test/java/org/corfudb/integration/StreamIT.java
test/src/test/resources/CorfuDB.properties

A simple integration test that writes random data to a stream,
reads it back and then verifies that the stream read matches
the written stream.

Added Stream Integration Test

---

infrastructure/pom.xml

Added commons-io dependency to the infrastructure pom file.
Addresses #342

Added Apache Commons

---

cmdlets/src/main/clojure/org/corfudb/shell.clj

This patch fixes a bug in the docopt parsing where the docopt parameter was missing.

clojure script bug fix

---

infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriter.java
infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/WriteOperation.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLog.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
test/src/test/java/org/corfudb/runtime/object/CorfuSMRObjectProxyTest.java
test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
test/src/test/java/org/corfudb/runtime/view/StreamViewTest.java

This patch implements batch processing for write requests,
where write requests are batched and sync'd to disk together,
then acknowledged.

Implemented Batch Disk Sync/Ack

---

pom.xml
test/src/test/java/org/corfudb/AbstractCorfuTest.java
test/src/test/java/org/corfudb/CorfuTestParameters.java
test/src/test/java/org/corfudb/runtime/collections/SMRMapTest.java
test/src/test/java/org/corfudb/runtime/object/CompileProxyTest.java
test/src/test/java/org/corfudb/runtime/object/CorfuCompoundObj.java
test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTXConcurrencyTest.java
test/src/test/java/org/corfudb/runtime/object/transactions/WriteWriteTXConcurrenctTest.java

This branch is used for testing of new transaction framework.

Branch for testing issues of transaction conflict resolution

---

format/pom.xml
format/proto/types.proto

Added maven hooks to generate protobuf sources.

Added Support For Protobufs

---

test/src/test/java/org/corfudb/AbstractCorfuTest.java

This patch fixes an issue with an exception occuring if the exception was thrown outside of the test framework or an inherited class.

Fix exception in test framework

---

TestingFramework.md

to address request by @slfritchie, added some documentation on the testing framework

explain the concurrecy test framework

---

infrastructure/src/main/java/org/corfudb/infrastructure/LayoutServer.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
runtime/src/main/java/org/corfudb/runtime/clients/BaseClient.java
runtime/src/main/java/org/corfudb/runtime/exceptions/ServerRejectedException.java
test/src/test/java/org/corfudb/runtime/clients/LayoutClientTest.java

Address review change requested in PR #363: Add `ServerRejectedException` to `CorfuMsgType` and add a new unit test for the `LayoutServer`'s change of behavior. cc: @dahliamalkhi

Add ServerRejectedException + new test for LayoutClientTest

---

runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteAfterWriteTransactionalContext.java
runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java
test/src/test/java/org/corfudb/runtime/object/transactions/WriteAfterWriteTransactionContextTest.java
test/src/test/java/org/corfudb/runtime/view/ObjectsViewTest.java

Added transaction logging support for optimistic transactions.

Transaction Logging in Optimistic Transactions

---

README.md

This is my first pull request to CorfuDB repo (also first commit to an open source project). Hope I could learn the process of contributing to open source projects through this pull request. I think the idea of CorfuDB is great, and I will keep watch and contribute to CorfuDB.
This is a simple typo error in document but might confuse the users who follow the documents to get started with CorfuDB. Hence I made this pull request.

Fix a command line error in README.md

---

samples/src/main/java/org/corfudb/samples/BaseCorfuAppUtils.java
samples/src/main/java/org/corfudb/samples/BatchedWriteTransaction.java
samples/src/main/java/org/corfudb/samples/SimpleAtomicTransaction.java
samples/src/main/java/org/corfudb/samples/SimpleUseBaseCorfuCollections.java
samples/src/main/java/org/corfudb/samples/SimpleUseCustomBaseCorfuObject.java
samples/src/main/java/org/corfudb/samples/WriteOnlySimpleTransaction.java
samples/src/main/java/org/corfudb/samples/WriteWriteTXs.java

fairly minor PR: addressing review comments by Konstantin on #409

fixing copy/paste errors pointed by Konstantin

---

infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
runtime/src/main/java/org/corfudb/util/TlsUtils.java

Options parsing refactoring for #417 (see review discussion there).

Experiment: refactor options parsing into common static method

---

infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java

Remove the conflict key class, replacing it with a hash code.

remove conflictKey class

---

runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java

This fix addresses issue #442 by @goyalkapil

clean up NettyClientRouter workerGroup on failed connection

---

runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java

This patch adds a flag to the runtime to disable hole filling.

Add option to disable hole-filling

---

runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/TransactionalContext.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteAfterWriteTransactionalContext.java

This pull request reverts micro TX support, which may have been causing performance regressions.

revert microTX

---

runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java

This pull request makes some minor cleanup to deprecated code.
These unused functions threw an exception when called for
the most part, or are just no longer used by any other
part of the runtime.

minor cleanup of some deprecated code

---

infrastructure/pom.xml
infrastructure/src/main/java/org/corfudb/infrastructure/AbstractServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/BaseServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/CorfuMsgHandler.java
infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/DataStore.java
infrastructure/src/main/java/org/corfudb/infrastructure/LayoutServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
infrastructure/src/main/java/org/corfudb/infrastructure/ServerHandler.java
runtime/pom.xml
runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
runtime/src/main/java/org/corfudb/runtime/clients/IClientRouter.java
runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
runtime/src/main/java/org/corfudb/util/MetricsUtils.java
test/src/test/java/org/corfudb/infrastructure/TestServerRouter.java
test/src/test/java/org/corfudb/runtime/clients/TestClientRouter.java
test/src/test/resources/metrics-configuration.sample.prop

Replacement for PR #424.  Contains corrections requested in 424's review process.

Add dropwizard metrics

---

test/src/test/java/org/corfudb/AbstractCorfuTest.java

Next incremental change from #449

Bugfixes in the abstract corfu test  (concurrency, output)

---

runtime/src/main/java/org/corfudb/protocols/wireprotocol/TokenRequest.java
runtime/src/main/java/org/corfudb/runtime/clients/SequencerClient.java
runtime/src/main/java/org/corfudb/runtime/view/AbstractReplicationView.java
runtime/src/main/java/org/corfudb/runtime/view/Layout.java
runtime/src/main/java/org/corfudb/runtime/view/SequencerView.java
runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/ReplexStreamView.java
test/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java

Next incremental change from https://github.com/CorfuDB/CorfuDB/pull/449

Some refactoring and cleanup on the client side

---

runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java

to make sure the version did not change during commit, we should
compare against the proxy version.

fix commit version

---

runtime/src/main/java/org/corfudb/runtime/view/QuorumFuturesFactory.java
runtime/src/main/java/org/corfudb/runtime/view/SequencerView.java
test/src/test/java/org/corfudb/runtime/view/QuorumFuturesFactoryTest.java

The first was a review suggestion from Michael, Warning - it will affect https://github.com/CorfuDB/CorfuDB/pull/462

QuorumFutureFactory->QuorumFuturesFactory, cleanup of SequencerView

---

runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
test/src/test/java/org/corfudb/runtime/object/transactions/UndoTest.java

also, added streamID to CorfuCopileProxy tracing

Fixed new undotests to guarantee desired outcome;

---

runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/SnapshotTransactionalContext.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteAfterWriteTransactionalContext.java

This patch adds an option to disable undo and optimistic undo

options to disable undo flag

---

test/src/test/java/org/corfudb/runtime/concurrent/MapsAsMQs.java
test/src/test/java/org/corfudb/runtime/concurrent/StreamSeekAtomicity.java

this branch incorporates the test introduced by @vjeko in #488, slightly cleaning it to match Corfu test style; and a couple more concurrency-test variations.

more concurrency tests.. passing.

---

runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java

Currently, access() in versionLockedObject performs an optimistic read.
Because the read is optimistic, sometimes the object could be concurrently
modified, causing an exception to be thrown. 
Previously we did not revalidate the lock on an exception, causing the client
to see the thrown exception. This patch modifies the VersionLockedObject to
revalidate the lock when an exception is thrown. If the read was valid,
the exception is re-thrown, otherwise, we upgrade to a write lock since
the exception was thrown due to an invalid view of then object.

revalidate lock on exception

---

runtime/src/main/java/org/corfudb/runtime/view/SealServersHelper.java

Resolves #518 
Catch Network Exception and prevent seal aborts to handle failures successfully.

Handling NetworkException by NettyClientRouter in SealServersHelper

---

annotationProcessor/src/main/java/org/corfudb/annotations/ObjectAnnotationProcessor.java
annotations/src/main/java/org/corfudb/annotations/MutatorAccessor.java
samples/src/main/java/org/corfudb/samples/CorfuCompoundObject.java
samples/src/main/java/org/corfudb/samples/CorfuSharedCounter.java
test/src/test/java/org/corfudb/runtime/object/ConflictParameterClass.java
test/src/test/java/org/corfudb/runtime/object/CorfuCompoundObj.java
test/src/test/java/org/corfudb/runtime/object/CorfuSharedCounter.java
test/src/test/java/org/corfudb/runtime/object/TestClassUsingAnnotation.java

Verify that all SMR methods(with a mutator annotation) specify the
name field.

Enforce Annotation Names

---

annotationProcessor/src/main/java/org/corfudb/annotations/ObjectAnnotationProcessor.java

Verify that mutator methods that require upcalls have unique names.

Verify Upcall Method Names

---

infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
test/src/test/java/org/corfudb/runtime/clients/LogUnitClientTest.java

This reverts commit 0e9586c0270198012cf04dc502d752bbb148d4b2, reversing
changes made to 5a0c271041ca99368804979050b5fd9a529b96ee.

Revert "Merge pull request #539 from CorfuDB/cacheSegmentHandles"

---

infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
test/src/test/java/org/corfudb/integration/AbstractIntegrationTest.java
test/src/test/java/org/corfudb/integration/ServerRestartTest.java

No longer persisting state in the sequencer.
Added randomized test for recovering sequencer state.

Stateless Sequencer amnesia fix

---

infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java

Implemented a generic pair to replace javafx's pair.

Remove Javafx Pair

---

runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java

This patch makes the client cache size configurable through
the CorfuRuntime settings.

Make Client Cache Size Configurable

---

runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java
test/src/test/java/org/corfudb/runtime/CorfuRuntimeTest.java
test/src/test/java/org/corfudb/runtime/view/QuorumReplicationStreamViewTest.java
test/src/test/java/org/corfudb/runtime/view/ReplexStreamViewTest.java

Reverts CorfuDB/CorfuDB#599
Reverting this PR until performance regressions are understood

Revert "Cleanup of runtime interface"

---

.travis_scripts/push_deb.sh

Fixing debian packages push to Corfu-Repos

Fix debian packages

---

infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
test/src/test/java/org/corfudb/runtime/clients/LogUnitClientTest.java

Properly return read exceptions.

Return Read Exceptions

---

runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java

Return true if readQueue is not empty.

Boolean logic fix BackpointerStreamView.getHasNext

---

runtime/src/main/java/org/corfudb/runtime/collections/SMRMap.java

Add Accessor Annotation to SMRMap scanAndFilter

Add Accessor Annotation to SMRMap scanAndFilter

---

infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
test/src/test/java/org/corfudb/runtime/clients/LogUnitClientTest.java

Implemented A cache flush api to clear the logunit caches.

Logunit Cache Flush

---

test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTest.java

still getting stack overflow with 'periodicCkpointTrimTest'

added a trim test

---

runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTest.java
test/src/test/java/org/corfudb/runtime/concurrent/MapsAsMQsTest.java
test/src/test/java/org/corfudb/runtime/view/stream/BackpointerStreamViewTest.java

This small PR introduces a minor boundary-fix to backpointerStreamView.java, which yields significant performance improvement (on my machine).
I also include a few minor test cleanups and another stream test.

More stream tests

---

.travis.yml
pom.xml
test/pom.xml

Attempting run on travis to fix broken coverage.

Fixing Coveralls coverage

---

checks.xml
pom.xml

This PR introduces checkstyle checking using a modified version of the 
Google style guide.

Turn on checkstyle, but don't error

---

corfu_scripts/corfu_logunit.clj
pom.xml

Fixing broken cmdlet test due to deprecated code.
Enabling integration tests on travis.

Fix and enable IT

---

runtime/src/main/java/org/corfudb/protocols/wireprotocol/ILogData.java
runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
test/src/test/java/org/corfudb/runtime/collections/SMRMapTest.java
test/src/test/java/org/corfudb/runtime/view/stream/BackpointerStreamViewTest.java

- Fix backpointer termination
- Unit Test

Terminate Backpointers at head of stream

---

.travis.yml
.travis_scripts/push_docker.sh
Dockerfile

For every merge to master, a new docker image is created and pushed to docker hub.
[https://hub.docker.com/r/corfudb/corfu/](https://hub.docker.com/r/corfudb/corfu/)

Adding docker integration

---

Dockerfile

Fixing cmdlet jar filename in Dockerfile.

Fixing renamed jar in Dockerfile

---

annotationProcessor/src/main/java/org/corfudb/annotations/ObjectAnnotationProcessor.java

This PR updates the style on org.corfudb.annotations, module annotationProcessor
to the new style guidelines.

Update style on package org.corfudb.annotations, module annotationProcessor

---

runtime/src/main/java/org/corfudb/security/sasl/SaslUtils.java
runtime/src/main/java/org/corfudb/security/sasl/plaintext/PlainTextCallbackHandler.java
runtime/src/main/java/org/corfudb/security/sasl/plaintext/PlainTextLoginModule.java
runtime/src/main/java/org/corfudb/security/sasl/plaintext/PlainTextSaslNettyClient.java
runtime/src/main/java/org/corfudb/security/sasl/plaintext/PlainTextSaslNettyServer.java
runtime/src/main/java/org/corfudb/security/sasl/plaintext/PlainTextSaslServer.java
runtime/src/main/java/org/corfudb/security/sasl/plaintext/PlainTextSaslServerProvider.java
runtime/src/main/java/org/corfudb/security/tls/TlsUtils.java

Checkstyle error fixes: comments, indentation, etc. for org.corfudb.security.*

Checkstyle fixups for org.corfudb.security.*

---

runtime/src/main/java/org/corfudb/runtime/clients/BaseClient.java
runtime/src/main/java/org/corfudb/runtime/clients/ClientHandler.java
runtime/src/main/java/org/corfudb/runtime/clients/ClientMsgHandler.java
runtime/src/main/java/org/corfudb/runtime/clients/IClient.java
runtime/src/main/java/org/corfudb/runtime/clients/IClientRouter.java
runtime/src/main/java/org/corfudb/runtime/clients/LayoutClient.java
runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
runtime/src/main/java/org/corfudb/runtime/clients/ManagementClient.java
runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
runtime/src/main/java/org/corfudb/runtime/clients/SequencerClient.java

Updating package org.corfudb.runtime.clients with new style guidelines.

Update package Clients in module Runtime to new style guidelines.

---

runtime/src/main/java/org/corfudb/runtime/object/AbstractCorfuWrapper.java
runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileWrapperBuilder.java
runtime/src/main/java/org/corfudb/runtime/object/ICorfuSMRProxyInternal.java
runtime/src/main/java/org/corfudb/runtime/object/ISMRStream.java
runtime/src/main/java/org/corfudb/runtime/object/StreamViewSMRAdapter.java
runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java

package org.corfudb.runtime.object

Update package Objects in module Runtime to new style guidelines.

---

runtime/src/main/java/org/corfudb/protocols/logprotocol/CheckpointEntry.java
runtime/src/main/java/org/corfudb/protocols/logprotocol/ISMRConsumable.java
runtime/src/main/java/org/corfudb/protocols/logprotocol/LogEntry.java
runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiObjectSMREntry.java
runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiSMREntry.java
runtime/src/main/java/org/corfudb/protocols/logprotocol/SMREntry.java
runtime/src/main/java/org/corfudb/protocols/logprotocol/StreamCOWEntry.java
runtime/src/main/java/org/corfudb/protocols/logprotocol/StreamData.java

Checkstyle error fixes: comments, indentation, etc. for org.corfudb.protocols.logprotocol.*

Checkstyle fixups for org.corfudb.protocols.logprotocol.*

---

runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java
runtime/src/main/java/org/corfudb/runtime/view/Address.java
runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
runtime/src/main/java/org/corfudb/runtime/view/Layout.java
runtime/src/main/java/org/corfudb/runtime/view/LayoutDeserializer.java
runtime/src/main/java/org/corfudb/runtime/view/LayoutView.java
runtime/src/main/java/org/corfudb/runtime/view/ObjectBuilder.java
runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java
runtime/src/main/java/org/corfudb/runtime/view/QuorumFuturesFactory.java
runtime/src/main/java/org/corfudb/runtime/view/SealServersHelper.java
runtime/src/main/java/org/corfudb/runtime/view/SequencerView.java
runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java

Update to new style guidelines package org.corfudb.runtime.view.*
This solves #697

Update style org.corfudb.runtime.view.*

---

infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java

This PR adds a shutdown hook, which calls shutdown() on each
server so they may shut down gracefully.

Add shutdown hooks which call shutdown() in each server.

---

runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/ReadSetInfo.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/SnapshotTransactionalContext.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/TransactionBuilder.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/TransactionType.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/TransactionalContext.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteAfterWriteTransactionalContext.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteSetInfo.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteSetSMRStream.java

Does not resolve static imports

Style updates org.corfudb.runtime.object.transactions (#695)

---

runtime/src/main/java/org/corfudb/runtime/collections/FGMap.java
runtime/src/main/java/org/corfudb/runtime/collections/ISMRMap.java
runtime/src/main/java/org/corfudb/runtime/collections/ISMRObject.java
runtime/src/main/java/org/corfudb/runtime/collections/SMRMap.java
runtime/src/main/java/org/corfudb/runtime/exceptions/DataOutrankedException.java
runtime/src/main/java/org/corfudb/runtime/exceptions/LayoutModificationException.java
runtime/src/main/java/org/corfudb/runtime/exceptions/NoRollbackException.java
runtime/src/main/java/org/corfudb/runtime/exceptions/OutrankedException.java
runtime/src/main/java/org/corfudb/runtime/exceptions/QuorumUnreachableException.java
runtime/src/main/java/org/corfudb/runtime/exceptions/TransactionAbortedException.java
runtime/src/main/java/org/corfudb/runtime/exceptions/TrimmedException.java
runtime/src/main/java/org/corfudb/runtime/exceptions/TrimmedUpcallException.java

style fix org.corfudb.runtime.collections/exceptions

---

infrastructure/src/main/java/org/corfudb/infrastructure/AbstractServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/BaseServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriter.java
infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriterOperation.java
infrastructure/src/main/java/org/corfudb/infrastructure/ClusterMetrics.java
infrastructure/src/main/java/org/corfudb/infrastructure/ConservativeFailureHandlerPolicy.java
infrastructure/src/main/java/org/corfudb/infrastructure/CorfuMsgHandler.java
infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/DataStore.java
infrastructure/src/main/java/org/corfudb/infrastructure/FailureHandlerDispatcher.java
infrastructure/src/main/java/org/corfudb/infrastructure/IDataStore.java
infrastructure/src/main/java/org/corfudb/infrastructure/IFailureHandlerPolicy.java
infrastructure/src/main/java/org/corfudb/infrastructure/IServerRouter.java
infrastructure/src/main/java/org/corfudb/infrastructure/LayoutServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/LayoutWorkflowManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/NettyServerRouter.java
infrastructure/src/main/java/org/corfudb/infrastructure/NodeHealth.java
infrastructure/src/main/java/org/corfudb/infrastructure/PeriodicPollPolicy.java
infrastructure/src/main/java/org/corfudb/infrastructure/PollReport.java
infrastructure/src/main/java/org/corfudb/infrastructure/PurgeFailurePolicy.java
infrastructure/src/main/java/org/corfudb/infrastructure/Rank.java
infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
infrastructure/src/main/java/org/corfudb/infrastructure/ServerHandler.java
test/src/test/java/org/corfudb/infrastructure/DataStoreTest.java

Does not handle static imports

Style updates org.corfudb.infrastructure (#688)

---

runtime/src/main/java/org/corfudb/runtime/object/StreamViewSMRAdapter.java
runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractContextStreamView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractStreamContext.java
runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/IStreamView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/StreamSpliterator.java
test/src/test/java/org/corfudb/runtime/view/StreamsViewTest.java

Style - org.corfudb.runtime.view.stream Module - runtime #699

Style Update for Stream Package

---

infrastructure/src/main/java/org/corfudb/infrastructure/AbstractServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/BaseServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/FailureHandlerDispatcher.java
infrastructure/src/main/java/org/corfudb/infrastructure/LayoutServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
runtime/src/main/java/org/corfudb/runtime/clients/BaseClient.java
runtime/src/main/java/org/corfudb/runtime/exceptions/ServerNotReadyException.java
runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java

Trigger server startup.
Sequencer and Logunit server calls are blocked until Management Servers signals startup.

Trigger server startup

---

pom.xml

This PR updates the versions of various components to their
latest versions.

Update logback, netty, caffeine, slf4j and surefire

---

test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTest.java

... by adding a new check for an `ExecutionException`, both in the `periodicCkpointTrimTest` test as well as in a new unit test.
Fixes #779

Fix intermittent periodicCkpointTrimTest test failure

---

pom.xml

This PR reverts the version updates from #778 except for logback.
-Michael

revert version updates from #778 except for logback

---

test/src/test/java/org/corfudb/runtime/concurrent/MapsAsMQsTest.java

Fixes #780 by replacing a racy lock+condition variable pair with a semaphore.  Prior to this fix, my laptop fails the `useMapsAsMQs` test roughly 1 failure out of 10-20 executions.  With this fix, I have seen 0 failures in 110 executions.

Convert lock+condition -> semaphore

---

infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/TokenResponse.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/TxResolutionInfo.java
runtime/src/main/java/org/corfudb/runtime/exceptions/TransactionAbortedException.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/ReadSetInfo.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteSetInfo.java
test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTransactionContextTest.java

This patch reverts the two-level conflict key table introduced in

Revert two-level conflict keys

---

infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java

This patch evicts segment handles that correspond to addresses
that have been prefix trimmed. As a result of this eviction,
memory and open file descriptors are cleaned.

Fix: LogUnit FD/Memory leak

---

infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java

Calculate and print how many files/bytes were deleted/freed during
a gc cycle.

Track Freed Bytes

---

infrastructure/src/main/java/org/corfudb/infrastructure/FailureHandlerDispatcher.java
runtime/src/main/java/org/corfudb/recovery/FastSmrMapsLoader.java

Added logging.
Retaining max value in stream tail map.

Recovery logging & retaining max value in fastLoader

---

runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/SnapshotTransactionalContext.java
test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTest.java

Factored out syncObjectUnsafe and wrapped it with a retry loop.

Retry On syncObjectUnsafe

---

runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiObjectSMREntry.java
runtime/src/main/java/org/corfudb/recovery/FastSmrMapsLoader.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteSetSMRStream.java
runtime/src/main/java/org/corfudb/util/Utils.java
test/src/test/java/org/corfudb/runtime/object/transactions/WriteAfterWriteTransactionContextTest.java
test/src/test/java/org/corfudb/runtime/view/ObjectsViewTest.java

Synchronize reads and writes on a MultiObjectSMREntry.

Synchronize MultiObjectSMREntry

---

.travis.yml
.travis_scripts/verify.sh
pom.xml

This PR adds support for sonarqube report generation during
build and during PR submission.

Add support for sonarqube

---

.travis_scripts/verify.sh

This PR modifies sonar to use preview mode (local) on external builds

don't submit to sonar on external

---

runtime/src/main/java/org/corfudb/recovery/FastSmrMapsLoader.java
runtime/src/main/java/org/corfudb/recovery/RecoveryUtils.java
runtime/src/main/java/org/corfudb/runtime/view/ObjectBuilder.java
runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java
test/src/test/java/org/corfudb/recovery/FastSmrMapsLoaderTest.java
test/src/test/java/org/corfudb/runtime/object/CorfuSMRObjectProxyTest.java
test/src/test/resources/logback-test.xml

It was using the default serializer. Now it can take a serializer as a parameter.

FastSmrLoader can set serializer

---

runtime/src/main/java/org/corfudb/protocols/logprotocol/CheckpointEntry.java
runtime/src/main/java/org/corfudb/recovery/RecoveryUtils.java
runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTrimTest.java

False Trim Exception

---

runtime/src/main/java/org/corfudb/runtime/MultiCheckpointWriter.java

Added extra logging to the MultiCheckpointWriter.

Add Extra Logging

---

infrastructure/src/main/java/org/corfudb/infrastructure/CorfuMsgHandler.java
infrastructure/src/main/java/org/corfudb/infrastructure/NettyServerRouter.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/ExceptionMsg.java
runtime/src/main/java/org/corfudb/runtime/clients/BaseClient.java

This PR intorduces a new message type ERROR_SERVER_EXCEPTION, which
exposes server exceptions to the client. In addition server errors
are caught and logged.

Improve error handling and diagnostics

---

infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java

trimPrefix was only removing segments that it held in memory, so
when the logunit restarts before a compact operation happens, some
of the segments would not be deleted. This can happen on trimmed
segments that are never loaded into memory after restarting the
logunit.

Remove All Segments

---

runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java

Fixed warn message for streams that ignore trimmed exceptions.

Fix Logging

---

infrastructure/src/main/java/org/corfudb/infrastructure/DataStore.java
infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
runtime/src/main/java/org/corfudb/util/MetricsUtils.java
runtime/src/main/resources/logback.xml

Adding metrics registry as a configurable parameter so that the application can pass its own registry and report the metrics in its own convenient way when required.

Configurable corfu metrics reporting

---

infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/TokenResponse.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/TokenType.java
runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java

This patch adds additional information to the sequencer response
in case of an abort. It is a subset of PR #800.

Add additional information to sequencer response

---

runtime/src/main/java/org/corfudb/protocols/wireprotocol/ILogData.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
runtime/src/main/java/org/corfudb/runtime/exceptions/AppendException.java
runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
test/src/test/java/org/corfudb/runtime/object/transactions/StreamTest.java

Bound the number of retries on an OverwriteException before giving
up.

Bound Write Retry

---

runtime/src/main/java/org/corfudb/protocols/wireprotocol/ILogData.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
runtime/src/main/java/org/corfudb/runtime/exceptions/AppendException.java
runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
test/src/test/java/org/corfudb/runtime/object/transactions/StreamTest.java

Bound the number of retries on an OverwriteException before giving
up.

PR 925 backport: Bound Write Retry

---

runtime/src/main/java/org/corfudb/util/GitRepositoryState.java

This PR fixes git repository state generation, which sometimes
errored due to git.properties not being present.

Fix repository state generation

---

runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransaction.java

This PR removes the inner methods from the CorfuCompileProxy.

Remove inner methods

---

runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java

Medhavi's tweaks to the CorfuTable consist of not using guava
for the internal data structures.

Remove ArrayList From CorfuTable

---

runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java

Remove parallelStream from methods that process the secondary
indicies.

Remove Parallel Stream

---

runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java

In VersionLockedObject, directAccessCheckFunction may access inconsistent
state since it is accessed under an optimistic lock, and throw an exception
as a result. For example, the optimistic stream could be unexpectedly null
due to a writer.
The PR catches the exception and upgrades the lock if the check throws an exception.

Catch exception in direct access check function

---

annotationProcessor/pom.xml
annotations/pom.xml
cmdlets/pom.xml
debian/pom.xml
format/pom.xml
generator/pom.xml
infrastructure/pom.xml
logReader/pom.xml
pom.xml
runtime/pom.xml
samples/pom.xml
test/pom.xml

Modifying 0.1-SNAPSHOT to 0.1.1-SNAPSHOT for Corfu v0.1.1

Changed version to 0.1.1-SNAPSHOT

---

runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java

Syncronize access around the data byte array.

Syncronize LogData

---

infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java
runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java

Removed usage of internal netty types.

Don't Use Internal Types

---

runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java
runtime/src/main/java/org/corfudb/recovery/RecoveryUtils.java
runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
test/src/test/java/org/corfudb/recovery/Helpers.java
test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java

A new API has been provided for the FastLoader to
selectively choose the streams it wants to load. It also
adds checkpoint streams for each stream added to the
whitelist.
Along, some refactoring of fastLoader testing.

FastLoader have a white list mode

---

generator/README.md
generator/pom.xml
generator/src/main/java/org/corfudb/generator/Correctness.java
generator/src/main/java/org/corfudb/generator/LongevityApp.java
generator/src/main/java/org/corfudb/generator/LongevityRun.java
generator/src/main/java/org/corfudb/generator/State.java
generator/src/main/java/org/corfudb/generator/distributions/Keys.java
generator/src/main/java/org/corfudb/generator/distributions/Operations.java
generator/src/main/java/org/corfudb/generator/distributions/Streams.java
generator/src/main/java/org/corfudb/generator/operations/CheckpointOperation.java
generator/src/main/java/org/corfudb/generator/operations/NestedTxOperation.java
generator/src/main/java/org/corfudb/generator/operations/Operation.java
generator/src/main/java/org/corfudb/generator/operations/ReadOperation.java
generator/src/main/java/org/corfudb/generator/operations/RemoveOperation.java
generator/src/main/java/org/corfudb/generator/operations/SleepOperation.java
generator/src/main/java/org/corfudb/generator/operations/SnapshotTxOperation.java
generator/src/main/java/org/corfudb/generator/operations/WriteAfterWriteTxOperation.java
generator/src/main/java/org/corfudb/generator/operations/WriteOperation.java
generator/src/main/resources/logback-test.xml
runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java

Longevity app

---

runtime/src/main/java/org/corfudb/runtime/object/VersionedObjectManager.java

Switching to a LongAccumulator to reduce synchronization in tracking pending requests in VersionedObjectManager.

Use LongAccumulator instead of Atomic

---

runtime/src/main/java/org/corfudb/protocols/wireprotocol/NettyCorfuMessageEncoder.java

Track and print the max write buffer size.

Track Max Write Size

---

infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java

Hi @no2chem, I am trying to get familiar with CORFU codebase and came across this PR https://github.com/CorfuDB/CorfuDB/pull/759
This is my first simple PR, let me know what you think.
It changes access modifier for all the functions in
SequenceServer.java which are not called from outside to 'private'.

Fixing access modifier in SequenceServer.java

---

infrastructure/src/main/java/org/corfudb/infrastructure/LayoutServer.java
runtime/src/main/java/org/corfudb/runtime/view/LayoutView.java
test/src/test/java/org/corfudb/runtime/view/LayoutViewTest.java

Prepare attempt in paxos should return layout with highest proposed rank.

Prepare: Return layout with highest rank

---

generator/src/main/java/org/corfudb/generator/LongevityApp.java

Ensure that even if the application is hung, we still terminate the run.

Longevity gets a hard stop at the end of run

---

infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriter.java
infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriterOperation.java
infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLog.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/RangeWriteMsg.java
runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
test/src/test/java/org/corfudb/runtime/clients/LogUnitClientTest.java

Implemented a StreamLog batch write API that writes a series of
consecutive addresses in one shot.

Batch Write Implementation

---

runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java

Changed the default constructor logging level.

CorfuTable Logging

---

.github/PULL_REQUEST_TEMPLATE.md

Description: This PR updates the pull request template to contain a field explaining the reason for the PR.
Related issue(s) (if applicable): discussed in #1030
🚫 There are no TODOs left in the code (non code change)
🚫 [Coding conventions](https://github.com/CorfuDB/CorfuDB/wiki/Corfu-Style-Guidelines) (e.g. for logging, unit tests) have been followed (non code change)
🚫 Change is covered by automated tests (non code change)
🚫 Public API has Javadoc (non code change)

Update and move PULL_REQUEST_TEMPLATE.md

---

format/proto/types.proto
infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/Action.java
infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/ActionStatus.java
infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/AddNodeWorkflow.java
infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/Orchestrator.java
infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/Workflow.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/AddNodeRequest.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/AddNodeResponse.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/OrchestratorRequest.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/OrchestratorResponse.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/QueryRequest.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/QueryResponse.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/Request.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/Response.java
runtime/src/main/java/org/corfudb/runtime/clients/ManagementClient.java
runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
test/src/test/java/org/corfudb/integration/AddNodeIT.java
test/src/test/java/org/corfudb/runtime/clients/ManagementClientTest.java

This PR introduces an orchestrator service that and a workflow abstraction that executes against the cluster.

Orchestrator Service

---

bin/corfu_add_node
cmdlets/src/main/clojure/org/corfudb/shell.clj
corfu_scripts/corfu_add_node.clj
pom.xml
runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
runtime/src/main/java/org/corfudb/runtime/clients/ManagementClient.java
runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
runtime/src/main/java/org/corfudb/runtime/view/ManagementView.java
test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java

Description: Introducing an add node cmdlet and a managementView Runtime API
Why should this be merged: To drive the add node functionality.
Related issue(s) (if applicable):

Add node cmdlet and Runtime API

---

format/proto/types.proto
infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/Orchestrator.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/Action.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/ActionStatus.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/AddNodeRequest.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/AddNodeWorkflow.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/CreateRequest.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/CreateWorkflowResponse.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/IWorkflow.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/OrchestratorMsg.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/OrchestratorRequestType.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/OrchestratorResponse.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/QueryRequest.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/Request.java
runtime/src/main/java/org/corfudb/runtime/clients/ManagementClient.java
test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
test/src/test/java/org/corfudb/integration/WorkflowIT.java

Refactor and Clean up.
Restructured some parts of the orchestrator.

Orchestrator Changes

---

infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/AddNodeWorkflow.java
runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java
runtime/src/main/java/org/corfudb/runtime/exceptions/LayoutModificationException.java
runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java
runtime/src/main/java/org/corfudb/runtime/view/ConservativeFailureHandlerPolicy.java
runtime/src/main/java/org/corfudb/runtime/view/IFailureHandlerPolicy.java
runtime/src/main/java/org/corfudb/runtime/view/Layout.java
runtime/src/main/java/org/corfudb/runtime/view/LayoutBuilder.java
runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
runtime/src/main/java/org/corfudb/runtime/view/PurgeFailurePolicy.java
runtime/src/main/java/org/corfudb/runtime/view/SealServersHelper.java
samples/src/main/java/org/corfudb/samples/WriteWriteTXs.java
test/src/test/java/org/corfudb/integration/SealIT.java
test/src/test/java/org/corfudb/integration/ServerRestartIT.java
test/src/test/java/org/corfudb/runtime/CorfuRuntimeTest.java
test/src/test/java/org/corfudb/runtime/view/LayoutViewTest.java
test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java

Exception cleanup.
An attempt to clean up some of the exception throwing/handling mess. 
Why should this be merged: This PR addresses technical debt.

Exception Cleanup

---

format/proto/types.proto
infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/Orchestrator.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/OrchestratorMsg.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/OrchestratorRequestType.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/RemoveNodeRequest.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/RemoveNodeWorkflow.java
runtime/src/main/java/org/corfudb/runtime/clients/ManagementClient.java
runtime/src/main/java/org/corfudb/runtime/view/LayoutBuilder.java
runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
test/src/test/java/org/corfudb/infrastructure/LayoutBuilderTest.java
test/src/test/java/org/corfudb/integration/WorkflowIT.java
test/src/test/java/org/corfudb/runtime/view/LayoutManagementViewTest.java

An implementation of a remove node. This workflow allows the removal
of a node from the cluster.
Description:
An implementation of a remove node workflow. This workflow extends the system's capability to downsize the cluster by removing nodes.
This PR and is needed to complete the clustering effort.
Related issue: #1039

Remove Node

---

format/proto/types.proto
infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/Action.java
infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/ActionStatus.java
infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/AddNodeWorkflow.java
infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/IWorkflow.java
infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/Orchestrator.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/CreateRequest.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/CreateWorkflowResponse.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/OrchestratorMsg.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/OrchestratorRequestType.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/OrchestratorResponse.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/OrchestratorResponseType.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/QueryResponse.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/Response.java
runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
runtime/src/main/java/org/corfudb/runtime/clients/ManagementClient.java
runtime/src/main/java/org/corfudb/runtime/exceptions/WorkflowException.java
runtime/src/main/java/org/corfudb/runtime/view/Layout.java
runtime/src/main/java/org/corfudb/runtime/view/LayoutBuilder.java
runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
runtime/src/main/java/org/corfudb/runtime/view/ManagementView.java
test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
test/src/test/java/org/corfudb/integration/WorkflowIT.java

Description:
Moved orchestrator types from types.proto to the wireprotocol
package and add clients for the orchestrator.
Required for clustering robustness

Code Re-org

---

runtime/src/main/java/org/corfudb/runtime/BootstrapUtil.java
test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java

Description: Bootstraps a cluster based on the given layout.
Why should this be merged: Allows a user to bootstraps the cluster.

Cluster bootstrap util

---

runtime/src/main/java/org/corfudb/runtime/BootstrapUtil.java

Description:
Overrides the bootstrapUtil to use provided corfuRuntimeParameters. Required to provide TLS parameters.
Why should this be merged: NettyClientRouters cannot create connection if security enabled.
Related issue(s) (if applicable): Fixes #1170

Pass TLS parameters to bootstrap util

---

runtime/src/main/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocol.java

Description:
Peek should return null when encountering QuorumUnreachableException.
Fixes test: checkRecoveryWriteTriggeredFromReadRecoversDataWhenTheQuorumIsLost
Re-adding catch block from intermediate change #1082 
Related issue(s) (if applicable): Fixes #1182

Fix QuorumReplicationProtocol

---

infrastructure/src/main/java/org/corfudb/infrastructure/NettyServerRouter.java
runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java

Increased number of server worker threads and changed some
unneeded logs.
improves logging and server performance

Config Changes

---

runtime/src/main/java/org/corfudb/util/MetricsUtils.java

Description:
This commit enables metrics collection and reporting based on the VM's metricsInterval. It also removes some of the obsolete code in MetricsUtils.
To enable collecting and reporting metrics.

Using VM interval property to enable metrics

---

pom.xml

Description:
Related issue(s) (if applicable): 
[Bug 2077884: Build and Packaging: Build] [OSS/TP] Outdated version of httpcomponents-client found
https://bugzilla.eng.vmware.com/show_bug.cgi?id=2077884#c6

Upgrade http-components: httpclient from 4.0.2 to 4.5.5

---

annotationProcessor/pom.xml
annotations/pom.xml
cmdlets/pom.xml
debian/pom.xml
format/pom.xml
generator/pom.xml
infrastructure/pom.xml
migration/pom.xml
pom.xml
runtime/pom.xml
samples/pom.xml
test/pom.xml

Description: Change Corfu version to 0.2.0 in master.
Why should this be merged: Upgrade Corfu version to 0.2.0 in master.

Changed version to 0.2.0

---

infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java
infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/SequencerTailsRecoveryMsg.java
runtime/src/main/java/org/corfudb/runtime/clients/SequencerClient.java
runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java
runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
test/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java
test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
test/src/test/java/org/corfudb/integration/SealIT.java
test/src/test/java/org/corfudb/runtime/clients/SequencerHandlerTest.java
test/src/test/java/org/corfudb/runtime/view/AbstractViewTest.java
test/src/test/java/org/corfudb/runtime/view/LayoutViewTest.java
test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java
test/src/test/java/org/corfudb/runtime/view/QuorumReplicationStreamViewTest.java

Description: Fixing correctness issue caused by a race condition in reconfiguring sequencer servers.
Why should this be merged: Fixes a correctness issue.
Related issue(s) (if applicable): #1268 , #1270

Persist sequencer epoch

---

test/src/test/java/org/corfudb/integration/WorkflowIT.java

Description: Fixes intermittent test failure. This fix shuts down the removed nodes.
NOTE: The main reason for this failure is the HoG and Paxos race #1222 
Why should this be merged: Avoids intermittent failure on CI.

Fix failing AddAndRemoveNodeIT

---

runtime/src/main/java/org/corfudb/util/NetworkUtils.java

This patch fixes a bug where binding to a interface can incorrectly
bind to the virtual interface with the same name prefix. Also,
I added the ability to explicitly bind to a virtual interface.
Why should this be merged: Addresses #1345

Fix Binding Bug and Enable Virtual Interface Binding

---

infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
runtime/src/main/java/org/corfudb/runtime/MultiCheckpointWriter.java
runtime/src/main/java/org/corfudb/util/MetricsUtils.java

Removed an unnecessary loop from the MultiCheckpointWriter.
Why should this be merged: Lower layers have bounded retries, infinitely loop in the MultiCheckpointWriter is not good.

Remove Infinite Loop

---

test/src/test/java/org/corfudb/integration/AbstractIT.java
test/src/test/java/org/corfudb/integration/cluster/Harness/Action.java
test/src/test/java/org/corfudb/integration/cluster/Harness/Harness.java
test/src/test/java/org/corfudb/integration/cluster/Harness/Node.java
test/src/test/java/org/corfudb/integration/cluster/Harness/ShutdownAction.java
test/src/test/java/org/corfudb/integration/cluster/Harness/StartAction.java

A harness to create integration tests for various cluster
scenarios.
Why should this be merged: Needed to implement cluster tests

Cluster Test Harness

---

infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/AddNodeWorkflow.java
runtime/src/main/java/org/corfudb/runtime/view/workflows/AddNode.java
runtime/src/main/java/org/corfudb/runtime/view/workflows/HealNode.java
runtime/src/main/java/org/corfudb/runtime/view/workflows/RemoveNode.java

Added more logs to workflows.
Why should this be merged: Improves logging

More Logging

---

runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java

Fixed a race that caused a NullPointerException when trying to
get a timer in sendMessageAndGetCompletable.
Why should this be merged: Fixes a race condition that can cause a NullPointerException when calling sendMessageAndGetCompletable

Timer Race

---

runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java

Fix issue on CorfuRuntime.connect to properly handle
unavailableServerExceptions that are thrown in between the fetchLayout
and the checkVersion.
Description:
Fixes a bug on CorfuRuntime.connect. In the case a server is reset right
in the middle of the fetchLayout and checkVersion of the CorfuRuntime
connect we are not catching this server exception and this is thrown up
to the client. Upon this exception we do not retry as the check version
is a complete informational step, no actual implications. If the server
is actually done this will be caught when attempting to perform any
operation against Corfu.
Why should this be merged: Bug Fix

Handle UnavailableServerException on CorfuRuntime

---

infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java
test/src/test/java/org/corfudb/infrastructure/FailureDetectorTest.java
test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java

Description:
Move sequencer bootstrap logic to run on recovery mode and fresh startup (with the correct token number).

Bootstrap Sequencer on Fresh Startup

---

annotationProcessor/pom.xml
annotations/pom.xml
cmdlets/pom.xml
debian/pom.xml
format/pom.xml
generator/pom.xml
infrastructure/pom.xml
migration/pom.xml
migration/src/main/java/org/corfudb/migration/LayoutReset.java
pom.xml
runtime/pom.xml
samples/pom.xml
test/pom.xml

Description: Increment master version to 0.2.2.
Why should this be merged: Branched out 0.2.1. Master should have a higher version.

Changed version to 0.2.2

---

infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java
runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java
runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
runtime/src/main/java/org/corfudb/util/LambdaUtils.java

Description:
Related issue(s) (if applicable): Fixes #1479

Fix SystemDownHandler crashing ScheduledExecutorService

---

runtime/src/main/java/org/corfudb/util/concurrent/SingletonResource.java

The current implementation was incorrectly using an atomic primitive
that was leading to creating multiple resources per singleton. In
this particular case, it was leaking netty channels through
CorfuRuntime instances. The new implementation uses double
synchronization check to implement acquisition.
Why should this be merged: Fixes a resource leak 
Related issue(s) (if applicable): #1493

Proper Singleton Implementation

---

infrastructure/src/main/java/org/corfudb/infrastructure/log/SegmentHandle.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java

Possible memory leaks in StreamLogFiles
Description:
memory leaks could happen in the current version of StreamLogFiles
Prevent memory leaks in the stream log layer.
There are methods:
- `SegmentHandle.close()` -> `channel.force(true);` can throw an exception and there is no finally construction to close the resource. The channel will remain unclosed.
- `StreamLogFiles.trimLogFile()->trimLogFile->getCompactedEntries->getChannel` - a file channel can be opened and then an exception can be thrown, so the channel remains open.
- `StreamLogFiles.getSegmentHandleForAddress()` - we create 4 channels `writeCh, readCh, trimmedCh, pendingTrimmedCh` we can create all these channels and then throw RuntimeException (see `getChannel` method) in the result all these channels …

Prevent memory leaks in StreamLogFiles

---

runtime/src/main/java/org/corfudb/runtime/view/workflows/AddNode.java
runtime/src/main/java/org/corfudb/runtime/view/workflows/HealNode.java
runtime/src/main/java/org/corfudb/runtime/view/workflows/RemoveNode.java

Description: Verify workflow completion on the same layout rather than querying the runtime layout.
Why should this be merged: All verification checks should be performed on the same layout.

Workflow verification based on same layout.

---

test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointTest.java

Made all the tests thread safe.
Why should this be merged: Fixes some tests that have been failing intermittently 
Related issue(s) (if applicable): #1527

Cleaned Up CheckpointTest

---

infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
infrastructure/src/main/resources/logback.prod.xml
infrastructure/src/main/resources/logback.xml
it/src/main/resources/logback.xml
test/src/test/resources/logback-test.xml

Description:
Fix mistake in log format
Fix mistake in log format. Improved log format

Fix UTC format for logs

---

.travis.yml

Description:
Fix Travis script to be able to trigger a build

Run tests to trigger by travis

---

infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java
infrastructure/src/main/java/org/corfudb/infrastructure/management/ClusterStateContext.java
infrastructure/src/main/java/org/corfudb/infrastructure/management/FailureDetector.java
infrastructure/src/main/java/org/corfudb/infrastructure/management/FullyConnectedClusterRecommendationEngine.java
infrastructure/src/main/java/org/corfudb/infrastructure/management/HealingDetector.java
test/src/test/java/org/corfudb/infrastructure/SequencerServerTest.java
test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java

Handling partial partitions.

---

runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
test/src/test/java/org/corfudb/runtime/view/stream/BackpointerStreamViewTest.java

Changed the semantics of get so that every invocation will return
a new StreamView object (i.e. not cached).
Why should this be merged: #1578 changed the semantics of get, this changes it back to the 
previous behavior.

IStreamView:get Semantics

---

runtime/src/main/java/org/corfudb/protocols/wireprotocol/ICorfuPayload.java
runtime/src/test/java/org/corfudb/protocols/wireprotocol/ICorfuPayloadTest.java

Description:
- Reformat ICorfuPayload code (text)
- Add a unit test for ICorfuPayload
More unit tests 

ICorfuPayload unit testing

---

test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java

Description:
Fixes the intermittent but frequent assertion failure in removeSingleNodeFailure.
To make sure of the UT test pass.

Fix Remove Single Node Failure UT

---

test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java

Description:
This commit evaluates the stable layout instead of verifying specific epoch (e.g. epoch 5).
Fix the intermittent UT failures when the stable layout is observed after specific epoch.

Fix Verify State Transfer and Merge In Healed UT

---

infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java

Description:
Extract config class for LogUnitServer, get rid of raw `Map<String, Object>` config
Makes configuration more clear, brings type safety

LogUnitServer optimization: extract config

---

it/Dockerfile

Description:
Optimizations for docker build in it module
changes allow using docker cache, no need to rebuild entire docker image

Optimize docker image build in it module

---

runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java

Changed the AddressSpaceCache to use an LRU

AddressSpaceView LRU Implementation

---

infrastructure/src/main/java/org/corfudb/infrastructure/LayoutServer.java

Description:
Removing unused option field and dead statements from the LayoutServer
Refactoring

Remove unused field and dead statements in LayoutServer

---

infrastructure/src/main/java/org/corfudb/infrastructure/ManagementServer.java

Description:
Avoids updating layout when unnecessary. There is a race condition and it happens when a node detect failedNodes (or healedNode) but by the time that ManagementServer receives the MANAGMENT_FAILING_DETECTED (or MANAGEMENT_HEALING_DETECTED) the appropriate action (ie. add to responsive / remove from unresponsive) is already taken. So currently management server just bumps up the layout with a new epoch without making any useful change to the layout. 
To avoid updating layout where responsive and unresponsive won't effectively changed as the result of detected failures and healings.

Avoid unnecessary layout updates

---

infrastructure/src/main/java/org/corfudb/infrastructure/management/FullyConnectedClusterRecommendationEngine.java

Description:
Adding more log statements to the recommendation enginer
For better debugging.

Adding more logs for failure detection

---

infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/ClientHandshakeHandler.java
runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
runtime/src/main/java/org/corfudb/util/retry/ExponentialBackoffRetry.java
runtime/src/main/java/org/corfudb/util/retry/IRetry.java
runtime/src/main/java/org/corfudb/util/retry/IntervalRetry.java
test/src/test/java/org/corfudb/util/retry/IRetryTest.java

This reverts commit 821e041fcce353881c13b346485e41f9d445718e.

Revert "Failed Authentication (#1572)"

---

runtime/src/main/java/org/corfudb/runtime/object/transactions/Transaction.java
test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
test/src/test/java/org/corfudb/runtime/object/transactions/AbstractTransactionContextTest.java

Remove User Defined Snapshot Token Verification from current version.

Remove User Defined Snapshot Verification

---

it/src/main/java/org/corfudb/universe/util/DockerManager.java

Fix incorrect sanity check for docker container restart which currently prevents normal restart attempts.

Fix incorrect sanity check for docker container restart

---

runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java
runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java

This patch fixes a deadlock situation where the FastObjectLoader
exhausts the common thread pool with parallelStream and then a
invalidateLayout is issued. Since the latter call is scheduled
on the same thread pool, the FastObjectLoader will not progress
because it relies on fetchLayout to complete, but it can't.
Why should this be merged: Fixes a deadlock created by the FastObjectLoader
Related issue(s) (if applicable): #1688 and #1687

Common Pool Deadlock

---

it/src/test/java/org/corfudb/universe/scenario/OneNodeDownIT.java
it/src/test/java/org/corfudb/universe/scenario/OneNodePausedIT.java
it/src/test/java/org/corfudb/universe/scenario/TwoNodesDownIT.java
runtime/src/main/java/org/corfudb/runtime/view/ClusterStatusReport.java
runtime/src/main/java/org/corfudb/runtime/view/ManagementView.java
test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java

Simplify and remove dependency with failure detector.
Introduce DB_SYNCING as a cluster state.

[Clean Rebase] Get Cluster Status API

---

infrastructure/src/main/java/org/corfudb/infrastructure/management/FailureDetector.java
runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java

Description:
Tune failure detector timeouts

Failure detector tune timeouts

---

runtime/src/main/java/org/corfudb/runtime/view/replication/ChainReplicationProtocol.java

Description:
Changing the log level of recover and propagate in ChainReplicationProtocol to decrease the amount of logging.
Also tightening the visibility of recover and propagate.
Too many logs being emitted 

Change log level in ChainReplicationProtocol for recover and propagate

---

runtime/src/main/java/org/corfudb/runtime/view/ManagementView.java

Addressing pending comments on get cluster status related functions.

Add comments to ManagementView

---

annotationProcessor/pom.xml
annotations/pom.xml
cmdlets/pom.xml
debian/pom.xml
format/pom.xml
generator/pom.xml
infrastructure/pom.xml
it/pom.xml
migration/pom.xml
pom.xml
runtime/pom.xml
samples/pom.xml
test/pom.xml

Description: Branched out 0.2.2. Changing version to 0.2.3
Why should this be merged: New version.

Changed version to 0.2.3

---

test/src/test/java/org/corfudb/integration/AbstractIT.java
test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java

Description: Fix intermittent test failure.

Fix intermittent test killAndHealNode.

---

runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java

Change log level for single step on followBackpointers and in addition add log to indicate only the start and end of a single step range. 
Why should this be merged: fixes log roll over
Related issue(s) (if applicable): #1729 
- [ x] There are no TODOs left in the code
- [x ] [Coding conventions](https://github.com/CorfuDB/CorfuDB/wiki/Corfu-Style-Guidelines) (e.g. for logging, unit tests) have been followed
- [x ] Change is covered by automated tests
- [ x] Public API has Javadoc

Fix followBackpointers Logging on Single Step

---

runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java

Moving change #1738 into corfu-0.2.2 branch

Remove GC Trim mark validation from CP

---

runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractContextStreamView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
test/src/test/java/org/corfudb/integration/WorkflowIT.java

The nextUpTo method can place the pointer at a trimmed position when stream
is built from a checkpoint only. For this reason a post validation is not required.

NextUpTo no post validation

---

runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractContextStreamView.java
test/src/test/java/org/corfudb/integration/AbstractIT.java
test/src/test/java/org/corfudb/integration/WorkflowIT.java

Fix #1746 applied on branch corfu-0.2.2

Non-Transactional Reads after GC Fix

---

infrastructure/src/main/java/org/corfudb/infrastructure/BatchWriter.java
infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLog.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
infrastructure/src/test/java/org/corfudb/infrastructure/log/StreamLogChecksumTest.java
runtime/src/main/java/org/corfudb/runtime/exceptions/DataCorruptionException.java
test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java

Description:
Fix warnings, code reformat
Basic simplifaction, get rid of abandoned code, code reformats for better readability, checksum unit test.

StreamLogFiles clean up

---

runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java

Description:
Adding metrics to VersionLockedObject methods in order to:
-Measure optimistic reads
-Measure read that required a full write lock
-Measure gc
-Measure updates
This level of detail is required to differentiate the hotspots which are responsible for most of a the times for reads.

Add timers for measuring vlo operations

---

README.md

Description: Fix README.md with the updated cluster setup steps.
Why should this be merged: README.md is broken as the cluster setup steps are no longer valid.
Related issue(s) (if applicable): #1266

Update cluster setup steps in README.md

---

runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
runtime/src/main/java/org/corfudb/runtime/clients/LogUnitClient.java
runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
runtime/src/main/java/org/corfudb/runtime/view/RuntimeLayout.java
test/src/test/java/org/corfudb/integration/MemoryFootprintIT.java
test/src/test/java/org/corfudb/util/MemoryFootprintMeasurerIT.java

Description:
Fixing metrics in LogUnitClient.
Removing the extra registry from CorfuRuntime.
Currently the metrics in LogUnitClient are empty and not being reported.
Related issue(s) (if applicable): #1785

Fixing reporting metrics from LogUnitClient

---

infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java

Description:
If the cluster state is already ready that implies that the primary sequencer is ready too.
If so, avoid repetitive futile attempts to re-bootstrap the primary sequencer.
Related issue(s) (if applicable): #1782 
- [ x] There are no TODOs left in the code
- [ x] [Coding conventions](https://github.com/CorfuDB/CorfuDB/wiki/Corfu-Style-Guidelines) (e.g. for logging, unit tests) have been followed
- [ x] Change is covered by automated tests

Skip bootstrapping an already bootstrapped sequencer

---

runtime/src/main/java/org/corfudb/util/MetricsUtils.java

Description:
This PR adds metrics of netty's direct and heap memory usages.
To monitor the potential off-heap memory leaks.
Related issue(s) (if applicable): #1820

Metrics for netty direct and heap memory usage

---

infrastructure/src/main/java/org/corfudb/infrastructure/management/FailureDetector.java

Description:
The failure detector uses the aggregated state to make a decision to mark a node as failed
Improves failure detection logic, makes it more stable

Failure detector aggregated state

---

infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java
runtime/src/main/java/org/corfudb/recovery/RecoveryUtils.java
runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
runtime/src/main/java/org/corfudb/runtime/view/replication/ChainReplicationProtocol.java
runtime/src/main/java/org/corfudb/runtime/view/replication/IReplicationProtocol.java
runtime/src/main/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocol.java
test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java

Revert "Cache-After-Write Race + Data Loss Bug (#1805)"

---

infrastructure/src/main/java/org/corfudb/infrastructure/BaseServer.java
runtime/src/main/java/org/corfudb/runtime/clients/BaseClient.java

Description:
Why should this be merged: More debugging info to diagnose epoch changes.

Log sender's IP during epoch change, log clientID when epoch change is initiated

---

runtime/src/main/java/org/corfudb/util/MetricsUtils.java

Description:
Adding metrics on direct and mapped buffer and other non-heap usages.
To measure non-heap memory usage/problems of CorfuDB.
Related issue(s) (if applicable): #1829

Add Metrics for Direct and Mapped buffer pools

---

test/src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java

Fixed a couple of tests.
Why should this be merged: fixes #1868

Fixed LogUnit UnitTest

---

infrastructure/src/main/java/org/corfudb/infrastructure/BaseServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServerNode.java
infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
test/src/test/java/org/corfudb/runtime/clients/NettyCommTest.java

Description: Cleans up Corfu Server startup. This paves way for JMH framework.
Why should this be merged: Simpler Corfu Server instantiation. Can further be used in tests to instantiate a server.

Cleanup CorfuServer startup.

---

infrastructure/src/main/java/org/corfudb/infrastructure/log/LogMetadata.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java

Description:
Collect as much information as possible in case of data corruption exception

Data corruption exception detailed error message

---

docs/failure-detector/failure-detector.md

Description:
Failure detector implementation details. Documentation 

Failure detector doc implementation details

---

infrastructure/src/test/java/org/corfudb/infrastructure/management/PollReportTest.java

Fix for PollReportTest
Description:

PollReportTest fix

---

.travis.yml
generator/src/main/resources/logback-test.xml
infrastructure/src/main/resources/logback.prod.xml
infrastructure/src/main/resources/logback.xml
it/src/main/resources/logback.xml
it/src/test/resources/logback-test.xml
pom.xml
runtime/src/main/resources/logback.xml
test/src/test/java/org/corfudb/integration/MemoryFootprintIT.java
test/src/test/resources/logback-test.xml

Porting the following to corfu-0.2.3
commit d07850b331ba6f988ebe0e7f8984c2b0865cb794
Author: Anny Martinez <annymartinez.m@gmail.com>
Date:   Fri May 31 20:39:56 2019 -0700
Update OpenSSL (#1914)
commit 41bcf76c5aec5958f4a103d5c45eee8b5ec7706d
Author: Maithem <Maithem@users.noreply.github.com>
Date:   Fri May 31 15:41:12 2019 -0700
Upgrade Travis Image (#1915)
Upgarde from trust to xenial.
commit 3016ab31aa2eead7a0d11ab6b641464db4c8c427
Author: Viacheslav <xrw.null@gmail.com>
Date:   Thu May 30 16:46:42 2019 -0700
Get rid of highlight in logs (#1852)

Cherry-pick from master to corfu-0.2.3

---

.travis.yml

Enable all unit tests
Description:

Enable all unit tests

---

infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/LogMetadata.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
runtime/src/main/java/org/corfudb/runtime/view/stream/StreamAddressSpace.java
test/src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java
test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java

Merge Stream Trim Mark Fix  into corfu-0.2.3

Log Unit Trim Mark Rebuilt Fix

---

infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java

Description:
Cherry picked fix from master

Flush Write Buffer

---

runtime/src/main/java/org/corfudb/security/tls/SslContextConstructor.java

Attempt to load openssl, if it doesn't exist use the JDK's provider
instead (i.e. JdkSslEngine).

Set Default SSL provider

---

test/src/test/java/org/corfudb/runtime/view/StateTransferTest.java

Description: Fixes a flaky test.
Why should this be merged: Fixes flaky state transfer test due to RPC timeout in the test.

Fix test - verifyPartialStateTransferCompletionOnRetry.

---

infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/AbstractLogSegment.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/CompactionPolicy.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/GarbageLogSegment.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/GarbageThresholdCompactionPolicy.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/SegmentManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogCompactor.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogDataStore.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogParams.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogSegment.java
infrastructure/src/test/java/org/corfudb/infrastructure/log/StreamLogDataStoreTest.java
test/src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java
test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
test/src/test/java/org/corfudb/infrastructure/log/StreamLogWithRankedAddressSpaceTest.java
test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java

Pull request on the feature branch:
LogUnit server GC phase 1: refactoring, extract/add parameters and add add skeleton codes for compaction.

LogUnit server GC phase 1: refactoring, params and add skeleton codes

---

runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java

Adding log information for debugging.

Add Log Info on Ignored TrimmedExceptions

---

annotationProcessor/pom.xml
annotations/pom.xml
cmdlets/pom.xml
common/pom.xml
debian/pom.xml
docs/dockerized-corfu.md
format/pom.xml
generator/pom.xml
infrastructure/pom.xml
it/pom.xml
pom.xml
runtime/pom.xml
samples/pom.xml
test/pom.xml

Description:
Change version to 0.3.0
Why should this be merged: Update version after branching out corfu-0.2.3

Changed version to 0.3.0

---

runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
test/src/test/java/org/corfudb/integration/ServerRestartIT.java
test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java

Port fix to multiple checkpointers to corfu-0.2.3

Fix to Concurrent Checkpointers (0.2.3)

---

infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogDataStore.java

Change Log Level StreamLogDataStore for readability (#1850) - 0.2.3

---

runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java

Change Log Level for Trim messages in Stream View (#1977) - 0.2.3

---

infrastructure/src/main/java/org/corfudb/infrastructure/BatchProcessor.java
infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/LogMetadata.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
runtime/src/main/java/org/corfudb/runtime/view/stream/StreamAddressSpace.java
test/src/test/java/org/corfudb/integration/ServerRestartIT.java
test/src/test/java/org/corfudb/integration/StreamAddressDiscoveryIT.java
test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java

[Corfu_0.2.3] Log Unit Stream's Address Space rebuilt

---

runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java

[Corfu-0.2.3] Add logs for debugging

---

runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java

We observed an Exception being thrown from an unexpected path. TrimmedExceptions when reading from a checkpoint on reset. Adding logs to ease debugging of this code path.

Add logs for debugging

---

runtime/src/main/java/org/corfudb/protocols/logprotocol/ISMRGarbageInfo.java
runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiObjectSMREntryGarbageInfo.java
runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiSMREntryGarbageInfo.java
runtime/src/main/java/org/corfudb/protocols/logprotocol/SMREntryGarbageInfo.java

Add more APIs to ISMRGabageInfo.

Replenish ISMRGabageInfo: add garbage size and empty check.

---

runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java

Convert removeFromQueue from recursive to iterative to avoid StackOverflow
exceptions in cases where holes are predominant in a stream.

Convert Recursion to Iteration

---

runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java

Convert removeFromQueue from recursive to iterative to avoid StackOverflow
exceptions in cases where holes are predominant in a stream.

Convert Recursion to Iteration (#2008)

---

runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java

If the FoL fails we have no logs that provide data on the actual error.

Add Log for Fast Object Loader Failure

---

runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
runtime/src/main/java/org/corfudb/util/MetricsUtils.java
test/src/test/java/org/corfudb/integration/TransactionStreamIT.java
test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java

Added weight(i.e. in-memory size) based eviction for the
AddressSpaceView cache.
Why should this be merged: Porting #1981

Memory Size Based Eviction

---

infrastructure/src/main/java/org/corfudb/infrastructure/LocalMonitoringService.java

Description:
Related issue(s) (if applicable): #2035

Prevent NPE in LocalMonitoringService (#2036)

---

infrastructure/src/main/java/org/corfudb/infrastructure/BatchProcessor.java
infrastructure/src/main/resources/logback.prod.xml
runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java

Description:
logging improvements

Logging improvements

---

runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java

Added extra stats(i.e. in-memory size, CP size in bytes) logging
for the checkpoint writer.
Why should this be merged: Improves logging and debuggability

Improved CheckpointWriter Logging

---

runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java

Description:
Decrease log level for "Trying connection" message

log message "Trying connection" lowered to trace level

---

infrastructure/src/main/java/org/corfudb/infrastructure/LayoutServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/Phase2Data.java
infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
infrastructure/src/main/java/org/corfudb/infrastructure/paxos/PaxosDataStore.java

Description:
Provide PaxosDataStore - needed to make Paxos implementation cleaner and more flexible.

Extract PaxosDataStore

---

infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java
runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java
runtime/src/main/java/org/corfudb/recovery/RecoveryUtils.java
runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
runtime/src/main/java/org/corfudb/runtime/view/ReadOptions.java
runtime/src/main/java/org/corfudb/runtime/view/StreamOptions.java
runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
test/src/test/java/org/corfudb/runtime/view/StreamViewTest.java
test/src/test/java/org/corfudb/runtime/view/stream/AbstractStreamViewTest.java

Porting:
Allow certain streams to not be cached.
nonCacheableStreams (#2015)

Non cacheable streams port

---

runtime/src/main/java/org/corfudb/runtime/view/ObjectBuilder.java

Without this debugging which table name is having issues becomes impossible

Log Stream name + ID on startup to help debugging

---

runtime/src/main/java/org/corfudb/protocols/wireprotocol/ICorfuPayload.java
runtime/src/main/java/org/corfudb/runtime/exceptions/SerializerException.java

Add Detailed Message to IOException

---

infrastructure/src/main/java/org/corfudb/infrastructure/log/LogMetadata.java
test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java

Description:
Correctly build the stream address space of a stream that
is completely checkpointed-- on state transfer
(i.e., a stream built from the checkpoint).

State Transfer Stream Address Space Bug Fix

---

infrastructure/src/main/java/org/corfudb/infrastructure/log/LogMetadata.java
test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java

State transfer stream tail rebuilt bug 0.2.3

---

infrastructure/src/main/java/org/corfudb/infrastructure/LayoutServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
test/src/test/java/org/corfudb/infrastructure/LayoutServerAssertions.java
test/src/test/java/org/corfudb/infrastructure/LayoutServerTest.java

Paxos mutable state port -- Corfu 0.2.3 Port

---

infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
runtime/src/main/java/org/corfudb/runtime/clients/LogUnitHandler.java

[0.2.3] Add logging on LogUnit for Data Corruption Exceptions

---

it/src/main/java/org/corfudb/universe/group/Group.java
it/src/main/java/org/corfudb/universe/group/cluster/AbstractCluster.java
it/src/main/java/org/corfudb/universe/group/cluster/AbstractCorfuCluster.java
it/src/main/java/org/corfudb/universe/group/cluster/AbstractSupportCluster.java
it/src/main/java/org/corfudb/universe/group/cluster/Cluster.java
it/src/main/java/org/corfudb/universe/group/cluster/CorfuCluster.java
it/src/main/java/org/corfudb/universe/group/cluster/SupportClusterParams.java
it/src/main/java/org/corfudb/universe/group/cluster/docker/DockerCorfuCluster.java
it/src/main/java/org/corfudb/universe/group/cluster/docker/DockerSupportCluster.java
it/src/main/java/org/corfudb/universe/node/Node.java
it/src/main/java/org/corfudb/universe/node/client/LocalCorfuClient.java
it/src/main/java/org/corfudb/universe/node/server/SupportServer.java
it/src/main/java/org/corfudb/universe/node/server/SupportServerParams.java
it/src/main/java/org/corfudb/universe/node/server/docker/DockerSupportServer.java
it/src/main/java/org/corfudb/universe/node/server/docker/PromethousConfig.java
it/src/main/java/org/corfudb/universe/scenario/fixture/Fixtures.java
it/src/main/java/org/corfudb/universe/universe/docker/DockerUniverse.java
it/src/test/java/org/corfudb/universe/GenericIntegrationTest.java
it/src/test/java/org/corfudb/universe/scenario/AllNodesPartitionedIT.java

Metrics support for the Universe framework

---

runtime/src/main/java/org/corfudb/recovery/FastObjectLoader.java
test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java

Remove checkpointing related code in fast loader.

Clearup checkpointing in fastloader

---

runtime/src/main/java/org/corfudb/runtime/GarbageInformer.java
runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
runtime/src/main/java/org/corfudb/runtime/view/Layout.java

Previous method to send garbage to LogUnit severs is not correct.

Fix SparseTrim RPC for GC

---

runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java

Expose aggregate statistics for syncObjectUnsafe.
Description:

Expose metrics for syncObjectUnsafe

---

format/pom.xml
runtime/pom.xml
runtime/proto/corfu_options.proto
runtime/proto/corfu_store_metadata.proto
test/pom.xml
test/src/test/resources/proto/test_schema.proto

Description:
Introducing the relevant protobufs required to initialize the CorfuStore.
Introducing CorfuStore.

Adding Protobufs for CorfuStore [PART 1]

---

runtime/src/main/java/org/corfudb/runtime/collections/CorfuRecord.java
runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java
runtime/src/main/java/org/corfudb/runtime/collections/ProtobufIndexer.java
runtime/src/main/java/org/corfudb/runtime/collections/Query.java
runtime/src/main/java/org/corfudb/runtime/collections/QueryOptions.java
runtime/src/main/java/org/corfudb/runtime/collections/QueryResult.java
test/src/test/java/org/corfudb/integration/CorfuStoreIT.java
test/src/test/java/org/corfudb/integration/CorfuStorePerfIT.java
test/src/test/java/org/corfudb/integration/Event.java
test/src/test/java/org/corfudb/runtime/collections/CorfuStoreTest.java

CorfuStore: Add Query, QueryOptions, QueryResult [PART 3]

---

runtime/proto/corfu_store_metadata.proto
runtime/src/main/java/org/corfudb/runtime/collections/CorfuDynamicKey.java
runtime/src/main/java/org/corfudb/runtime/collections/CorfuDynamicMessage.java
runtime/src/main/java/org/corfudb/runtime/collections/CorfuDynamicRecord.java
runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java
runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java
runtime/src/main/java/org/corfudb/util/serializer/DynamicProtobufSerializer.java
runtime/src/main/java/org/corfudb/util/serializer/ProtobufSerializer.java
samples/pom.xml
test/src/test/java/org/corfudb/integration/CorfuStoreIT.java

Schema-less tooling

---

.travis.yml
samples/pom.xml
samples/proto/person_profile.proto
samples/proto/vehicle.proto
samples/proto/work_experience.proto
samples/src/main/java/org/corfudb/samples/CorfuStoreSample.java

Description:
Sample application to write and read from CorfuStore.
Sample code to help write applications.

CorfuStore Sample App

---

it/src/main/java/org/corfudb/universe/node/client/ClientParams.java
it/src/main/java/org/corfudb/universe/node/server/CorfuServerParams.java
it/src/main/java/org/corfudb/universe/node/server/SupportServerParams.java
pom.xml

Description:
Bump lombok version to 1.18.10

Bump lombok version to 1.18.10

---

corfudb-tools/README
corfudb-tools/pom.xml
corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowser.java
corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserMain.java
corfudb-tools/src/main/resources/logback.prod.xml
pom.xml
samples/src/main/java/org/corfudb/samples/CorfuStoreSample.java
test/pom.xml
test/src/test/java/org/corfudb/integration/CorfuStoreBrowserIT.java

Schemaless Browser Tool using Dynamic Messages.
Description:

Schemaless Browser Tool

---

runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java

Description:
This change allowed us to identify which streams are responsible for the deserialization exception and is critical to triaging deployment issues.

Log the address & streams on deserialization exceptions

---

runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java
runtime/src/main/java/org/corfudb/runtime/collections/CorfuStreamEntries.java
runtime/src/main/java/org/corfudb/runtime/collections/CorfuStreamEntry.java
runtime/src/main/java/org/corfudb/runtime/collections/StreamListener.java
runtime/src/main/java/org/corfudb/runtime/collections/TableSchema.java

Introduces the streaming api for CorfuStore
These are just stubs for clients to code against.
Implementation will follow later.

CorfuStore: add Streaming API interfaces and stubs

---

runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
runtime/src/main/java/org/corfudb/runtime/ViewsGarbageCollector.java
runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
runtime/src/main/java/org/corfudb/runtime/object/ISMRStream.java
runtime/src/main/java/org/corfudb/runtime/object/StreamViewSMRAdapter.java
runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/AbstractTransactionalContext.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/WriteSetSMRStream.java
runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java
runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
runtime/src/main/java/org/corfudb/runtime/view/replication/AbstractReplicationProtocol.java
runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractStreamContext.java
runtime/src/main/java/org/corfudb/runtime/view/stream/IStreamView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/ThreadSafeStreamView.java

Trim runtime garbage at all layers when compactionMark is updated.

Re-introduce ViewsGarbageCollector

---

runtime/src/main/java/org/corfudb/runtime/GarbageInformer.java
test/src/test/java/org/corfudb/recovery/FastObjectLoaderTest.java
test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTransactionContextTest.java
test/src/test/java/org/corfudb/runtime/object/transactions/SnapshotTransactionContextTest.java

fix some bugs which usages gcUnsafe in an incorrect way.

fix not thread-safe usage of gcUnsafe

---

corfudb-tools/README
debian/pom.xml

Description:
Packaging the browser in the debian file.
This is not deployed to the appliance otherwise.

[CorfuStore] Packaging the CorfuStoreBrowser.

---

runtime/src/main/java/org/corfudb/runtime/collections/CorfuStoreEntry.java
runtime/src/main/java/org/corfudb/runtime/collections/Query.java
runtime/src/main/java/org/corfudb/runtime/collections/QueryOptions.java
runtime/src/main/java/org/corfudb/runtime/collections/Table.java
test/src/test/java/org/corfudb/runtime/collections/CorfuStoreTest.java

Description:
Added API to return key with the payload on scan and filter and queries.
Added API to return the keyset.
Added API to clear a table.

[CorfuStore] API to return CorfuStoreEntries, keySet & clear.

---

runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java
runtime/src/main/java/org/corfudb/runtime/collections/CorfuStreamEntry.java
runtime/src/main/java/org/corfudb/runtime/collections/StreamingSubscriptionContext.java
runtime/src/main/java/org/corfudb/runtime/collections/TableSchema.java
runtime/src/main/java/org/corfudb/runtime/collections/TransactionPoller.java
runtime/src/main/java/org/corfudb/runtime/collections/TxnStreamingManager.java
test/src/test/java/org/corfudb/integration/StreamingIT.java

Description:
This is the first cut of the implementation of the streaming APIs of the CorfuStore.
This change has two commits, 
1. Sundar's API and stub change.
2. Change to implement the APIs.
I am still working on the unit tests.

CorfuStore: Implementation of Streaming APIs

---

runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java

Re-add APIs for temporary backward compatibility for easier integration.

Re-add APIs for temporary backward compatibility for easier integration.

---

.travis.yml

Setup settings.xml in travis.yml
Without settings.xml it's not possible to deploy artifacts
Description:

Setup settings.xml in travis.yml

---

corfudb-tools/README
corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserMain.java
corfudb-tools/src/main/resources/logback.xml
runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java

Description:
Needed to debug a case where a particular entry cannot be deserialized.

Log the byteBuf on deserialization error

---

coverage/pom.xml

Description:
Lower report aggregate maven build phase to 'test' so it runs on travis.

Change Report Aggregate Maven Phase

---

pom.xml

Update netty-all and netty-tcnative versions.

Update Netty Version

---

corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowser.java
corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserMain.java

Callers want a way to clear the contents of a CorfuStore table via CLI.
They also want a way to just show the size of a table without actually dumping the whole content.

CorfuStoreBrowser: Support infoTable and dropTable

---

corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowser.java
corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserMain.java
test/src/test/java/org/corfudb/integration/CorfuStoreBrowserIT.java

Move all functionality out of the Main class.
Address review comments left out in previous review.
Add code coverage tests for all the new functions.

CorfuBrowser: Use Nullable, refactor code

---

pom.xml

Description:
Make AsserJ up-to-date. The current version is more than 2 years old

Update assertj to 3.14.0

---

common/pom.xml
infrastructure/pom.xml
runtime/pom.xml
runtime/src/main/java/org/corfudb/util/MetricsUtils.java

Description:
Update dropwizard-metrics. The current version is archaic from 2014

Update dropwizard-metrics to 4.1.2

---

.gitignore

Description:
Ignore flattened pom files in git repo

Ignore flattened pom files

---

benchmarks/pom.xml
benchmarks/src/jmh/java/org/corfudb/benchmarks/cluster/ClusterBenchmark.java
benchmarks/src/jmh/resources/corfu.version
benchmarks/src/main/resources/logback.xml
it/src/main/java/org/corfudb/universe/UniverseAppUtil.java
it/src/test/java/org/corfudb/universe/GenericIntegrationTest.java

Fix benchmark module to make it work with the latest version of the universe framework
Description:

Make benchmark module to work with latest version of universe fr

---

runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java

This patch removes a circular dependency between threads acquiring
the VLO lock and threads used for parallel stream operations (i.e
scanAndFilter).
Why should this be merged: Fixes a deadlock bug

VersionLockedObject and CorfuTable Deadlock

---

log-replication/src/main/java/org/corfudb/logreplication/fsm/InLogEntrySyncState.java
log-replication/src/main/java/org/corfudb/logreplication/fsm/InRequireSnaphotSyncState.java
log-replication/src/main/java/org/corfudb/logreplication/fsm/InSnapshotSyncState.java
log-replication/src/main/java/org/corfudb/logreplication/fsm/InitializedState.java
log-replication/src/main/java/org/corfudb/logreplication/fsm/LogReplicationConfig.java
log-replication/src/main/java/org/corfudb/logreplication/fsm/LogReplicationEvent.java
log-replication/src/main/java/org/corfudb/logreplication/fsm/LogReplicationFSM.java
log-replication/src/main/java/org/corfudb/logreplication/receiver/RxMessage.java
log-replication/src/main/java/org/corfudb/logreplication/transmitter/ReplicationManager.java
log-replication/src/main/java/org/corfudb/logreplication/transmitter/SnapshotReader.java
log-replication/src/main/java/org/corfudb/logreplication/transmitter/SnapshotSyncContext.java

Fix package name on SnapshotReader

---

log-replication/src/main/java/org/corfudb/logreplication/fsm/LogReplicationConfig.java

State and Events redefined

---

log-replication/src/main/java/org/corfudb/logreplication/transmitter/SnapshotReader.java

Adding some comments.

---

log-replication/src/main/java/org/corfudb/logreplication/fsm/LogReplicationEvent.java
log-replication/src/main/java/org/corfudb/logreplication/receiver/DataReceiver.java
log-replication/src/main/java/org/corfudb/logreplication/receiver/LogEntryWriter.java
log-replication/src/main/java/org/corfudb/logreplication/receiver/SnapshotWriter.java
log-replication/src/main/java/org/corfudb/logreplication/transmitter/LogEntryReader.java
log-replication/src/main/java/org/corfudb/logreplication/transmitter/SnapshotReader.java

Add comments to reader/writer.

---

log-replication/src/main/java/org/corfudb/logreplication/PersistedReplicationMetadata.java
log-replication/src/main/java/org/corfudb/logreplication/fsm/LogReplicationConfig.java
log-replication/src/main/java/org/corfudb/logreplication/receiver/LogEntryWriter.java
log-replication/src/main/java/org/corfudb/logreplication/receiver/PersistedWriterMetadata.java
log-replication/src/main/java/org/corfudb/logreplication/receiver/StreamsSnapshotWriter.java
log-replication/src/main/java/org/corfudb/logreplication/transmitter/PersistedReaderMetadata.java
log-replication/src/main/java/org/corfudb/logreplication/transmitter/StreamsLogEntryReader.java
log-replication/src/main/java/org/corfudb/logreplication/transmitter/StreamsSnapshotReader.java

Adding persistent metadata for log reader/writer.

---

runtime/src/main/java/org/corfudb/runtime/collections/PersistedStreamingMap.java
runtime/src/main/java/org/corfudb/runtime/collections/RocksDbEntryIterator.java
test/src/test/java/org/corfudb/runtime/collections/DiskBackedCorfuClientTest.java
test/src/test/java/org/corfudb/runtime/collections/RocksDbEntryIteratorTest.java

Implement keySet

---

log-replication/src/main/java/org/corfudb/logreplication/SinkManager.java
log-replication/src/main/java/org/corfudb/logreplication/message/MessageMetadata.java
log-replication/src/main/java/org/corfudb/logreplication/receive/LogEntryWriter.java
test/src/test/java/org/corfudb/integration/LogEntryReplicationIT.java
test/src/test/java/org/corfudb/integration/StreamSnapshotReplicationIT.java
test/src/test/java/org/corfudb/logreplication/fsm/StreamLogEntryReaderWriterTest.java

Move ack to DataSender. Will DataSender from writer.

---

infrastructure/src/main/java/org/corfudb/infrastructure/log/GarbageLogSegment.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogCompactor.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
test/src/test/java/org/corfudb/runtime/object/transactions/AbstractTransactionsTest.java

GC: Fix potential issues in garbage write path on both server & client.

GC: Fix potential issues in garbage write path on server & client.

---

runtime/src/main/java/org/corfudb/protocols/wireprotocol/ILogData.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
test/src/test/java/org/corfudb/runtime/CompressionTest.java
test/src/test/java/org/corfudb/runtime/view/AddressSpaceViewTest.java
test/src/test/java/org/corfudb/runtime/view/ChainReplicationViewTest.java
test/src/test/java/org/corfudb/runtime/view/StateTransferTest.java

Change Codec String Types to Enums

---

log-replication/src/main/java/org/corfudb/logreplication/fsm/InLogEntrySyncState.java
log-replication/src/main/java/org/corfudb/logreplication/send/LogEntrySender.java
test/src/test/java/org/corfudb/integration/StreamSnapshotReplicationIT.java
test/src/test/java/org/corfudb/logreplication/fsm/LogReplicationFSMTest.java

Seek Opaque Stream only on Snapshot Sync Transition

---

log-replication/src/main/java/org/corfudb/logreplication/SinkManager.java
log-replication/src/main/java/org/corfudb/logreplication/SourceManager.java
test/src/test/java/org/corfudb/integration/StreamSnapshotReplicationIT.java

- Fix SinkManager sending ACK after apply

Add integer as ACK counter in SourceManager

---

log-replication/src/main/java/org/corfudb/logreplication/SinkManager.java
log-replication/src/main/java/org/corfudb/logreplication/send/LogEntrySender.java
log-replication/src/main/java/org/corfudb/logreplication/send/StreamsLogEntryReader.java
test/src/test/java/org/corfudb/integration/LogReplicationIT.java
test/src/test/java/org/corfudb/integration/SourceForwardingDataSender.java
test/src/test/java/org/corfudb/logreplication/fsm/LogReplicationFSMTest.java

- Fix NullPointer Bug on SinkManager
- Add log entry sync cross table (invalid) test

Rename Log Replication IT

---

corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowser.java
corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserMain.java
runtime/proto/corfu_store_metadata.proto
runtime/src/main/java/org/corfudb/runtime/collections/Table.java
runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java
runtime/src/main/java/org/corfudb/util/serializer/DynamicProtobufSerializer.java
test/src/test/java/org/corfudb/integration/CorfuStoreBrowserIT.java
test/src/test/java/org/corfudb/integration/CorfuStoreIT.java

This is needed for the checkpointer to make sure that
a disk based table is opened as a disk based table and
not an in-memory table.

CorfuStore: Record if table is opened as disk based

---

log-replication/src/main/java/org/corfudb/logreplication/SourceManager.java
log-replication/src/main/java/org/corfudb/logreplication/fsm/ObservableAckMsg.java
test/src/test/java/org/corfudb/integration/LogReplicationIT.java

Federation: Add Ack Msg Observable.

---

it/src/main/java/org/corfudb/universe/UniverseManager.java
it/src/main/java/org/corfudb/universe/group/Group.java
it/src/main/java/org/corfudb/universe/group/cluster/AbstractCluster.java
it/src/main/java/org/corfudb/universe/group/cluster/AbstractCorfuCluster.java
it/src/main/java/org/corfudb/universe/group/cluster/AbstractSupportCluster.java
it/src/main/java/org/corfudb/universe/group/cluster/CorfuCluster.java
it/src/main/java/org/corfudb/universe/group/cluster/docker/DockerCorfuCluster.java
it/src/main/java/org/corfudb/universe/group/cluster/process/ProcessCorfuCluster.java
it/src/main/java/org/corfudb/universe/group/cluster/vm/RemoteOperationHelper.java
it/src/main/java/org/corfudb/universe/group/cluster/vm/VmCorfuCluster.java
it/src/main/java/org/corfudb/universe/node/client/LocalCorfuClient.java
it/src/main/java/org/corfudb/universe/node/server/AbstractCorfuServer.java
it/src/main/java/org/corfudb/universe/node/server/process/ExecutionHelper.java
it/src/main/java/org/corfudb/universe/node/server/process/ProcessCorfuServer.java
it/src/main/java/org/corfudb/universe/node/server/vm/VmCorfuServer.java
it/src/main/java/org/corfudb/universe/node/server/vm/VmCorfuServerParams.java
it/src/main/java/org/corfudb/universe/scenario/fixture/Fixtures.java
it/src/main/java/org/corfudb/universe/universe/docker/FakeDns.java
it/src/main/java/org/corfudb/universe/universe/process/ProcessUniverse.java
it/src/main/java/org/corfudb/universe/universe/vm/VmManager.java
it/src/main/java/org/corfudb/universe/universe/vm/VmUniverse.java
it/src/test/java/org/corfudb/universe/GenericIntegrationTest.java
it/src/test/java/org/corfudb/universe/scenario/OneNodeDownIT.java

Description:
Universe: Download Corfu logs from remote VM-s fixes/improvements

Universe framework: collect server logs, fixes for VM/PROCESS

---

runtime/src/main/java/org/corfudb/runtime/exceptions/TrimmedException.java
test/src/test/java/org/corfudb/integration/ReplicationReaderWriterIT.java

Test TrimmedException on Snapshot Reader and LogEntryReader

---

runtime/src/main/java/org/corfudb/runtime/BootstrapUtil.java
runtime/src/main/java/org/corfudb/runtime/RebootUtil.java
runtime/src/main/java/org/corfudb/runtime/clients/NettyClientRouter.java
test/src/test/java/org/corfudb/runtime/clients/NettyClientRouterTest.java

Thread Clean Up

---

infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServerCache.java
test/src/test/java/org/corfudb/runtime/object/transactions/SequencerServerCacheTest.java

Reverts CorfuDB/CorfuDB#2300
We have decided to perform additional testing before merging into the master.

Revert "Xq/seqcache01"

---

infrastructure/src/main/java/org/corfudb/infrastructure/LogReplicationServer.java
log-replication/resources/corfu_replication_config.properties
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationManager.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CrossSiteConfiguration.java
log-replication/src/main/java/org/corfudb/logreplication/runtime/LogReplicationClient.java
log-replication/src/main/java/org/corfudb/logreplication/runtime/LogReplicationHandler.java
log-replication/src/main/java/org/corfudb/logreplication/runtime/LogReplicationRuntime.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/CorfuMsgType.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/logreplication/LogReplicationQueryLeaderShipResponse.java

Implement discovery log replication topology service.

---

infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServerCache.java
test/src/test/java/org/corfudb/runtime/object/transactions/SequencerServerCacheTest.java

This reverts commit 7f9c3fef9fcca6b0ced3f1ea92c3b42af67525b3.
Description:

Revert "Revert "Xq/seqcache01 (#2300)" (#2464)"

---

infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java
infrastructure/src/main/java/org/corfudb/infrastructure/management/CompleteGraphAdvisor.java

Description:
Decrease level of logging for not important logs

Failure detector logs

---

test/src/test/java/org/corfudb/integration/SourceForwardingDataSender.java

Fix tests.

---

log-replication/src/main/java/org/corfudb/logreplication/send/LogEntrySender.java
test/src/test/java/org/corfudb/integration/LogReplicationIT.java
test/src/test/java/org/corfudb/integration/SourceForwardingDataSender.java

Description:
- Return empty CompletableFuture when message is dropped (test)
- On Log Entry Message Resend register CF for completion

Fix IT Tests

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/SinkManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/StreamsSnapshotWriter.java

* Only apply SMR entries that with higher address than the cleartable.
Description:

Optimized applying shadow streams.

---

infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServerCache.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
test/src/test/java/org/corfudb/infrastructure/LogUnitServerTest.java

Include deep size of metadataMap in LogData size calculation for Caffeine.

Include deep size of metadataMap in LogData size calculation for Caffeine

---

runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java
test/src/test/java/org/corfudb/runtime/collections/CorfuStoreTest.java

Description:
Consumers of CorfuStore are ok expecting their transactions aborting due to conflict but prefer that internal transactions like the one in openTable() be retried automatically on failure

CorfuStore: retry internal txns on openTable

---

log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationServer.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationSiteManagerAdapter.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CrossSiteConfiguration.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/DefaultSiteManager.java

Add SiteManager Adapter and default implementation.

---

log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationManager.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationServer.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationSiteManagerAdapter.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/DefaultSiteManager.java
log-replication/src/main/java/org/corfudb/logreplication/runtime/LogReplicationRuntime.java

Notification of Site Role Change.

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/LogReplicationConfig.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/PersistedWriterMetadata.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/SinkManager.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationManager.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationServer.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationSiteManagerAdapter.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CrossSiteConfiguration.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/DefaultSiteManager.java
test/src/test/java/org/corfudb/integration/CorfuReplicationE2EIT.java
test/src/test/java/org/corfudb/integration/LogReplicationIT.java
test/src/test/java/org/corfudb/integration/ReplicationReaderWriterIT.java
test/src/test/java/org/corfudb/logreplication/fsm/ReplicationReaderWriterTest.java

* Add a notification for site change to notify the app for test purpose.
* Make corfu mananger as a runnable to start as a thread.
* Add both src site and dst site info as part of the metadata file
* Todo: add site epoc to the persistent writer information.
* Todo: make apply as a synchronized function.
Description:

Add a test case for site role type change.

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/LogReplicationConfig.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/SinkBufferManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/SinkManager.java
log-replication/src/main/java/org/corfudb/logreplication/fsm/LogReplicationFSM.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationManager.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationSiteManagerAdapter.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CrossSiteConfiguration.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/DefaultSiteManager.java
log-replication/src/main/java/org/corfudb/logreplication/runtime/LogReplicationRuntime.java
log-replication/src/main/java/org/corfudb/logreplication/send/LogEntryReader.java
log-replication/src/main/java/org/corfudb/logreplication/send/SnapshotReader.java
log-replication/src/main/java/org/corfudb/logreplication/send/SnapshotSender.java
log-replication/src/main/java/org/corfudb/logreplication/send/StreamsLogEntryReader.java
log-replication/src/main/java/org/corfudb/logreplication/send/StreamsSnapshotReader.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/logreplication/LogReplicationEntry.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/logreplication/LogReplicationEntryMetadata.java
test/src/test/java/org/corfudb/integration/CorfuReplicationE2EIT.java
test/src/test/java/org/corfudb/integration/LogReplicationIT.java
test/src/test/java/org/corfudb/integration/ReplicationReaderWriterIT.java
test/src/test/java/org/corfudb/logreplication/fsm/EmptySnapshotReader.java
test/src/test/java/org/corfudb/logreplication/fsm/LogReplicationFSMTest.java
test/src/test/java/org/corfudb/logreplication/fsm/ReplicationReaderWriterTest.java
test/src/test/java/org/corfudb/logreplication/fsm/TestLogEntryReader.java
test/src/test/java/org/corfudb/logreplication/fsm/TestSnapshotReader.java

Add epoch to cross site config and log message.

---

log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationServer.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationSiteManagerAdapter.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/DefaultSiteManager.java
test/src/test/java/org/corfudb/integration/CorfuReplicationE2EIT.java

Add eventQueue API for Site Discovery Service.

---

runtime/src/main/java/org/corfudb/runtime/collections/TxBuilder.java
test/src/test/java/org/corfudb/logreplication/fsm/ReplicationReaderWriterTest.java

Add logUpdate API for CorfuStore TxBuilder.

---

cmdlets/pom.xml
format/pom.xml
runtime/pom.xml
samples/pom.xml
test/pom.xml

Description:
Keeps it consistent with verticals consuming it.

Upgrade to proto 3.6.1

---

log-replication/src/main/java/org/corfudb/logreplication/SourceManager.java
log-replication/src/main/java/org/corfudb/logreplication/fsm/LogReplicationEvent.java
log-replication/src/main/java/org/corfudb/logreplication/fsm/LogReplicationFSM.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationManager.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CrossSiteConfiguration.java
log-replication/src/main/java/org/corfudb/logreplication/runtime/LogReplicationRuntime.java
log-replication/src/main/java/org/corfudb/logreplication/send/LogEntrySender.java
test/src/test/java/org/corfudb/integration/LogReplicationIT.java
test/src/test/java/org/corfudb/integration/SourceForwardingDataSender.java

Stop log replication properly.

---

infrastructure/pom.xml
infrastructure/proto/log_replication_writer_metadata.proto
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/LogEntryWriter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/PersistedWriterMetadata.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/SinkManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/StreamsSnapshotWriter.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationServer.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/DefaultSiteManager.java
log-replication/src/main/java/org/corfudb/logreplication/send/StreamsSnapshotReader.java
runtime/src/main/java/org/corfudb/runtime/collections/TxBuilder.java
test/src/test/java/org/corfudb/integration/LogReplicationIT.java
test/src/test/java/org/corfudb/logreplication/fsm/ReplicationReaderWriterTest.java

Implement persistent writer metadata with UFO API.

---

pom.xml

Upgrade Netty to 4.1.50.Final [2.3 bport]

---

pom.xml

```
+----------------+--------+----------------------+
| CVE            |   CVSS | Date                 |
|----------------+--------+----------------------|
| CVE-2019-20445 |    9.1 | 2020-01-29T21:15:00Z |
| CVE-2019-20444 |    9.1 | 2020-01-29T21:15:00Z |
| CVE-2020-7238  |    7.5 | 2020-01-27T17:15:00Z |
| CVE-2020-11612 |    9.8 | 2020-04-07T18:15:00Z |
+----------------+--------+----------------------+
```
Description:

Upgrade Netty to 4.1.50.Final

---

cmdlets/pom.xml
it/pom.xml

Description:
Compliance requirements

Upgrade jackson-databind to 2.10.1

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/receive/LogReplicationSinkManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/receive/PersistedWriterMetadata.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/receive/SinkBufferManager.java
log-replication/resources/corfu_replication_config.properties
log-replication/src/main/java/org/corfudb/logreplication/fsm/InSnapshotSyncState.java
log-replication/src/main/java/org/corfudb/logreplication/fsm/LogReplicationFSM.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuInterClusterReplicationServer.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationManager.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CrossSiteConfiguration.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/DefaultSiteManager.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/DiscoveryServiceEvent.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/LogReplicationLockListener.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/LogReplicationNodeInfo.java
log-replication/src/main/java/org/corfudb/logreplication/runtime/CorfuLogReplicationRuntime.java
log-replication/src/main/java/org/corfudb/logreplication/runtime/LogReplicationClient.java
log-replication/src/main/java/org/corfudb/logreplication/send/LogEntrySender.java
log-replication/src/main/java/org/corfudb/logreplication/send/SnapshotSender.java
log-replication/src/main/java/org/corfudb/logreplication/send/logreader/LogEntryReader.java
log-replication/src/main/java/org/corfudb/logreplication/send/logreader/StreamsLogEntryReader.java
log-replication/src/main/java/org/corfudb/logreplication/send/logreader/StreamsSnapshotReader.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/logreplication/LogReplicationEntryMetadata.java
runtime/src/main/proto/messages.proto
test/src/test/java/org/corfudb/integration/CorfuReplicationSiteConfigIT.java
test/src/test/java/org/corfudb/integration/SourceForwardingDataSender.java
test/src/test/java/org/corfudb/logreplication/fsm/TestLogEntryReader.java
utils/src/main/java/org/corfudb/utils/common/CorfuMessageConverter.java

Add site flip test.

---

log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuInterClusterReplicationServer.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationDiscoveryServiceAdapter.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationManager.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/CorfuReplicationSiteManagerAdapter.java
log-replication/src/main/java/org/corfudb/logreplication/infrastructure/DefaultSiteManager.java
log-replication/src/main/java/org/corfudb/logreplication/runtime/CorfuLogReplicationRuntime.java
test/src/test/java/org/corfudb/integration/CorfuReplicationSiteConfigIT.java

Add Query of log replication status API.

---

cmdlets/pom.xml
it/pom.xml

Compliance upgrade.
Description:

Upgrade jackson-databind to 2.11.0

---

runtime/pom.xml
runtime/src/main/java/org/corfudb/runtime/collections/PersistedStreamingMap.java
runtime/src/main/java/org/corfudb/runtime/collections/WrappedRocksIterator.java
test/src/test/java/org/corfudb/runtime/collections/DiskBackedCorfuClientTest.java

```
+----------------+--------+----------------------+
| CVE            |   CVSS | Date                 |
|----------------+--------+----------------------|
| CVE-2016-3189  |    6.5 | 2016-06-30T17:59:00Z |
| CVE-2019-12900 |    9.8 | 2019-06-19T23:15:00Z |
+----------------+--------+----------------------+
```
Description:

Upgrade org.rocksdb.rocksdbjni to 6.8.1

---

cmdlets/pom.xml
format/pom.xml
it/pom.xml
pom.xml
runtime/pom.xml
runtime/src/main/java/org/corfudb/runtime/collections/PersistedStreamingMap.java
runtime/src/main/java/org/corfudb/runtime/collections/WrappedRocksIterator.java
samples/pom.xml
test/pom.xml
test/src/test/java/org/corfudb/runtime/collections/DiskBackedCorfuClientTest.java

Upgrade protobuf3.61 netty4.1.50 jackson2.11.0 BPORT

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/ClusterDescriptor.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryServiceAdapter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/NodeDescriptor.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/TopologyDescriptor.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/CorfuReplicationClusterManagerAdapter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultClusterManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationSourceManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/EmptySnapshotReader.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/LogReplicationFSM.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/TestLogEntryReader.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/TestSnapshotReader.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SnapshotSender.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/LogEntryReader.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/SnapshotReader.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/StreamsLogEntryReader.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/StreamsSnapshotReader.java
test/src/test/java/org/corfudb/integration/CorfuReplicationSiteConfigIT.java
test/src/test/resources/logback-test.xml

Description:
Fix topology config change logic and make CorfuReplicationSiteConfigIT work

Fix topology config change logic

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/utils/LogReplicationStreamNameTableManager.java

If the version table is dropped using the CorfuStoreBrowser(UFO) for testing, it will be empty and should be re-created.

Handle the case where Version Table is empty.

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryServiceAdapter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/CorfuReplicationClusterManagerAdapter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/CorfuReplicationClusterManagerBaseAdapter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/CorfuReplicationSiteManagerBaseAdapter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultClusterManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/LogReplicationPluginConfig.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/NegotiatingState.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/VerifyingRemoteLeaderState.java
test/src/test/java/org/corfudb/integration/CorfuReplicationSiteConfigIT.java

Add ClusterManager Interface.

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/StreamsLogEntryReader.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/NegotiatingState.java

Add logging around negotiation response processing for debugging.

Add Logging around Negotiation Response Processing

---

pom.xml

Description:
Updare corfu version to 0.3.1-SNAPSHOT

Updare corfu version to 0.3.1-SNAPSHOT

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java
utils/src/main/java/org/corfudb/utils/lock/persistence/LockStore.java

Description:
Consolidate Corfu's System Namespace, to the commonly used.

Use Corfu's common system namespace

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/ObservableAckMsg.java
test/src/test/java/org/corfudb/integration/LogReplicationIT.java
test/src/test/java/org/corfudb/integration/ReplicationReaderWriterIT.java
test/src/test/java/org/corfudb/integration/SourceForwardingDataSender.java

Description:
Fix testLogEntrySyncValidCrossTablesWithWritingAtSrc IT

Fix Log Replication Failing IT

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InSnapshotSyncState.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InitializedState.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SnapshotSender.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/StreamsLogEntryReader.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/StreamsSnapshotReader.java
test/src/test/java/org/corfudb/infrastructure/logreplication/LogUpdateAPITest.java

Description:
Improve debugging with extra logging.

Add Logging

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/LogReplicationNegotiationException.java

Description: Correct printing of Negotiation Exception cause.

Message on LR Negotiation Exception

---

runtime/pom.xml

upgrade RoaringBitmap

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultClusterManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationSourceManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SenderBufferManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/CorfuLogReplicationRuntime.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/LogReplicationClientRouter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/ReplicatingState.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/VerifyingRemoteLeaderState.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/WaitingForConnectionsState.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/sample/NettyLogReplicationServerChannelAdapter.java
runtime/src/main/java/org/corfudb/runtime/collections/TransactionPoller.java
test/src/test/java/org/corfudb/integration/CorfuReplicationReconfigurationIT.java
test/src/test/java/org/corfudb/integration/LogReplicationAbstractIT.java
utils/src/main/java/org/corfudb/utils/lock/Lock.java
utils/src/main/java/org/corfudb/utils/lock/LockClient.java
utils/src/main/java/org/corfudb/utils/lock/states/HasLeaseState.java
utils/src/main/java/org/corfudb/utils/lock/states/LockState.java

Description:
1. Fix Issue when Standby connection is lost
2. Fix replication server graceful shutdown
3. Add logging
4. Adjust default and configurable lock values: monitor, renewal, lease duration and lease check

Standby Connection Loss Fix

---

infrastructure/proto/log_replication_metadata.proto
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationAckReader.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SnapshotSender.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SnapshotSenderBufferManager.java

Sync Status API improvements.

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuInterClusterReplicationServer.java
runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java

+Add in cleanshutdown too
Description:

Flush logger context for LR on exit

---

test/src/test/java/org/corfudb/integration/LockIT.java

#Overview
Description:
- Intermittent failures due to race condition on FSM transition which affects all other 3 tests in LockIT.
Why should this be merged: stabilize Lock ITs
Related issue(s) (if applicable): #2700

Fix Lock ITs

---

runtime/src/main/java/org/corfudb/runtime/collections/CorfuQueue.java
test/src/test/java/org/corfudb/runtime/collections/CorfuQueueTest.java

Since CorfuQueue::enqueue depends on a transactional context to
work correctly, a validation step is required to fail enqueue
calls that are not within a transaction.
Description:
Why should this be merged: Addresses #2710

Fail Non-Transactional Enqueue

---

runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiObjectSMREntry.java
runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java

Measure Serialize/Deserialize/VLO_SYNC latency

---

runtime/src/main/java/org/corfudb/protocols/wireprotocol/DataType.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/ILogData.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/IMetadata.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
runtime/src/main/java/org/corfudb/runtime/view/replication/ChainReplicationProtocol.java
runtime/src/main/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocol.java
runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
test/src/test/java/org/corfudb/runtime/clients/LogUnitHandlerTest.java

Description:
- Reuse serialization handle, which reduces number of serializations.
- Acquire token after payload serialized, which reduces reader wait time.
Related issue(s) (if applicable): #1949

Stream write path performance optimization.

---

runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java

If layoutHelper returns a WrongClusterException best to shutdown

---

infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogDataStore.java
runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
test/src/test/java/org/corfudb/infrastructure/AutoCommitServiceTest.java

Description:
Fix auto commit range check and flaky unit test.
Related issue(s) (if applicable): #2725, #2730

Fix auto commit range check and flaky unit test.

---

corfudb-tools/pom.xml
corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowser.java
corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserMain.java
test/src/test/java/org/corfudb/integration/CorfuStoreBrowserIT.java

Use JsonFormat to display for future editing
Description:

CorfuStoreBrowser: variable size records for loading data

---

infrastructure/src/main/java/org/corfudb/infrastructure/AutoCommitService.java
test/src/test/java/org/corfudb/infrastructure/AutoCommitServiceTest.java

Fix unit test that is not calling join on futures.
Why should this be merged: Fix unit test that can fail in some cases.

Fix unit test that is not calling join on futures.

---

infrastructure/src/main/java/org/corfudb/infrastructure/log/statetransfer/segment/TransferSegmentRangeSplit.java

Description:
Fixes annotation imports.

Fix annotations for TransferSegmentRangeSplit

---

infrastructure/proto/log_replication_metadata.proto
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/ClusterDescriptor.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryServiceAdapter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/DiscoveryServiceEvent.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/LogReplicationEventListener.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/CorfuReplicationClusterManagerAdapter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/CorfuReplicationClusterManagerBaseAdapter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationAckReader.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationSourceManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InLogEntrySyncState.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InSnapshotSyncState.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InitializedState.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/LogReplicationEvent.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/LogReplicationFSM.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/StoppedState.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/WaitSnapshotApplyState.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/LogReplicationEventMetadata.java
test/src/test/java/org/corfudb/infrastructure/logreplication/LogReplicationFSMTest.java
test/src/test/java/org/corfudb/integration/CorfuReplicationClusterConfigIT.java
test/src/test/java/org/corfudb/integration/LogReplicationIT.java

Description:
Added return value for force sync

Store Snapshot Sync Info in Sync Status table

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SnapshotSender.java
test/src/test/java/org/corfudb/integration/LogReplicationIT.java

Description:
- Bring back original semantics of this test
- Bug Fix to cover this test case
Why should this be merged: Brings back a valid test case which semantics was lost by a change.

Fix testSnapshotSyncForEmptyLog

---

infrastructure/proto/log_replication_metadata.proto
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationAckReader.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java
test/src/test/java/org/corfudb/integration/CorfuReplicationClusterConfigIT.java

Description:
Set Sync status for LR

Added Unavailable + Not_Started to LR

---

infrastructure/proto/sample.proto
infrastructure/src/main/java/org/corfudb/infrastructure/LogReplicationServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultLogReplicationConfigAdapter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/StreamsSnapshotWriter.java
test/src/test/java/org/corfudb/integration/CorfuReplicationE2EIT.java
test/src/test/java/org/corfudb/integration/CorfuReplicationReconfigurationIT.java
test/src/test/java/org/corfudb/integration/CorfuReplicationTrimIT.java
test/src/test/java/org/corfudb/integration/LogReplicationAbstractIT.java

[Backport] Resume Snapshot Sync Apply on Restart

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/ClusterDescriptor.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/TopologyDescriptor.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/LogReplicationPluginConfig.java

Use Node Id to match topology for LR

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/ClusterDescriptor.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/TopologyDescriptor.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/LogReplicationPluginConfig.java

Addressed comments
Description:

[Backport] Use node_id to match topology in LR

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/LogReplicationEventListener.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultClusterManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/utils/LogReplicationStreamNameTableManager.java
runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java
runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java
runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java
runtime/src/main/java/org/corfudb/util/serializer/DynamicProtobufSerializer.java
runtime/src/main/java/org/corfudb/util/serializer/ProtobufSerializer.java
test/src/test/java/org/corfudb/integration/CorfuReplicationClusterConfigIT.java
test/src/test/java/org/corfudb/integration/CorfuReplicationReconfigurationIT.java
test/src/test/java/org/corfudb/integration/CorfuStoreBrowserIT.java
test/src/test/java/org/corfudb/integration/CorfuStoreIT.java
utils/src/main/java/org/corfudb/utils/lock/persistence/LockStore.java

Disable TX Logging for LR

---

runtime/proto/corfu_options.proto
runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
runtime/src/main/java/org/corfudb/runtime/collections/Table.java
runtime/src/main/java/org/corfudb/runtime/collections/TxnContext.java
test/src/test/java/org/corfudb/runtime/collections/CorfuStoreShimTest.java
test/src/test/resources/proto/sample_schema.proto

CorfuStore: Stream tails per table api needed for search

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/ClusterDescriptor.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/NodeDescriptor.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/TopologyDescriptor.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultClusterManager.java

Distinguish node identifier from connection identifier

---

runtime/src/main/java/org/corfudb/runtime/object/transactions/TransactionalContext.java

Log when TransactionContext is getting removed, which allows us to track
a transaction life-cycle.
Description:

Instrument TransactionContext logging

---

test/src/test/java/org/corfudb/runtime/clients/NettyCommTest.java

Description:
Fix flaky NettyCommTest.
NettyCommTest often fails because of ping timeout, if we'd try more times and one of them would work then the test works.

CICD workflow: fix flaky NettyCommTest

---

runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java
runtime/src/main/java/org/corfudb/runtime/collections/StreamManager.java
runtime/src/main/java/org/corfudb/runtime/collections/Table.java
runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java
test/src/test/java/org/corfudb/integration/StreamingIT.java

Description:
Implements backward compatible interfaces for CorfuStore streaming redeisgn.

CorfuStore streaming redesign part 1 - interfaces.

---

test/src/test/java/org/corfudb/CorfuTestParameters.java

Description:
adjust test timeouts

CICD workflow: adjust test timeouts

---

common/src/main/java/org/corfudb/common/metrics/micrometer/MeterRegistryProvider.java
common/src/main/java/org/corfudb/common/metrics/micrometer/MicroMeterUtils.java
common/src/main/java/org/corfudb/common/metrics/micrometer/README.md
infrastructure/src/main/java/org/corfudb/infrastructure/BatchProcessor.java
infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/HandlerMethods.java
infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServerCache.java
infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServerCache.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/statetransfer/transferprocessor/BasicTransferProcessor.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/statetransfer/transferprocessor/ParallelTransferProcessor.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuInterClusterReplicationServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/management/FailureDetector.java
infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/RestoreRedundancyMergeSegments.java
infrastructure/src/main/resources/logback.prod.xml
infrastructure/src/main/resources/logback.xml
runtime/pom.xml
runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java
scripts/corfu_server.sh
test/src/test/java/org/corfudb/integration/AbstractIT.java
test/src/test/java/org/corfudb/integration/StateTransferIT.java
test/src/test/resources/logback-test-corfu-metrics.xml

Description:
Enable some server metrics.

Server side corfu metrics

---

generator/src/main/java/org/corfudb/generator/StringIndexer.java
runtime/proto/example_schemas.proto
runtime/src/main/java/org/corfudb/runtime/collections/CorfuTable.java
runtime/src/main/java/org/corfudb/runtime/collections/Index.java
runtime/src/main/java/org/corfudb/runtime/collections/ManagedTxnContext.java
runtime/src/main/java/org/corfudb/runtime/collections/ProtobufIndexer.java
runtime/src/main/java/org/corfudb/runtime/collections/Query.java
runtime/src/main/java/org/corfudb/runtime/collections/Table.java
runtime/src/main/java/org/corfudb/runtime/collections/TxnContext.java
test/src/test/java/org/corfudb/runtime/collections/CorfuStoreShimTest.java
test/src/test/java/org/corfudb/runtime/collections/CorfuTableTest.java
test/src/test/java/org/corfudb/runtime/collections/StringIndexer.java
test/src/test/java/org/corfudb/runtime/collections/StringMultiIndexer.java
test/src/test/java/org/corfudb/runtime/collections/UuidIndexer.java
test/src/test/resources/proto/sample_schema.proto

UFO Secondary Indexes remove comparator for indexes on Protobufs

---

common/src/main/java/org/corfudb/common/metrics/micrometer/MeterRegistryProvider.java
infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/HandlerMethods.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuInterClusterReplicationServer.java
infrastructure/src/main/resources/logback.prod.xml
runtime/pom.xml
runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
test/pom.xml
test/src/main/java/org/corfudb/test/LsofSpec.java

Description:
Fixes log binding issues. 

Remove deps on logback

---

infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServerCache.java

If unspecified Caffeine will use the common thread pool to execute
its cache eviction logic, this can be confusing when debugging
and it causes multiple threads to "spin up" since it uses a
forkjoin pool. This patch makes the writing thread do the eviction.
Why should this be merged: Reduces the number of threads
Related issue(s) (if applicable): clone of #2460

Use Writer Thread for Cache Eviction

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationAckReader.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InitializedState.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/StoppedState.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java

Handle TAE for LR sync status update

---

runtime/proto/example_schemas.proto
runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java
runtime/src/main/java/org/corfudb/runtime/collections/CorfuStoreShim.java
runtime/src/main/java/org/corfudb/runtime/collections/CorfuStreamEntry.java
runtime/src/main/java/org/corfudb/runtime/collections/StreamListener.java
runtime/src/main/java/org/corfudb/runtime/collections/StreamManager.java
runtime/src/main/java/org/corfudb/runtime/collections/StreamNotificationTask.java
runtime/src/main/java/org/corfudb/runtime/collections/StreamPollingTask.java
runtime/src/main/java/org/corfudb/runtime/collections/StreamSubscription.java
runtime/src/main/java/org/corfudb/runtime/collections/StreamSubscriptionMetrics.java
runtime/src/main/java/org/corfudb/runtime/collections/StreamingManager.java
runtime/src/main/java/org/corfudb/runtime/collections/Table.java
runtime/src/main/java/org/corfudb/runtime/view/SequencerView.java
runtime/src/main/java/org/corfudb/runtime/view/StreamOptions.java
runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java
runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractContextStreamView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/AddressMapStreamView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/BackpointerStreamView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/IStreamView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/ThreadSafeStreamView.java
test/src/test/java/org/corfudb/integration/StreamingIT.java
test/src/test/java/org/corfudb/runtime/collections/CorfuStoreTest.java
test/src/test/resources/proto/sample_schema.proto

Description:
Implements the new subscription API and new threading model for
streaming and integrate into CorfuStore.

CorfuStore streaming redesign part 3 - implementation and integration.

---

test/src/test/java/org/corfudb/infrastructure/ManagementServerTest.java

Description: Fixed ManagementServerTest.triggerFailureHandler which could be flaky
in some corner cases. This PR will also be used for testing the current CI at this moment.

Fix flaky tests

---

infrastructure/src/main/java/org/corfudb/infrastructure/RequestHandlerMethods.java

Fix and capture micrometer server-side metrics for Protobuf RPCs.
Description:

Capture server-side metrics for Protobuf RPCs

---

common/src/main/java/org/corfudb/common/metrics/micrometer/README.md
infrastructure/src/main/java/org/corfudb/infrastructure/management/FailureDetector.java
runtime/src/main/java/org/corfudb/runtime/collections/StreamSubscriptionMetrics.java

Description:
Description of all the metrics in the codebase.

Metrics docs

---

runtime/src/main/java/org/corfudb/runtime/view/stream/StreamAddressSpace.java

Reduce StreamAddressSpace trim log from warn to trace.

Reduce Logging Level

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/CorfuLogReplicationRuntime.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/LogReplicationClientRouter.java

Log Replication: onClusterChange call back

---

pom.xml

Description:
Update slf4j dependencies and maven plugins (corfu-0.3.1.2 branch)

Update slf4j dependencies and maven plugins

---

common/src/main/java/org/corfudb/common/metrics/micrometer/MeterRegistryProvider.java
runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiObjectSMREntry.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java
runtime/src/main/java/org/corfudb/runtime/collections/StreamSubscriptionMetrics.java
runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
runtime/src/main/java/org/corfudb/runtime/view/SequencerView.java
runtime/src/main/java/org/corfudb/runtime/view/replication/ChainReplicationProtocol.java

Make runtime registry static and add metrics to MOSMREntry de/serializations

Refactor + metrics

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
runtime/src/main/java/org/corfudb/runtime/view/replication/ReadWaitHoleFillPolicy.java
utils/src/main/java/org/corfudb/utils/lock/LockClient.java
utils/src/main/java/org/corfudb/utils/lock/states/HasLeaseState.java

Backport: Log Replication: Bug fix + More Lock logging

---

common/src/main/java/org/corfudb/common/metrics/micrometer/registries/LoggingMeterRegistryWithHistogramSupport.java
infrastructure/src/main/java/org/corfudb/infrastructure/BatchProcessor.java
infrastructure/src/main/java/org/corfudb/infrastructure/RequestHandlerMethods.java
infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/SequencerServerCache.java
infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java
runtime/src/main/java/org/corfudb/protocols/logprotocol/MultiObjectSMREntry.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java
runtime/src/main/java/org/corfudb/runtime/collections/CorfuStoreMetrics.java
runtime/src/main/java/org/corfudb/runtime/collections/StreamSubscriptionMetrics.java
runtime/src/main/java/org/corfudb/runtime/collections/TableMetrics.java
runtime/src/main/java/org/corfudb/runtime/collections/TimingHistogram.java
runtime/src/main/java/org/corfudb/runtime/collections/TxnContext.java
runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java
runtime/src/main/java/org/corfudb/runtime/object/VersionLockedObject.java
runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java
runtime/src/main/java/org/corfudb/runtime/view/SequencerView.java
runtime/src/main/java/org/corfudb/runtime/view/replication/ChainReplicationProtocol.java

* Remove 95 percentile from logs.
* Don't log zero values.
* Fix some timing bugs.

Reduce metrics noise + fix some metrics reporting  bugs

---

.github/workflows/pull_request.yml
.mvn/settings.xml
infrastructure/pom.xml
pom.xml

Version Compatibility Test Automation - Phase 1

---

.github/workflows/publish-corfu.yml

Description:
Github actions: publish Corfu artifacts

Github actions: publish corfu artifacts

---

.github/workflows/publish-corfu.yml
.mvn/settings.xml
generator/pom.xml
infrastructure/pom.xml

Description: We didn't access GitHub secrets correctly in xml files. This commit provide a fix for this issue.

Fix Github secrets access

---

.github/workflows/pull_request.yml

Description:
Github actions: a fix in the injection framework action

Github actions: a fix in the injection framework action

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogEntrySinkBufferManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogEntryWriter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/StreamsSnapshotWriter.java
test/src/test/java/org/corfudb/integration/ReplicationReaderWriterIT.java

[BACKPORT] LR's backup restore workflow fix to 0.3.1.4

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogEntrySinkBufferManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogEntryWriter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/StreamsSnapshotWriter.java
test/src/test/java/org/corfudb/integration/ReplicationReaderWriterIT.java

Backport LR backup workflow fix to 0.3.1.3

---

corfudb-tools/README
corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditor.java
corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditorMain.java
test/src/test/java/org/corfudb/integration/CorfuStoreBrowserEditorIT.java

- Rename CorfuStoreBrowser
- Eliminate time stamps from output of browser/editor tool
- Improve wording in README
Description:

Minor Fixes in Browser/Editor Tool.

---

.github/workflows/pull_request.yml

Description:
Upload correctness logs as artifacts, which allows analyzing correctness logs 

Injection-framework: upload correctness logs as artifacts

---

runtime/src/main/java/org/corfudb/runtime/collections/TxnContext.java

Description:
Read-only transactions are expected to be very fast
and they could be invoked several times.
So the fixed cost overhead for setup and teardown
needs to be optimized.
Remove commitCallbacks from reads since they only apply to writes.
Move logs to trace from debug.

TxnContext: Performance enhancements for read path

---

infrastructure/pom.xml
pom.xml
runtime/pom.xml

Description:
Update dependency versions

update dependency versions

---

runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java

- This patch catches the WrongClusterException from the `getLayoutUninterruptibly()` method's `layout.get()` call.
- It is observed in a case when the server gets restarted and gets a new `clusterID`, the old client just keeps retrying with the `WrongClusterException`.
- Error message:
```
AbstractView 3417 getLayoutUninterruptibly: Encountered unchecked exception. Aborting layoutHelper
java.util.concurrent.ExecutionException: org.corfudb.runtime.exceptions.WrongClusterException: Expected: rRZQ5MveQBydt4CdJW2Qgg Actual: lcYPrdK1QV-3OZMqyg_iSQ
```
Description:
Why should this be merged: It fixes the WCE error.

Catch WrongClusterException on get layout method

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java

Description:
Fix NPE that introduced by new UFO API.

Log Replication: Fix NPE that introduced by new UFO API.

---

corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditor.java
corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditorMain.java
test/src/test/java/org/corfudb/integration/CorfuStoreBrowserEditorIT.java

Description:
Why should this be merged: Without this there is no way for folks to delete specific records from a CorfuStore Table
Related issue(s) (if applicable): #2956

CorfuStoreBrowser: Add deleteRecord to delete dynamic records

---

common/src/main/java/org/corfudb/common/metrics/micrometer/registries/LoggingMeterRegistryWithHistogramSupport.java

Description:
Timer percentiles are gauges and we report 0 values for gauges right now.
This patch does not allow the timer percentiles (median, 99p) to be zeros.

Fix timer percentile zeros

---

common/src/main/java/org/corfudb/common/metrics/micrometer/MicroMeterUtils.java

Description:
Fix the format of client black list entries.

Fix format issue in blacklist

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/StreamsSnapshotWriter.java
runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java

Description:
This was addressed in PR #2848, but this code path was not covered.
Why should this be merged: bug fix in client

Handle TransactionAbortedException on metadata table updates

---

runtime/src/main/java/org/corfudb/runtime/collections/Table.java

Description:
Cache improvement to reduce NoRollBackExceptions.

Cache Optimization

---

.github/workflows/code-coverage.yml
.github/workflows/pull_request.yml

Description:
Code coverage improvements

Code coverage improvements

---

docs/failure-detector/file-system-failure-detection.puml
docs/failure-detector/filesystem-failures.md
infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java
infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
infrastructure/src/main/java/org/corfudb/infrastructure/management/ClusterStateContext.java
infrastructure/src/main/java/org/corfudb/infrastructure/management/IDetector.java
infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java
infrastructure/src/main/java/org/corfudb/infrastructure/management/failuredetector/EpochHandler.java
infrastructure/src/main/java/org/corfudb/infrastructure/management/failuredetector/FailureDetectorDataStore.java
infrastructure/src/main/java/org/corfudb/infrastructure/management/failuredetector/FailureDetectorException.java
infrastructure/src/main/java/org/corfudb/infrastructure/management/failuredetector/FailureDetectorHelper.java
infrastructure/src/main/java/org/corfudb/infrastructure/management/failuredetector/HealingAgent.java
infrastructure/src/test/java/org/corfudb/infrastructure/LayoutBasedTestHelper.java
infrastructure/src/test/java/org/corfudb/infrastructure/NodeNames.java
infrastructure/src/test/java/org/corfudb/infrastructure/management/NodeStateTestUtil.java
infrastructure/src/test/java/org/corfudb/infrastructure/management/failuredetector/EpochHandlerTest.java
infrastructure/src/test/java/org/corfudb/infrastructure/management/failuredetector/FailureDetectorHelperTest.java
infrastructure/src/test/java/org/corfudb/infrastructure/management/failuredetector/HealingAgentTest.java
runtime/src/main/java/org/corfudb/runtime/view/SealServersHelper.java
runtime/src/main/java/org/corfudb/util/CFUtils.java
test/src/test/java/org/corfudb/infrastructure/ReconfigurationEventHandlerTest.java
test/src/test/resources/logback-test.xml

Description:
Failure Detector refactoring: make FD more async

FailureDetector: File system failures. Refactoring. Part 1

---

runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java
test/src/test/java/org/corfudb/runtime/collections/CorfuStoreShimTest.java

Description:
Code Coverage tests for the closeTable() corner cases and API description for public api

closeTable: Code Coverage Unit Tests & API desc

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultSnapshotSyncPlugin.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/LogReplicationPluginConfig.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java
pom.xml
runtime/proto/example_schemas.proto
runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java
runtime/src/main/java/org/corfudb/runtime/collections/CorfuStoreShim.java
runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java
test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java
test/src/test/java/org/corfudb/integration/LogReplicationAbstractIT.java
test/src/test/java/org/corfudb/runtime/collections/CorfuStoreShimTest.java
test/src/test/resources/transport/grpcConfig.properties

Master to 3.2.1

---

.github/workflows/injection-framework-test.yml

Description:
Pass Corfu server version into universe-tests

Pass corfu server version into universe-tests

---

infrastructure/proto/sample.proto
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/OptimisticTransactionalContext.java
runtime/src/main/java/org/corfudb/runtime/object/transactions/Transaction.java
runtime/src/main/java/org/corfudb/runtime/view/ObjectsView.java
test/src/test/java/org/corfudb/infrastructure/logreplication/LogReplicationTest.java
test/src/test/java/org/corfudb/infrastructure/logreplication/LogUpdateAPITest.java
test/src/test/java/org/corfudb/integration/CorfuLongRunningClientIT.java
test/src/test/java/org/corfudb/integration/CorfuReplicationClusterConfigIT.java
test/src/test/java/org/corfudb/integration/CorfuStoreIT.java
test/src/test/java/org/corfudb/integration/LogReplicationAbstractIT.java
test/src/test/java/org/corfudb/integration/LogReplicationIT.java
test/src/test/java/org/corfudb/integration/LogReplicationReaderWriterIT.java
test/src/test/java/org/corfudb/integration/StreamingIT.java
test/src/test/java/org/corfudb/integration/TransactionStreamIT.java
test/src/test/java/org/corfudb/runtime/BackupRestoreIT.java
test/src/test/java/org/corfudb/runtime/object/transactions/OptimisticTransactionContextTest.java
test/src/test/java/org/corfudb/runtime/object/transactions/WriteAfterWriteTransactionContextTest.java
test/src/test/java/org/corfudb/runtime/view/ObjectsViewTest.java
test/src/test/java/org/corfudb/runtime/view/StreamViewTest.java

With stream tags, transaction stream(and hence transaction logging) are
no longer required.
This is a cherry-pick of PR 3095

Remove Transaction Logging and Transaction Stream.

---

common/src/main/java/org/corfudb/common/metrics/micrometer/README.md
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/ClusterDescriptor.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/TopologyDescriptor.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultClusterManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationSourceManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/LogReplicationFSM.java
runtime/src/main/java/org/corfudb/runtime/collections/TxnContext.java

Description:
To let logs in LR more easier to read, should remove duplicate logs, also include my previous PR of update the metric document
improve code quality

Remove redundant logs in LR

---

common/src/main/java/org/corfudb/common/metrics/micrometer/README.md
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/ClusterDescriptor.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/TopologyDescriptor.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultClusterManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationSourceManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/LogReplicationFSM.java
runtime/src/main/java/org/corfudb/runtime/collections/TxnContext.java

* update the documents of metrics
* remove reduntant log in LR
Description:

Remove redundant logs in LR (#3154)

---

pom.xml

Upgrade netty to 4.1.73

---

pom.xml
runtime/pom.xml

Upgrade netty grpc versions

---

infrastructure/src/main/java/org/corfudb/infrastructure/LogReplicationServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InLogEntrySyncState.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InSnapshotSyncState.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogEntrySinkBufferManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogEntryWriter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/SinkBufferManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/LogEntrySender.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SnapshotSender.java
infrastructure/src/test/java/org/corfudb/infrastructure/LogReplicationServerTest.java
test/src/test/java/org/corfudb/integration/LogReplicationIT.java
test/src/test/java/org/corfudb/integration/SourceForwardingDataSender.java

Description:
**Cherry-picked commits from master:**
https://github.com/CorfuDB/CorfuDB/commit/26b519bf818f9b25906777f44c6f89d620d0c2a2
https://github.com/CorfuDB/CorfuDB/commit/6df67c81226a980b48b1628d6a85166a5339fd65
https://github.com/CorfuDB/CorfuDB/commit/6855612d2b1995c33d7ca6acce329b33c66c9d92

LR: clear pendingQueue, drop msg when not standby, set data_consistent on snapshot_Start

---

cmdlets/pom.xml
it/pom.xml

Update jackson-databind to 2.11.4

---

cmdlets/pom.xml
it/pom.xml

Update jackson-databind to 2.11.4 from 2.11.0 (#3189)

---

corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditor.java
corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditorMain.java
test/src/test/java/org/corfudb/integration/CorfuStoreBrowserEditorIT.java

Why should this be merged:  Useful debugging operation

Add support for 'addRecord' in the browser/editor tool.

---

corfudb-tools/README
infrastructure/src/main/resources/corfu_plugin_config.properties
it/src/main/java/org/corfudb/universe/group/cluster/CorfuClusterParams.java
it/src/main/java/org/corfudb/universe/node/server/CorfuServerParams.java
pom.xml
test/dependency-reduced-pom.xml
test/src/test/resources/transport/nettyConfig.properties
test/src/test/resources/transport/nettyConfigUpgradeActive.properties
test/src/test/resources/transport/nettyConfigUpgradeStandby.properties

Description:
Why should this be merged: Move corfu base version from 0.3.0-SNAPSHOT to 0.4.0-SNAPSHOT

Move corfu version to 0.4.0.0

---

cmdlets/pom.xml
it/pom.xml

Update jackson-databind from 2.11.4 to 2.12.6

---

cmdlets/pom.xml
it/pom.xml

Update jackson-databind from 2.11.4 to 2.12.6 (#3233)

---

pom.xml
runtime/pom.xml
utils/pom.xml

Update gson to 2.9.0 (#3238)

---

common/src/main/java/org/corfudb/common/metrics/micrometer/JVMMetrics.java

Description:
Add JVM memory and thread metrics

Add some jvm memory metrics

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/utils/LogReplicationConfigManager.java
test/src/test/java/org/corfudb/integration/CorfuReplicationUpgradeIT.java

Description:
The maintaining of Streams_Name_Table is a bit redundant in LR workflow. This commit will stop using that table. Note that it cannot be totally removed at this time for rolling upgrade consideration. An issue is created for potential removal in the future (i.e. after N - 2 version iteration).
Also done as part of effort to achieve dynamic stream discovery, as getting rid of this table could greatly simplify the updating and maintaining of LogReplicationConfig in dynamic scenario.
Related issue(s) (if applicable): #3322

[P1] Log Replication: stop using Streams_Name_Table

---

runtime/pom.xml

Description:
https://nvd.nist.gov/vuln/detail/cve-2018-25032

Update rocksdb-jni to 7.4.5

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/LogReplicationConfig.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuInterClusterReplicationServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/LogReplicationServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/ReplicationSession.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/ReplicationSubscriber.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultAdapterForUpgrade.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultAdapterForUpgradeActive.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultAdapterForUpgradeStandby.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultLogReplicationConfigAdapter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/ILogReplicationConfigAdapter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationAckReader.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationSourceManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/LogReplicationFSM.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogEntryWriter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/StreamsSnapshotWriter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/StreamsLogEntryReader.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/StreamsSnapshotReader.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/CorfuLogReplicationRuntime.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/utils/LogReplicationConfigManager.java
infrastructure/src/test/java/org/corfudb/infrastructure/LogReplicationServerTest.java
test/src/test/java/org/corfudb/infrastructure/logreplication/LogReplicationConfigManagerTest.java
test/src/test/java/org/corfudb/infrastructure/logreplication/LogReplicationFSMTest.java
test/src/test/java/org/corfudb/integration/LogReplicationIT.java
test/src/test/java/org/corfudb/integration/LogReplicationReaderWriterIT.java
test/src/test/java/org/corfudb/integration/SourceForwardingDataSender.java

Extend ReplicationConfig to contain streams to replicate for different replication models.

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java
test/src/test/java/org/corfudb/integration/CorfuReplicationClusterConfigIT.java

Description:
When a cluster is removed from the topology, we stop the FSM against the removed cluster, but we don't remove the replication details from the LR status table. 
This change address the removal.

delete the standby cluster info on topology change from LrStatus table

---

corfudb-tools/src/main/java/org/corfudb/compactor/CorfuStoreCompactorMain.java
infrastructure/src/main/java/org/corfudb/infrastructure/InvokeCheckpointingJvm.java
runtime/src/main/java/org/corfudb/runtime/CompactorMetadataTables.java

Description:
Minor fixes to support freeze compaction with previous versions, 
upgrade scenarios and other small logging changes

Minor fix to support freeze compaction and upgrade scenarios

---

cmdlets/pom.xml
it/pom.xml

Description:
Address
https://nvd.nist.gov/vuln/detail/CVE-2022-42003
https://nvd.nist.gov/vuln/detail/CVE-2022-42004

Update jackson databind to 2.14.0-rc1

---

test/src/test/java/org/corfudb/infrastructure/CompactorServiceTest.java

Depending on partition size, writing a fixed number of records may not always be sufficient in triggering a QuotaExceededException for quotaExceededTest. This is fixed by continually writing until the quota is exhausted.
Description:

Fix flaky test quotaExceededTest

---

.ci/infrastructure-docker-build.sh
infrastructure/Dockerfile
infrastructure/src/main/resources/compactor-logback.prod.xml
infrastructure/src/main/resources/corfu-compactor-config.yml
scripts/compactor_runner.py

Description:
Invoke server side checkpointing in corfu containers
Without enabling server side checkpointing, corfu running in docker containers will run out of disk space

Enable compaction in corfu docker containers

---

test/src/test/java/org/corfudb/integration/CorfuReplicationClusterConfigIT.java

This test did not account for the delay in the asynchronous processing of a lock release/expiry.  This made it to fail intermittently.
The fix reduces the overall wait time required in the test and also accounts for the async event processing delay.
Why should this be merged: Fixes a flaky LR test

Fix flaky test CorfuReplicationClusterConfigIT.testActiveLockRelease()

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/utils/LogReplicationConfigManager.java
test/src/test/java/org/corfudb/infrastructure/logreplication/LogReplicationConfigManagerTest.java
test/src/test/java/org/corfudb/integration/CorfuReplicationClusterConfigIT.java
test/src/test/java/org/corfudb/integration/LogReplicationAbstractIT.java

Codacy Fixes from the rebase with master.

Codacy fixes

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogEntryWriter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/utils/LogReplicationConfigManager.java
test/src/test/java/org/corfudb/integration/LogReplicationIT.java

Cherry-pick of PR 3417
Description:

Minor LR Fixes Identified During Code Inspection.

---

infrastructure/proto/log_replication_metadata.proto

Description:
LR V2 will support multiple replication models. Introducing enum for initial models.
Why should this be merged: base models for LR Version 2

Introduce Replication Models

---

cmdlets/pom.xml
it/pom.xml

Address
https://nvd.nist.gov/vuln/detail/CVE-2022-42003
https://nvd.nist.gov/vuln/detail/CVE-2022-42004
Description:

Update jackson databind to 2.14.0-rc1 for 4.1.0 (#3379)

---

.github/workflows/code-coverage.yml
.github/workflows/compatibility-test.yml
.github/workflows/injection-framework-test.yml
.github/workflows/integration-test.yml
.github/workflows/unit-test.yml
.github/workflows/universe-test.yml
cmdlets/pom.xml
common/pom.xml
coverage/README.md
coverage/pom.xml
it/pom.xml
pom.xml
samples/pom.xml
scripts/corfu_replication_server.sh
scripts/corfu_server.sh
test/pom.xml
test/src/test/java/org/corfudb/integration/AbstractIT.java
utils/pom.xml

Generate test coverage report combining Unit and Integration Tests.
Description:
This PR introduces the following features -
- Execute all tests during code-coverage GitHub action.
- Collect and aggregate their test coverage results.
- Upload the results to Codacy and Codecov.
- Add a README file for code coverage information.
- Remove duplicate protobuf dependencies from pom.xml.
Improves and streamlines CI/CD.

Code Coverage: Aggregate Unit and Integration Tests

---

infrastructure/src/main/resources/corfu-compactor-config.yml

Modify yml file

---

corfudb-tools/src/main/java/org/corfudb/compactor/CorfuStoreCompactorConfig.java
scripts/compactor_runner.py
test/src/test/java/org/corfudb/infrastructure/CompactorServiceUnitTest.java
test/src/test/java/org/corfudb/runtime/DistributedCheckpointerTest.java
test/src/test/java/org/corfudb/runtime/DistributedCheckpointerUnitTest.java
test/src/test/java/org/corfudb/runtime/MockLivenessUpdater.java

+Add UTs
+Move test files to the right location
+Rename config variable
Description:

Clean up compactor related files and tests

---

infrastructure/src/main/java/org/corfudb/infrastructure/CompactorService.java

Handle exception thrown while invoking DistributedCheckpointerHelper in CompactorService
Description:

Add Exception handler in CompactorService

---

infrastructure/src/main/java/org/corfudb/infrastructure/CompactorLeaderServices.java
runtime/src/main/java/org/corfudb/runtime/DistributedCheckpointer.java
test/src/test/java/org/corfudb/infrastructure/CompactorServiceTest.java

Fix instant trigger failure case 410

---

infrastructure/src/main/java/org/corfudb/infrastructure/InvokeCheckpointingJvm.java

Add sudo to process builder

---

infrastructure/src/main/java/org/corfudb/infrastructure/CompactorService.java
runtime/src/main/java/org/corfudb/runtime/DistributedCheckpointer.java
test/src/test/java/org/corfudb/infrastructure/CompactorServiceUnitTest.java
test/src/test/java/org/corfudb/runtime/DistributedCheckpointerUnitTest.java

Fix null manager status 410

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/sample/GRPCLogReplicationServerChannelAdapter.java

Description:
Flaky test fix:
CorfuReplicationE2EIT with gRPC plugin: Make gRPC server side handlers singe-threaded (https://github.com/CorfuDB/CorfuDB/issues/3358)
Related issue(s) (if applicable): #3358

CorfuReplicationE2EIT: Make gRPC server side handlers singe-threaded

---

runtime/proto/service/log_replication.proto
runtime/src/main/java/org/corfudb/runtime/LogReplicationLogicalGroupClient.java
test/src/test/java/org/corfudb/runtime/LogReplicationLogicalGroupClientTest.java

Description:
Duplicate of PR "LR Client #3463" rebased on master.
Related issue(s) (if applicable):

LR Client for Logical Groups

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationSourceManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/LogReplicationFSM.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/WaitSnapshotApplyState.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/CorfuLogReplicationRuntime.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/NegotiatingState.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/utils/LogReplicationConfigManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/utils/LogReplicationUpgradeManager.java
test/src/test/java/org/corfudb/infrastructure/logreplication/LogReplicationFSMTest.java
test/src/test/java/org/corfudb/integration/CorfuReplicationUpgradeIT.java
test/src/test/java/org/corfudb/integration/LogReplicationIT.java

Why should this be merged:  Necessary code cleanup 
Testing Done:
No new tests added as it is simply a movement/reorganization of code.

Separate Upgrade/Version-related code from ConfigManager.

---

scripts/compactor_runner.py
scripts/compactor_utils.py

Only server can trigger the script with startCheckpointing param. Hence modify grep accordingly. Also remove upgrade param.
Description:

Modify compactor script

---

.github/workflows/compatibility-test.yml
.github/workflows/injection-framework-test.yml
.github/workflows/integration-test.yml
.github/workflows/unit-test.yml
.github/workflows/universe-test.yml

Ubuntu image version upgrade in GitHub Actions.
Description:
Update image label to ubuntu-latest.
Fix https://github.com/actions/runner-images/issues/6002 to ensure continued support.
Why should this be merged: Fixes the issue.

Upgrade GitHub Workflow to use latest Ubuntu

---

scripts/compactor_runner.py

Description:
The class names in `compactor_runner.py` needs to be corrected.

Fix class names in compactor_runner.py

---

scripts/compactor_runner.py

The compactor script is modified to accommodate more memory options that will be passed to it as a config file
Description:

Modify compactor script to accommodate more memory options

---

infrastructure/src/main/java/org/corfudb/infrastructure/InvokeCheckpointingJvm.java

When the compactor triggers the compactor_runner script, if there are any failures before the script initializes its logger, the error log isn't logged anywhere. This fix helps with capturing the error logs from compactor_runner and logging them in the compactor logfile.
Description:

Capture error logs from compactor_runner script in the compactor logfile

---

infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServerNode.java
infrastructure/src/main/java/org/corfudb/infrastructure/datastore/DataStore.java

Description:
Trying to create a service directory in a loop rather than exit
issue #3578

Retry creating service directory

---

corfudb-tools/pom.xml
infrastructure/pom.xml
pom.xml
runtime/pom.xml
samples/pom.xml
test/pom.xml
utils/pom.xml

Upgrade protobuf version to 3.21.7 to fix security vulnerabilities.
Description:

Upgrade protobuf version to 3.21.7

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java

Add SessionManager null check in discovery service adapter

---

runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java

Description:
Right after upgrade if a large number of tables are opened in parallel, the chances of collisions increase many fold since many tables may share the same protobuf schemas under the hood.

registerTable needs to retry more times before giving up

---

infrastructure/src/main/resources/corfu-compactor-config.yml
scripts/compactor_runner.py

Make compactor take a ServerAddress config
from YML file whose value can be replaced
by corfu-server init script.
Description:

Add 'ServerAddress' Compactor Config

---

docs/log-replicator/routing_queues.md
runtime/proto/queue.proto

Description:
Details design based on discussions and can be useful when looking back to see why certain decisions were made.

Design Spec for LR Routing Queue model

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuInterClusterReplicationServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/CorfuReplicationClusterManagerAdapter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultAdapterForUpgrade.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultClusterManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultLogReplicationConfigAdapter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/ILogReplicationVersionAdapter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/utils/LogReplicationUpgradeManager.java
test/src/test/java/org/corfudb/infrastructure/logreplication/RollingUpgradeHandlerTest.java
test/src/test/java/org/corfudb/integration/CorfuReplicationUpgradeIT.java

compute saasEndpoint for runtime in interClusterReplicationServer

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuInterClusterReplicationServerNode.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/SessionManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/LogReplicationClientServerRouter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/client/IClientChannelAdapter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/sample/GRPCLogReplicationClientChannelAdapter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/sample/GRPCLogReplicationServerChannelAdapter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/server/IServerChannelAdapter.java

Bring back IChannelContext for LR IServerChannelAdapter

---

runtime/src/main/java/org/corfudb/runtime/collections/Table.java
runtime/src/main/java/org/corfudb/runtime/collections/TxnContext.java
test/src/test/java/org/corfudb/runtime/collections/CorfuQueueTest.java

Add logUpdate() method for LR Routing Queue model

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/config/LogReplicationRoutingQueueConfig.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/BaseLogEntryReader.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/utils/LogReplicationConfigManager.java
runtime/src/main/java/org/corfudb/runtime/LogReplicationRoutingQueueClient.java

Routing queue config & default subscriber

---

docs/log-replicator/routing_queues.md
runtime/src/main/java/org/corfudb/runtime/collections/Table.java
runtime/src/main/java/org/corfudb/runtime/collections/TxnContext.java
test/src/test/java/org/corfudb/runtime/collections/CorfuQueueTest.java

Q lookalike logupdate test

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/SessionManager.java

correcting a typo: getSinkCluster instead of getSourceCluster

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/LogReplicationClientServerRouter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/client/IClientChannelAdapter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/sample/GRPCLogReplicationClientChannelAdapter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/transport/sample/GRPCLogReplicationServerHandler.java

extract request/response checks from transport plugin to router

---

infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java

Description:
When the old corfu server node is being restarted from one thread, due to the lack of synchronization primitives, another thread starts a new corfu server node immediately without waiting for the restart to finish and the resources to get released. This results in the inconsistent state of some of the shared static components - HealthMonitor and MetricsRegistry. As a result, sometimes they do not start. 
This patch makes the main thread wait for the restart thread so that the start always happens AFTER the activeServer.close() is done.

Wait until the reset is complete before starting another server

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/BaseLogEntryReader.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/RoutingQueuesLogEntryReader.java

Filter entries based on Destination in RoutingQueuesLogEntryReaders.

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/config/LogReplicationRoutingQueueConfig.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java
runtime/src/main/java/org/corfudb/runtime/LogReplicationUtils.java
runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java

register replicated Q on the sink side

---

runtime/src/main/java/org/corfudb/runtime/collections/PersistedStreamingMap.java

Retrieve the table size by reading "rocksdb.estimate-num-keys" property from RocksDB. Although still approximate, this approach is more accurate as it relies on compaction to eliminate duplicate counting.
Description:

@rocksdb: Change how table size is computed

---

runtime/src/main/java/org/corfudb/runtime/collections/PersistedStreamingMap.java

Retrieve the table size reading "rocksdb.estimate-num-keys" property from RocksDB. Although still approximate, this approach is more accurate as it relies on compaction to eliminate duplicate counting.
Description:

@rocksdb: Change how table size is computed (#3680)

---

runtime/src/main/java/org/corfudb/runtime/RoutingQueueSenderClient.java
test/src/test/java/org/corfudb/integration/LogReplicationRoutingQueueIT.java

Implementation for client-requested Snapshot Sync.

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/StreamsSnapshotWriter.java

Fix in SnapshotWriter to get the correct streams to replicate.

---

runtime/src/main/java/org/corfudb/runtime/collections/TxnContext.java

Class-cast fix in TxnContext.delete()

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SnapshotSender.java
test/src/test/java/org/corfudb/integration/LogReplicationRoutingQueueIT.java

Fix the base snapshot timestamp in SnapshotSender.

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/RoutingQueuesSnapshotReader.java
runtime/src/main/java/org/corfudb/runtime/RoutingQueueSenderClient.java

Snasphot sync fixes

---

runtime/src/main/java/org/corfudb/runtime/RoutingQueueSenderClient.java
test/src/test/java/org/corfudb/infrastructure/log/StreamLogFilesTest.java
test/src/test/java/org/corfudb/infrastructure/logreplication/RoutingQueuesSnapshotReaderTest.java
test/src/test/java/org/corfudb/integration/AbstractIT.java
test/src/test/java/org/corfudb/integration/LogReplicationRoutingQueueIT.java
test/src/test/java/org/corfudb/integration/StreamingPatternsIT.java
test/src/test/resources/logback-test.xml

Add iretry block around markComplete()

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/RoutingQueuesSnapshotReader.java

Start snapshotReader from trimMark when appropriate

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/RoutingQueuesSnapshotReader.java

Reset in-memory variables on reader reset.

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/LogEntrySender.java

Backoff period for log_entry sync

---

runtime/src/main/java/org/corfudb/runtime/RoutingQueueSenderClient.java

Log the total LR metadata size in a snapshot payload.

---

infrastructure/src/main/java/org/corfudb/infrastructure/log/statetransfer/StateTransferManager.java
infrastructure/src/test/java/org/corfudb/infrastructure/log/statetransfer/StateTransferManagerTest.java

* Addresses in a batch are sequential
Description:
Cherry-pick on 0.4.1.2

Addresses in a batch are sequential (#3706)

---

.github/workflows/cloud-deployment-test.yml
corfu_scripts/corfu_bootstrap_cluster.clj

Description:
Add the ability to bootstrap a certain node with a layout.

Bootstrap a particular node

---

.github/workflows/cloud-deployment-test.yml
corfu_scripts/corfu_bootstrap_cluster.clj

Description:
Cherry-pick bootstrap script into 0.4.1.2

Bootstrap a particular node (#3746)

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/LogReplicationClientServerRouter.java

For a given session, either Source or Sink is a connection starter.

---

infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServerNode.java

Description:
Reset bug fix cherry-pick for corfu-0.4.1.2

Reset bug fix 0.4.1.2

---

common/src/main/java/org/corfudb/common/compression/ZSTDCompression.java
common/src/main/java/org/corfudb/common/metrics/micrometer/README.md
runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java

Add metrics in write path that is useful for compactor (#3753)

---

runtime/src/main/java/org/corfudb/runtime/LRSiteDiscoveryListener.java

String utils related fix in LR Site Discovery.

---

infrastructure/src/main/java/org/corfudb/infrastructure/management/failuredetector/ClusterGraph.java
infrastructure/src/test/java/org/corfudb/infrastructure/management/ClusterGraphTest.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/failuredetector/NodeConnectivity.java

Description:
Fixes in the symmetric graph: prevents FD from throwing NPE in case if the graph is in inconsistent state

Fixes in the symmetric graph

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InSnapshotSyncState.java
runtime/src/main/java/org/corfudb/runtime/RoutingQueueSenderClient.java

Re-request for snapshot sync data regardless of 'from' and 'to' states on entry in Snapshot Sync.

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InSnapshotSyncState.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/LogReplicationEventMetadata.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SnapshotSender.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/RoutingQueuesSnapshotReader.java

Request for snapshot sync data only if timed out waiting for data.

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/SessionManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultClusterManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/LogReplicationClientServerRouter.java
test/src/test/java/org/corfudb/infrastructure/logreplication/SessionManagerTest.java

connect to all sessions on leadership acquire

---

runtime/src/main/java/org/corfudb/runtime/collections/CorfuStore.java

Description:
TrimmedExceptions should not cause a failure in creation of a scoped transaction context itself.

Retry ScopedTransaction creation on TrimmedException in MVCC

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/StreamsSnapshotWriter.java

Fix null metadata in the dummy message written after Snapshot Sync completion

---

runtime/src/main/java/org/corfudb/runtime/RoutingQueueSenderClient.java

Description:
Delete the cli's global full sync request to avoid re-requesting on restarts - this avoid multiple full syncs from getting triggered

Delete the cli's global full sync request to avoid re-requesting

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SnapshotSender.java
test/src/test/java/org/corfudb/integration/LogReplicationIT.java
test/src/test/java/org/corfudb/integration/SourceForwardingDataSender.java

add logic to resend last msg during snapshot sync

---

infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/config/LogReplicationConfig.java
runtime/src/main/java/org/corfudb/runtime/RoutingQueueSenderClient.java
runtime/src/main/java/org/corfudb/runtime/collections/TransactionCrud.java

LR: Reduce CacheSize, Bump up Server Threads, Skip NS validation for internal tables

---

infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServerNode.java

Description:
Cherry-pick of reset fix on corfu-0.3.2.3

Corfu 0.3.2.3 reset fix

---

runtime/src/main/java/org/corfudb/runtime/RoutingQueueSenderClient.java

Description:
Reduces unnecessary full sync data generated from routing queue client and allows batches of full syncs to complete without re-doing extra rounds

RQ: Cancel previous full sync request for same destination

---

docs/failure-detector/failure-detection-unstable-node.md
infrastructure/src/main/java/org/corfudb/infrastructure/management/failuredetector/HealingAgent.java
infrastructure/src/main/java/org/corfudb/infrastructure/management/failuredetector/LayoutRateLimit.java
infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/HealNodeWorkflow.java
infrastructure/src/test/java/org/corfudb/infrastructure/management/failuredetector/LayoutRateLimitTest.java
runtime/src/main/java/org/corfudb/runtime/view/Layout.java

- Allow graceful cooldown for non-problematic nodes
- Add a configurable timeout multiplier for cooldown limits
- Modify test cases to match the latest changes
- Sort probes list before writing to the layouts (verify)
- Modify/Refactor new sub-classes fields and methods to match the requirements.
Description:

Keep Exponential Backoff for timeouts and allow cooldown

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/LRRollingUpgradeHandler.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/LogReplicationEventListener.java

Upgrade Handler Proto Fixes for RQ Bidirectional

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/LogReplicationSourceManager.java
test/src/test/java/org/corfudb/integration/LogReplicationIT.java
test/src/test/java/org/corfudb/integration/SourceForwardingDataSender.java

Add tests for dropped SNAPSHOT_START and out-of-order messages + Minor cleanup in LogReplicationIT.

---

test/src/test/java/org/corfudb/integration/LogReplicationIT.java

Description:
verifying the fix 

Fix for flaky test in LogReplicationIT

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/NegotiatingState.java
runtime/proto/service/log_replication.proto

Cleanup redundant and unused event types for requesting a Snapshot Sync.

---

infrastructure/src/main/java/org/corfudb/infrastructure/BatchProcessor.java

This patch adds logs in cases where the BatchProcessor thread encounters a throwable. Note that this PR does not attempt to remediate any issues encountered.
Description: This patch adds logs in cases where the BatchProcessor thread encounters a throwable. Note that this PR does not attempt to remediate any issues encountered.
Why should this be merged: Improve observability and debuggability in this area. 

BatchProcessor Error Logging

---

infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java
infrastructure/src/main/resources/compactor-logback.prod.xml
infrastructure/src/main/resources/logback.prod.xml
runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java

Description:
LogUnitServer.handleWrite() logs optimization

Logs optimization

---

runtime/src/main/java/org/corfudb/runtime/RoutingQueueSenderClient.java
test/src/test/java/org/corfudb/integration/LogReplicationRoutingQueueIT.java

RQ: IT for Full Sync Cancellation

---

infrastructure/src/main/java/org/corfudb/infrastructure/BatchProcessor.java

Set error status on throwable in batch processor

---

.github/workflows/cloud-deployment-test.yml
infrastructure/Dockerfile
infrastructure/src/main/resources/corfu-compactor-config.yml
scripts/compactor_runner.py

Jdk 11 fix gc

---

infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java
runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
test/src/test/java/org/corfudb/integration/WorkflowIT.java
test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java

Reverts CorfuDB/CorfuDB#3773 to address a bug and adds a test to reproduce the issue.

Revert "Do not ping unresponsive nodes when invalidating layout"

---

infrastructure/Dockerfile

Upgrade version to avoid hitting the
issue https://github.com/yaml/pyyaml/issues/724.
Description:

Upgrade pyyaml to 6.0.1

---

runtime/src/main/java/org/corfudb/runtime/Restore.java
test/src/test/java/org/corfudb/runtime/BackupRestoreIT.java

When Restore is invoked with mode as FULL, compactor should be disabled before starting and during restore process. This commit fixes the issue where during restore, the compactor metadata tables get set with values that existed during backup causing compactor to run in parallel with restore sometimes
Description:

Do not restore some compactor metadata tables (#3852)

---

.github/workflows/cloud-deployment-test.yml
.github/workflows/code-coverage.yml
.github/workflows/compatibility-test.yml
.github/workflows/injection-framework-test.yml
.github/workflows/integration-test.yml
.github/workflows/publish-corfu.yml
.github/workflows/unit-test.yml
.github/workflows/universe-test.yml

Description:
Github actions: workflow and plugins upgrade

Github actions: workflow and plugins upgrade

---

common/src/main/java/org/corfudb/common/compression/ZSTDCompression.java
corfudb-tools/src/main/java/org/corfudb/compactor/CompactorBaseConfig.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/LogReplicationEventListener.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationAckReader.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationSourceManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InLogEntrySyncState.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InSnapshotSyncState.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InitializedState.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/LogReplicationEvent.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/LogReplicationFSM.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/LogReplicationState.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/WaitSnapshotApplyState.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/LogReplicationEventMetadata.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/SnapshotSender.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/NegotiatingState.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/ReplicatingState.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/ILogData.java
runtime/src/main/java/org/corfudb/protocols/wireprotocol/LogData.java
runtime/src/main/java/org/corfudb/runtime/CheckpointWriter.java
runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
runtime/src/main/java/org/corfudb/runtime/exceptions/WriteSizeException.java
runtime/src/main/java/org/corfudb/runtime/view/StreamsView.java
runtime/src/main/java/org/corfudb/runtime/view/stream/AbstractQueuedStreamView.java
test/src/test/java/org/corfudb/infrastructure/logreplication/LogReplicationFSMTest.java
test/src/test/java/org/corfudb/integration/CorfuReplicationClusterConfigIT.java
test/src/test/java/org/corfudb/integration/LogReplicationIT.java
test/src/test/java/org/corfudb/runtime/checkpoint/CheckpointSmokeTest.java
test/src/test/java/org/corfudb/runtime/object/transactions/StreamTest.java

Description:
Original PRs in the order of the commits:
https://github.com/CorfuDB/CorfuDB/pull/3789
https://github.com/CorfuDB/CorfuDB/pull/3821
https://github.com/CorfuDB/CorfuDB/pull/3892

LR: Reworked PRs on top of revert

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/WaitSnapshotApplyState.java

Description:
stopSnapshotApply variable is currently trying to gate the metadata request sent during the waitSnapshotApply.
But its ineffective because once a replication_stop event is received, the state is transitioned from WaitSnapshotApply state to INITIALIZED state. 
Also, currently stopSnapshotApply is set to false only if the state was transitioned from INITIALIZED state..this is when the previous snapshot sync was interrupted, and the sink is yet to apply the data.
But if a new snapshot sync gets triggered in WaitSnapshotApply, stopSnapshotApply is set to true, and when we transition to WaitSnapshotApply, we don't send out the metadata request more than once. This is a bug.
We don't need stopSnapshotApply at all since state transition happens immediately and the events are …

LR: remove stopSnapshotApply from WaitSnapshotApply

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/LogReplicationEventListener.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/InSnapshotSyncState.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/WaitSnapshotApplyState.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java

Description:
This PR addresses the comments in https://github.com/CorfuDB/CorfuDB/pull/3939

LR: addressing comments in #3939

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/WaitSnapshotApplyState.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java
test/src/test/java/org/corfudb/integration/CorfuReplicationReconfigurationIT.java

Description:
In cases where a `FORCE_SNAPSHOT_SYNC` is abandoned due to a restart or otherwise, since the force sync events are deleted on a per uuid basis, the abandoned events will just hang around indefinitely. This change introduces a clear after each successfully processed force sync event so that all prior events are discarded when the latest completes.

Clear Event Table on Force Sync Completion

---

runtime/src/main/java/org/corfudb/util/serializer/ProtobufSerializer.java
test/src/test/java/org/corfudb/integration/CorfuStoreIT.java

Description:
If a bad metadata was inserted incorrectly a NullPointerException was thrown & there was no information present to find out what was inserted.
Instead a proper SerializerException is thrown which has debugging information.

ProtobufSerializer: Log Exception for wrong metadata SMR

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogEntryWriter.java

LR: Log abort details when writing the replicated data

---

pom.xml
runtime/pom.xml
runtime/src/main/java/org/corfudb/runtime/collections/CheckedRocksIterator.java
runtime/src/main/java/org/corfudb/runtime/collections/WrappedRocksIterator.java

Switch back to using a private RocksDB artifact

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/PgUtils/PostgresUtils.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java

Adopt LR discovery service callbacks for PG

---

runtime/src/main/java/org/corfudb/util/serializer/DynamicProtobufSerializer.java

Cherry-pick of https://github.com/CorfuDB/CorfuDB/pull/3924
Description:
Related issue(s) (if applicable): #3924

Print Error Information for Invalid Inputs to Corfu Editor.

---

corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditor.java

Description:
Without this we cannot enable clear audit trails.

CorfuStore Editor: Capture previous value and record modified

---

common/src/main/java/org/corfudb/common/metrics/micrometer/MeterRegistryProvider.java
common/src/main/java/org/corfudb/common/metrics/micrometer/registries/RegistryLoader.java
common/src/main/java/org/corfudb/common/metrics/micrometer/registries/RegistryProvider.java

Merge registry changes into release branch

Metric registry provider metadata (#4006)

---

common/src/main/java/org/corfudb/common/metrics/micrometer/MeterRegistryProvider.java
common/src/main/java/org/corfudb/common/metrics/micrometer/registries/RegistryLoader.java
common/src/main/java/org/corfudb/common/metrics/micrometer/registries/RegistryProvider.java

Reverts CorfuDB/CorfuDB#4011
Reason: It was not intended for 4.2.1 rel.

Revert "Metric registry provider metadata (#4006)"

---

common/src/main/java/org/corfudb/common/metrics/micrometer/MeterRegistryProvider.java

This code refactors the registerProvidedRegistries method. The registry metadata needs to be non-empty in order to load and instantiate metrics registries.

Do not use ServiceLoader unless the config is present

---

infrastructure/src/main/java/org/corfudb/infrastructure/health/HealthMonitor.java
infrastructure/src/test/java/org/corfudb/infrastructure/health/HealthMonitorTest.java

Description:
Report overall corfu node health status as an encoded micrometer metric.

Health status as metric

---

cmdlets/pom.xml
it/pom.xml

Fixes CVE-2023-35116.
Description:

Update jackson dependencies to 2.18.2

---

.github/workflows/cloud-deployment-test.yml
.github/workflows/code-coverage.yml
.github/workflows/compatibility-test.yml
.github/workflows/injection-framework-test.yml
.github/workflows/integration-test.yml
.github/workflows/publish-corfu.yml
.github/workflows/unit-test.yml
.github/workflows/universe-test.yml

Description:
Ubuntu Version Update - unblock docker-based build targets

Update ubuntu runner version

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/PgUtils/PgLeadershipCallback.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/PgUtils/PgLeadershipService.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/PgUtils/PostgresException.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/PgUtils/PostgresUtils.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/PgUtils/SQLExceptionHandler.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/DiscoveryServiceEvent.java
test/src/test/java/org/corfudb/integration/pg/PostgresReplicationE2EIT.java
test/src/test/java/org/corfudb/integration/pg/PostgresUtilsTest.java

Replication leadership

---

.github/workflows/cloud-deployment-test.yml
.github/workflows/code-coverage.yml
.github/workflows/compatibility-test.yml
.github/workflows/injection-framework-test.yml
.github/workflows/integration-test.yml
.github/workflows/publish-corfu.yml
.github/workflows/unit-test.yml
.github/workflows/universe-test.yml
cmdlets/pom.xml
common/pom.xml
corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditor.java
generator/pom.xml
infrastructure/pom.xml
infrastructure/src/main/java/org/corfudb/infrastructure/LogReplicationServer.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/LogReplicationConfig.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/fsm/TestLogEntryReader.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogEntryWriter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationSinkManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/SinkBufferManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/LogEntrySender.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/LogEntryReader.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/send/logreader/StreamsLogEntryReader.java
it/pom.xml
pom.xml
runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java
runtime/src/main/java/org/corfudb/runtime/view/TableRegistry.java
test/src/test/java/org/corfudb/infrastructure/logreplication/LogEntryReaderTest.java
test/src/test/java/org/corfudb/infrastructure/logreplication/LogEntryWriterTest.java
test/src/test/java/org/corfudb/integration/SourceForwardingDataSender.java

Description: For maintenance release 4.2.2. 
Note for merging: Do basic merge, **NOT SQUASH MERGE** as we want to retain the commits individually.

Cherry-pick commits from master to corfu-0.4.2.2

---

.ci/infrastructure-docker-build.sh
.github/workflows/cloud-deployment-test.yml
.github/workflows/code-coverage.yml
.github/workflows/compatibility-test.yml
.github/workflows/injection-framework-test.yml
.github/workflows/integration-test.yml
.github/workflows/publish-corfu.yml
.github/workflows/unit-test.yml
.github/workflows/universe-test.yml
README.md
common/pom.xml
generator/pom.xml
it/pom.xml
pom.xml
test/pom.xml

Migrate to JDK 17.
Description:

Migrate to JDK 17

---

infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/CorfuReplicationDiscoveryService.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/CorfuReplicationClusterManagerBaseAdapter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/infrastructure/plugins/DefaultClusterManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogEntrySinkBufferManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogEntryWriter.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java
test/src/test/java/org/corfudb/integration/CorfuReplicationClusterConfigIT.java

[Backport] LR bugfix: set LAST_LOG_ENTRY_APPLIED on snapshot completion (#4038)

---

.github/workflows/injection-framework-test.yml
.github/workflows/publish-corfu.yml
corfudb-tools/README
infrastructure/src/main/resources/corfu_plugin_config.properties
pom.xml
test/src/test/resources/transport/grpcConfig.properties
test/src/test/resources/transport/nettyConfig.properties
test/src/test/resources/transport/nettyConfigUpgradeActive.properties
test/src/test/resources/transport/nettyConfigUpgradeStandby.properties

Bump Corfu Version to 0.9.1.0

---

.github/workflows/cloud-deployment-test.yml
.github/workflows/compatibility-test.yml
.github/workflows/injection-framework-test.yml
.github/workflows/publish-corfu.yml
corfudb-tools/README
infrastructure/src/main/resources/corfu_plugin_config.properties
pom.xml
test/src/test/resources/transport/grpcConfig.properties
test/src/test/resources/transport/nettyConfig.properties
test/src/test/resources/transport/nettyConfigUpgradeActive.properties
test/src/test/resources/transport/nettyConfigUpgradeStandby.properties

Bump Corfu Version to 0.4.2.2

---

corfudb-tools/src/main/java/org/corfudb/browser/CorfuBrowserEditorCommands.java
corfudb-tools/src/main/java/org/corfudb/browser/CorfuOfflineBrowserEditor.java
corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditor.java
corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditorMain.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationAckReader.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/NegotiatingState.java
pom.xml
runtime/src/main/java/org/corfudb/runtime/collections/Table.java
runtime/src/main/java/org/corfudb/runtime/view/stream/StreamAddressSpace.java
runtime/src/main/java/org/corfudb/util/FileWatcher.java
runtime/src/test/java/org/corfudb/runtime/utils/FileWatcherTest.java
test/src/test/java/org/corfudb/integration/CorfuReplicationClusterConfigIT.java
test/src/test/java/org/corfudb/integration/CorfuStoreBrowserEditorIT.java
test/src/test/java/org/corfudb/runtime/view/stream/StreamAddressSpaceTest.java

901 cherry picks from master

---

corfudb-tools/src/main/java/org/corfudb/browser/CorfuBrowserEditorCommands.java
corfudb-tools/src/main/java/org/corfudb/browser/CorfuOfflineBrowserEditor.java
corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditor.java
corfudb-tools/src/main/java/org/corfudb/browser/CorfuStoreBrowserEditorMain.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/LogReplicationAckReader.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/replication/receive/LogReplicationMetadataManager.java
infrastructure/src/main/java/org/corfudb/infrastructure/logreplication/runtime/fsm/NegotiatingState.java
runtime/src/main/java/org/corfudb/runtime/view/stream/StreamAddressSpace.java
runtime/src/main/java/org/corfudb/util/FileWatcher.java
runtime/src/test/java/org/corfudb/runtime/utils/FileWatcherTest.java
test/src/test/java/org/corfudb/integration/CorfuReplicationClusterConfigIT.java
test/src/test/java/org/corfudb/integration/CorfuStoreBrowserEditorIT.java
test/src/test/java/org/corfudb/runtime/view/stream/StreamAddressSpaceTest.java

Backport fixes into corfu-0.4.2.4
